// UEFA 챔피언스 리그 팀 정보
import { TeamMapping } from '.';

// UEFA 챔피언스 리그 2023/24 시즌 팀 데이터
export const CHAMPIONS_LEAGUE_TEAMS: TeamMapping[] = [
  {
    id: 50, 
    name_ko: '맨체스터 시티',
    name_en: 'Manchester City',
    country_ko: '잉글랜드',
    country_en: 'England',
    code: 'MCI',
  },
  {
    id: 541, 
    name_ko: '레알 마드리드',
    name_en: 'Real Madrid',
    country_ko: '스페인',
    country_en: 'Spain',
    code: 'RMA',
  },
  {
    id: 505, 
    name_ko: '인터 밀란',
    name_en: 'Inter Milan',
    country_ko: '이탈리아',
    country_en: 'Italy',
    code: 'INT',
  },
  {
    id: 489, 
    name_ko: 'AC 밀란',
    name_en: 'AC Milan',
    country_ko: '이탈리아',
    country_en: 'Italy',
    code: 'MIL',
  },
  {
    id: 165, 
    name_ko: '도르트문트',
    name_en: 'Borussia Dortmund',
    country_ko: '독일',
    country_en: 'Germany',
    code: 'BVB',
  },
  {
    id: 157, 
    name_ko: '바이에른 뮌헨',
    name_en: 'Bayern Munich',
    country_ko: '독일',
    country_en: 'Germany',
    code: 'BAY',
  },
  {
    id: 85, 
    name_ko: 'PSG',
    name_en: 'Paris Saint-Germain',
    country_ko: '프랑스',
    country_en: 'France',
    code: 'PSG',
  },
  {
    id: 529, 
    name_ko: '바르셀로나',
    name_en: 'FC Barcelona',
    country_ko: '스페인',
    country_en: 'Spain',
    code: 'BAR',
  },
  {
    id: 530, 
    name_ko: '아틀레티코 마드리드',
    name_en: 'Atletico Madrid',
    country_ko: '스페인',
    country_en: 'Spain',
    code: 'ATM',
  },
  {
    id: 33, 
    name_ko: '맨체스터 유나이티드',
    name_en: 'Manchester United',
    country_ko: '잉글랜드',
    country_en: 'England',
    code: 'MUN',
  },
  {
    id: 40, 
    name_ko: '리버풀',
    name_en: 'Liverpool',
    country_ko: '잉글랜드',
    country_en: 'England',
    code: 'LIV',
  },
  {
    id: 47, 
    name_ko: '토트넘',
    name_en: 'Tottenham Hotspur',
    country_ko: '잉글랜드',
    country_en: 'England',
    code: 'TOT',
  },
  {
    id: 42, 
    name_ko: '아스널',
    name_en: 'Arsenal',
    country_ko: '잉글랜드',
    country_en: 'England',
    code: 'ARS',
  },
  {
    id: 492, 
    name_ko: '나폴리',
    name_en: 'Napoli',
    country_ko: '이탈리아',
    country_en: 'Italy',
    code: 'NAP',
  },
  {
    id: 496, 
    name_ko: '유벤투스',
    name_en: 'Juventus',
    country_ko: '이탈리아',
    country_en: 'Italy',
    code: 'JUV',
  },
  {
    id: 212, 
    name_ko: '포르투',
    name_en: 'FC Porto',
    country_ko: '포르투갈',
    country_en: 'Portugal',
    code: 'FCP',
  },
  {
    id: 211, 
    name_ko: '벤피카',
    name_en: 'SL Benfica',
    country_ko: '포르투갈',
    country_en: 'Portugal',
    code: 'BEN',
  },
  {
    id: 194, 
    name_ko: '아약스',
    name_en: 'Ajax',
    country_ko: '네덜란드',
    country_en: 'Netherlands',
    code: 'AJX',
  },
  {
    id: 169, 
    name_ko: '레버쿠젠',
    name_en: 'Bayer Leverkusen',
    country_ko: '독일',
    country_en: 'Germany',
    code: 'B04',
  },
  {
    id: 173, 
    name_ko: 'RB 라이프치히',
    name_en: 'RB Leipzig',
    country_ko: '독일',
    country_en: 'Germany',
    code: 'RBL',
  },
  {
    id: 851, 
    name_ko: '브뤼헤',
    name_en: 'Club Brugge KV',
    country_ko: '벨기에',
    country_en: 'Belgium',
    code: 'BRU',
  },
  {
    id: 550, 
    name_ko: '셀틱',
    name_en: 'Celtic',
    country_ko: '스코틀랜드',
    country_en: 'Scotland',
    code: 'CEL',
  },
  {
    id: 610, 
    name_ko: '샤흐타르 도네츠크',
    name_en: 'Shakhtar Donetsk',
    country_ko: '우크라이나',
    country_en: 'Ukraine',
    code: 'SHA',
  },
  {
    id: 874, 
    name_ko: '레드불 잘츠부르크',
    name_en: 'Red Bull Salzburg',
    country_ko: '오스트리아',
    country_en: 'Austria',
    code: 'RBS',
  }
]; 