export const liverpoolPlayers = [
    { id: 280, name: "Alisson Becker", koreanName: "알리송 베커" },
    { id: 162687, name: "V. Jaroš", koreanName: "비테크 야로시" },
    { id: 281, name: "C. Kelleher", koreanName: "카오이민 켈레허" },
    { id: 180316, name: "H. Davies", koreanName: "하비 데이비스" },
    { id: 284, name: "J. Gomez", koreanName: "조 고메즈" },
    { id: 290, name: "V. van Dijk", koreanName: "버질 반 다이크" },
    { id: 1145, name: "I. Konaté", koreanName: "이브라히마 코나테" },
    { id: 1600, name: "K. Tsimikas", koreanName: "코스타스 치미카스" },
    { id: 289, name: "A. Robertson", koreanName: "앤드류 로버트슨" },
    { id: 407032, name: "A. Nallo", koreanName: "암브로즈 날로" },
    { id: 283, name: "T. Alexander-Arnold", koreanName: "트렌트 알렉산더-아놀드" },
    { id: 158698, name: "J. Quansah", koreanName: "자렐 쿠안사" },
    { id: 180317, name: "C. Bradley", koreanName: "코너 브래들리" },
    { id: 284286, name: "Isaac Mabaya", koreanName: "아이작 마바야" },
    { id: 8500, name: "W. Endo", koreanName: "엔도 와타루" },
    { id: 1096, name: "D. Szoboszlai", koreanName: "도미니크 소보슬라이" },
    { id: 6716, name: "A. Mac Allister", koreanName: "알렉시스 맥 알리스터" },
    { id: 293, name: "C. Jones", koreanName: "커티스 존스" },
    { id: 19035, name: "H. Elliott", koreanName: "하비 엘리엇" },
    { id: 542, name: "R. Gravenberch", koreanName: "라이언 흐라번베르흐" },
    { id: 287109, name: "J. McConnell", koreanName: "제임스 맥코넬" },
    { id: 389032, name: "K. Morrison", koreanName: "루이스 모리슨" },
    { id: 162590, name: "T. Morton", koreanName: "타일러 모튼" },
    { id: 397997, name: "T. Nyoni", koreanName: "트레이 넌이" },
    { id: 2489, name: "L. Díaz", koreanName: "루이스 디아스" },
    { id: 51617, name: "D. Núñez", koreanName: "다르윈 누녜스" },
    { id: 306, name: "Mohamed Salah", koreanName: "모하메드 살라" },
    { id: 30410, name: "F. Chiesa", koreanName: "페데리코 키에사" },
    { id: 247, name: "C. Gakpo", koreanName: "코디 각포" },
    { id: 2678, name: "Diogo Jota", koreanName: "디오고 조타" },
    { id: 340246, name: "Trent Toure Kone Doherty", koreanName: "트렌트 투레 코네 도허티" },
    { id: 452685, name: "R. Ngumoha", koreanName: "루엘 응구모하" },
    { id: 380657, name: "R. Young", koreanName: "루이스 영" },
  ];
  
  
  export const NottinghamForestPlayers = [
    { "id": 18836, "name": "W. Hennessey", "korean_name": "웨인 헤네시" },
    { "id": 2919, "name": "M. Sels", "korean_name": "마르크 셀스" },
    { "id": 10373, "name": "Carlos Miguel", "korean_name": "카를로스 미겔" },
    { "id": 67943, "name": "Morato", "korean_name": "모라토" },
    { "id": 363695, "name": "Murillo", "korean_name": "무리요" },
    { "id": 138780, "name": "N. Williams", "korean_name": "니콜라 윌리엄스" },
    { "id": 17365, "name": "H. Toffolo", "korean_name": "해리 토폴로" },
    { "id": 47547, "name": "Álex Moreno", "korean_name": "알렉스 모레노" },
    { "id": 18739, "name": "W. Boly", "korean_name": "윌리 볼리" },
    { "id": 2817, "name": "N. Milenković", "korean_name": "니콜라 밀렌코비치" },
    { "id": 2771, "name": "O. Aina", "korean_name": "오소리 아이나" },
    { "id": 329357, "name": "Z. Abbott", "korean_name": "제이크 애보트" },
    { "id": 22149, "name": "I. Sangaré", "korean_name": "이브상 가레" },
    { "id": 138908, "name": "E. Anderson", "korean_name": "엘리슨 앤더슨" },
    { "id": 18746, "name": "M. Gibbs-White", "korean_name": "마커스 깁스 화이트" },
    { "id": 6056, "name": "N. Domínguez", "korean_name": "니콜라스 도밍게즈" },
    { "id": 19305, "name": "R. Yates", "korean_name": "라이언 예이츠" },
    { "id": 275170, "name": "Danilo", "korean_name": "다니로" },
    { "id": 8598, "name": "T. Awoniyi", "korean_name": "타이워 아워니이" },
    { "id": 18931, "name": "C. Wood", "korean_name": "크리스 우드" },
    { "id": 2298, "name": "C. Hudson-Odoi", "korean_name": "칼럼 허드슨 오도이" },
    { "id": 380492, "name": "Eric Emanuel da Silva Moreira", "korean_name": "에릭 에마누엘 다 실바 모레이라" },
    { "id": 141901, "name": "Jota Silva", "korean_name": "조타 실바" },
    { "id": 153430, "name": "A. Elanga", "korean_name": "안드레아스 엘랑가" },
    { "id": 196298, "name": "R. Sosa", "korean_name": "르앙소사" },
    { "id": 328096, "name": "Joel Tshisanga Ndala", "korean_name": "조엘 시상가 은달라" }
  ];
  

export const Arsenalplayers = [
    {"id": 19465, "name": "David Raya", "korean_name": "데이비드 라야"},
    {"id": 912, "name": "Neto", "korean_name": "네토"},
    {"id": 342243, "name": "T. Setford", "korean_name": "T. 셋포드"},
    {"id": 337933, "name": "Alexei Rojas Fedorushchenko", "korean_name": "알렉세이 로하스 페도로쉔코"},
    {"id": 416697, "name": "J. Porter", "korean_name": "J. 포터"},
    {"id": 22090, "name": "W. Saliba", "korean_name": "윌리엄 살리바"},
    {"id": 1117, "name": "K. Tierney", "korean_name": "키어런 티어니"},
    {"id": 19959, "name": "B. White", "korean_name": "벤 화이트"},
    {"id": 22224, "name": "Gabriel Magalhães", "korean_name": "가브리엘 마갈량스"},
    {"id": 38746, "name": "J. Timber", "korean_name": "J. 팀버"},
    {"id": 61431, "name": "J. Kiwior", "korean_name": "J. 키비오르"},
    {"id": 641, "name": "O. Zinchenko", "korean_name": "오레크산드르 진첸코"},
    {"id": 2597, "name": "T. Tomiyasu", "korean_name": "토미야스 타케히로"},
    {"id": 157052, "name": "R. Calafiori", "korean_name": "로렌초 칼라포리"},
    {"id": 380696, "name": "Joshua Nichols", "korean_name": "조슈아 니콜스"},
    {"id": 49, "name": "T. Partey", "korean_name": "토마스 파르티"},
    {"id": 37127, "name": "M. Ødegaard", "korean_name": "마르틴 외데가르드"},
    {"id": 2289, "name": "Jorginho", "korean_name": "조르지뉴"},
    {"id": 47311, "name": "Mikel Merino", "korean_name": "미켈 메리노"},
    {"id": 2937, "name": "D. Rice", "korean_name": "데클란 라이스"},
    {"id": 313229, "name": "J. Gower", "korean_name": "J. 고워"},
    {"id": 313245, "name": "M. Lewis-Skelly", "korean_name": "M. 루이스-스켈리"},
    {"id": 313236, "name": "E. Nwaneri", "korean_name": "E. 누와네리"},
    {"id": 278074, "name": "S. Oulad M'Hand", "korean_name": "S. 울라드 핸드"},
    {"id": 1460, "name": "B. Saka", "korean_name": "부카요 사카"},
    {"id": 643, "name": "Gabriel Jesus", "korean_name": "가브리엘 제수스"},
    {"id": 127769, "name": "Gabriel Martinelli", "korean_name": "가브리엘 마르티넬리"},
    {"id": 1946, "name": "L. Trossard", "korean_name": "리오넬 트로사르"},
    {"id": 978, "name": "K. Havertz", "korean_name": "카이 하베르츠"},
    {"id": 645, "name": "R. Sterling", "korean_name": "랄프 스털링"},
    {"id": 153407, "name": "N. Butler-Oyedeji", "korean_name": "N. 버틀러-오예데지"},
    {"id": 407033, "name": "Ismeal Kabia", "korean_name": "이스마엘 카비아"}
  ]
  
  export const NewcastleUnitedplayers = [
    {"id": 18886, "name": "M. Dúbravka", "koreanName": "마르틴 두브라브카"},
    {"id": 557, "name": "O. Vlachodimos", "koreanName": "오디세아스 블라호디모스"},
    {"id": 18911, "name": "N. Pope", "koreanName": "니컬라스 포프"},
    {"id": 18737, "name": "J. Ruddy", "koreanName": "존 러디"},
    {"id": 44912, "name": "M. Gillespie", "koreanName": "마크 질레스피"},
    {"id": 169, "name": "K. Trippier", "koreanName": "키런 트리피어"},
    {"id": 38734, "name": "S. Botman", "koreanName": "슈코드란 보트만"},
    {"id": 2806, "name": "F. Schär", "koreanName": "프라니시 스카르"},
    {"id": 18894, "name": "J. Lascelles", "koreanName": "제임스 래셀스"},
    {"id": 18941, "name": "M. Targett", "koreanName": "마티 타게트"},
    {"id": 2855, "name": "E. Krafth", "koreanName": "엠릴 크라프트"},
    {"id": 284492, "name": "L. Hall", "koreanName": "루이스 홀"},
    {"id": 158694, "name": "T. Livramento", "koreanName": "티노 리브라멘토"},
    {"id": 18961, "name": "D. Burn", "koreanName": "대니얼 번"},
    {"id": 337934, "name": "L. Shahar", "koreanName": "루크 샤하르"},
    {"id": 19076, "name": "J. Lewis", "koreanName": "제이슨 루이스"},
    {"id": 31146, "name": "S. Tonali", "koreanName": "사무엘 토날리"},
    {"id": 18778, "name": "H. Barnes", "koreanName": "하비 바른스"},
    {"id": 19163, "name": "J. Murphy", "koreanName": "제이슨 머피"},
    {"id": 1463, "name": "J. Willock", "koreanName": "조엘 윌록"},
    {"id": 18901, "name": "S. Longstaff", "koreanName": "셰인 롱스타프"},
    {"id": 10135, "name": "Bruno Guimarães", "koreanName": "브루노 기마랑이스"},
    {"id": 328105, "name": "L. Miley", "koreanName": "리암 마일리"},
    {"id": 723, "name": "Joelinton", "koreanName": "조엘린턴"},
    {"id": 2939, "name": "C. Wilson", "koreanName": "칼럼 윌슨"},
    {"id": 138787, "name": "A. Gordon", "koreanName": "안소니 고든"},
    {"id": 2864, "name": "A. Isak", "koreanName": "알렉산더 이삭"},
    {"id": 315237, "name": "W. Osula", "koreanName": "윌리엄 오술라"},
    {"id": 401389, "name": "T. Sanusi", "koreanName": "타이산 수누시"},
    {"id": 394165, "name": "S. Neave", "koreanName": "세드릭 네이브"}
  ]
  
  export const Chelseaplayers = [
    {"id":18959, "english_name":"Robert Sánchez", "korean_name":"로버트 산체스"},
    {"id":286616, "english_name":"F. Jörgensen", "korean_name":"F. 요르겐센"},
    {"id":19012, "english_name":"M. Bettinelli", "korean_name":"M. 베티넬리"},
    {"id":152955, "english_name":"L. Bergström", "korean_name":"L. 베르그스트룬"},
    {"id":303667, "english_name":"E. Beach", "korean_name":"E. 비치"},
    {"id":47380, "english_name":"Marc Cucurella", "korean_name":"마르크 쿠쿠렐라"},
    {"id":19145, "english_name":"T. Adarabioyo", "korean_name":"T. 아다라비오요"},
    {"id":95, "english_name":"B. Badiashile", "korean_name":"B. 바디아시르"},
    {"id":152953, "english_name":"L. Colwill", "korean_name":"L. 콜윌"},
    {"id":19720, "english_name":"T. Chalobah", "korean_name":"T. 찰로바"},
    {"id":19545, "english_name":"R. James", "korean_name":"R. 제임스"},
    {"id":161907, "english_name":"M. Gusto", "korean_name":"M. 구스토"},
    {"id":22094, "english_name":"W. Fofana", "korean_name":"W. 포파나"},
    {"id":422780, "english_name":"A. Anselmino", "korean_name":"A. 안셀미노"},
    {"id":366735, "english_name":"Joshua Kofi Acheampong", "korean_name":"조슈아 코피 아챔퐁"},
    {"id":306263, "english_name":"Richard Olise", "korean_name":"리처드 올리세"},
    {"id":364048, "english_name":"Harrison Murray-Campbell", "korean_name":"해리슨 머리-캠벨"},
    {"id":328093, "english_name":"I. Samuels-Smith", "korean_name":"I. 새뮤얼스-스미스"},
    {"id":334042, "english_name":"Kaiden Wilson", "korean_name":"카이든 윌슨"},
    {"id":398000, "english_name":"G. Antwi", "korean_name":"G. 안트위"},
    {"id":5996, "english_name":"E. Fernández", "korean_name":"E. 페르난데스"},
    {"id":63577, "english_name":"M. Mudryk", "korean_name":"M. 무드리크"},
    {"id":152982, "english_name":"C. Palmer", "korean_name":"C. 팔머"},
    {"id":148099, "english_name":"K. Dewsbury-Hall", "korean_name":"K. 듀즈버리-홀"},
    {"id":116117, "english_name":"M. Caicedo", "korean_name":"M. 카이세도"},
    {"id":365660, "english_name":"K. Dyer", "korean_name":"K. 다이어"},
    {"id":329347, "english_name":"O. Kellyman", "korean_name":"O. 켈리맨"},
    {"id":395762, "english_name":"M. Amougou", "korean_name":"M. 아무구"},
    {"id":282125, "english_name":"R. Lavia", "korean_name":"R. 라비아"},
    {"id":327733, "english_name":"Sam Rak-Sakyi", "korean_name":"샘 락-사키"},
    {"id":482888, "english_name":"R. Walsh", "korean_name":"R. 월시"},
    {"id":1864, "english_name":"Pedro Neto", "korean_name":"페드로 네토"},
    {"id":136723, "english_name":"N. Madueke", "korean_name":"N. 마두에케"},
    {"id":283058, "english_name":"N. Jackson", "korean_name":"N. 잭슨"},
    {"id":269, "english_name":"C. Nkunku", "korean_name":"C. 은쿤쿠"},
    {"id":18, "english_name":"J. Sancho", "korean_name":"J. 산초"},
    {"id":334037, "english_name":"Tyrique George", "korean_name":"타이리크 조지"},
    {"id":392270, "english_name":"Marc Guiu", "korean_name":"마르크 기우"},
    {"id":360011, "english_name":"Ato Ampah", "korean_name":"Ato 암파"},
    {"id":359117, "english_name":"Shumaira Mheuka", "korean_name":"슈마이라 무에카"},
    {"id":291476, "english_name":"D. Fofana", "korean_name":"D. 포파나"}
  ]
  
  export const ManchesterCityplayers = [
    {"id": 25004, "english_name": "S. Ortega", "korean_name": "S. 오르테가"},
    {"id": 617, "english_name": "Ederson", "korean_name": "에데르손"},
    {"id": 19197, "english_name": "S. Carson", "korean_name": "S. 카슨"},
    {"id": 437557, "english_name": "S. Brits", "korean_name": "S. 브리츠"},
    {"id": 567, "english_name": "Rúben Dias", "korean_name": "루벤 디아스"},
    {"id": 626, "english_name": "J. Stones", "korean_name": "J. 스톤스"},
    {"id": 18861, "english_name": "N. Aké", "korean_name": "N. 아케"},
    {"id": 414359, "english_name": "Vitor Nunes", "korean_name": "비토르 누네스"},
    {"id": 129033, "english_name": "J. Gvardiol", "korean_name": "J. 과르디올"},
    {"id": 5, "english_name": "M. Akanji", "korean_name": "M. 아칸지"},
    {"id": 360114, "english_name": "A. Khusanov", "korean_name": "A. 쿠사노프"},
    {"id": 404656, "english_name": "Jahmai Simpson-Pusey", "korean_name": "자마이 심슨-푸시"},
    {"id": 293168, "english_name": "Max Alleyne", "korean_name": "맥스 알리네"},
    {"id": 284230, "english_name": "R. Lewis", "korean_name": "R. 루이스"},
    {"id": 2291, "english_name": "M. Kovačić", "korean_name": "M. 코바치치"},
    {"id": 19187, "english_name": "J. Grealish", "korean_name": "J. 그릴리시"},
    {"id": 161933, "english_name": "Nico González", "korean_name": "니코 곤잘레스"},
    {"id": 44, "english_name": "Rodri", "korean_name": "로드리"},
    {"id": 629, "english_name": "K. De Bruyne", "korean_name": "K. 드 브라위너"},
    {"id": 633, "english_name": "İ. Gündoğan", "korean_name": "İ. 귄도안"},
    {"id": 636, "english_name": "Bernardo Silva", "korean_name": "베르나르도 실바"},
    {"id": 41621, "english_name": "Matheus Nunes", "korean_name": "마테우스 누네스"},
    {"id": 414385, "english_name": "C. Echeverri", "korean_name": "C. 에체베리"},
    {"id": 631, "english_name": "P. Foden", "korean_name": "P. 포든"},
    {"id": 278133, "english_name": "Oscar Bobb", "korean_name": "오스카 밥"},
    {"id": 307123, "english_name": "N. O'Reilly", "korean_name": "N. 오라이리"},
    {"id": 158697, "english_name": "J. McAtee", "korean_name": "J. 맥어티"},
    {"id": 81573, "english_name": "Omar Marmoush", "korean_name": "오마르 마르무쉬"},
    {"id": 1100, "english_name": "E. Haaland", "korean_name": "E. 홀란드"},
    {"id": 1422, "english_name": "J. Doku", "korean_name": "J. 도쿠"},
    {"id": 266657, "english_name": "Sávio", "korean_name": "사비오"},
    {"id": 284409, "english_name": "D. Mubama", "korean_name": "D. 무바마"}
  ]
  
  export  const AstonVillaplayers = [
    {"id": 19599, "englishName": "E. Martínez", "koreanName": "에미리안"},
    {"id": 766, "englishName": "R. Olsen", "koreanName": "로빈 올슨"},
    {"id": 148270, "englishName": "O. Zych", "koreanName": "오. 지흐"},
    {"id": 398004, "englishName": "S. Proctor", "koreanName": "S. 프로터"},
    {"id": 19298, "englishName": "M. Cash", "koreanName": "맷 캐시"},
    {"id": 21998, "englishName": "A. Disasi", "koreanName": "아흐메드 디사시"},
    {"id": 19354, "englishName": "E. Konsa", "koreanName": "에즈리 콘사"},
    {"id": 19179, "englishName": "T. Mings", "koreanName": "타이론 밍스"},
    {"id": 2724, "englishName": "L. Digne", "koreanName": "루카 디뉴"},
    {"id": 46815, "englishName": "Pau Torres", "koreanName": "파우 토레스"},
    {"id": 388013, "englishName": "Andrés García", "koreanName": "안드레스 가르시아"},
    {"id": 138816, "englishName": "I. Maatsen", "koreanName": "이브 마첸"},
    {"id": 284457, "englishName": "L. Bogarde", "koreanName": "루이스 보가르데"},
    {"id": 19177, "englishName": "K. Hause", "koreanName": "케이든 하우스"},
    {"id": 360269, "englishName": "Triston Rowe", "koreanName": "트리스턴 로우"},
    {"id": 357060, "englishName": "T. Katsukunya", "koreanName": "T. 카츠쿠니야"},
    {"id": 2287, "englishName": "R. Barkley", "koreanName": "로스 바클리"},
    {"id": 19191, "englishName": "J. McGinn", "koreanName": "존 맥기넌"},
    {"id": 2926, "englishName": "Y. Tielemans", "koreanName": "유리 틸레만스"},
    {"id": 162714, "englishName": "A. Onana", "koreanName": "앙드레 오나나"},
    {"id": 983, "englishName": "L. Bailey", "koreanName": "레온 베일리"},
    {"id": 19192, "englishName": "J. Ramsey", "koreanName": "제이콥 램지"},
    {"id": 1904, "englishName": "B. Kamara", "koreanName": "브바카르 카마라"},
    {"id": 434180, "englishName": "Aidan Borland", "koreanName": "에이든 보를랜드"},
    {"id": 360268, "englishName": "J. Jimoh", "koreanName": "제이 제이모"},
    {"id": 380715, "englishName": "B. Broggio", "koreanName": "브라이언 브로지오"},
    {"id": 453101, "englishName": "B. Burrows", "koreanName": "브렌던 버로우즈"},
    {"id": 909, "englishName": "M. Rashford", "koreanName": "마커스 래시포드"},
    {"id": 19366, "englishName": "O. Watkins", "koreanName": "올리 워킨스"},
    {"id": 249, "englishName": "D. Malen", "koreanName": "다니엘 말렌"},
    {"id": 746, "englishName": "Marco Asensio", "koreanName": "마르코 아센시오"},
    {"id": 19170, "englishName": "M. Rogers", "koreanName": "마르코 로저스"}
]

export const Bournemouthplayers = [
    {"id": 2273, "name": "Kepa", "koreanName": "케파"},
    {"id": 151756, "name": "W. Dennis", "koreanName": "W. 데니스"},
    {"id": 394710, "name": "C. McKenna", "koreanName": "C. 맥케나"},
    {"id": 361497, "name": "D. Huijsen", "koreanName": "D. 후이센"},
    {"id": 206254, "name": "M. Kerkez", "koreanName": "M. 케르케즈"},
    {"id": 6610, "name": "M. Senesi", "koreanName": "M. 세네시"},
    {"id": 18869, "name": "A. Smith", "koreanName": "A. 스미스"},
    {"id": 363333, "name": "J. Soler", "koreanName": "J. 솔레르"},
    {"id": 51051, "name": "J. Araujo", "koreanName": "J. 아라우호"},
    {"id": 20093, "name": "J. Hill", "koreanName": "J. 힐"},
    {"id": 161671, "name": "I. Zabarnyi", "koreanName": "I. 자바르니"},
    {"id": 359942, "name": "M. Akinmboni", "koreanName": "M. 아킨보니"},
    {"id": 382170, "name": "M. Kinsey-Wellings", "koreanName": "M. 킨지-웰링스"},
    {"id": 449224, "name": "Archie Harris", "koreanName": "아치 해리스"},
    {"id": 18872, "name": "L. Cook", "koreanName": "L. 쿡"},
    {"id": 18870, "name": "D. Brooks", "koreanName": "D. 브룩스"},
    {"id": 304853, "name": "A. Scott", "koreanName": "A. 스콧"},
    {"id": 1125, "name": "R. Christie", "koreanName": "R. 크리스티"},
    {"id": 1150, "name": "T. Adams", "koreanName": "T. 아담스"},
    {"id": 19245, "name": "M. Tavernier", "koreanName": "M. 태버니어"},
    {"id": 402432, "name": "Ben Winterburn", "koreanName": "벤 윈터번"},
    {"id": 152856, "name": "Evanilson", "koreanName": "에바닐슨"},
    {"id": 284797, "name": "D. Ouattara", "koreanName": "D. 우아타라"},
    {"id": 37161, "name": "L. Sinisterra", "koreanName": "L. 시니스테라"},
    {"id": 792, "name": "J. Kluivert", "koreanName": "J. 클루이베르트"},
    {"id": 296458, "name": "D. Jebbison", "koreanName": "D. 제비슨"},
    {"id": 19281, "name": "A. Semenyo", "koreanName": "A. 세멘요"},
    {"id": 47499, "name": "E. Ünal", "koreanName": "E. 위날"},
    {"id": 298060, "name": "Z. Silcott-Duberry", "koreanName": "Z. 실콧-더버리"},
    {"id": 382160, "name": "D. Adu-Adjei", "koreanName": "D. 아두-아제이"},
    {"id": 334725, "name": "D. Sadi", "koreanName": "D. 사디"},
    {"id": 402434, "name": "Remy Rees-Dottin", "koreanName": "레미 리스-도틴"}
  ]
  
  export const Fulhamplayers = [
    {"id": 1438, "english_name": "B. Leno", "korean_name": "베른트 레노"},
    {"id": 19312, "english_name": "S. Benda", "korean_name": "슈테판 벤다"},
    {"id": 657, "english_name": "K. Tete", "korean_name": "케빈 테테"},
    {"id": 152967, "english_name": "C. Bassey", "korean_name": "오마르 바세이"},
    {"id": 2729, "english_name": "J. Andersen", "korean_name": "요한 안데르센"},
    {"id": 131, "english_name": "Jorge Cuenca", "korean_name": "호르헤 쿠엥카"},
    {"id": 2920, "english_name": "T. Castagne", "korean_name": "티모시 카스타뉴"},
    {"id": 18814, "english_name": "I. Diop", "korean_name": "이브 디오프"},
    {"id": 19549, "english_name": "A. Robinson", "korean_name": "안톤 로빈슨"},
    {"id": 384981, "english_name": "S. Amissah", "korean_name": "세바스티안 아미사"},
    {"id": 19480, "english_name": "H. Reed", "korean_name": "헨리 리드"},
    {"id": 19221, "english_name": "H. Wilson", "korean_name": "헨리 윌슨"},
    {"id": 19025, "english_name": "T. Cairney", "korean_name": "토미 케어니"},
    {"id": 1934, "english_name": "S. Berge", "korean_name": "숀 베르게"},
    {"id": 899, "english_name": "Andreas Pereira", "korean_name": "안드레아스 페레이라"},
    {"id": 2823, "english_name": "S. Lukić", "korean_name": "사르코 루키치"},
    {"id": 389315, "english_name": "Joshua King", "korean_name": "조슈아 킹"},
    {"id": 19032, "english_name": "R. Sessegnon", "korean_name": "라이언 세세뇽"},
    {"id": 1161, "english_name": "E. Smith Rowe", "korean_name": "에밀 스미스 로우"},
    {"id": 2887, "english_name": "R. Jiménez", "korean_name": "로드리고 히메네스"},
    {"id": 195106, "english_name": "Rodrigo Muniz", "korean_name": "로드리고 무니즈"},
    {"id": 18753, "english_name": "Adama Traoré", "korean_name": "아다마 트라오레"},
    {"id": 104, "english_name": "Carlos Vinícius", "korean_name": "카를로스 비니시우스"},
    {"id": 1455, "english_name": "A. Iwobi", "korean_name": "알렉스 이워비"},
    {"id": 727, "english_name": "R. Nelson", "korean_name": "리세드 넬슨"},
    {"id": 2294, "english_name": "Willian", "korean_name": "윌리안"},
    {"id": 359386, "english_name": "M. Godo", "korean_name": "마르코 고도"}
]

export const Brightonplayers = [
    { id: 129058, name: "B. Verbruggen", koreanName: "B. 베르브루헨" },
    { id: 18960, name: "J. Steele", koreanName: "J. 스틸" },
    { id: 167663, name: "T. McGill", koreanName: "T. 맥길" },
    { id: 201368, name: "Killian Cahill", koreanName: "킬리안 카힐" },
    { id: 278088, name: "C. Rushworth", koreanName: "C. 러시워스" },
    { id: 138815, name: "T. Lamptey", koreanName: "T. 램프티" },
    { id: 7600, name: "Igor", koreanName: "이고르" },
    { id: 19265, name: "A. Webster", koreanName: "A. 웹스터" },
    { id: 18963, name: "L. Dunk", koreanName: "L. 덩크" },
    { id: 161663, name: "E. Cashin", koreanName: "E. 캐신" },
    { id: 38695, name: "J. van Hecke", koreanName: "J. 반 헥" },
    { id: 46731, name: "P. Estupiñán", koreanName: "P. 에스투피냥" },
    { id: 537, name: "J. Veltman", koreanName: "J. 벨트만" },
    { id: 379618, name: "J. Slater", koreanName: "J. 슬레이터" },
    { id: 328076, name: "C. Tasker", koreanName: "C. 태스커" },
    { id: 296, name: "J. Milner", koreanName: "J. 밀너" },
    { id: 18973, name: "S. March", koreanName: "S. 마치" },
    { id: 328225, name: "B. Gruda", koreanName: "B. 그루다" },
    { id: 356041, name: "C. Baleba", koreanName: "C. 발레바" },
    { id: 106835, name: "K. Mitoma", koreanName: "K. 미토마" },
    { id: 1361, name: "F. Kadıoğlu", koreanName: "F. 카디오글루" },
    { id: 278370, name: "D. Gómez", koreanName: "D. 고메즈" },
    { id: 265820, name: "Y. Ayari", koreanName: "Y. 아야리" },
    { id: 92993, name: "M. Wieffer", koreanName: "M. 위퍼" },
    { id: 19030, name: "M. O'Riley", koreanName: "M. 오라일리" },
    { id: 305730, name: "J. Hinshelwood", koreanName: "J. 힌셜우드" },
    { id: 359842, name: "Joe Knight", koreanName: "조 나이트" },
    { id: 10329, name: "João Pedro", koreanName: "조앙 페드로" },
    { id: 301771, name: "S. Adingra", koreanName: "S. 아딩라" },
    { id: 90590, name: "G. Rutter", koreanName: "G. 루터" },
    { id: 383685, name: "Y. Minteh", koreanName: "Y. 민테" },
    { id: 1469, name: "D. Welbeck", koreanName: "D. 웰벡" }
  ];
    