// Search domain exports (리팩토링됨)
export * from './types'
export * from './actions'
export { searchPosts } from './actions/searchPosts'
export { searchComments } from './actions/searchComments'
export { searchTeams, getPopularTeams, getTeamCountByLeague } from './actions/searchTeams'
export { default as SearchBar } from './components/SearchBar'
export { default as SearchHeader } from './components/SearchHeader'
export { default as SearchResultsContainer } from './components/SearchResultsContainer'
export { default as PostSearchResults } from './components/PostSearchResults'
export { default as CommentSearchResults } from './components/CommentSearchResults'
export { default as TeamSearchResults } from './components/TeamSearchResults'
export { default as Pagination } from './components/Pagination' 