import { PlayerMapping } from './index';

// Albirex Niigata (알비렉스 니가타) - Team ID: 311
export const ALBIREX_NIIGATA_PLAYERS: PlayerMapping[] = [
  { id: 9264, name: "K. Fujita", korean_name: "후지타 고타로", team_id: 311, position: "Goalkeeper", number: 1, age: 24 },
  { id: 9274, name: "J. Geria", korean_name: "제이슨 게리아", team_id: 311, position: "Defender", number: 2, age: 32 },
  { id: 9276, name: "S. Okamoto", korean_name: "오카모토 슌야", team_id: 311, position: "Defender", number: 4, age: 25 },
  { id: 9269, name: "M. Fitzgerald", korean_name: "마이클 피츠제럴드", team_id: 311, position: "Defender", number: 5, age: 37 },
  { id: 9303, name: "K. Taniguchi", korean_name: "타니구치 카즈야", team_id: 311, position: "Attacker", number: 7, age: 30 },
  { id: 9302, name: "K. Yamura", korean_name: "야무라 카즈키", team_id: 311, position: "Attacker", number: 9, age: 28 },
  { id: 9295, name: "Danilo Gomes", korean_name: "다닐로 고메스", team_id: 311, position: "Midfielder", number: 11, age: 26 },
  { id: 9294, name: "R. Ochiai", korean_name: "오치아이 료타", team_id: 311, position: "Midfielder", number: 13, age: 26 },
  { id: 9272, name: "F. Hayakawa", korean_name: "하야카와 후미야", team_id: 311, position: "Defender", number: 15, age: 31 },
  { id: 9287, name: "H. Akiyama", korean_name: "아키야마 하루키", team_id: 311, position: "Midfielder", number: 16, age: 25 },
  { id: 9298, name: "Y. Wakatsuki", korean_name: "와카츠키 유야", team_id: 311, position: "Attacker", number: 18, age: 23 },
  { id: 9278, name: "Y. Hoshi", korean_name: "호시 유타카", team_id: 311, position: "Midfielder", number: 19, age: 33 },
  { id: 9292, name: "Miguel Silveira", korean_name: "미겔 실베이라", team_id: 311, position: "Midfielder", number: 20, age: 22 },
  { id: 9267, name: "R. Tashiro", korean_name: "타시로 료타", team_id: 311, position: "Goalkeeper", number: 21, age: 27 },
  { id: 9280, name: "T. Arai", korean_name: "아라이 타쿠마", team_id: 311, position: "Midfielder", number: 22, age: 28 },
  { id: 9265, name: "D. Yoshimitsu", korean_name: "요시미츠 다이키", team_id: 311, position: "Goalkeeper", number: 23, age: 32 },
  { id: 9289, name: "S. Fujiwara", korean_name: "후지와라 소타", team_id: 311, position: "Defender", number: 25, age: 30 },
  { id: 9279, name: "J. Okumura", korean_name: "오쿠무라 준", team_id: 311, position: "Midfielder", number: 30, age: 24 },
  { id: 9275, name: "Y. Horigome", korean_name: "호리고메 유타", team_id: 311, position: "Defender", number: 31, age: 31 },
  { id: 9286, name: "Y. Takagi", korean_name: "타카기 유타", team_id: 311, position: "Midfielder", number: 33, age: 33 },
  { id: 9273, name: "K. Chiba", korean_name: "치바 카즈히코", team_id: 311, position: "Defender", number: 35, age: 40 },
  { id: 9271, name: "K. Mori", korean_name: "모리 켄토", team_id: 311, position: "Defender", number: 38, age: 26 },
  { id: 9283, name: "M. Hasegawa", korean_name: "하세가와 마사히로", team_id: 311, position: "Attacker", number: 41, age: 27 },
  { id: 9268, name: "K. Hashimoto", korean_name: "하시모토 켄타", team_id: 311, position: "Defender", number: 42, age: 26 },
  { id: 9288, name: "Keisuke Kasai", korean_name: "카사이 케이스케", team_id: 311, position: "Midfielder", number: 46, age: 23 },
  { id: 9281, name: "Y. Otake", korean_name: "오타케 유키", team_id: 311, position: "Midfielder", number: 48, age: 20 },
  { id: 9282, name: "H. Uemura", korean_name: "우에무라 히로키", team_id: 311, position: "Defender", number: 50, age: 24 },
  { id: 9300, name: "Moraes", korean_name: "모라에스", team_id: 311, position: "Attacker", number: 55, age: 25 },
  { id: 9299, name: "A. Boudah", korean_name: "압델라지즈 부다", team_id: 311, position: "Attacker", number: 65, age: 26 },
  { id: 9297, name: "Y. Ono", korean_name: "오노 유키", team_id: 311, position: "Attacker", number: 99, age: 33 },
  { id: 9266, name: "S. Uchiyama", korean_name: "우치야마 소타", team_id: 311, position: "Goalkeeper", number: null, age: 19 },
  { id: 9270, name: "Y. Yasuda", korean_name: "야스다 유키", team_id: 311, position: "Defender", number: null, age: 18 },
];

// Avispa Fukuoka (아비스파 후쿠오카) - Team ID: 316
export const AVISPA_FUKUOKA_PLAYERS: PlayerMapping[] = [
  { id: 9306, name: "T. Nagaishi", korean_name: "나가이시 타쿠야", team_id: 316, position: "Goalkeeper", number: 1, age: 29 },
  { id: 9311, name: "M. Yuzawa", korean_name: "유자와 마사야", team_id: 316, position: "Midfielder", number: 2, age: 32 },
  { id: 9314, name: "T. Nara", korean_name: "나라 타케히로", team_id: 316, position: "Defender", number: 3, age: 32 },
  { id: 9308, name: "T. Kamijima", korean_name: "카미지마 타쿠야", team_id: 316, position: "Defender", number: 5, age: 28 },
  { id: 9325, name: "M. Shigemi", korean_name: "시게미 마사히로", team_id: 316, position: "Midfielder", number: 6, age: 24 },
  { id: 9324, name: "K. Konno", korean_name: "곤노 카즈키", team_id: 316, position: "Midfielder", number: 8, age: 28 },
  { id: 9330, name: "S. Zahedi", korean_name: "샤룬 자헤디", team_id: 316, position: "Attacker", number: 9, age: 30 },
  { id: 9334, name: "H. Jogo", korean_name: "조고 히로유키", team_id: 316, position: "Attacker", number: 10, age: 39 },
  { id: 9320, name: "T. Miki", korean_name: "미키 타쿠야", team_id: 316, position: "Midfielder", number: 11, age: 27 },
  { id: 9331, name: "N. Ben Khalifa", korean_name: "나심 벤 칼리파", team_id: 316, position: "Attacker", number: 13, age: 33 },
  { id: 9319, name: "S. Nago", korean_name: "나고 신야", team_id: 316, position: "Attacker", number: 14, age: 29 },
  { id: 9326, name: "H. Akino", korean_name: "아키노 히로키", team_id: 316, position: "Midfielder", number: 15, age: 31 },
  { id: 9316, name: "I. Oda", korean_name: "오다 이치야", team_id: 316, position: "Defender", number: 16, age: 27 },
  { id: 9332, name: "Wellington Tanque", korean_name: "웰링턴 탄키", team_id: 316, position: "Attacker", number: 17, age: 37 },
  { id: 9329, name: "Y. Iwasaki", korean_name: "이와사키 유야", team_id: 316, position: "Attacker", number: 18, age: 27 },
  { id: 9313, name: "Kim Moon-Hyeon", korean_name: "김문현", team_id: 316, position: "Defender", number: 19, age: 23 },
  { id: 9317, name: "T. Ando", korean_name: "안도 타쿠마", team_id: 316, position: "Defender", number: 20, age: 26 },
  { id: 9328, name: "K. Fujimoto", korean_name: "후지모토 카나메", team_id: 316, position: "Attacker", number: 22, age: 27 },
  { id: 9307, name: "Y. Obata", korean_name: "오바타 유키", team_id: 316, position: "Goalkeeper", number: 24, age: 24 },
  { id: 9322, name: "Y. Kitajima", korean_name: "키타지마 유키", team_id: 316, position: "Midfielder", number: 25, age: 25 },
  { id: 9335, name: "S. Usui", korean_name: "우스이 소타", team_id: 316, position: "Attacker", number: 27, age: 24 },
  { id: 9315, name: "Y. Maejima", korean_name: "마에지마 유키", team_id: 316, position: "Defender", number: 29, age: 28 },
  { id: 9305, name: "M. Murakami", korean_name: "무라카미 마사야", team_id: 316, position: "Goalkeeper", number: 31, age: 33 },
  { id: 9337, name: "A. Sani Brown", korean_name: "아브둘 하킴 사니 브라운", team_id: 316, position: null, number: 32, age: null },
  { id: 9327, name: "S. Brown", korean_name: "사니 브라운", team_id: 316, position: "Attacker", number: 32, age: 19 },
  { id: 9309, name: "M. Tashiro", korean_name: "타시로 마사히로", team_id: 316, position: "Defender", number: 37, age: 32 },
  { id: 9318, name: "J. Ikeda", korean_name: "이케다 준야", team_id: 316, position: "Defender", number: 40, age: 29 },
  { id: 9312, name: "Y. Hashimoto", korean_name: "하시모토 유키", team_id: 316, position: "Midfielder", number: 47, age: 23 },
  { id: 9333, name: "S. Sato", korean_name: "사토 슌", team_id: 316, position: "Attacker", number: 50, age: 22 },
  { id: 9304, name: "K. Suganuma", korean_name: "스가누마 카즈야", team_id: 316, position: "Goalkeeper", number: 51, age: 24 },
  { id: 9336, name: "H. Maeda", korean_name: "마에다 하루토", team_id: 316, position: "Attacker", number: 53, age: 17 },
  { id: 9310, name: "T. Shichi", korean_name: "시치 타쿠야", team_id: 316, position: "Defender", number: 77, age: 32 },
  { id: 9321, name: "D. Matsuoka", korean_name: "마츠오카 다이키", team_id: 316, position: "Midfielder", number: 88, age: 24 },
  { id: 9339, name: "H. Maeda", korean_name: "마에다 히로키", team_id: 316, position: null, number: null, age: null },
  { id: 9340, name: "K. Suganuma", korean_name: "스가누마 코타", team_id: 316, position: null, number: null, age: null },
  { id: 9338, name: "M. Kim", korean_name: "김민혁", team_id: 316, position: null, number: null, age: null },
  { id: 9323, name: "S. Takemoto", korean_name: "타케모토 슌", team_id: 316, position: "Midfielder", number: null, age: 16 },
];

// Cerezo Osaka (세레소 오사카) - Team ID: 291
export const CEREZO_OSAKA_PLAYERS: PlayerMapping[] = [
  { id: 9345, name: "K. Fukui", korean_name: "후쿠이 켄타로", team_id: 291, position: "Goalkeeper", number: 1, age: 30 },
  { id: 9370, name: "N. Matsumoto", korean_name: "마츠모토 나오키", team_id: 291, position: "Midfielder", number: 2, age: 24 },
  { id: 9348, name: "T. Nakamura", korean_name: "나카무라 타카히로", team_id: 291, position: "Defender", number: 2, age: 24 },
  { id: 9351, name: "R. Shindo", korean_name: "신도 료타", team_id: 291, position: "Defender", number: 3, age: 29 },
  { id: 9365, name: "Y. Hirano", korean_name: "히라노 요시토", team_id: 291, position: "Midfielder", number: 4, age: 29 },
  { id: 9368, name: "H. Kida", korean_name: "키다 히로시", team_id: 291, position: "Midfielder", number: 5, age: 25 },
  { id: 9357, name: "K. Noborizato", korean_name: "노보리자토 켄타", team_id: 291, position: "Defender", number: 6, age: 35 },
  { id: 9359, name: "S. Uejo", korean_name: "우에조 신야", team_id: 291, position: "Midfielder", number: 7, age: 28 },
  { id: 9367, name: "R. Osako", korean_name: "오사코 료타", team_id: 291, position: "Midfielder", number: 8, age: 21 },
  { id: 9369, name: "S. Kagawa", korean_name: "카가와 신지", team_id: 291, position: "Midfielder", number: 8, age: 36 },
  { id: 9374, name: "Rafael Ratão", korean_name: "하파엘 하타오", team_id: 291, position: "Attacker", number: 9, age: 30 },
  { id: 9361, name: "S. Tanaka", korean_name: "타나카 슌야", team_id: 291, position: "Midfielder", number: 10, age: 28 },
  { id: 9377, name: "Thiago Andrade", korean_name: "치아구 안드라지", team_id: 291, position: "Midfielder", number: 11, age: 25 },
  { id: 9372, name: "M. Nakajima", korean_name: "나카지마 마사토", team_id: 291, position: "Attacker", number: 13, age: 26 },
  { id: 9277, name: "K. Funaki", korean_name: "후나키 켄타", team_id: 291, position: "Defender", number: 14, age: 27 },
  { id: 9353, name: "H. Okuda", korean_name: "오쿠다 히로키", team_id: 291, position: "Defender", number: 16, age: 24 },
  { id: 9364, name: "R. Sakata", korean_name: "사카타 료타", team_id: 291, position: "Midfielder", number: 17, age: 21 },
  { id: 9342, name: "Kim Jin-Hyeon", korean_name: "김진현", team_id: 291, position: "Goalkeeper", number: 21, age: 38 },
  { id: 9354, name: "Niko Takahashi Cendagorta", korean_name: "니코 타카하시 센다고르타", team_id: 291, position: "Defender", number: 22, age: 20 },
  { id: 9346, name: "Dion-Johan Cools", korean_name: "디온 요한 쿨스", team_id: 291, position: "Defender", number: 27, age: 29 },
  { id: 9373, name: "K. Furuyama", korean_name: "후루야마 카이", team_id: 291, position: "Attacker", number: 29, age: 23 },
  { id: 9352, name: "R. Nishio", korean_name: "니시오 료타", team_id: 291, position: "Defender", number: 33, age: 24 },
  { id: 3377, name: "K. Yoshino", korean_name: "요시노 카즈키", team_id: 291, position: "Midfielder", number: 35, age: 31 },
  { id: 9347, name: "Chimezie Kai Ezemuokwe", korean_name: "치메지 카이 에제무오크웨", team_id: 291, position: "Defender", number: 43, age: 16 },
  { id: 9350, name: "S. Hatanaka", korean_name: "하타나카 슌야", team_id: 291, position: "Defender", number: 44, age: 30 },
  { id: 9341, name: "K. Makiguchi", korean_name: "마키구치 켄타", team_id: 291, position: "Goalkeeper", number: 47, age: 21 },
  { id: 9360, name: "M. Shibayama", korean_name: "시바야마 마사히로", team_id: 291, position: "Midfielder", number: 48, age: 23 },
  { id: 9376, name: "Vitor Bueno", korean_name: "비토르 부에노", team_id: 291, position: "Attacker", number: 55, age: 31 },
  { id: 9349, name: "A. Ohata", korean_name: "오하타 아키라", team_id: 291, position: "Defender", number: 66, age: 24 },
  { id: 9358, name: "Lucas Fernandes", korean_name: "루카스 페르난데스", team_id: 291, position: "Midfielder", number: 77, age: 31 },
  { id: 9344, name: "Go Kambayashi", korean_name: "칸바야시 고", team_id: 291, position: "Goalkeeper", number: null, age: 23 },
  { id: 9343, name: "K. Isibor", korean_name: "이시보르 켄타", team_id: 291, position: "Goalkeeper", number: null, age: 18 },
  { id: 9371, name: "R. Onoda", korean_name: "오노다 료", team_id: 291, position: "Attacker", number: null, age: 18 },
];

// Fagiano Okayama (파지아노 오카야마) - Team ID: 310
export const FAGIANO_OKAYAMA_PLAYERS: PlayerMapping[] = [
  { id: 9379, name: "M. Sasaki", korean_name: "사사키 마사히로", team_id: 310, position: "Goalkeeper", number: 1, age: 23 },
  { id: 9386, name: "Y. Tatsuta", korean_name: "타츠타 유야", team_id: 310, position: "Defender", number: 2, age: 27 },
  { id: 9392, name: "K. Fujii", korean_name: "후지이 카즈마", team_id: 310, position: "Midfielder", number: 3, age: 22 },
  { id: 9423, name: "K. Fujii", korean_name: "후지이 켄타", team_id: 310, position: null, number: 3, age: null },
  { id: 9391, name: "K. Abe", korean_name: "아베 켄타로", team_id: 310, position: "Defender", number: 4, age: 26 },
  { id: 9416, name: "K. Abe", korean_name: "아베 코타로", team_id: 310, position: null, number: 4, age: null },
  { id: 9387, name: "Y. Yanagi", korean_name: "야나기 유타", team_id: 310, position: "Defender", number: 5, age: 31 },
  { id: 9405, name: "Y. Wakasa", korean_name: "와카사 유키", team_id: 310, position: "Midfielder", number: 6, age: 29 },
  { id: 9402, name: "R. Takeuchi", korean_name: "타케우치 료타", team_id: 310, position: "Midfielder", number: 7, age: 34 },
  { id: 9404, name: "A. Esaka", korean_name: "에사카 아츠시", team_id: 310, position: "Attacker", number: 8, age: 33 },
  { id: 9408, name: "Gleyson", korean_name: "글레이송", team_id: 310, position: "Attacker", number: 11, age: 29 },
  { id: 9410, name: "R. Ota", korean_name: "오타 료타", team_id: 310, position: "Attacker", number: 11, age: 23 },
  { id: 9378, name: "J. Kanayama", korean_name: "카나야마 준", team_id: 310, position: "Goalkeeper", number: 13, age: 37 },
  { id: 9401, name: "R. Tabei", korean_name: "타베이 료", team_id: 310, position: "Midfielder", number: 14, age: 26 },
  { id: 9384, name: "K. Kudo", korean_name: "쿠도 카즈키", team_id: 310, position: "Defender", number: 15, age: 22 },
  { id: 9394, name: "Y. Iesaka", korean_name: "이에사카 유야", team_id: 310, position: "Midfielder", number: 16, age: 23 },
  { id: 9406, name: "R. Sueyoshi", korean_name: "스에요시 료타", team_id: 310, position: "Midfielder", number: 17, age: 29 },
  { id: 9390, name: "D. Tagami", korean_name: "타가미 다이키", team_id: 310, position: "Defender", number: 18, age: 32 },
  { id: 9419, name: "H. Iwabuchi", korean_name: "이와부치 히로키", team_id: 310, position: null, number: 19, age: null },
  { id: 9396, name: "H. Iwabuchi", korean_name: "이와부치 히로시", team_id: 310, position: "Midfielder", number: 19, age: 28 },
  { id: 9380, name: "K. Kawakami", korean_name: "카와카미 켄타", team_id: 310, position: "Goalkeeper", number: 21, age: 24 },
  { id: 9414, name: "K. Ichimi", korean_name: "이치미 카즈키", team_id: 310, position: "Attacker", number: 22, age: 28 },
  { id: 9400, name: "R. Saga", korean_name: "사가 료타", team_id: 310, position: "Midfielder", number: 23, age: 27 },
  { id: 9399, name: "I. Fujita", korean_name: "후지타 이사오", team_id: 310, position: "Midfielder", number: 24, age: 34 },
  { id: 9403, name: "T. Kimura", korean_name: "키무라 타쿠마", team_id: 310, position: "Attacker", number: 27, age: 27 },
  { id: 9418, name: "T. Kimura", korean_name: "키무라 토모야", team_id: 310, position: null, number: 27, age: null },
  { id: 9393, name: "M. Matsumoto", korean_name: "마츠모토 미츠루", team_id: 310, position: "Midfielder", number: 28, age: 30 },
  { id: 9412, name: "K. Saito", korean_name: "사이토 카즈야", team_id: 310, position: "Attacker", number: 29, age: 32 },
  { id: 9397, name: "Y. Kamiya", korean_name: "카미야 유키", team_id: 310, position: "Midfielder", number: 33, age: 28 },
  { id: 9398, name: "R. Sato", korean_name: "사토 료", team_id: 310, position: "Midfielder", number: 39, age: 19 },
  { id: 9284, name: "E. Miyamoto", korean_name: "미야모토 에이지", team_id: 310, position: "Midfielder", number: 41, age: 27 },
  { id: 9421, name: "Y. Suzuki", korean_name: "스즈키 유키", team_id: 310, position: null, number: 43, age: null },
  { id: 9385, name: "Y. Suzuki", korean_name: "스즈키 유타", team_id: 310, position: "Defender", number: 43, age: 27 },
  { id: 9382, name: "S. Brodersen", korean_name: "스테판 브로더센", team_id: 310, position: "Goalkeeper", number: 49, age: 28 },
  { id: 9422, name: "H. Kato", korean_name: "카토 하루키", team_id: 310, position: null, number: 50, age: null },
  { id: 9407, name: "H. Kato", korean_name: "카토 히로시", team_id: 310, position: "Midfielder", number: 50, age: 24 },
  { id: 9383, name: "T. Yanagi", korean_name: "야나기 타카히로", team_id: 310, position: "Defender", number: 88, age: 28 },
  { id: 9409, name: "Werik Popó", korean_name: "베리크 포포", team_id: 310, position: "Attacker", number: 98, age: 24 },
  { id: 9420, name: "Lucao", korean_name: "루카오", team_id: 310, position: null, number: 99, age: null },
  { id: 9415, name: "Lucão", korean_name: "루카오", team_id: 310, position: "Attacker", number: 99, age: 30 },
  { id: 9413, name: "K. Suemune", korean_name: "스에무네 카이", team_id: 310, position: "Attacker", number: null, age: 18 },
  { id: 9388, name: "R. Senda", korean_name: "센다 료타", team_id: 310, position: "Defender", number: null, age: 18 },
  { id: 9417, name: "R. Tabei", korean_name: "타베이 료타", team_id: 310, position: null, number: null, age: null },
  { id: 9424, name: "Y. Iesaka", korean_name: "이에사카 유지", team_id: 310, position: null, number: null, age: null },
];

// FC Tokyo (FC 도쿄) - Team ID: 292
export const FC_TOKYO_PLAYERS: PlayerMapping[] = [
  { id: 9439, name: "S. Muroya", korean_name: "무로야 세이", team_id: 292, position: "Defender", number: 2, age: 31 },
  { id: 9433, name: "Baek In-Hwan", korean_name: "백인환", team_id: 292, position: "Defender", number: 3, age: 20 },
  { id: 9430, name: "M. Morishige", korean_name: "모리시게 마사토", team_id: 292, position: "Defender", number: 3, age: 38 },
  { id: 9436, name: "Y. Kimoto", korean_name: "키모토 야스유키", team_id: 292, position: "Defender", number: 4, age: 32 },
  { id: 9434, name: "S. Kimura", korean_name: "키무라 슌", team_id: 292, position: "Defender", number: 5, age: 24 },
  { id: 9440, name: "Y. Nagatomo", korean_name: "나가토모 유토", team_id: 292, position: "Defender", number: 5, age: 39 },
  { id: 9441, name: "K. Bangnagande", korean_name: "카가 반냐간데", team_id: 292, position: "Defender", number: 6, age: 24 },
  { id: 9447, name: "S. Anzai", korean_name: "안자이 슌스케", team_id: 292, position: "Midfielder", number: 7, age: 23 },
  { id: 9453, name: "T. Ko", korean_name: "고 타쿠마", team_id: 292, position: "Midfielder", number: 8, age: 27 },
  { id: 9442, name: "K. Higashi", korean_name: "히가시 케이고", team_id: 292, position: "Midfielder", number: 10, age: 35 },
  { id: 9455, name: "T. Ogashiwa", korean_name: "오가시와 타카시", team_id: 292, position: "Attacker", number: 11, age: 27 },
  { id: 9426, name: "G. Hatano", korean_name: "하타노 고", team_id: 292, position: "Goalkeeper", number: 13, age: 27 },
  { id: 9454, name: "K. Yamashita", korean_name: "야마시타 켄타", team_id: 292, position: "Attacker", number: 14, age: 29 },
  { id: 9463, name: "K. Sato", korean_name: "사토 켄타", team_id: 292, position: "Midfielder", number: 16, age: 24 },
  { id: 9449, name: "K. Tsukagawa", korean_name: "츠카가와 켄타로", team_id: 292, position: "Midfielder", number: 16, age: 31 },
  { id: 9452, name: "T. Terayama", korean_name: "테라야마 타케루", team_id: 292, position: "Midfielder", number: 17, age: 25 },
  { id: 9448, name: "K. Hashimoto", korean_name: "하시모토 켄타", team_id: 292, position: "Midfielder", number: 18, age: 32 },
  { id: 9462, name: "Marcelo Ryan", korean_name: "마르셀로 라이언", team_id: 292, position: "Attacker", number: 19, age: 23 },
  { id: 9451, name: "K. Endo", korean_name: "엔도 케이타", team_id: 292, position: "Midfielder", number: 22, age: 28 },
  { id: 9435, name: "A. Scholz", korean_name: "야쿠프 슐츠", team_id: 292, position: "Defender", number: 24, age: 33 },
  { id: 9465, name: "T. Kominato", korean_name: "코미나토 타쿠", team_id: 292, position: null, number: 25, age: null },
  { id: 9446, name: "Kyota Tokiwa", korean_name: "토키와 쿄타", team_id: 292, position: "Midfielder", number: 27, age: 23 },
  { id: 9459, name: "L. Nozawa", korean_name: "노자와 렌", team_id: 292, position: "Attacker", number: 28, age: 22 },
  { id: 9438, name: "T. Oka", korean_name: "오카 타케루", team_id: 292, position: "Defender", number: 30, age: 24 },
  { id: 9428, name: "M. Kobayashi", korean_name: "코바야시 마사토", team_id: 292, position: "Goalkeeper", number: 31, age: 20 },
  { id: 9431, name: "K. Doi", korean_name: "도이 켄타", team_id: 292, position: "Defender", number: 32, age: 21 },
  { id: 9450, name: "K. Tawaratsumida", korean_name: "타와라츠미다 카이", team_id: 292, position: "Midfielder", number: 33, age: 21 },
  { id: 9443, name: "H. Nishido", korean_name: "니시도 히로키", team_id: 292, position: "Midfielder", number: 36, age: 24 },
  { id: 9445, name: "K. Koizumi", korean_name: "코이즈미 켄타", team_id: 292, position: "Midfielder", number: 37, age: 30 },
  { id: 9461, name: "T. Nakagawa", korean_name: "나카가와 테루히토", team_id: 292, position: "Attacker", number: 39, age: 33 },
  { id: 9464, name: "Marcos Guilherme de Almeida Santos Matos", korean_name: "마르코스 기예르미", team_id: 292, position: "Midfielder", number: 40, age: 30 },
  { id: 9427, name: "T. Nozawa", korean_name: "노자와 타이치", team_id: 292, position: "Goalkeeper", number: 41, age: 23 },
  { id: 9437, name: "Henrique Trevisan", korean_name: "엔히키 트레비잔", team_id: 292, position: "Defender", number: 44, age: 28 },
  { id: 9444, name: "Y. Arai", korean_name: "아라이 유키", team_id: 292, position: "Midfielder", number: 48, age: 21 },
  { id: 9457, name: "M. Kitahara", korean_name: "키타하라 마사토", team_id: 292, position: "Attacker", number: 77, age: 16 },
  { id: 9425, name: "Kim Seung-Gyu", korean_name: "김승규", team_id: 292, position: "Goalkeeper", number: 81, age: 35 },
  { id: 9458, name: "T. Yamaguchi", korean_name: "야마구치 타케루", team_id: 292, position: "Attacker", number: 88, age: 19 },
  { id: 9456, name: "Everton Galdino", korean_name: "에베르통 갈디노", team_id: 292, position: "Attacker", number: 98, age: 28 },
  { id: 9432, name: "K. Shirai", korean_name: "시라이 켄타", team_id: 292, position: "Defender", number: 99, age: 31 },
  { id: 9429, name: "W. Goto", korean_name: "고토 와타루", team_id: 292, position: "Goalkeeper", number: null, age: 19 },
];

// Gamba Osaka (감바 오사카) - Team ID: 293
export const GAMBA_OSAKA_PLAYERS: PlayerMapping[] = [
  { id: 9468, name: "M. Higashiguchi", korean_name: "히가시구치 마사아키", team_id: 293, position: "Goalkeeper", number: 1, age: 39 },
  { id: 9470, name: "S. Fukuoka", korean_name: "후쿠오카 슌스케", team_id: 293, position: "Defender", number: 2, age: 30 },
  { id: 9473, name: "R. Handa", korean_name: "한다 료타", team_id: 293, position: "Defender", number: 3, age: 23 },
  { id: 9476, name: "K. Kurokawa", korean_name: "쿠로카와 켄타", team_id: 293, position: "Defender", number: 4, age: 28 },
  { id: 9472, name: "G. Miura", korean_name: "미우라 겐키", team_id: 293, position: "Defender", number: 5, age: 30 },
  { id: 9488, name: "T. Usami", korean_name: "우사미 타카시", team_id: 293, position: "Attacker", number: 7, age: 33 },
  { id: 9491, name: "D. Hayashi", korean_name: "하야시 다이스케", team_id: 293, position: "Attacker", number: 8, age: 28 },
  { id: 9487, name: "R. Meshino", korean_name: "메시노 료타로", team_id: 293, position: "Attacker", number: 8, age: 27 },
  { id: 9480, name: "S. Kurata", korean_name: "쿠라타 슈", team_id: 293, position: "Midfielder", number: 10, age: 37 },
  { id: 9489, name: "I. Jebali", korean_name: "이삼 제발리", team_id: 293, position: "Attacker", number: 11, age: 34 },
  { id: 9482, name: "S. Abe", korean_name: "아베 슈토", team_id: 293, position: "Midfielder", number: 13, age: 28 },
  { id: 9478, name: "T. Kishimoto", korean_name: "키시모토 타케후사", team_id: 293, position: "Defender", number: 15, age: 28 },
  { id: 9483, name: "T. Suzuki", korean_name: "스즈키 토쿠라", team_id: 293, position: "Midfielder", number: 16, age: 28 },
  { id: 9490, name: "R. Yamashita", korean_name: "야마시타 료", team_id: 293, position: "Midfielder", number: 17, age: 28 },
  { id: 9467, name: "R. Araki", korean_name: "아라키 류세이", team_id: 293, position: "Goalkeeper", number: 18, age: 18 },
  { id: 9474, name: "S. Nakatani", korean_name: "나카타니 쇼야", team_id: 293, position: "Defender", number: 20, age: 29 },
  { id: 9475, name: "R. Hatsuse", korean_name: "하츠세 료헤이", team_id: 293, position: "Defender", number: 21, age: 28 },
  { id: 9469, name: "J. Ichimori", korean_name: "이치모리 준", team_id: 293, position: "Goalkeeper", number: 22, age: 34 },
  { id: 9492, name: "D. Hümmet", korean_name: "다비드 휨메트", team_id: 293, position: "Attacker", number: 23, age: 29 },
  { id: 9471, name: "Y. Egawa", korean_name: "에가와 유우", team_id: 293, position: "Defender", number: 24, age: 25 },
  { id: 9485, name: "R. Mito", korean_name: "미토 료타", team_id: 293, position: "Midfielder", number: 27, age: 23 },
  { id: 9466, name: "Zhang Ao lin", korean_name: "장아오린", team_id: 293, position: "Goalkeeper", number: 31, age: 20 },
  { id: 9498, name: "T. Yamamoto", korean_name: "야마모토", team_id: 293, position: null, number: 36, age: null },
  { id: 5465, name: "Gaku Nawata", korean_name: "나와타 가쿠", team_id: 293, position: "Midfielder", number: 38, age: 19 },
  { id: 9486, name: "H. Minamino", korean_name: "미나미노 히로키", team_id: 293, position: "Attacker", number: 42, age: 21 },
  { id: 9500, name: "Y. Nobata", korean_name: "노바타", team_id: 293, position: null, number: 43, age: null },
  { id: 9479, name: "K. Okunuki", korean_name: "오쿠누키 코우세이", team_id: 293, position: "Midfielder", number: 44, age: 26 },
  { id: 9484, name: "Juan Alano", korean_name: "후안 알라노", team_id: 293, position: "Midfielder", number: 47, age: 29 },
  { id: 9477, name: "S. Sasaki", korean_name: "사사키 쇼타", team_id: 293, position: "Defender", number: 67, age: 25 },
  { id: 9495, name: "Welton Felipe", korean_name: "웰통 펠리페", team_id: 293, position: "Midfielder", number: 97, age: 28 },
  { id: 9499, name: "T. Yamamoto", korean_name: "야마모토", team_id: 293, position: null, number: null, age: null },
];

// Kashima (가시마 앤틀러스) - Team ID: 290
export const KASHIMA_PLAYERS: PlayerMapping[] = [
  { id: 9504, name: "T. Hayakawa", korean_name: "하야카와 타쿠야", team_id: 290, position: "Goalkeeper", number: 1, age: 26 },
  { id: 9512, name: "K. Anzai", korean_name: "안자이 켄타", team_id: 290, position: "Defender", number: 2, age: 30 },
  { id: 9506, name: "Kim Tae-Hyeon", korean_name: "김태현", team_id: 290, position: "Defender", number: 3, age: 25 },
  { id: 9515, name: "I. Sekigawa", korean_name: "세키가와 이사무", team_id: 290, position: "Defender", number: 5, age: 25 },
  { id: 9522, name: "K. Misao", korean_name: "미사오 켄타", team_id: 290, position: "Midfielder", number: 6, age: 29 },
  { id: 9505, name: "R. Ogawa", korean_name: "오가와 료헤이", team_id: 290, position: "Defender", number: 7, age: 29 },
  { id: 9526, name: "Léo Ceará", korean_name: "레오 세아라", team_id: 290, position: "Attacker", number: 9, age: 30 },
  { id: 9517, name: "G. Shibasaki", korean_name: "시바사키 가쿠", team_id: 290, position: "Midfielder", number: 10, age: 33 },
  { id: 9532, name: "K. Tagawa", korean_name: "타가와 켄타", team_id: 290, position: "Attacker", number: 11, age: 26 },
  { id: 9529, name: "K. Chinen", korean_name: "치넨 켄타", team_id: 290, position: "Attacker", number: 13, age: 30 },
  { id: 9519, name: "Y. Higuchi", korean_name: "히구치 유야", team_id: 290, position: "Midfielder", number: 14, age: 29 },
  { id: 9523, name: "Talles", korean_name: "탈레스", team_id: 290, position: "Attacker", number: 17, age: 27 },
  { id: 9533, name: "S. Morooka", korean_name: "모로오카 신", team_id: 290, position: "Attacker", number: 19, age: 25 },
  { id: 9521, name: "Y. Funabashi", korean_name: "후나바시 유타", team_id: 290, position: "Midfielder", number: 20, age: 23 },
  { id: 9507, name: "K. Nono", korean_name: "노노 케이타", team_id: 290, position: "Defender", number: 22, age: 23 },
  { id: 9511, name: "K. Tsukui", korean_name: "츠쿠이 켄타", team_id: 290, position: "Defender", number: 23, age: 21 },
  { id: 9513, name: "R. Koike", korean_name: "코이케 료타", team_id: 290, position: "Defender", number: 25, age: 30 },
  { id: 9520, name: "Y. Matsumura", korean_name: "마츠무라 유키", team_id: 290, position: "Midfielder", number: 27, age: 24 },
  { id: 9509, name: "S. Mizoguchi", korean_name: "미조구치 쇼타", team_id: 290, position: "Defender", number: 28, age: 21 },
  { id: 9502, name: "Y. Kajikawa", korean_name: "카지카와 유키", team_id: 290, position: "Goalkeeper", number: 29, age: 34 },
  { id: 9503, name: "T. Yamada", korean_name: "야마다 타쿠마", team_id: 290, position: "Goalkeeper", number: 31, age: 23 },
  { id: 9516, name: "H. Matsumoto", korean_name: "마츠모토 하루키", team_id: 290, position: "Defender", number: 32, age: 19 },
  { id: 9528, name: "H. Tokuda", korean_name: "토쿠다 히로키", team_id: 290, position: "Attacker", number: 34, age: 18 },
  { id: 9508, name: "M. Sato", korean_name: "사토 마사히로", team_id: 290, position: "Defender", number: 36, age: 18 },
  { id: 9501, name: "Park Eui-Jeong", korean_name: "박의정", team_id: 290, position: "Goalkeeper", number: 38, age: 21 },
  { id: 9524, name: "Y. Shimoda", korean_name: "시모다 유키", team_id: 290, position: "Midfielder", number: 40, age: 21 },
  { id: 9531, name: "Y. Suzuki", korean_name: "스즈키 유마", team_id: 290, position: "Attacker", number: 40, age: 29 },
  { id: 9530, name: "M. Yoshida", korean_name: "요시다 마사토", team_id: 290, position: "Attacker", number: 45, age: 17 },
  { id: 9510, name: "N. Ueda", korean_name: "우에다 나오미치", team_id: 290, position: "Defender", number: 55, age: 31 },
  { id: 9518, name: "R. Araki", korean_name: "아라키 료", team_id: 290, position: "Midfielder", number: 71, age: 23 },
  { id: 9527, name: "A. Čavrić", korean_name: "알렉산다르 차브리치", team_id: 290, position: "Midfielder", number: 77, age: 31 },
  { id: 9535, name: "A. Motosuna", korean_name: "모토스나", team_id: 290, position: null, number: null, age: null },
  { id: 9534, name: "M. Yoshida", korean_name: "요시다", team_id: 290, position: null, number: null, age: null },
];

// Kashiwa Reysol (가시와 레이솔) - Team ID: 281
export const KASHIWA_REYSOL_PLAYERS: PlayerMapping[] = [
  { id: 9537, name: "H. Saruta", korean_name: "사루타 히로키", team_id: 281, position: "Goalkeeper", number: 1, age: 26 },
  { id: 9549, name: "H. Mitsumaru", korean_name: "미츠마루 히로키", team_id: 281, position: "Defender", number: 2, age: 32 },
  { id: 9540, name: "Diego", korean_name: "디에고", team_id: 281, position: "Midfielder", number: 3, age: 30 },
  { id: 9546, name: "T. Koga", korean_name: "코가 타쿠마", team_id: 281, position: "Defender", number: 4, age: 27 },
  { id: 9543, name: "H. Tanaka", korean_name: "타나카 히로키", team_id: 281, position: "Defender", number: 5, age: 22 },
  { id: 9561, name: "Y. Yamada", korean_name: "야마다 유키", team_id: 281, position: "Midfielder", number: 6, age: 25 },
  { id: 9555, name: "Y. Koizumi", korean_name: "코이즈미 유키", team_id: 281, position: "Attacker", number: 8, age: 29 },
  { id: 9575, name: "M. Hosoya", korean_name: "호소야 마코토", team_id: 281, position: "Attacker", number: 9, age: 24 },
  { id: 9560, name: "Masa", korean_name: "마사", team_id: 281, position: "Attacker", number: 11, age: 26 },
  { id: 9550, name: "T. Inukai", korean_name: "이누카이 타쿠야", team_id: 281, position: "Defender", number: 13, age: 32 },
  { id: 9558, name: "T. Koyamatsu", korean_name: "코야마츠 타쿠마", team_id: 281, position: "Midfielder", number: 14, age: 30 },
  { id: 9301, name: "Y. Komi", korean_name: "코미 유우", team_id: 281, position: "Attacker", number: 15, age: 23 },
  { id: 9548, name: "E. Katayama", korean_name: "카타야마 에이지", team_id: 281, position: "Defender", number: 16, age: 34 },
  { id: 9554, name: "K. Tezuka", korean_name: "테즈카 켄타", team_id: 281, position: "Midfielder", number: 17, age: 29 },
  { id: 9571, name: "Y. Kakita", korean_name: "카키타 유타", team_id: 281, position: "Attacker", number: 18, age: 28 },
  { id: 9556, name: "F. Mohamado", korean_name: "파리드 모하마도", team_id: 281, position: "Midfielder", number: 19, age: 21 },
  { id: 9552, name: "H. Nakama", korean_name: "나카마 히로시", team_id: 281, position: "Attacker", number: 19, age: 33 },
  { id: 9553, name: "Y. Konishi", korean_name: "코니시 유키", team_id: 281, position: "Midfielder", number: 21, age: 27 },
  { id: 9544, name: "H. Noda", korean_name: "노다 히로키", team_id: 281, position: "Defender", number: 22, age: 28 },
  { id: 9567, name: "T. Kubo", korean_name: "쿠보 타쿠야", team_id: 281, position: "Midfielder", number: 24, age: 26 },
  { id: 9538, name: "R. Kojima", korean_name: "코지마 료타", team_id: 281, position: "Goalkeeper", number: 25, age: 28 },
  { id: 9542, name: "D. Sugioka", korean_name: "스기오카 다이키", team_id: 281, position: "Defender", number: 26, age: 27 },
  { id: 9570, name: "K. Kumasaka", korean_name: "쿠마사카 켄타", team_id: 281, position: "Midfielder", number: 27, age: 24 },
  { id: 9565, name: "S. Toshima", korean_name: "토시마 신야", team_id: 281, position: "Midfielder", number: 28, age: 30 },
  { id: 9577, name: "Kengo Nagai", korean_name: "나가이 켄고", team_id: 281, position: "Goalkeeper", number: 29, age: 31 },
  { id: 9293, name: "T. Shimamura", korean_name: "시마무라 타이치", team_id: 281, position: "Midfielder", number: 29, age: 26 },
  { id: 9557, name: "S. Naruse", korean_name: "나루세 쇼타", team_id: 281, position: "Midfielder", number: 31, age: 24 },
  { id: 9578, name: "Y. Yamanouchi", korean_name: "야마노우치", team_id: 281, position: null, number: 32, age: null },
  { id: 9291, name: "E. Shirai", korean_name: "시라이 에이타", team_id: 281, position: "Midfielder", number: 33, age: 30 },
  { id: 9573, name: "S. Nakajima", korean_name: "나카지마 쇼", team_id: 281, position: "Attacker", number: 37, age: 23 },
  { id: 9551, name: "N. Nakagawa", korean_name: "나카가와 나오키", team_id: 281, position: "Midfielder", number: 39, age: 23 },
  { id: 9566, name: "R. Harakawa", korean_name: "하라카와 료", team_id: 281, position: "Midfielder", number: 40, age: 32 },
  { id: 9539, name: "D. Sakata", korean_name: "사카타 다이키", team_id: 281, position: "Goalkeeper", number: 41, age: 31 },
  { id: 9545, name: "W. Harada", korean_name: "하라다 와타루", team_id: 281, position: "Midfielder", number: 42, age: 29 },
  { id: 9536, name: "K. Matsumoto", korean_name: "마츠모토 켄타", team_id: 281, position: "Goalkeeper", number: 46, age: 28 },
  { id: 9563, name: "K. Kumasawa", korean_name: "쿠마사와 켄타", team_id: 281, position: "Midfielder", number: 48, age: 24 },
  { id: 9541, name: "S. Baba", korean_name: "바바 슌스케", team_id: 281, position: "Defender", number: 88, age: 24 },
  { id: 9559, name: "K. Chonan", korean_name: "초난 켄타", team_id: 281, position: "Midfielder", number: null, age: 15 },
  { id: 9547, name: "T. Kuwata", korean_name: "쿠와타 타쿠마", team_id: 281, position: "Defender", number: null, age: 23 },
  { id: 9572, name: "Y. Furusawa", korean_name: "후루사와 유키", team_id: 281, position: "Attacker", number: null, age: 22 },
  { id: 9569, name: "Y. Kamo", korean_name: "카모 유키", team_id: 281, position: "Midfielder", number: null, age: 17 },
];

// Kawasaki Frontale (가와사키 프론탈레) - Team ID: 294
export const KAWASAKI_FRONTALE_PLAYERS: PlayerMapping[] = [
  { id: 9584, name: "Jung Sung-Ryong", korean_name: "정성룡", team_id: 294, position: "Goalkeeper", number: 1, age: 40 },
  { id: 120, name: "K. Takai", korean_name: "타카이 켄타", team_id: 294, position: "Defender", number: 2, age: 21 },
  { id: 9596, name: "Jesiel", korean_name: "제시엘", team_id: 294, position: "Defender", number: 4, age: 31 },
  { id: 9588, name: "A. Sasaki", korean_name: "사사키 아키히로", team_id: 294, position: "Defender", number: 5, age: 25 },
  { id: 9599, name: "Y. Yamamoto", korean_name: "야마모토 유키", team_id: 294, position: "Midfielder", number: 6, age: 28 },
  { id: 9591, name: "S. Kurumaya", korean_name: "쿠루마야 쇼고", team_id: 294, position: "Defender", number: 7, age: 33 },
  { id: 9604, name: "K. Tachibanada", korean_name: "타치바나다 켄타", team_id: 294, position: "Midfielder", number: 8, age: 27 },
  { id: 9611, name: "Erison", korean_name: "에리송", team_id: 294, position: "Attacker", number: 9, age: 26 },
  { id: 9609, name: "R. Oshima", korean_name: "오시마 료타", team_id: 294, position: "Midfielder", number: 10, age: 32 },
  { id: 9613, name: "Y. Kobayashi", korean_name: "코바야시 유", team_id: 294, position: "Attacker", number: 11, age: 38 },
  { id: 9593, name: "S. Miura", korean_name: "미우라 슌", team_id: 294, position: "Defender", number: 13, age: 25 },
  { id: 9603, name: "Y. Wakizaka", korean_name: "와키자카 야스토", team_id: 294, position: "Midfielder", number: 14, age: 30 },
  { id: 9592, name: "S. Tanabe", korean_name: "타나베 쇼고", team_id: 294, position: "Defender", number: 15, age: 23 },
  { id: 9608, name: "Y. Ozeki", korean_name: "오제키 유키", team_id: 294, position: "Midfielder", number: 16, age: 20 },
  { id: 9614, name: "T. Ito", korean_name: "이토 타쿠마", team_id: 294, position: "Midfielder", number: 17, age: 28 },
  { id: 9562, name: "Y. Segawa", korean_name: "세가와 유키", team_id: 294, position: "Midfielder", number: 18, age: 31 },
  { id: 9607, name: "S. Kawahara", korean_name: "카와하라 소타", team_id: 294, position: "Midfielder", number: 19, age: 27 },
  { id: 9585, name: "S. Ando", korean_name: "안도 소타", team_id: 294, position: "Goalkeeper", number: 21, age: 35 },
  { id: 9589, name: "F. Uremović", korean_name: "프란코 우레모비치", team_id: 294, position: "Defender", number: 22, age: 28 },
  { id: 9610, name: "Marcinho", korean_name: "마르시뉴", team_id: 294, position: "Midfielder", number: 23, age: 30 },
  { id: 9615, name: "T. Miyagi", korean_name: "미야기 텐", team_id: 294, position: "Attacker", number: 24, age: 24 },
  { id: 9602, name: "H. Yamauchi", korean_name: "야마우치 히로토", team_id: 294, position: "Midfielder", number: 26, age: 24 },
  { id: 9586, name: "R. Kamihashi", korean_name: "카미하시 료", team_id: 294, position: "Defender", number: 27, age: 23 },
  { id: 9601, name: "Patrick Verhon", korean_name: "패트릭 베르혼", team_id: 294, position: "Midfielder", number: 28, age: 21 },
  { id: 9616, name: "Toya Myogan", korean_name: "묘간 토야", team_id: 294, position: "Midfielder", number: 29, age: 21 },
  { id: 9590, name: "H. Noda", korean_name: "노다 히로키", team_id: 294, position: "Defender", number: 30, age: 19 },
  { id: 9619, name: "H. Noda", korean_name: "노다", team_id: 294, position: null, number: 30, age: null },
  { id: 9595, name: "S. van Wermeskerken", korean_name: "스벤 반 베르메스케르켄", team_id: 294, position: "Defender", number: 31, age: 31 },
  { id: 9587, name: "Y. Maruyama", korean_name: "마루야마 유키", team_id: 294, position: "Defender", number: 35, age: 36 },
  { id: 9617, name: "K. Mochiyama", korean_name: "모치야마", team_id: 294, position: null, number: 36, age: null },
  { id: 9618, name: "K. Tsuchiya", korean_name: "츠치야", team_id: 294, position: null, number: 39, age: null },
  { id: 9594, name: "K. Tsuchiya", korean_name: "츠치야 켄타", team_id: 294, position: "Defender", number: 39, age: 19 },
  { id: 9579, name: "S. Nakagawa", korean_name: "나카가와 슌", team_id: 294, position: "Goalkeeper", number: 39, age: 24 },
  { id: 9600, name: "A. Ienaga", korean_name: "이에나가 아키히로", team_id: 294, position: "Midfielder", number: 41, age: 39 },
  { id: 9598, name: "C. Haydar", korean_name: "차를레스 하이다르", team_id: 294, position: "Defender", number: 44, age: 24 },
  { id: 9612, name: "L. Romanić", korean_name: "루카 로마니치", team_id: 294, position: "Attacker", number: 91, age: 27 },
  { id: 9580, name: "L. Yamaguchi", korean_name: "야마구치 류", team_id: 294, position: "Goalkeeper", number: 98, age: 27 },
  { id: 9582, name: "H. Izawa", korean_name: "이자와 히로키", team_id: 294, position: "Goalkeeper", number: null, age: 18 },
  { id: 9581, name: "Lee Geun-Hyeong", korean_name: "이근형", team_id: 294, position: "Goalkeeper", number: null, age: 19 },
  { id: 9583, name: "N. Matsuzawa", korean_name: "마츠자와 나오키", team_id: 294, position: "Goalkeeper", number: null, age: 18 },
];

// Kyoto Sanga (교토 상가) - Team ID: 302
export const KYOTO_SANGA_PLAYERS: PlayerMapping[] = [
  { id: 9623, name: "Gu Sung-Yun", korean_name: "구성윤", team_id: 302, position: "Goalkeeper", number: 1, age: 31 },
  { id: 9631, name: "R. Iida", korean_name: "이이다 료타", team_id: 302, position: "Defender", number: 2, age: 20 },
  { id: 9629, name: "S. Fukuda", korean_name: "후쿠다 슌스케", team_id: 302, position: "Defender", number: 2, age: 25 },
  { id: 9625, name: "S. Asada", korean_name: "아사다 슌", team_id: 302, position: "Defender", number: 3, age: 27 },
  { id: 9633, name: "Patrick William", korean_name: "패트릭 윌리엄", team_id: 302, position: "Defender", number: 4, age: 28 },
  { id: 9634, name: "H. Tawiah", korean_name: "하산 타위아", team_id: 302, position: "Defender", number: 5, age: 27 },
  { id: 9640, name: "João Pedro", korean_name: "조앙 페드루", team_id: 302, position: "Midfielder", number: 6, age: 26 },
  { id: 1700, name: "S. Kawasaki", korean_name: "카와사키 슌타", team_id: 302, position: "Midfielder", number: 7, age: 24 },
  { id: 9635, name: "T. Yonemoto", korean_name: "요네모토 타카시", team_id: 302, position: "Midfielder", number: 8, age: 35 },
  { id: 9652, name: "Rafael Elias", korean_name: "하파엘 엘리아스", team_id: 302, position: "Attacker", number: 9, age: 26 },
  { id: 9641, name: "S. Fukuoka", korean_name: "후쿠오카 슌스케", team_id: 302, position: "Midfielder", number: 10, age: 25 },
  { id: 9655, name: "Marco Túlio", korean_name: "마르쿠 툴리오", team_id: 302, position: "Attacker", number: 11, age: 27 },
  { id: 9653, name: "T. Hara", korean_name: "하라 타쿠미", team_id: 302, position: "Attacker", number: 14, age: 26 },
  { id: 9632, name: "K. Nagata", korean_name: "나가타 켄타", team_id: 302, position: "Defender", number: 15, age: 23 },
  { id: 9637, name: "Léo Gomes", korean_name: "레오 고메스", team_id: 302, position: "Midfielder", number: 16, age: 28 },
  { id: 9636, name: "S. Takeda", korean_name: "타케다 슌야", team_id: 302, position: "Midfielder", number: 16, age: 31 },
  { id: 9649, name: "Y. Anzai", korean_name: "안자이 유마", team_id: 302, position: "Midfielder", number: 17, age: 20 },
  { id: 9642, name: "T. Matsuda", korean_name: "마츠다 타쿠미", team_id: 302, position: "Attacker", number: 18, age: 30 },
  { id: 9626, name: "K. Kita", korean_name: "키타 켄타", team_id: 302, position: "Defender", number: 20, age: 20 },
  { id: 9621, name: "K. Kakoi", korean_name: "카코이 켄타", team_id: 302, position: "Goalkeeper", number: 21, age: 34 },
  { id: 9628, name: "H. Sugai", korean_name: "스가이 히로키", team_id: 302, position: "Defender", number: 22, age: 27 },
  { id: 9630, name: "Y. Miyamoto", korean_name: "미야모토 유키", team_id: 302, position: "Defender", number: 24, age: 26 },
  { id: 9624, name: "G. Ota", korean_name: "오타 고", team_id: 302, position: "Goalkeeper", number: 26, age: 35 },
  { id: 9638, name: "F. Yamada", korean_name: "야마다 후미야", team_id: 302, position: "Midfielder", number: 27, age: 24 },
  { id: 9644, name: "M. Okugawa", korean_name: "오쿠가와 마사야", team_id: 302, position: "Attacker", number: 29, age: 29 },
  { id: 9651, name: "S. Hiraga", korean_name: "히라가 슌", team_id: 302, position: "Attacker", number: 31, age: 20 },
  { id: 9643, name: "T. Hirato", korean_name: "히라토 타쿠야", team_id: 302, position: "Midfielder", number: 39, age: 28 },
  { id: 9646, name: "K. Sato", korean_name: "사토 켄타", team_id: 302, position: "Midfielder", number: 44, age: 25 },
  { id: 9645, name: "R. Nakano", korean_name: "나카노 료", team_id: 302, position: "Midfielder", number: 48, age: 23 },
  { id: 9627, name: "Y. Suzuki", korean_name: "스즈키 유야", team_id: 302, position: "Defender", number: 50, age: 33 },
  { id: 9648, name: "Barreto", korean_name: "바헤투", team_id: 302, position: "Midfielder", number: 88, age: 30 },
  { id: 9654, name: "S. Nagasawa", korean_name: "나가사와 슌", team_id: 302, position: "Attacker", number: 93, age: 37 },
  { id: 9620, name: "Marc Vito", korean_name: "마르크 비토", team_id: 302, position: "Goalkeeper", number: 96, age: 29 },
  { id: 9622, name: "A. Fantini", korean_name: "안드레아 판티니", team_id: 302, position: "Goalkeeper", number: null, age: 27 },
  { id: 9647, name: "Yoon Sung-Jun", korean_name: "윤성준", team_id: 302, position: "Midfielder", number: null, age: 18 },
];

// Machida Zelvia (마치다 젤비아) - Team ID: 303
export const MACHIDA_ZELVIA_PLAYERS: PlayerMapping[] = [
  { id: 9657, name: "K. Tani", korean_name: "타니 켄타", team_id: 303, position: "Goalkeeper", number: 1, age: 25 },
  { id: 9667, name: "H. Nakamura", korean_name: "나카무라 히로키", team_id: 303, position: "Defender", number: 2, age: 28 },
  { id: 9691, name: "Tomoki Imai", korean_name: "이마이 토모키", team_id: 303, position: "Defender", number: 2, age: 35 },
  { id: 9662, name: "G. Shōji", korean_name: "쇼지 겐", team_id: 303, position: "Defender", number: 3, age: 33 },
  { id: 9664, name: "R. Kikuchi", korean_name: "키쿠치 료타", team_id: 303, position: "Defender", number: 4, age: 29 },
  { id: 9666, name: "I. Drešević", korean_name: "이반 드레셰비치", team_id: 303, position: "Defender", number: 5, age: 28 },
  { id: 9663, name: "H. Mochizuki", korean_name: "모치즈키 히로키", team_id: 303, position: "Defender", number: 6, age: 24 },
  { id: 9683, name: "Y. Soma", korean_name: "소마 유키", team_id: 303, position: "Attacker", number: 7, age: 28 },
  { id: 9673, name: "K. Sento", korean_name: "센토 카즈키", team_id: 303, position: "Midfielder", number: 8, age: 31 },
  { id: 9684, name: "S. Fujio", korean_name: "후지오 슌", team_id: 303, position: "Attacker", number: 9, age: 24 },
  { id: 9687, name: "Na Sang-Ho", korean_name: "나상호", team_id: 303, position: "Attacker", number: 10, age: 29 },
  { id: 9677, name: "A. Masuyama", korean_name: "마스야마 아키라", team_id: 303, position: "Midfielder", number: 11, age: 28 },
  { id: 9659, name: "T. Morita", korean_name: "모리타 타쿠마", team_id: 303, position: "Goalkeeper", number: 13, age: 35 },
  { id: 9682, name: "M. Duke", korean_name: "미첼 듀크", team_id: 303, position: "Attacker", number: 15, age: 34 },
  { id: 9679, name: "H. Mae", korean_name: "마에 히로키", team_id: 303, position: "Midfielder", number: 16, age: 30 },
  { id: 9676, name: "H. Shimoda", korean_name: "시모다 히로키", team_id: 303, position: "Midfielder", number: 18, age: 34 },
  { id: 9665, name: "Y. Nakayama", korean_name: "나카야마 유키", team_id: 303, position: "Defender", number: 19, age: 28 },
  { id: 9689, name: "T. Nishimura", korean_name: "니시무라 타쿠미", team_id: 303, position: "Attacker", number: 20, age: 29 },
  { id: 9681, name: "T. Numata", korean_name: "누마타 타쿠미", team_id: 303, position: "Attacker", number: 22, age: 26 },
  { id: 9680, name: "R. Shirasaki", korean_name: "시라사키 료헤이", team_id: 303, position: "Midfielder", number: 23, age: 32 },
  { id: 9668, name: "K. Hayashi", korean_name: "하야시 켄타", team_id: 303, position: "Defender", number: 26, age: 25 },
  { id: 9671, name: "Cha Je-Hoon", korean_name: "차재훈", team_id: 303, position: "Midfielder", number: 28, age: 19 },
  { id: 9690, name: "Y. Nakashima", korean_name: "나카시마 유키", team_id: 303, position: "Attacker", number: 30, age: 41 },
  { id: 9481, name: "N. Lavi", korean_name: "니르 라비", team_id: 303, position: "Midfielder", number: 31, age: 29 },
  { id: 9660, name: "Y. Arai", korean_name: "아라이 유키", team_id: 303, position: "Goalkeeper", number: 44, age: 30 },
  { id: 9678, name: "K. Higuchi", korean_name: "히구치 켄타", team_id: 303, position: "Midfielder", number: 46, age: 22 },
  { id: 9685, name: "K. Kuwayama", korean_name: "쿠와야마 켄타", team_id: 303, position: "Attacker", number: 49, age: 23 },
  { id: 9658, name: "A. Burns", korean_name: "애덤 번스", team_id: 303, position: "Goalkeeper", number: 50, age: 22 },
  { id: 9669, name: "D. Okamura", korean_name: "오카무라 다이키", team_id: 303, position: "Defender", number: 50, age: 28 },
  { id: 9675, name: "D. Takahashi", korean_name: "타카하시 다이키", team_id: 303, position: "Midfielder", number: 66, age: 26 },
  { id: 9661, name: "T. Narasaka", korean_name: "나라사카 타쿠마", team_id: 303, position: "Defender", number: 77, age: 23 },
  { id: 9686, name: "Oh Se-Hun", korean_name: "오세훈", team_id: 303, position: "Attacker", number: 90, age: 26 },
  { id: 9670, name: "C. Mayaka", korean_name: "클린턴 마야카", team_id: 303, position: "Midfielder", number: null, age: 19 },
  { id: 9656, name: "Kaung Zan Mara", korean_name: "카웅 잔 마라", team_id: 303, position: "Goalkeeper", number: null, age: 23 },
  { id: 9674, name: "T. Takasaki", korean_name: "타카사키", team_id: 303, position: "Midfielder", number: null, age: 19 },
];

// Nagoya Grampus (나고야 그램퍼스) - Team ID: 288
export const NAGOYA_GRAMPUS_PLAYERS: PlayerMapping[] = [
  { id: 9693, name: "D. Schmidt", korean_name: "다니엘 슈미트", team_id: 288, position: "Goalkeeper", number: 1, age: 33 },
  { id: 9695, name: "T. Kodama", korean_name: "코다마 타쿠야", team_id: 288, position: "Goalkeeper", number: 1, age: 38 },
  { id: 9700, name: "Y. Nogami", korean_name: "노가미 유키", team_id: 288, position: "Midfielder", number: 2, age: 34 },
  { id: 9703, name: "Y. Sato", korean_name: "사토 유키", team_id: 288, position: "Defender", number: 3, age: 27 },
  { id: 9699, name: "D. Miya", korean_name: "미야 다이키", team_id: 288, position: "Defender", number: 4, age: 29 },
  { id: 9701, name: "A. Kawazura", korean_name: "카와즈라 아키라", team_id: 288, position: "Defender", number: 6, age: 31 },
  { id: 9717, name: "R. Izumi", korean_name: "이즈미 료타", team_id: 288, position: "Attacker", number: 7, age: 32 },
  { id: 9706, name: "K. Shiihashi", korean_name: "시이하시 켄타", team_id: 288, position: "Midfielder", number: 8, age: 28 },
  { id: 9716, name: "Y. Asano", korean_name: "아사노 유키", team_id: 288, position: "Midfielder", number: 9, age: 28 },
  { id: 8589, name: "Mateus", korean_name: "마테우스", team_id: 288, position: "Attacker", number: 10, age: 31 },
  { id: 9723, name: "Y. Yamagishi", korean_name: "야마기시 유키", team_id: 288, position: "Attacker", number: 11, age: 32 },
  { id: 9698, name: "H. Fujii", korean_name: "후지이 히로키", team_id: 288, position: "Defender", number: 13, age: 25 },
  { id: 9710, name: "T. Morishima", korean_name: "모리시마 타쿠미", team_id: 288, position: "Midfielder", number: 14, age: 28 },
  { id: 9709, name: "S. Inagaki", korean_name: "이나가키 신지", team_id: 288, position: "Midfielder", number: 15, age: 34 },
  { id: 9692, name: "Y. Takeda", korean_name: "타케다 유키", team_id: 288, position: "Goalkeeper", number: 16, age: 38 },
  { id: 9707, name: "T. Uchida", korean_name: "우치다 타쿠야", team_id: 288, position: "Defender", number: 17, age: 27 },
  { id: 9728, name: "K. Nagai", korean_name: "나가이 켄타", team_id: 288, position: "Attacker", number: 18, age: 36 },
  { id: 9705, name: "K. Mikuni", korean_name: "미쿠니 켄타", team_id: 288, position: "Defender", number: 20, age: 25 },
  { id: 9694, name: "D. Sugimoto", korean_name: "스기모토 다이키", team_id: 288, position: "Goalkeeper", number: 21, age: 32 },
  { id: 9713, name: "G. Kato", korean_name: "카토 겐타", team_id: 288, position: "Midfielder", number: 26, age: 22 },
  { id: 9711, name: "K. Nakayama", korean_name: "나카야마 켄타", team_id: 288, position: "Midfielder", number: 27, age: 29 },
  { id: 9719, name: "S. Sugiura", korean_name: "스기우라 슌", team_id: 288, position: "Midfielder", number: 30, age: 19 },
  { id: 9718, name: "H. Suzuki", korean_name: "스즈키 히로키", team_id: 288, position: "Midfielder", number: 32, age: 20 },
  { id: 9715, name: "T. Kikuchi", korean_name: "키쿠치 타쿠마", team_id: 288, position: "Midfielder", number: 33, age: 26 },
  { id: 9697, name: "A. Pisano", korean_name: "안드레아 피사노", team_id: 288, position: "Goalkeeper", number: 35, age: 19 },
  { id: 9714, name: "M. Ono", korean_name: "오노 마사히로", team_id: 288, position: "Midfielder", number: 41, age: 29 },
  { id: 9704, name: "S. Mori", korean_name: "모리 슌타", team_id: 288, position: "Midfielder", number: 44, age: 18 },
  { id: 9702, name: "S. Tokumoto", korean_name: "토쿠모토 슌", team_id: 288, position: "Defender", number: 55, age: 30 },
  { id: 9712, name: "R. Yamanaka", korean_name: "야마나카 료타", team_id: 288, position: "Midfielder", number: 66, age: 32 },
  { id: 9708, name: "T. Hara", korean_name: "하라 타쿠미", team_id: 288, position: "Defender", number: 70, age: 27 },
  { id: 9727, name: "K. Sakakibara", korean_name: "사카키바라 켄타", team_id: 288, position: "Attacker", number: 71, age: 24 },
  { id: 9721, name: "K. Junker", korean_name: "케네디 융커", team_id: 288, position: "Attacker", number: 77, age: 31 },
  { id: 9726, name: "Lelê", korean_name: "렐레", team_id: 288, position: "Attacker", number: 99, age: 28 },
  { id: 9722, name: "A. Mawuto", korean_name: "아담 마우토", team_id: 288, position: "Attacker", number: null, age: 22 },
  { id: 9729, name: "H. Suzuki", korean_name: "스즈키", team_id: 288, position: null, number: null, age: null },
  { id: 9720, name: "R. Onishi", korean_name: "오니시 료", team_id: 288, position: "Attacker", number: null, age: 18 },
];

// Sanfrecce Hiroshima (산프레체 히로시마) - Team ID: 282
export const SANFRECCE_HIROSHIMA_PLAYERS: PlayerMapping[] = [
  { id: 9734, name: "K. Osako", korean_name: "오사코 켄타", team_id: 282, position: "Goalkeeper", number: 1, age: 26 },
  { id: 9741, name: "T. Yamasaki", korean_name: "야마사키 타쿠마", team_id: 282, position: "Defender", number: 3, age: 24 },
  { id: 9737, name: "H. Araki", korean_name: "아라키 히로키", team_id: 282, position: "Defender", number: 4, age: 29 },
  { id: 9751, name: "H. Kawabe", korean_name: "카와베 히로유키", team_id: 282, position: "Attacker", number: 6, age: 30 },
  { id: 9761, name: "R. Germain", korean_name: "로이스 제르맹", team_id: 282, position: "Attacker", number: 9, age: 30 },
  { id: 9755, name: "Marcos Júnior", korean_name: "마르코스 주니오르", team_id: 282, position: "Attacker", number: 10, age: 32 },
  { id: 9738, name: "N. Arai", korean_name: "아라이 나오키", team_id: 282, position: "Defender", number: 13, age: 29 },
  { id: 9758, name: "O. Iyoha", korean_name: "오소멘 이요하", team_id: 282, position: "Attacker", number: 13, age: 27 },
  { id: 9745, name: "S. Tanaka", korean_name: "타나카 슌", team_id: 282, position: "Midfielder", number: 14, age: 23 },
  { id: 9739, name: "S. Nakano", korean_name: "나카노 슌", team_id: 282, position: "Midfielder", number: 15, age: 25 },
  { id: 9574, name: "K. Kinoshita", korean_name: "키노시타 켄타", team_id: 282, position: "Attacker", number: 17, age: 31 },
  { id: 9754, name: "D. Suga", korean_name: "스가 다이키", team_id: 282, position: "Midfielder", number: 18, age: 27 },
  { id: 9736, name: "S. Sasaki", korean_name: "사사키 슌", team_id: 282, position: "Defender", number: 19, age: 36 },
  { id: 9746, name: "S. Inoue", korean_name: "이노우에 슌", team_id: 282, position: "Midfielder", number: 20, age: 28 },
  { id: 9732, name: "Y. Tanaka", korean_name: "타나카 유키", team_id: 282, position: "Goalkeeper", number: 21, age: 30 },
  { id: 9743, name: "S. Higashi", korean_name: "히가시 슌", team_id: 282, position: "Midfielder", number: 24, age: 25 },
  { id: 9748, name: "Y. Chajima", korean_name: "차지마 유키", team_id: 282, position: "Midfielder", number: 25, age: 34 },
  { id: 9733, name: "Jeong Min-Ki", korean_name: "정민기", team_id: 282, position: "Goalkeeper", number: 26, age: 29 },
  { id: 9744, name: "T. Arslan", korean_name: "톨가 아르슬란", team_id: 282, position: "Midfielder", number: 30, age: 35 },
  { id: 9749, name: "S. Koshimichi", korean_name: "코시미치 슌", team_id: 282, position: "Midfielder", number: 32, age: 21 },
  { id: 9740, name: "T. Shiotani", korean_name: "시오타니 츠카사", team_id: 282, position: "Midfielder", number: 33, age: 37 },
  { id: 9752, name: "Y. Nakajima", korean_name: "나카지마 유키", team_id: 282, position: "Attacker", number: 35, age: 19 },
  { id: 9766, name: "A. Inoue", korean_name: "이노우에", team_id: 282, position: "Attacker", number: 36, age: 19 },
  { id: 3516, name: "Kim Ju-Sung", korean_name: "김주성", team_id: 282, position: "Defender", number: 37, age: 25 },
  { id: 9730, name: "C. Hill", korean_name: "코너 힐", team_id: 282, position: "Goalkeeper", number: 38, age: 23 },
  { id: 9763, name: "S. Nakamura", korean_name: "나카무라 슌", team_id: 282, position: "Attacker", number: 39, age: 23 },
  { id: 9285, name: "M. Ohara", korean_name: "오하라 마사키", team_id: 282, position: "Midfielder", number: 40, age: 25 },
  { id: 9762, name: "S. Kobayashi", korean_name: "코바야시 슌", team_id: 282, position: "Attacker", number: 45, age: 17 },
  { id: 9753, name: "T. Semba", korean_name: "센바 타쿠마", team_id: 282, position: "Midfielder", number: 47, age: 26 },
  { id: 9757, name: "M. Kato", korean_name: "카토 미쓰키", team_id: 282, position: "Attacker", number: 51, age: 28 },
  { id: 9496, name: "M. Mitsuta", korean_name: "미츠타 마코토", team_id: 282, position: "Attacker", number: 51, age: 26 },
  { id: 9381, name: "G. Kawanami", korean_name: "카와나미 고", team_id: 282, position: "Goalkeeper", number: 77, age: 34 },
  { id: 9756, name: "V. Germain", korean_name: "발렌탱 제르맹", team_id: 282, position: "Attacker", number: 98, age: 35 },
  { id: 9731, name: "H. Ogawa", korean_name: "오가와 히로키", team_id: 282, position: "Goalkeeper", number: null, age: 18 },
  { id: 9764, name: "M. Sota", korean_name: "소타", team_id: 282, position: "Attacker", number: null, age: 18 },
];

// Shimizu S-pulse (시미즈 에스펄스) - Team ID: 283
export const SHIMIZU_S_PULSE_PLAYERS: PlayerMapping[] = [
  { id: 9770, name: "Y. Oki", korean_name: "오키 유키", team_id: 283, position: "Goalkeeper", number: 1, age: 26 },
  { id: 9772, name: "Y. Takahashi", korean_name: "타카하시 유키", team_id: 283, position: "Defender", number: 3, age: 32 },
  { id: 9782, name: "S. Hasukawa", korean_name: "하스카와 슌", team_id: 283, position: "Defender", number: 4, age: 27 },
  { id: 9776, name: "K. Kitazume", korean_name: "키타즈메 켄타", team_id: 283, position: "Defender", number: 5, age: 33 },
  { id: 9793, name: "K. Miyamoto", korean_name: "미야모토 켄타", team_id: 283, position: "Midfielder", number: 6, age: 29 },
  { id: 9790, name: "Capixaba", korean_name: "카픽사바", team_id: 283, position: "Midfielder", number: 7, age: 28 },
  { id: 9794, name: "K. Kozuka", korean_name: "코즈카 켄타", team_id: 283, position: "Attacker", number: 8, age: 31 },
  { id: 9796, name: "H. Nakahara", korean_name: "나카하라 히로키", team_id: 283, position: "Midfielder", number: 11, age: 29 },
  { id: 9781, name: "R. Yamahara", korean_name: "야마하라 료", team_id: 283, position: "Midfielder", number: 14, age: 26 },
  { id: 9805, name: "K. Chiba", korean_name: "치바 켄타", team_id: 283, position: "Attacker", number: 15, age: 22 },
  { id: 9808, name: "T. Umeda", korean_name: "우메다", team_id: 283, position: null, number: 16, age: null },
  { id: 9767, name: "T. Umeda", korean_name: "우메다 타쿠야", team_id: 283, position: "Goalkeeper", number: 16, age: 25 },
  { id: 9791, name: "M. Yumiba", korean_name: "유미바 마사키", team_id: 283, position: "Midfielder", number: 17, age: 23 },
  { id: 9802, name: "S. Saito", korean_name: "사이토 슌", team_id: 283, position: "Attacker", number: 18, age: 25 },
  { id: 9789, name: "K. Matsuzaki", korean_name: "마츠자키 켄타", team_id: 283, position: "Midfielder", number: 19, age: 28 },
  { id: 9798, name: "S. Yajima", korean_name: "야지마 슌", team_id: 283, position: "Midfielder", number: 21, age: 31 },
  { id: 9803, name: "K. Kitagawa", korean_name: "키타가와 켄타", team_id: 283, position: "Attacker", number: 23, age: 29 },
  { id: 9780, name: "Mateus Brunetti", korean_name: "마테우스 브루네티", team_id: 283, position: "Defender", number: 25, age: 26 },
  { id: 9807, name: "R. Gunji", korean_name: "군지 료", team_id: 283, position: "Attacker", number: 27, age: 20 },
  { id: 9785, name: "Y. Yoshida", korean_name: "요시다 유키", team_id: 283, position: "Midfielder", number: 28, age: 35 },
  { id: 9806, name: "A. Ahmedov", korean_name: "아흐메도프", team_id: 283, position: "Attacker", number: 29, age: 30 },
  { id: 9795, name: "T. Inui", korean_name: "이누이 타카시", team_id: 283, position: "Attacker", number: 33, age: 37 },
  { id: 9809, name: "Z. Uno", korean_name: "우노", team_id: 283, position: null, number: 36, age: null },
  { id: 9786, name: "Z. Uno", korean_name: "우노 젠", team_id: 283, position: "Midfielder", number: 36, age: 22 },
  { id: 9787, name: "R. Ohata", korean_name: "오하타 료", team_id: 283, position: "Midfielder", number: 37, age: 22 },
  { id: 9775, name: "K. Haneda", korean_name: "하네다 켄타", team_id: 283, position: "Defender", number: 41, age: 28 },
  { id: 9788, name: "Y. Doi", korean_name: "도이 유키", team_id: 283, position: "Midfielder", number: 42, age: 18 },
  { id: 9769, name: "R. Abe", korean_name: "아베 료", team_id: 283, position: "Goalkeeper", number: 46, age: 24 },
  { id: 9800, name: "Y. Shimamoto", korean_name: "시마모토 유키", team_id: 283, position: "Midfielder", number: 47, age: 19 },
  { id: 9792, name: "S. Kotake", korean_name: "코타케 슌", team_id: 283, position: "Midfielder", number: 49, age: 19 },
  { id: 9801, name: "A. Stephens", korean_name: "아담 스티븐스", team_id: 283, position: "Attacker", number: 50, age: 31 },
  { id: 9797, name: "M. Nishihara", korean_name: "니시하라 마사키", team_id: 283, position: "Midfielder", number: 55, age: 19 },
  { id: 9778, name: "J. Sumiyoshi", korean_name: "스미요시 준", team_id: 283, position: "Defender", number: 66, age: 28 },
  { id: 9779, name: "S. Takagi", korean_name: "타카기 슌", team_id: 283, position: "Defender", number: 70, age: 23 },
  { id: 9771, name: "Y. Inokoshi", korean_name: "이노코시 유키", team_id: 283, position: "Goalkeeper", number: 71, age: 24 },
  { id: 9799, name: "Matheus Bueno", korean_name: "마테우스 부에노", team_id: 283, position: "Midfielder", number: 98, age: 27 },
  { id: 9773, name: "K. Iwanaga", korean_name: "이와나가 켄타", team_id: 283, position: "Defender", number: null, age: 18 },
  { id: 9784, name: "T. Iwao", korean_name: "이와오 타쿠마", team_id: 283, position: "Defender", number: null, age: 18 },
  { id: 9777, name: "T. Kemmotsu", korean_name: "켐모츠 타쿠마", team_id: 283, position: "Defender", number: null, age: 25 },
  { id: 9768, name: "T. Sasaki", korean_name: "사사키 타쿠마", team_id: 283, position: "Goalkeeper", number: null, age: 18 },
];

// Shonan Bellmare (쇼난 벨마레) - Team ID: 284
export const SHONAN_BELLMARE_PLAYERS: PlayerMapping[] = [
  { id: 9820, name: "T. Hata", korean_name: "하타 타쿠마", team_id: 284, position: "Defender", number: 3, age: 23 },
  { id: 9821, name: "K. Tachi", korean_name: "타치 켄타", team_id: 284, position: "Defender", number: 4, age: 28 },
  { id: 9828, name: "Zé Ricardo", korean_name: "제 히카르도", team_id: 284, position: "Midfielder", number: 6, age: 26 },
  { id: 9835, name: "K. Onose", korean_name: "오노세 켄타", team_id: 284, position: "Midfielder", number: 7, age: 32 },
  { id: 9819, name: "K. Ohno", korean_name: "오노 켄타", team_id: 284, position: "Defender", number: 8, age: 36 },
  { id: 9841, name: "Y. Oda", korean_name: "오다 유키", team_id: 284, position: "Attacker", number: 9, age: 24 },
  { id: 9844, name: "A. Suzuki", korean_name: "스즈키 아키라", team_id: 284, position: "Attacker", number: 10, age: 22 },
  { id: 9831, name: "T. Hiraoka", korean_name: "히라오카 타쿠마", team_id: 284, position: "Midfielder", number: 13, age: 23 },
  { id: 9832, name: "A. Barada", korean_name: "안드레 바라다", team_id: 284, position: "Midfielder", number: 14, age: 34 },
  { id: 9833, name: "K. Okuno", korean_name: "오쿠노 켄타", team_id: 284, position: "Midfielder", number: 15, age: 25 },
  { id: 9845, name: "R. Nemoto", korean_name: "네모토 료", team_id: 284, position: "Attacker", number: 16, age: 25 },
  { id: 9837, name: "S. Tamura", korean_name: "타무라 슌", team_id: 284, position: "Midfielder", number: 17, age: 23 },
  { id: 9829, name: "M. Ikeda", korean_name: "이케다 마사키", team_id: 284, position: "Midfielder", number: 18, age: 26 },
  { id: 5082, name: "S. Fukuda", korean_name: "후쿠다 슌", team_id: 284, position: "Attacker", number: 19, age: 24 },
  { id: 5097, name: "J. Suzuki", korean_name: "스즈키 준", team_id: 284, position: "Defender", number: 20, age: 22 },
  { id: 9836, name: "S. Ishibashi", korean_name: "이시바시 슌", team_id: 284, position: "Midfielder", number: 20, age: 19 },
  { id: 9815, name: "T. Nagai", korean_name: "나가이 타쿠마", team_id: 284, position: "Goalkeeper", number: 21, age: 30 },
  { id: 9824, name: "K. Oiwa", korean_name: "오이와 켄타", team_id: 284, position: "Defender", number: 22, age: 36 },
  { id: 9816, name: "K. Matsumoto", korean_name: "마츠모토 켄타", team_id: 284, position: "Defender", number: 23, age: 18 },
  { id: 9363, name: "H. Okuno", korean_name: "오쿠노 히로키", team_id: 284, position: "Midfielder", number: 25, age: 36 },
  { id: 9847, name: "Luiz Phellype", korean_name: "루이스 펠리페", team_id: 284, position: "Attacker", number: 27, age: 32 },
  { id: 9296, name: "S. Ota", korean_name: "오타 슌", team_id: 284, position: "Midfielder", number: 28, age: 29 },
  { id: 9846, name: "K. Watanabe", korean_name: "와타나베 켄타", team_id: 284, position: "Attacker", number: 29, age: 23 },
  { id: 9812, name: "K. Sanada", korean_name: "사나다 켄타", team_id: 284, position: "Goalkeeper", number: 31, age: 26 },
  { id: 9849, name: "K. Sanada", korean_name: "사나다", team_id: 284, position: null, number: 31, age: null },
  { id: 9823, name: "S. Matsumura", korean_name: "마츠무라 슌", team_id: 284, position: "Midfielder", number: 32, age: 22 },
  { id: 9822, name: "N. Takahashi", korean_name: "타카하시 나오키", team_id: 284, position: "Defender", number: 33, age: 24 },
  { id: 9827, name: "Y. Suzuki", korean_name: "스즈키 유키", team_id: 284, position: "Midfielder", number: 37, age: 32 },
  { id: 9810, name: "K. Itohara", korean_name: "이토하라 켄타", team_id: 284, position: "Goalkeeper", number: 41, age: 27 },
  { id: 9783, name: "Kim Min-Tae", korean_name: "김민태", team_id: 284, position: "Defender", number: 47, age: 32 },
  { id: 9848, name: "Shinya Nakano", korean_name: "나카노 신야", team_id: 284, position: "Defender", number: 47, age: 22 },
  { id: 9826, name: "T. Fujii", korean_name: "후지이 타쿠마", team_id: 284, position: "Midfielder", number: 50, age: 27 },
  { id: 9747, name: "H. Matsumoto", korean_name: "마츠모토 히로키", team_id: 284, position: "Midfielder", number: 66, age: 25 },
  { id: 9840, name: "H. Ishii", korean_name: "이시이 히로키", team_id: 284, position: "Attacker", number: 77, age: 20 },
  { id: 9813, name: "N. Kamifukumoto", korean_name: "카미후쿠모토 나오키", team_id: 284, position: "Goalkeeper", number: 99, age: 36 },
  { id: 9818, name: "K. Honda", korean_name: "혼다 켄타", team_id: 284, position: "Defender", number: null, age: 19 },
];

// Tokyo Verdy (도쿄 베르디) - Team ID: 306
export const TOKYO_VERDY_PLAYERS: PlayerMapping[] = [
  { id: 9851, name: "Matheus Vidotto", korean_name: "마테우스 비도토", team_id: 306, position: "Goalkeeper", number: 1, age: 32 },
  { id: 9862, name: "D. Fukazawa", korean_name: "후카자와 다이키", team_id: 306, position: "Midfielder", number: 2, age: 27 },
  { id: 9857, name: "H. Taniguchi", korean_name: "타니구치 히로키", team_id: 306, position: "Defender", number: 3, age: 26 },
  { id: 9860, name: "N. Hayashi", korean_name: "하야시 나오키", team_id: 306, position: "Defender", number: 4, age: 27 },
  { id: 9873, name: "Y. Tsunashima", korean_name: "츠나시마 유키", team_id: 306, position: "Midfielder", number: 4, age: 25 },
  { id: 9514, name: "K. Chida", korean_name: "치다 켄타", team_id: 306, position: "Defender", number: 5, age: 31 },
  { id: 9854, name: "R. Inoue", korean_name: "이노우에 료타", team_id: 306, position: "Defender", number: 5, age: 25 },
  { id: 9863, name: "K. Miyahara", korean_name: "미야하라 켄타", team_id: 306, position: "Defender", number: 6, age: 29 },
  { id: 9872, name: "K. Morita", korean_name: "모리타 켄타", team_id: 306, position: "Midfielder", number: 7, age: 25 },
  { id: 9865, name: "K. Saito", korean_name: "사이토 켄타", team_id: 306, position: "Midfielder", number: 8, age: 28 },
  { id: 9882, name: "I. Someno", korean_name: "소메노 이사무", team_id: 306, position: "Attacker", number: 9, age: 24 },
  { id: 9724, name: "Y. Kimura", korean_name: "키무라 유키", team_id: 306, position: "Attacker", number: 10, age: 24 },
  { id: 9875, name: "H. Yamami", korean_name: "야마미 히로키", team_id: 306, position: "Attacker", number: 11, age: 26 },
  { id: 9885, name: "G. Yamada", korean_name: "야마다 겐타", team_id: 306, position: "Attacker", number: 13, age: 25 },
  { id: 9870, name: "Y. Fukuda", korean_name: "후쿠다 유키", team_id: 306, position: "Attacker", number: 14, age: 26 },
  { id: 9855, name: "K. Suzuki", korean_name: "스즈키 켄타", team_id: 306, position: "Defender", number: 15, age: 23 },
  { id: 9866, name: "R. Hirakawa", korean_name: "히라카와 료", team_id: 306, position: "Midfielder", number: 16, age: 25 },
  { id: 9868, name: "T. Inami", korean_name: "이나미 타쿠마", team_id: 306, position: "Midfielder", number: 17, age: 26 },
  { id: 9874, name: "Y. Matsuhashi", korean_name: "마츠하시 유키", team_id: 306, position: "Midfielder", number: 19, age: 24 },
  { id: 9871, name: "Soma Meshino", korean_name: "메시노 소마", team_id: 306, position: "Midfielder", number: 20, age: 24 },
  { id: 9850, name: "H. Mawatari", korean_name: "마와타리 히로키", team_id: 306, position: "Goalkeeper", number: 21, age: 31 },
  { id: 9852, name: "Y. Nagasawa", korean_name: "나가사와 유키", team_id: 306, position: "Goalkeeper", number: 21, age: 29 },
  { id: 9867, name: "H. Onaga", korean_name: "오나가 히로키", team_id: 306, position: "Midfielder", number: 22, age: 30 },
  { id: 9881, name: "I. Kumatoriya", korean_name: "쿠마토리야 이사무", team_id: 306, position: "Attacker", number: 25, age: 22 },
  { id: 9858, name: "Y. Uchida", korean_name: "우치다 유키", team_id: 306, position: "Midfielder", number: 26, age: 23 },
  { id: 9877, name: "R. Shirai", korean_name: "시라이 료", team_id: 306, position: "Attacker", number: 27, age: 20 },
  { id: 9864, name: "J. Yamamoto", korean_name: "야마모토 준", team_id: 306, position: "Midfielder", number: 28, age: 19 },
  { id: 9856, name: "M. Sako", korean_name: "사코 마사키", team_id: 306, position: "Defender", number: 29, age: 23 },
  { id: 9876, name: "G. Kawamura", korean_name: "카와무라 겐타", team_id: 306, position: "Attacker", number: 30, age: 19 },
  { id: 9859, name: "R. Matsuda", korean_name: "마츠다 료", team_id: 306, position: "Defender", number: 36, age: 26 },
  { id: 9879, name: "S. Kawasaki", korean_name: "카와사키 슌", team_id: 306, position: "Attacker", number: 37, age: 24 },
  { id: 9493, name: "S. Toyama", korean_name: "토야마 슌", team_id: 306, position: "Attacker", number: 38, age: 23 },
  { id: 9884, name: "Shion Nakayama", korean_name: "나카야마 시온", team_id: 306, position: "Midfielder", number: 39, age: 18 },
  { id: 9869, name: "Y. Arai", korean_name: "아라이 유키", team_id: 306, position: "Attacker", number: 40, age: 22 },
  { id: 9886, name: "S. Teranuma", korean_name: "테라누마 슌", team_id: 306, position: "Attacker", number: 45, age: 24 },
  { id: 9887, name: "Ghaith Mansour Hamid Al Mhairat", korean_name: "가이스 만수르", team_id: 306, position: "Attacker", number: 71, age: 22 },
  { id: 849, name: "H. Hirao", korean_name: "히라오 히로키", team_id: 306, position: "Attacker", number: 71, age: 20 },
  { id: 9888, name: "H. Hirao", korean_name: "히라오", team_id: 306, position: null, number: 71, age: null },
  { id: 9853, name: "K. Nakamura", korean_name: "나카무라 켄타", team_id: 306, position: "Goalkeeper", number: null, age: 20 },
];

// Urawa (우라와 레즈) - Team ID: 287
export const URAWA_PLAYERS: PlayerMapping[] = [
  { id: 9890, name: "S. Nishikawa", korean_name: "니시카와 슌지", team_id: 287, position: "Goalkeeper", number: 1, age: 39 },
  { id: 9896, name: "Danilo Boza", korean_name: "다닐로 보자", team_id: 287, position: "Defender", number: 3, age: 27 },
  { id: 9899, name: "H. Ishihara", korean_name: "이시하라 히로키", team_id: 287, position: "Defender", number: 4, age: 26 },
  { id: 9895, name: "M. Høibråten", korean_name: "마리우스 회이브로텐", team_id: 287, position: "Defender", number: 5, age: 30 },
  { id: 9913, name: "T. Matsumoto", korean_name: "마츠모토 타쿠야", team_id: 287, position: "Midfielder", number: 6, age: 27 },
  { id: 9916, name: "Matheus Sávio", korean_name: "마테우스 사비오", team_id: 287, position: "Midfielder", number: 8, age: 28 },
  { id: 9908, name: "G. Haraguchi", korean_name: "하라구치 겐키", team_id: 287, position: "Midfielder", number: 9, age: 34 },
  { id: 9915, name: "S. Nakajima", korean_name: "나카지마 쇼마", team_id: 287, position: "Midfielder", number: 10, age: 31 },
  { id: 9910, name: "Samuel Gustafson", korean_name: "사무엘 구스타프손", team_id: 287, position: "Midfielder", number: 11, age: 30 },
  { id: 9919, name: "Thiago Santana", korean_name: "치아구 산타나", team_id: 287, position: "Attacker", number: 12, age: 32 },
  { id: 9914, name: "R. Watanabe", korean_name: "와타나베 료", team_id: 287, position: "Midfielder", number: 13, age: 29 },
  { id: 9902, name: "T. Sekine", korean_name: "세키네 타쿠마", team_id: 287, position: "Midfielder", number: 14, age: 30 },
  { id: 9894, name: "K. Matsuyama", korean_name: "마츠야마 켄타", team_id: 287, position: "Goalkeeper", number: 15, age: 27 },
  { id: 9891, name: "A. Niekawa", korean_name: "니에카와 아키라", team_id: 287, position: "Goalkeeper", number: 16, age: 31 },
  { id: 9921, name: "H. Komori", korean_name: "코모리 히로키", team_id: 287, position: "Attacker", number: 17, age: 25 },
  { id: 9804, name: "T. Takahashi", korean_name: "타카하시 타쿠마", team_id: 287, position: "Attacker", number: 18, age: 27 },
  { id: 9362, name: "S. Homma", korean_name: "혼마 슌", team_id: 287, position: "Midfielder", number: 19, age: 25 },
  { id: 9460, name: "M. Nagakura", korean_name: "나가쿠라 마사토", team_id: 287, position: "Attacker", number: 20, age: 26 },
  { id: 9912, name: "T. Okubo", korean_name: "오쿠보 타쿠마", team_id: 287, position: "Midfielder", number: 21, age: 27 },
  { id: 9903, name: "K. Shibato", korean_name: "시바토 켄타", team_id: 287, position: "Midfielder", number: 22, age: 30 },
  { id: 9907, name: "Y. Matsuo", korean_name: "마츠오 유키", team_id: 287, position: "Midfielder", number: 24, age: 28 },
  { id: 9904, name: "K. Yasui", korean_name: "야스이 켄타", team_id: 287, position: "Midfielder", number: 25, age: 25 },
  { id: 9897, name: "T. Ogiwara", korean_name: "오기와라 타쿠야", team_id: 287, position: "Defender", number: 26, age: 26 },
  { id: 9925, name: "T. Teruuchi", korean_name: "테루우치 타쿠마", team_id: 287, position: "Attacker", number: 27, age: 19 },
  { id: 9898, name: "K. Nemoto", korean_name: "네모토 켄타", team_id: 287, position: "Defender", number: 28, age: 23 },
  { id: 9760, name: "N. Maeda", korean_name: "마에다 나오키", team_id: 287, position: "Attacker", number: 30, age: 31 },
  { id: 9928, name: "Yudai Fujiwara", korean_name: "후지와라 유다이", team_id: 287, position: "Defender", number: 34, age: 23 },
  { id: 9356, name: "R. Inoue", korean_name: "이노우에 료타", team_id: 287, position: "Defender", number: 35, age: 28 },
  { id: 9918, name: "J. Hayakawa", korean_name: "하야카와 준", team_id: 287, position: "Midfielder", number: 39, age: 20 },
  { id: 9839, name: "R. Nitta", korean_name: "닛타 료", team_id: 287, position: "Attacker", number: 41, age: 22 },
  { id: 9917, name: "T. Kaneko", korean_name: "카네코 타쿠마", team_id: 287, position: "Midfielder", number: 77, age: 28 },
  { id: 9814, name: "S. Yoshida", korean_name: "요시다 슌", team_id: 287, position: "Goalkeeper", number: 81, age: 29 },
  { id: 9905, name: "Y. Naganuma", korean_name: "나가누마 유키", team_id: 287, position: "Midfielder", number: 88, age: 28 },
  { id: 9927, name: "Isaac Kiese Thelin", korean_name: "이삭 키에세 텔린", team_id: 287, position: "Attacker", number: 99, age: 33 },
  { id: 9889, name: "A. Malcolm", korean_name: "앤서니 말콤", team_id: 287, position: "Goalkeeper", number: null, age: 17 },
  { id: 9926, name: "Hiroki Abe", korean_name: "아베 히로키", team_id: 287, position: "Attacker", number: null, age: 26 },
  { id: 9906, name: "R. Hidano", korean_name: "히다노 료", team_id: 287, position: "Midfielder", number: null, age: 22 },
  { id: 9893, name: "R. Sato", korean_name: "사토 료", team_id: 287, position: "Goalkeeper", number: null, age: 22 },
  { id: 9909, name: "T. Wada", korean_name: "와다 타쿠마", team_id: 287, position: "Midfielder", number: null, age: 16 },
  { id: 9901, name: "Y. Tanaka", korean_name: "타나카 유키", team_id: 287, position: "Defender", number: null, age: 17 },
];

// Vissel Kobe (비셀 고베) - Team ID: 289
export const VISSEL_KOBE_PLAYERS: PlayerMapping[] = [
  { id: 9930, name: "D. Maekawa", korean_name: "마에카와 다이키", team_id: 289, position: "Goalkeeper", number: 1, age: 31 },
  { id: 9950, name: "N. Iino", korean_name: "이이노 나오키", team_id: 289, position: "Midfielder", number: 2, age: 29 },
  { id: 9939, name: "Matheus Thuler", korean_name: "마테우스 툴레르", team_id: 289, position: "Defender", number: 3, age: 26 },
  { id: 9933, name: "T. Yamakawa", korean_name: "야마카와 타쿠마", team_id: 289, position: "Defender", number: 4, age: 28 },
  { id: 9650, name: "M. Saito", korean_name: "사이토 마사키", team_id: 289, position: "Midfielder", number: 5, age: 26 },
  { id: 9957, name: "T. Ohgihara", korean_name: "오기하라 타쿠마", team_id: 289, position: "Midfielder", number: 6, age: 34 },
  { id: 9949, name: "Y. Ideguchi", korean_name: "이데구치 유야", team_id: 289, position: "Midfielder", number: 7, age: 29 },
  { id: 9963, name: "T. Miyashiro", korean_name: "미야시로 타쿠마", team_id: 289, position: "Midfielder", number: 9, age: 25 },
  { id: 9962, name: "Y. Osako", korean_name: "오사코 유야", team_id: 289, position: "Attacker", number: 10, age: 35 },
  { id: 9946, name: "Y. Muto", korean_name: "무토 요시노리", team_id: 289, position: "Attacker", number: 11, age: 33 },
  { id: 9953, name: "D. Sasaki", korean_name: "사사키 다이키", team_id: 289, position: "Attacker", number: 13, age: 26 },
  { id: 9951, name: "K. Yuruki", korean_name: "유루키 켄타", team_id: 289, position: "Midfielder", number: 14, age: 30 },
  { id: 9943, name: "Y. Honda", korean_name: "혼다 유키", team_id: 289, position: "Defender", number: 15, age: 34 },
  { id: 9937, name: "Caetano", korean_name: "카이타노", team_id: 289, position: "Defender", number: 16, age: 26 },
  { id: 9947, name: "H. Ide", korean_name: "이데 히로키", team_id: 289, position: "Midfielder", number: 18, age: 31 },
  { id: 9942, name: "Y. Koike", korean_name: "코이케 유키", team_id: 289, position: "Defender", number: 20, age: 29 },
  { id: 9929, name: "S. Arai", korean_name: "아라이 슌지", team_id: 289, position: "Goalkeeper", number: 21, age: 37 },
  { id: 9389, name: "H. Motoyama", korean_name: "모토야마 히로키", team_id: 289, position: "Defender", number: 22, age: 26 },
  { id: 9945, name: "R. Hirose", korean_name: "히로세 료", team_id: 289, position: "Defender", number: 23, age: 30 },
  { id: 9934, name: "G. Sakai", korean_name: "사카이 고토쿠", team_id: 289, position: "Defender", number: 24, age: 34 },
  { id: 9958, name: "Y. Kuwasaki", korean_name: "쿠와사키 유키", team_id: 289, position: "Midfielder", number: 25, age: 27 },
  { id: 9968, name: "Jean Patrick", korean_name: "장 파트릭", team_id: 289, position: "Attacker", number: 26, age: 28 },
  { id: 9688, name: "Erik", korean_name: "에리크", team_id: 289, position: "Attacker", number: 27, age: 31 },
  { id: 9964, name: "R. Komatsu", korean_name: "코마츠 료", team_id: 289, position: "Attacker", number: 29, age: 27 },
  { id: 9948, name: "K. Yamauchi", korean_name: "야마우치 켄타", team_id: 289, position: "Midfielder", number: 30, age: 23 },
  { id: 9936, name: "T. Iwanami", korean_name: "이와나미 타카시", team_id: 289, position: "Defender", number: 31, age: 31 },
  { id: 9932, name: "R. Ubong", korean_name: "로버트 우봉", team_id: 289, position: "Goalkeeper", number: 32, age: 20 },
  { id: 9965, name: "R. Hashimoto", korean_name: "하시모토 료", team_id: 289, position: "Attacker", number: 33, age: 20 },
  { id: 9960, name: "N. Tominaga", korean_name: "토미나가 나오키", team_id: 289, position: "Attacker", number: 35, age: 21 },
  { id: 9955, name: "M. Hidaka", korean_name: "히다카 마사키", team_id: 289, position: "Midfielder", number: 44, age: 22 },
  { id: 9931, name: "P. Obi", korean_name: "피터 오비", team_id: 289, position: "Goalkeeper", number: 50, age: 28 },
  { id: 9967, name: "T. Seguchi", korean_name: "세구치 타쿠마", team_id: 289, position: "Attacker", number: 51, age: 17 },
  { id: 9956, name: "K. Hamasaki", korean_name: "하마사키 켄타", team_id: 289, position: "Midfielder", number: 52, age: 18 },
  { id: 9961, name: "Y. Miyahara", korean_name: "미야하라 유키", team_id: 289, position: "Attacker", number: 55, age: 20 },
  { id: 9952, name: "T. Satomi", korean_name: "사토미 타쿠마", team_id: 289, position: "Midfielder", number: 56, age: 16 },
  { id: 9940, name: "R. Irie", korean_name: "이리에 료", team_id: 289, position: "Defender", number: 57, age: 21 },
  { id: 9944, name: "R. Matsuda", korean_name: "마츠다 료", team_id: 289, position: "Defender", number: 66, age: 34 },
  { id: 9969, name: "Shūichi Gonda", korean_name: "곤다 슈이치", team_id: 289, position: "Goalkeeper", number: 71, age: 36 },
  { id: 9154, name: "Klismahn", korean_name: "클리스만", team_id: 289, position: "Midfielder", number: 77, age: 26 },
  { id: 9935, name: "S. Hara", korean_name: "하라 슌", team_id: 289, position: "Defender", number: null, age: 18 },
];

// Yokohama FC (요코하마 FC) - Team ID: 307
export const YOKOHAMA_FC_PLAYERS: PlayerMapping[] = [
  { id: 9974, name: "Phelipe Megiolaro", korean_name: "펠리페 메지올라로", team_id: 307, position: "Goalkeeper", number: 1, age: 26 },
  { id: 9973, name: "R. Ishii", korean_name: "이시이 료", team_id: 307, position: "Goalkeeper", number: 1, age: 25 },
  { id: 9978, name: "B. Nduka", korean_name: "보니페이스 은두카", team_id: 307, position: "Defender", number: 2, age: 29 },
  { id: 9987, name: "J. Suzuki", korean_name: "스즈키 준", team_id: 307, position: "Defender", number: 3, age: 29 },
  { id: 10017, name: "Y. Lara", korean_name: "라라", team_id: 307, position: null, number: 4, age: null },
  { id: 10002, name: "Yuri Lara", korean_name: "유리 라라", team_id: 307, position: "Midfielder", number: 4, age: 31 },
  { id: 9977, name: "A. Fukumori", korean_name: "후쿠모리 아키라", team_id: 307, position: "Defender", number: 5, age: 33 },
  { id: 10000, name: "Y. Komai", korean_name: "코마이 유키", team_id: 307, position: "Midfielder", number: 6, age: 33 },
  { id: 10001, name: "L. Takae", korean_name: "타카에 루카", team_id: 307, position: "Midfielder", number: 7, age: 27 },
  { id: 10008, name: "M. Suzuki", korean_name: "스즈키 마사키", team_id: 307, position: "Attacker", number: 7, age: 31 },
  { id: 9999, name: "T. Yamane", korean_name: "야마네 타쿠마", team_id: 307, position: "Midfielder", number: 8, age: 26 },
  { id: 10012, name: "S. Sakuragawa", korean_name: "사쿠라가와 슌", team_id: 307, position: "Attacker", number: 9, age: 24 },
  { id: 10009, name: "João Paulo", korean_name: "조앙 파울로", team_id: 307, position: "Attacker", number: 10, age: 29 },
  { id: 10006, name: "Keijiro Ogawa", korean_name: "오가와 케이지로", team_id: 307, position: "Attacker", number: 13, age: 33 },
  { id: 9990, name: "Y. Nakano", korean_name: "나카노 유키", team_id: 307, position: "Midfielder", number: 14, age: 32 },
  { id: 10007, name: "S. Ito", korean_name: "이토 슌", team_id: 307, position: "Attacker", number: 15, age: 37 },
  { id: 9985, name: "M. Ito", korean_name: "이토 마사키", team_id: 307, position: "Defender", number: 16, age: 33 },
  { id: 9995, name: "M. Arai", korean_name: "아라이 마사키", team_id: 307, position: "Midfielder", number: 17, age: 28 },
  { id: 9981, name: "S. Van Eerden", korean_name: "숀 반 에르덴", team_id: 307, position: "Defender", number: 19, age: 21 },
  { id: 9993, name: "T. Murata", korean_name: "무라타 타쿠마", team_id: 307, position: "Midfielder", number: 20, age: 25 },
  { id: 9975, name: "A. Ichikawa", korean_name: "이치카와 아키라", team_id: 307, position: "Goalkeeper", number: 21, age: 27 },
  { id: 9984, name: "K. Iwatake", korean_name: "이와타케 켄타", team_id: 307, position: "Defender", number: 22, age: 29 },
  { id: 10003, name: "Michel", korean_name: "미셸", team_id: 307, position: "Midfielder", number: 23, age: 28 },
  { id: 9991, name: "R. Kubota", korean_name: "쿠보타 료", team_id: 307, position: "Attacker", number: 23, age: 24 },
  { id: 9972, name: "J. Słowik", korean_name: "야쿠프 스워비크", team_id: 307, position: "Goalkeeper", number: 24, age: 34 },
  { id: 9986, name: "Léo Bahia", korean_name: "레오 바이아", team_id: 307, position: "Defender", number: 27, age: 31 },
  { id: 10020, name: "K. Kumakura", korean_name: "쿠마쿠라", team_id: 307, position: null, number: 28, age: null },
  { id: 9997, name: "K. Kumakura", korean_name: "쿠마쿠라 켄타", team_id: 307, position: "Defender", number: 28, age: 23 },
  { id: 9988, name: "K. Yamazaki", korean_name: "야마자키 켄타", team_id: 307, position: "Defender", number: 30, age: 30 },
  { id: 10013, name: "K. Muroi", korean_name: "무로이 켄타", team_id: 307, position: "Attacker", number: 33, age: 25 },
  { id: 9989, name: "H. Ogura", korean_name: "오구라 히로키", team_id: 307, position: "Midfielder", number: 34, age: 24 },
  { id: 10004, name: "K. Maeda", korean_name: "마에다 켄타", team_id: 307, position: "Attacker", number: 37, age: 18 },
  { id: 10015, name: "K. Mori", korean_name: "모리 켄타", team_id: 307, position: "Attacker", number: 39, age: 25 },
  { id: 9996, name: "Takanari Endo", korean_name: "엔도 타카나리", team_id: 307, position: "Midfielder", number: 39, age: 23 },
  { id: 10019, name: "T. Endo", korean_name: "엔도", team_id: 307, position: null, number: 39, age: null },
  { id: 9970, name: "M. Endo", korean_name: "엔도 마사키", team_id: 307, position: "Goalkeeper", number: 40, age: 24 },
  { id: 9971, name: "T. Shibuya", korean_name: "시부야 타쿠마", team_id: 307, position: "Goalkeeper", number: 45, age: 30 },
  { id: 10010, name: "Izumi Miyata", korean_name: "미야타 이즈미", team_id: 307, position: "Attacker", number: 46, age: 24 },
  { id: 9979, name: "S. Sato", korean_name: "사토 슌", team_id: 307, position: "Defender", number: 46, age: 22 },
  { id: 9983, name: "K. Shimbo", korean_name: "심보 켄타", team_id: 307, position: "Defender", number: 48, age: 23 },
  { id: 10005, name: "N. Komazawa", korean_name: "코마자와 나오키", team_id: 307, position: "Attacker", number: 49, age: 23 },
  { id: 9998, name: "K. Nagata", korean_name: "나가타 켄타", team_id: 307, position: "Midfielder", number: 50, age: 23 },
  { id: 9980, name: "K. Hosoi", korean_name: "호소이 켄타", team_id: 307, position: "Midfielder", number: 70, age: 22 },
  { id: 10016, name: "K. Hosoi", korean_name: "호소이", team_id: 307, position: null, number: 70, age: null },
  { id: 9494, name: "K. Yamada", korean_name: "야마다 켄타", team_id: 307, position: "Midfielder", number: 76, age: 26 },
  { id: 9992, name: "Adaílton", korean_name: "아다일톤", team_id: 307, position: "Attacker", number: 90, age: 35 },
  { id: 9843, name: "Lukian", korean_name: "루키안", team_id: 307, position: "Attacker", number: 91, age: 34 },
  { id: 9994, name: "J. Hashimoto", korean_name: "하시모토 준", team_id: 307, position: "Midfielder", number: null, age: 24 },
  { id: 9976, name: "J. Hata", korean_name: "하타 준", team_id: 307, position: "Defender", number: null, age: 18 },
  { id: 10018, name: "R. Ishii", korean_name: "이시이", team_id: 307, position: null, number: null, age: null },
  { id: 9982, name: "S. Tsukuda", korean_name: "츠쿠다 슌", team_id: 307, position: "Defender", number: null, age: 18 },
];

// Yokohama F. Marinos (요코하마 F. 마리노스) - Team ID: 296
export const YOKOHAMA_F_MARINOS_PLAYERS: PlayerMapping[] = [
  { id: 9811, name: "W. Popp", korean_name: "윌리엄 포프", team_id: 296, position: "Goalkeeper", number: 1, age: 31 },
  { id: 9938, name: "K. Nagato", korean_name: "나가토 켄타", team_id: 296, position: "Defender", number: 2, age: 30 },
  { id: 10042, name: "K. Watanabe", korean_name: "와타나베 켄타", team_id: 296, position: "Midfielder", number: 6, age: 27 },
  { id: 9525, name: "Élber", korean_name: "엘베르", team_id: 296, position: "Midfielder", number: 7, age: 33 },
  { id: 10044, name: "T. Kida", korean_name: "키다 타쿠마", team_id: 296, position: "Midfielder", number: 8, age: 31 },
  { id: 10052, name: "D. Tono", korean_name: "토노 다이키", team_id: 296, position: "Attacker", number: 9, age: 26 },
  { id: 10053, name: "Yan Matheus", korean_name: "얀 마테우스", team_id: 296, position: "Midfielder", number: 11, age: 27 },
  { id: 10032, name: "J. Quiñónes", korean_name: "제퍼슨 키뇨네스", team_id: 296, position: "Defender", number: 13, age: 28 },
  { id: 10050, name: "A. Uenaka", korean_name: "우에나카 아키라", team_id: 296, position: "Midfielder", number: 14, age: 24 },
  { id: 10027, name: "R. Kato", korean_name: "카토 료", team_id: 296, position: "Defender", number: 16, age: 26 },
  { id: 10040, name: "K. Inoue", korean_name: "이노우에 켄타", team_id: 296, position: "Midfielder", number: 17, age: 27 },
  { id: 10058, name: "George Onaiwu", korean_name: "조지 오나이우", team_id: 296, position: "Midfielder", number: 18, age: 25 },
  { id: 10062, name: "G. Onaiwu", korean_name: "오나이우", team_id: 296, position: null, number: 18, age: null },
  { id: 10024, name: "Park Il-Gyu", korean_name: "박일규", team_id: 296, position: "Goalkeeper", number: 19, age: 36 },
  { id: 10039, name: "J. Amano", korean_name: "아마노 준", team_id: 296, position: "Midfielder", number: 20, age: 34 },
  { id: 10025, name: "H. Iikura", korean_name: "이이쿠라 히로키", team_id: 296, position: "Goalkeeper", number: 21, age: 39 },
  { id: 10041, name: "E. Matsuda", korean_name: "마츠다 에이지", team_id: 296, position: "Midfielder", number: 22, age: 24 },
  { id: 10034, name: "R. Tsunoda", korean_name: "츠노다 료", team_id: 296, position: "Defender", number: 22, age: 26 },
  { id: 10056, name: "R. Miyaichi", korean_name: "미야이치 료", team_id: 296, position: "Attacker", number: 23, age: 33 },
  { id: 10043, name: "T. Suzuki", korean_name: "스즈키 타쿠마", team_id: 296, position: "Midfielder", number: 25, age: 25 },
  { id: 10064, name: "D. David", korean_name: "다비드", team_id: 296, position: null, number: 26, age: null },
  { id: 10055, name: "D. David", korean_name: "다비드", team_id: 296, position: "Attacker", number: 26, age: 29 },
  { id: 10031, name: "K. Matsubara", korean_name: "마츠바라 켄타", team_id: 296, position: "Defender", number: 27, age: 32 },
  { id: 10038, name: "R. Yamane", korean_name: "야마네 료", team_id: 296, position: "Midfielder", number: 28, age: 22 },
  { id: 10045, name: "Yuri Araújo", korean_name: "유리 아라우조", team_id: 296, position: "Midfielder", number: 30, age: 29 },
  { id: 10021, name: "R. Kimura", korean_name: "키무라 료", team_id: 296, position: "Goalkeeper", number: 31, age: 22 },
  { id: 10059, name: "Y. Tanaka", korean_name: "타나카", team_id: 296, position: null, number: 32, age: null },
  { id: 10061, name: "K. Suwama", korean_name: "스와마", team_id: 296, position: null, number: 33, age: null },
  { id: 10030, name: "K. Suwama", korean_name: "스와마 켄타", team_id: 296, position: "Defender", number: 33, age: 22 },
  { id: 10047, name: "T. Kimura", korean_name: "키무라 타쿠마", team_id: 296, position: "Midfielder", number: 34, age: 25 },
  { id: 10063, name: "K. Sekitomi", korean_name: "세키토미", team_id: 296, position: null, number: 35, age: null },
  { id: 10060, name: "S. Kanta", korean_name: "칸타", team_id: 296, position: "Defender", number: 35, age: null },
  { id: 10057, name: "Jordy Croux", korean_name: "조르디 크루", team_id: 296, position: "Midfielder", number: 37, age: 31 },
  { id: 10035, name: "T. Watanabe", korean_name: "와타나베 타쿠마", team_id: 296, position: "Defender", number: 39, age: 26 },
  { id: 10046, name: "K. Matsumura", korean_name: "마츠무라 켄타", team_id: 296, position: "Midfielder", number: 41, age: 21 },
  { id: 10029, name: "R. Noguchi", korean_name: "노구치 료", team_id: 296, position: "Defender", number: 43, age: 19 },
  { id: 10028, name: "T. Deng", korean_name: "덩 티엔", team_id: 296, position: "Defender", number: 44, age: 28 },
  { id: 10048, name: "K. Aziangbe", korean_name: "케빈 아지앙베", team_id: 296, position: "Defender", number: 45, age: 22 },
  { id: 10051, name: "H. Asada", korean_name: "아사다 히로키", team_id: 296, position: "Attacker", number: 46, age: 17 },
  { id: 10037, name: "K. Yamamura", korean_name: "야마무라 켄타", team_id: 296, position: "Midfielder", number: 47, age: 36 },
  { id: 10054, name: "K. Tanimura", korean_name: "타니무라 켄타", team_id: 296, position: "Attacker", number: 48, age: 27 },
  { id: 10036, name: "K. Kato", korean_name: "카토 켄타", team_id: 296, position: "Midfielder", number: 49, age: 17 },
  { id: 10026, name: "K. Suzuki", korean_name: "스즈키 켄타", team_id: 296, position: "Goalkeeper", number: null, age: 18 },
  { id: 10022, name: "Shoma Yamashita", korean_name: "야마시타 쇼마", team_id: 296, position: "Goalkeeper", number: null, age: 19 },
];

export const J1_LEAGUE_PLAYERS = [
  ...ALBIREX_NIIGATA_PLAYERS,
  ...AVISPA_FUKUOKA_PLAYERS,
  ...CEREZO_OSAKA_PLAYERS,
  ...FAGIANO_OKAYAMA_PLAYERS,
  ...FC_TOKYO_PLAYERS,
  ...GAMBA_OSAKA_PLAYERS,
  ...KASHIMA_PLAYERS,
  ...KASHIWA_REYSOL_PLAYERS,
  ...KAWASAKI_FRONTALE_PLAYERS,
  ...KYOTO_SANGA_PLAYERS,
  ...MACHIDA_ZELVIA_PLAYERS,
  ...NAGOYA_GRAMPUS_PLAYERS,
  ...SANFRECCE_HIROSHIMA_PLAYERS,
  ...SHIMIZU_S_PULSE_PLAYERS,
  ...SHONAN_BELLMARE_PLAYERS,
  ...TOKYO_VERDY_PLAYERS,
  ...URAWA_PLAYERS,
  ...VISSEL_KOBE_PLAYERS,
  ...YOKOHAMA_FC_PLAYERS,
  ...YOKOHAMA_F_MARINOS_PLAYERS,
];
