import { PlayerMapping } from './index';

// K리그1 선수 매핑 데이터 Part 2 (나머지 9개 팀)

// FC Seoul (Team ID: 2766) - 38명
export const FC_SEOUL_PLAYERS: PlayerMapping[] = [
  { id: 34260, name: "Choi Chul-Won", korean_name: "최철원", team_id: 2766, position: "Goalkeeper" },
  { id: 356228, name: "Lim Jun-Sub", korean_name: "임준섭", team_id: 2766, position: "Goalkeeper" },
  { id: 34564, name: "Kang Hyeon-Mu", korean_name: "강현무", team_id: 2766, position: "Goalkeeper" },
  { id: 506300, name: "Yun Ki-Wook", korean_name: "윤기욱", team_id: 2766, position: "Goalkeeper" },
  { id: 53900, name: "Yazan Al Arab", korean_name: "야잔 알 아랍", team_id: 2766, position: "Defender" },
  { id: 403351, name: "Kim Hyeon-Deok", korean_name: "김현덕", team_id: 2766, position: "Defender" },
  { id: 197983, name: "Choi Jun", korean_name: "최준", team_id: 2766, position: "Defender" },
  { id: 34137, name: "Lee Han-Do", korean_name: "이한도", team_id: 2766, position: "Defender" },
  { id: 2896, name: "Kim Jin-Su", korean_name: "김진수", team_id: 2766, position: "Defender" },
  { id: 34496, name: "Kim Ju-Sung", korean_name: "김주성", team_id: 2766, position: "Defender" },
  { id: 33759, name: "Lee Sang-Min", korean_name: "이상민", team_id: 2766, position: "Defender" },
  { id: 453266, name: "Bae Hyun-Seo", korean_name: "배현서", team_id: 2766, position: "Defender" },
  { id: 404914, name: "Ahn Jae-Min", korean_name: "안재민", team_id: 2766, position: "Defender" },
  { id: 453265, name: "Choi Jun-Yeong", korean_name: "최준영", team_id: 2766, position: "Defender" },
  { id: 356197, name: "Park Seong-Hun", korean_name: "박성훈", team_id: 2766, position: "Defender" },
  { id: 34811, name: "Kim Jin-Ya", korean_name: "김진야", team_id: 2766, position: "Defender" },
  { id: 403350, name: "Cho Young-Kwang", korean_name: "조영광", team_id: 2766, position: "Defender" },
  { id: 34480, name: "Jeong Seung-Won", korean_name: "정승원", team_id: 2766, position: "Midfielder" },
  { id: 34575, name: "Lee Seung-Mo", korean_name: "이승모", team_id: 2766, position: "Midfielder" },
  { id: 900, name: "J. Lingard", korean_name: "링가드", team_id: 2766, position: "Midfielder" },
  { id: 41472, name: "A. Paločević", korean_name: "팔로체비치", team_id: 2766, position: "Midfielder" },
  { id: 34475, name: "Ryu Jae-Moon", korean_name: "류재문", team_id: 2766, position: "Midfielder" },
  { id: 511830, name: "Ji-Won Kim", korean_name: "김지원", team_id: 2766, position: "Midfielder" },
  { id: 403353, name: "Hwang Do-Yoon", korean_name: "황도윤", team_id: 2766, position: "Midfielder" },
  { id: 356199, name: "Park Jang Han-Gyeol", korean_name: "박장한결", team_id: 2766, position: "Midfielder" },
  { id: 453263, name: "Her Dong-Min", korean_name: "허동민", team_id: 2766, position: "Midfielder" },
  { id: 453262, name: "Min Ji-Hoon", korean_name: "민지훈", team_id: 2766, position: "Midfielder" },
  { id: 34517, name: "Cho Young-Wook", korean_name: "조영욱", team_id: 2766, position: "Attacker" },
  { id: 40486, name: "P. Klimala", korean_name: "클리말라", team_id: 2766, position: "Attacker" },
  { id: 25305, name: "Cheon Seong-Hoon", korean_name: "천성훈", team_id: 2766, position: "Attacker" },
  { id: 403355, name: "Son Seung-Beom", korean_name: "손승범", team_id: 2766, position: "Attacker" },
  { id: 472153, name: "Kang Ju-Hyeok", korean_name: "강주혁", team_id: 2766, position: "Attacker" },
  { id: 34392, name: "Moon Seon-Min", korean_name: "문선민", team_id: 2766, position: "Attacker" },
  { id: 506299, name: "G. Samuel", korean_name: "사무엘", team_id: 2766, position: "Attacker" },
  { id: 306618, name: "Kang Seong-Jin", korean_name: "강성진", team_id: 2766, position: "Attacker" },
  { id: 199299, name: "Jung Han-Min", korean_name: "정한민", team_id: 2766, position: "Attacker" },
  { id: 14320, name: "M. Dugandžić", korean_name: "두간지치", team_id: 2766, position: "Attacker" },
  { id: 41134, name: "Lucas Silva", korean_name: "루카스 실바", team_id: 2766, position: "Attacker" },
];

// Gangwon FC (Team ID: 2746) - 46명
export const GANGWON_FC_PLAYERS: PlayerMapping[] = [
  { id: 34641, name: "Lee Gwang-Yeon", korean_name: "이광연", team_id: 2746, position: "Goalkeeper" },
  { id: 173405, name: "Park Cheong-Hyo", korean_name: "박청효", team_id: 2746, position: "Goalkeeper" },
  { id: 518076, name: "Hong Jin-Hyeok", korean_name: "홍진혁", team_id: 2746, position: "Goalkeeper" },
  { id: 453972, name: "Kim Yu-Sung", korean_name: "김유성", team_id: 2746, position: "Goalkeeper" },
  { id: 403344, name: "Cho Min-Kyu", korean_name: "조민규", team_id: 2746, position: "Goalkeeper" },
  { id: 224652, name: "Seo Min-Woo", korean_name: "서민우", team_id: 2746, position: "Defender" },
  { id: 304951, name: "Lee Gi-Hyuk", korean_name: "이기혁", team_id: 2746, position: "Defender" },
  { id: 403346, name: "Jo Hyun-Tae", korean_name: "조현태", team_id: 2746, position: "Defender" },
  { id: 270144, name: "M. Tuci", korean_name: "투치", team_id: 2746, position: "Defender" },
  { id: 34692, name: "Choi Jeong-Hoon", korean_name: "최정훈", team_id: 2746, position: "Defender" },
  { id: 403348, name: "Lee Dong-Jin", korean_name: "이동진", team_id: 2746, position: "Defender" },
  { id: 2894, name: "Hong Chul", korean_name: "홍철", team_id: 2746, position: "Defender" },
  { id: 304954, name: "Song Jun-Seok", korean_name: "송준석", team_id: 2746, position: "Defender" },
  { id: 99279, name: "Han-Sol Choi", korean_name: "최한솔", team_id: 2746, position: "Defender" },
  { id: 356200, name: "Kim Sin-Jin", korean_name: "김신진", team_id: 2746, position: "Defender" },
  { id: 414158, name: "Kang Joon-Hyuck", korean_name: "강준혁", team_id: 2746, position: "Defender" },
  { id: 506287, name: "Jeong Seung-Bin", korean_name: "정승빈", team_id: 2746, position: "Defender" },
  { id: 506286, name: "Park Soo-Hwan", korean_name: "박수환", team_id: 2746, position: "Defender" },
  { id: 34615, name: "Kim Dong-Hyun", korean_name: "김동현", team_id: 2746, position: "Midfielder" },
  { id: 304959, name: "Kim Dae-Woo", korean_name: "김대우", team_id: 2746, position: "Midfielder" },
  { id: 34812, name: "Kim Kang-Guk", korean_name: "김강국", team_id: 2746, position: "Midfielder" },
  { id: 506285, name: "Kim Tae-Hwan", korean_name: "김태환", team_id: 2746, position: "Midfielder" },
  { id: 449318, name: "Hwang Eun-Chong", korean_name: "황은총", team_id: 2746, position: "Midfielder" },
  { id: 453969, name: "Shin Min-Ha", korean_name: "신민하", team_id: 2746, position: "Midfielder" },
  { id: 228837, name: "Goo Bon-Cheol", korean_name: "구본철", team_id: 2746, position: "Midfielder" },
  { id: 34786, name: "Yun Il-Lok", korean_name: "윤일록", team_id: 2746, position: "Midfielder" },
  { id: 34348, name: "Lee You-Hyeon", korean_name: "이유현", team_id: 2746, position: "Midfielder" },
  { id: 453259, name: "Won Hee-Do", korean_name: "원희도", team_id: 2746, position: "Midfielder" },
  { id: 301577, name: "Kang Yun-Gu", korean_name: "강윤구", team_id: 2746, position: "Attacker" },
  { id: 10176, name: "Vitor Gabriel", korean_name: "비토르 가브리엘", team_id: 2746, position: "Attacker" },
  { id: 474635, name: "Jin Jun-Seo", korean_name: "진준서", team_id: 2746, position: "Attacker" },
  { id: 34556, name: "Kim Gun-Hee", korean_name: "김건희", team_id: 2746, position: "Attacker" },
  { id: 404196, name: "Cho Jin-Hyuk", korean_name: "조진혁", team_id: 2746, position: "Attacker" },
  { id: 34442, name: "Lee Sang-Heon", korean_name: "이상헌", team_id: 2746, position: "Attacker" },
  { id: 34163, name: "Park Ho-Young", korean_name: "박호영", team_id: 2746, position: "Attacker" },
  { id: 197987, name: "Kim Min-Jun", korean_name: "김민준", team_id: 2746, position: "Attacker" },
  { id: 405575, name: "Kim Do-Hyun", korean_name: "김도현", team_id: 2746, position: "Attacker" },
  { id: 506281, name: "Yoo Byung-Heon", korean_name: "유병헌", team_id: 2746, position: "Attacker" },
  { id: 506283, name: "Lee Ji-Ho", korean_name: "이지호", team_id: 2746, position: "Attacker" },
  { id: 41652, name: "Romário Baldé", korean_name: "로마리우 발데", team_id: 2746, position: "Attacker" },
  { id: 15548, name: "Kuagica Sebastião Bondo David", korean_name: "쿠아기사", team_id: 2746, position: "Attacker" },
  { id: 506282, name: "Sung Ki-Wan", korean_name: "성기완", team_id: 2746, position: "Attacker" },
  { id: 474634, name: "Kim Hyung-Jin", korean_name: "김형진", team_id: 2746, position: "Attacker" },
  { id: 34611, name: "Choe Byeong-Chan", korean_name: "최병찬", team_id: 2746, position: "Attacker" },
  { id: 411324, name: "Jung In-Jeung", korean_name: "정인증", team_id: 2746, position: "Attacker" },
  { id: 550389, name: "Goo Bon-Cheul", korean_name: "구본철", team_id: 2746, position: undefined },
];

// Gimcheon Sangmu FC (Team ID: 2768) - 42명
export const GIMCHEON_SANGMU_FC_PLAYERS: PlayerMapping[] = [
  { id: 34487, name: "Baek Jong-Beom", korean_name: "백종범", team_id: 2768, position: "Goalkeeper" },
  { id: 34186, name: "Kim Tae-Hoon", korean_name: "김태훈", team_id: 2768, position: "Goalkeeper" },
  { id: 263116, name: "Lee Ju-Hyun", korean_name: "이주현", team_id: 2768, position: "Goalkeeper" },
  { id: 304974, name: "Jeong Myeong-Je", korean_name: "정명제", team_id: 2768, position: "Goalkeeper" },
  { id: 34788, name: "Kim Dong-Heon", korean_name: "김동헌", team_id: 2768, position: "Goalkeeper" },
  { id: 146471, name: "Kim Min-Kyu", korean_name: "김민규", team_id: 2768, position: "Defender" },
  { id: 14697, name: "Kim Hyun-Woo", korean_name: "김현우", team_id: 2768, position: "Defender" },
  { id: 228836, name: "Kim Kang-San", korean_name: "김강산", team_id: 2768, position: "Defender" },
  { id: 7217, name: "Oh In-Pyo", korean_name: "오인표", team_id: 2768, position: "Defender" },
  { id: 34767, name: "Lim Dug-Keun", korean_name: "임덕근", team_id: 2768, position: "Defender" },
  { id: 357207, name: "Choi Ye-Hoon", korean_name: "최예훈", team_id: 2768, position: "Defender" },
  { id: 357208, name: "Hong Uk-Hyeon", korean_name: "홍욱현", team_id: 2768, position: "Defender" },
  { id: 304944, name: "Park Jin-Seong", korean_name: "박진성", team_id: 2768, position: "Defender" },
  { id: 34416, name: "Kim Min-Duk", korean_name: "김민덕", team_id: 2768, position: "Defender" },
  { id: 34686, name: "Park Dae-Won", korean_name: "박대원", team_id: 2768, position: "Defender" },
  { id: 308272, name: "Lee Jung-Taek", korean_name: "이정택", team_id: 2768, position: "Defender" },
  { id: 309843, name: "Lee Chan-Ouk", korean_name: "이찬욱", team_id: 2768, position: "Defender" },
  { id: 356105, name: "Min Kyung-Hyun", korean_name: "민경현", team_id: 2768, position: "Defender" },
  { id: 34310, name: "Park Soo-Il", korean_name: "박수일", team_id: 2768, position: "Defender" },
  { id: 33202, name: "Jo Jin-Woo", korean_name: "조진우", team_id: 2768, position: "Defender" },
  { id: 411141, name: "Yu Sun", korean_name: "유선", team_id: 2768, position: "Defender" },
  { id: 34661, name: "Lee Hyun-Sik", korean_name: "이현식", team_id: 2768, position: "Midfielder" },
  { id: 403349, name: "Lee Seung-Won", korean_name: "이승원", team_id: 2768, position: "Midfielder" },
  { id: 99249, name: "Won Ki-Jong", korean_name: "원기종", team_id: 2768, position: "Midfielder" },
  { id: 224633, name: "Lee Sang-Min", korean_name: "이상민", team_id: 2768, position: "Midfielder" },
  { id: 224641, name: "Lee Jin-Yong", korean_name: "이진용", team_id: 2768, position: "Midfielder" },
  { id: 356242, name: "Choi Gi-Yun", korean_name: "최기윤", team_id: 2768, position: "Midfielder" },
  { id: 402849, name: "Park Se-Jin", korean_name: "박세진", team_id: 2768, position: "Midfielder" },
  { id: 304904, name: "Kim Yi-Seok", korean_name: "김이석", team_id: 2768, position: "Midfielder" },
  { id: 34623, name: "Tae-Jun Park", korean_name: "박태준", team_id: 2768, position: "Midfielder" },
  { id: 99222, name: "Kim Kyung-Jun", korean_name: "김경준", team_id: 2768, position: "Attacker" },
  { id: 34481, name: "Kim Dae-Won", korean_name: "김대원", team_id: 2768, position: "Attacker" },
  { id: 228842, name: "Kim In-Gyun", korean_name: "김인균", team_id: 2768, position: "Attacker" },
  { id: 34580, name: "Kim Chan", korean_name: "김찬", team_id: 2768, position: "Attacker" },
  { id: 304960, name: "Park Sang-Hyeok", korean_name: "박상혁", team_id: 2768, position: "Attacker" },
  { id: 328138, name: "Chu Sang-Hun", korean_name: "주상훈", team_id: 2768, position: "Attacker" },
  { id: 128777, name: "Yu Kang-Hyun", korean_name: "유강현", team_id: 2768, position: "Attacker" },
  { id: 403359, name: "Kim Ju-Chan", korean_name: "김주찬", team_id: 2768, position: "Attacker" },
  { id: 34469, name: "Go Jae-Hyeon", korean_name: "고재현", team_id: 2768, position: "Attacker" },
  { id: 34258, name: "Mo Jae-Hyeon", korean_name: "모재현", team_id: 2768, position: "Attacker" },
  { id: 550367, name: "Choi Ye-Hoon", korean_name: "최예훈", team_id: 2768, position: undefined },
  { id: 550542, name: "Lee Ju-Hyun", korean_name: "이주현", team_id: 2768, position: undefined },
];

// Gwangju FC (Team ID: 2759) - 41명
export const GWANGJU_FC_PLAYERS: PlayerMapping[] = [
  { id: 99559, name: "Kim Kyeong-Min", korean_name: "김경민", team_id: 2759, position: "Goalkeeper" },
  { id: 308724, name: "Roh Hee-Dong", korean_name: "노희동", team_id: 2759, position: "Goalkeeper" },
  { id: 472257, name: "Kim Dong-Hwa", korean_name: "김동화", team_id: 2759, position: "Goalkeeper" },
  { id: 408840, name: "Kim Tae-Joon", korean_name: "김태준", team_id: 2759, position: "Goalkeeper" },
  { id: 403361, name: "Jo Seong-Kwon", korean_name: "조성권", team_id: 2759, position: "Defender" },
  { id: 34539, name: "Lee Min-Gi", korean_name: "이민기", team_id: 2759, position: "Defender" },
  { id: 54597, name: "Bruno Oliveira", korean_name: "브루노 올리베이라", team_id: 2759, position: "Defender" },
  { id: 268622, name: "Byeon Jun-Soo", korean_name: "변준수", team_id: 2759, position: "Defender" },
  { id: 34610, name: "Ahn Young-Kyu", korean_name: "안영규", team_id: 2759, position: "Defender" },
  { id: 454029, name: "Jin Si-Woo", korean_name: "진시우", team_id: 2759, position: "Defender" },
  { id: 356378, name: "Kim Jin-Ho", korean_name: "김진호", team_id: 2759, position: "Defender" },
  { id: 460723, name: "Kwak Sung-Hun", korean_name: "곽성훈", team_id: 2759, position: "Defender" },
  { id: 34685, name: "Min Sang-Gi", korean_name: "민상기", team_id: 2759, position: "Defender" },
  { id: 3464, name: "J. Asani", korean_name: "아사니", team_id: 2759, position: "Midfielder" },
  { id: 262128, name: "Lee Kang-Hyun", korean_name: "이강현", team_id: 2759, position: "Midfielder" },
  { id: 26098, name: "Choi Kyoung-Rok", korean_name: "최경록", team_id: 2759, position: "Midfielder" },
  { id: 356251, name: "Yu Je-Ho", korean_name: "유제호", team_id: 2759, position: "Midfielder" },
  { id: 403362, name: "Jung Ji-Hun", korean_name: "정지훈", team_id: 2759, position: "Midfielder" },
  { id: 506280, name: "Kang Hui-Su", korean_name: "강희수", team_id: 2759, position: "Midfielder" },
  { id: 34510, name: "Kim Han-Gil", korean_name: "김한길", team_id: 2759, position: "Midfielder" },
  { id: 34472, name: "Oh Hu-Seong", korean_name: "오후성", team_id: 2759, position: "Midfielder" },
  { id: 2902, name: "Ju Se-Jong", korean_name: "주세종", team_id: 2759, position: "Midfielder" },
  { id: 472264, name: "Yong-Jun Hong", korean_name: "홍용준", team_id: 2759, position: "Midfielder" },
  { id: 310870, name: "Gabriel Tigrão", korean_name: "가브리엘 티그라오", team_id: 2759, position: "Attacker" },
  { id: 57162, name: "H. Friðjónsson", korean_name: "프리욘손", team_id: 2759, position: "Attacker" },
  { id: 34443, name: "Park Jeong-In", korean_name: "박정인", team_id: 2759, position: "Attacker" },
  { id: 9659, name: "Reis", korean_name: "헤이스", team_id: 2759, position: "Attacker" },
  { id: 34330, name: "In-Hyeok Park", korean_name: "박인혁", team_id: 2759, position: "Attacker" },
  { id: 201289, name: "Kwon Sung-Yun", korean_name: "권성윤", team_id: 2759, position: "Attacker" },
  { id: 453967, name: "Ahn Hyeok-Ju", korean_name: "안혁주", team_id: 2759, position: "Attacker" },
  { id: 34553, name: "Shin Chang-Moo", korean_name: "신창무", team_id: 2759, position: "Attacker" },
  { id: 203221, name: "Hwang Jae-Hwan", korean_name: "황재환", team_id: 2759, position: "Attacker" },
  { id: 479273, name: "Kim Yun-Ho", korean_name: "김윤호", team_id: 2759, position: "Attacker" },
  { id: 96335, name: "João Magno", korean_name: "주앙 마그노", team_id: 2759, position: "Attacker" },
  { id: 34591, name: "Ha Seung-Un", korean_name: "하승운", team_id: 2759, position: "Attacker" },
  { id: 453968, name: "Moon Min-seo", korean_name: "문민서", team_id: 2759, position: "Attacker" },
  { id: 423712, name: "Lee Jae-Hwan", korean_name: "이재환", team_id: 2759, position: "Attacker" },
  { id: 550369, name: "Lee Min-Ki", korean_name: "이민기", team_id: 2759, position: undefined },
  { id: 550411, name: "Jin Si-woo", korean_name: "진시우", team_id: 2759, position: undefined },
  { id: 550439, name: "Ahn Hyeok-Ju", korean_name: "안혁주", team_id: 2759, position: undefined },
  { id: 550541, name: "Kim Dong-Hwa", korean_name: "김동화", team_id: 2759, position: undefined },
];

// Jeju United FC (Team ID: 2761) - 42명
export const JEJU_UNITED_FC_PLAYERS: PlayerMapping[] = [
  { id: 34602, name: "Kim Dong-Jun", korean_name: "김동준", team_id: 2761, position: "Goalkeeper" },
  { id: 213979, name: "An Chan-Gi", korean_name: "안찬기", team_id: 2761, position: "Goalkeeper" },
  { id: 357218, name: "Cho Seong-Been", korean_name: "조성빈", team_id: 2761, position: "Goalkeeper" },
  { id: 423693, name: "Joo Seung-Min", korean_name: "주승민", team_id: 2761, position: "Goalkeeper" },
  { id: 34269, name: "Kim Jae-Woo", korean_name: "김재우", team_id: 2761, position: "Defender" },
  { id: 199847, name: "Jang Min-Gyu", korean_name: "장민규", team_id: 2761, position: "Defender" },
  { id: 34726, name: "Song Ju-Hun", korean_name: "송주훈", team_id: 2761, position: "Defender" },
  { id: 99568, name: "Chung Woon", korean_name: "정운", team_id: 2761, position: "Defender" },
  { id: 237141, name: "Oh Jae-Hyeok", korean_name: "오재혁", team_id: 2761, position: "Defender" },
  { id: 34273, name: "An Tae-Hyun", korean_name: "안태현", team_id: 2761, position: "Defender" },
  { id: 50375, name: "Rim Chang-Woo", korean_name: "림창우", team_id: 2761, position: "Defender" },
  { id: 34607, name: "Lim Chai-Min", korean_name: "임채민", team_id: 2761, position: "Defender" },
  { id: 453261, name: "Jo In-Jung", korean_name: "조인정", team_id: 2761, position: "Defender" },
  { id: 34681, name: "Kim Tae-Hwan", korean_name: "김태환", team_id: 2761, position: "Defender" },
  { id: 201292, name: "Choi Won-Chang", korean_name: "최원창", team_id: 2761, position: "Defender" },
  { id: 506279, name: "Kim Ji-Woon", korean_name: "김지운", team_id: 2761, position: "Defender" },
  { id: 301229, name: "Italo Moreira", korean_name: "이탈로 모레이라", team_id: 2761, position: "Midfielder" },
  { id: 2904, name: "Kim Jung-Min", korean_name: "김정민", team_id: 2761, position: "Midfielder" },
  { id: 34777, name: "Lee Chang-Min", korean_name: "이창민", team_id: 2761, position: "Midfielder" },
  { id: 32869, name: "Yu In-Soo", korean_name: "유인수", team_id: 2761, position: "Midfielder" },
  { id: 510580, name: "Kim Jun-Ha", korean_name: "김준하", team_id: 2761, position: "Midfielder" },
  { id: 34358, name: "Kim Geon-Woong", korean_name: "김건웅", team_id: 2761, position: "Midfielder" },
  { id: 453260, name: "Kim Jae-Min", korean_name: "김재민", team_id: 2761, position: "Midfielder" },
  { id: 304965, name: "Kim Bong-Soo", korean_name: "김봉수", team_id: 2761, position: "Midfielder" },
  { id: 510579, name: "Kim Jin-Ho", korean_name: "김진호", team_id: 2761, position: "Midfielder" },
  { id: 428144, name: "Kwon Sun-Ho", korean_name: "권순호", team_id: 2761, position: "Midfielder" },
  { id: 237049, name: "Kim Ryun-Seong", korean_name: "김윤성", team_id: 2761, position: "Midfielder" },
  { id: 34329, name: "Kim Seung-Sub", korean_name: "김승섭", team_id: 2761, position: "Attacker" },
  { id: 34397, name: "Tiago Alves", korean_name: "티아고 알베스", team_id: 2761, position: "Attacker" },
  { id: 109209, name: "Yuri", korean_name: "유리", team_id: 2761, position: "Attacker" },
  { id: 96733, name: "Nam Tae-Hee", korean_name: "남태희", team_id: 2761, position: "Attacker" },
  { id: 11008, name: "Evandro", korean_name: "에반드로", team_id: 2761, position: "Attacker" },
  { id: 294905, name: "Pedrinho", korean_name: "페드리뉴", team_id: 2761, position: "Attacker" },
  { id: 305695, name: "Denilson", korean_name: "데닐손", team_id: 2761, position: "Attacker" },
  { id: 34781, name: "Seo Jin-Su", korean_name: "서진수", team_id: 2761, position: "Attacker" },
  { id: 305751, name: "Shin Sang-Eun", korean_name: "신상은", team_id: 2761, position: "Attacker" },
  { id: 404913, name: "Ji Sang-Wook", korean_name: "지상욱", team_id: 2761, position: "Attacker" },
  { id: 228856, name: "Lee Kun-Hee", korean_name: "이건희", team_id: 2761, position: "Attacker" },
  { id: 34501, name: "Park Dong-Jin", korean_name: "박동진", team_id: 2761, position: "Attacker" },
  { id: 34148, name: "Kim Ju-Kong", korean_name: "김주공", team_id: 2761, position: "Attacker" },
  { id: 510578, name: "Kang Min-Jae", korean_name: "강민재", team_id: 2761, position: "Attacker" },
  { id: 243923, name: "Kim Hyeon-Wu", korean_name: "김현우", team_id: 2761, position: "Attacker" },
];

// Jeonbuk Motors (Team ID: 2762) - 55명
export const JEONBUK_MOTORS_PLAYERS: PlayerMapping[] = [
  { id: 34371, name: "Kim Jeong-Hoon", korean_name: "김정훈", team_id: 2762, position: "Goalkeeper" },
  { id: 363020, name: "Jeon Ji-Wan", korean_name: "전지완", team_id: 2762, position: "Goalkeeper" },
  { id: 34374, name: "Song Bum-Keun", korean_name: "송범근", team_id: 2762, position: "Goalkeeper" },
  { id: 512563, name: "Lee Han-gyeol", korean_name: "이한결", team_id: 2762, position: "Goalkeeper" },
  { id: 34537, name: "Kim Young-Bin", korean_name: "김영빈", team_id: 2762, position: "Defender" },
  { id: 403340, name: "Choi Woo-Jin", korean_name: "최우진", team_id: 2762, position: "Defender" },
  { id: 34453, name: "Jeong Tae-Wook", korean_name: "정태욱", team_id: 2762, position: "Defender" },
  { id: 2913, name: "Kwon Chang-Hoon", korean_name: "권창훈", team_id: 2762, position: "Defender" },
  { id: 34417, name: "Kim Tae-Hwan", korean_name: "김태환", team_id: 2762, position: "Defender" },
  { id: 2893, name: "Choi Chul-Soon", korean_name: "최철순", team_id: 2762, position: "Defender" },
  { id: 34376, name: "Hong Jeong-Ho", korean_name: "홍정호", team_id: 2762, position: "Defender" },
  { id: 356215, name: "Lee Jun-Ho", korean_name: "이준호", team_id: 2762, position: "Defender" },
  { id: 510089, name: "Kim Jun-Yeong", korean_name: "김준영", team_id: 2762, position: "Defender" },
  { id: 412095, name: "Kim Ha-Jun", korean_name: "김하준", team_id: 2762, position: "Defender" },
  { id: 99299, name: "Kim Tae-Hyun", korean_name: "김태현", team_id: 2762, position: "Defender" },
  { id: 356216, name: "Park Kyu-Min", korean_name: "박규민", team_id: 2762, position: "Defender" },
  { id: 34609, name: "Yeon Je-Un", korean_name: "연제운", team_id: 2762, position: "Defender" },
  { id: 508428, name: "Hwang Jung-Gu", korean_name: "황정구", team_id: 2762, position: "Defender" },
  { id: 508427, name: "Hwang Seung-Jun", korean_name: "황승준", team_id: 2762, position: "Defender" },
  { id: 513800, name: "Kim Su-Hyung", korean_name: "김수형", team_id: 2762, position: "Defender" },
  { id: 508425, name: "Lee Jae-Jun", korean_name: "이재준", team_id: 2762, position: "Defender" },
  { id: 423701, name: "Seo Jeong-Hyeok", korean_name: "서정혁", team_id: 2762, position: "Defender" },
  { id: 511559, name: "Yun Ju-Young", korean_name: "윤주영", team_id: 2762, position: "Defender" },
  { id: 99211, name: "Park Jin-Seop", korean_name: "박진섭", team_id: 2762, position: "Midfielder" },
  { id: 41273, name: "João Gamboa", korean_name: "주앙 감보아", team_id: 2762, position: "Midfielder" },
  { id: 34584, name: "Lee Soo-Bin", korean_name: "이수빈", team_id: 2762, position: "Midfielder" },
  { id: 34655, name: "Han Kook-Young", korean_name: "한국영", team_id: 2762, position: "Midfielder" },
  { id: 34598, name: "Song Min-Kyu", korean_name: "송민규", team_id: 2762, position: "Midfielder" },
  { id: 34171, name: "Lee Dong-Jun", korean_name: "이동준", team_id: 2762, position: "Midfielder" },
  { id: 2914, name: "Lee Seung-Woo", korean_name: "이승우", team_id: 2762, position: "Midfielder" },
  { id: 363021, name: "Kang Sang-Yoon", korean_name: "강상윤", team_id: 2762, position: "Midfielder" },
  { id: 34708, name: "Jeon Jin-Woo", korean_name: "전진우", team_id: 2762, position: "Midfielder" },
  { id: 423704, name: "Jin Tae-Ho", korean_name: "진태호", team_id: 2762, position: "Midfielder" },
  { id: 51311, name: "N. Boateng", korean_name: "보아텡", team_id: 2762, position: "Midfielder" },
  { id: 34738, name: "Lee Yeong-Jae", korean_name: "이영재", team_id: 2762, position: "Midfielder" },
  { id: 34208, name: "Maeng Seong-Ung", korean_name: "맹성웅", team_id: 2762, position: "Midfielder" },
  { id: 427052, name: "J. Anasmo", korean_name: "아나스모", team_id: 2762, position: "Midfielder" },
  { id: 405547, name: "Lee Kyu-Dong", korean_name: "이규동", team_id: 2762, position: "Midfielder" },
  { id: 454027, name: "Jang Nam-ung", korean_name: "장남웅", team_id: 2762, position: "Midfielder" },
  { id: 306608, name: "Jeon Byung-Kwan", korean_name: "전병관", team_id: 2762, position: "Midfielder" },
  { id: 34385, name: "Han Kyo-Won", korean_name: "한교원", team_id: 2762, position: "Midfielder" },
  { id: 34168, name: "Kim Jin-Gyu", korean_name: "김진규", team_id: 2762, position: "Midfielder" },
  { id: 449324, name: "Han Seok-Jin", korean_name: "한석진", team_id: 2762, position: "Midfielder" },
  { id: 508424, name: "Kim Min-Jae", korean_name: "김민재", team_id: 2762, position: "Midfielder" },
  { id: 508423, name: "Yoon Hyun-Seok", korean_name: "윤현석", team_id: 2762, position: "Midfielder" },
  { id: 197251, name: "Tiago Orobó", korean_name: "티아고 오로보", team_id: 2762, position: "Attacker" },
  { id: 356124, name: "Park Jae-Yong", korean_name: "박재용", team_id: 2762, position: "Attacker" },
  { id: 356239, name: "Um Seung-Min", korean_name: "엄승민", team_id: 2762, position: "Attacker" },
  { id: 47374, name: "P. Twumasi", korean_name: "트우마시", team_id: 2762, position: "Attacker" },
  { id: 266665, name: "Hernandes", korean_name: "에르난데스", team_id: 2762, position: "Attacker" },
  { id: 119025, name: "A. Compagno", korean_name: "콤파뇨", team_id: 2762, position: "Attacker" },
  { id: 508426, name: "Jeong Sang-Woon", korean_name: "정상운", team_id: 2762, position: "Attacker" },
  { id: 508422, name: "Kang Hyeon-Jong", korean_name: "강현종", team_id: 2762, position: "Attacker" },
  { id: 405546, name: "Kim Chang-Hun", korean_name: "김창훈", team_id: 2762, position: "Attacker" },
  { id: 409425, name: "Sung Jin-Young", korean_name: "성진영", team_id: 2762, position: "Attacker" },
];

// Pohang Steelers (Team ID: 2764) - 46명
export const POHANG_STEELERS_PLAYERS: PlayerMapping[] = [
  { id: 34120, name: "Yun Pyeong-Gook", korean_name: "윤평국", team_id: 2764, position: "Goalkeeper" },
  { id: 99205, name: "Hwang In-Jae", korean_name: "황인재", team_id: 2764, position: "Goalkeeper" },
  { id: 423692, name: "Hong Seong-Min", korean_name: "홍성민", team_id: 2764, position: "Goalkeeper" },
  { id: 474148, name: "Kwon Neung", korean_name: "권능", team_id: 2764, position: "Goalkeeper" },
  { id: 301575, name: "Lee Dong-Hee", korean_name: "이동희", team_id: 2764, position: "Defender" },
  { id: 356233, name: "Lee Gyu-Baek", korean_name: "이규백", team_id: 2764, position: "Defender" },
  { id: 34571, name: "Jeon Min-Gwang", korean_name: "전민광", team_id: 2764, position: "Defender" },
  { id: 7032, name: "J. Aspropotamitis", korean_name: "아스프로타미티스", team_id: 2764, position: "Defender" },
  { id: 472263, name: "Kang Min-Jun", korean_name: "강민준", team_id: 2764, position: "Defender" },
  { id: 146509, name: "Park Seung-Wook", korean_name: "박승욱", team_id: 2764, position: "Defender" },
  { id: 34650, name: "Shin Kwang-Hoon", korean_name: "신광훈", team_id: 2764, position: "Defender" },
  { id: 91677, name: "Park Chan-Yong", korean_name: "박찬용", team_id: 2764, position: "Defender" },
  { id: 453315, name: "Lee Dong-hyeop", korean_name: "이동협", team_id: 2764, position: "Defender" },
  { id: 506305, name: "Han Hyeon-Seo", korean_name: "한현서", team_id: 2764, position: "Defender" },
  { id: 506306, name: "Cha Jun-Young", korean_name: "차준영", team_id: 2764, position: "Defender" },
  { id: 237220, name: "Lee Tae-Seok", korean_name: "이태석", team_id: 2764, position: "Defender" },
  { id: 34743, name: "Jo Sung-Wook", korean_name: "조성욱", team_id: 2764, position: "Defender" },
  { id: 423700, name: "Lee Chang-Woo", korean_name: "이창우", team_id: 2764, position: "Defender" },
  { id: 306614, name: "Eo Jeong-Won", korean_name: "어정원", team_id: 2764, position: "Midfielder" },
  { id: 34694, name: "Kim Jong-Woo", korean_name: "김종우", team_id: 2764, position: "Midfielder" },
  { id: 237933, name: "Oberdan", korean_name: "오베르단", team_id: 2764, position: "Midfielder" },
  { id: 36440, name: "Juninho Rocha", korean_name: "주니뉴 로샤", team_id: 2764, position: "Midfielder" },
  { id: 335129, name: "Cho Jae-Hun", korean_name: "조재훈", team_id: 2764, position: "Midfielder" },
  { id: 304971, name: "Kim Jun-Ho", korean_name: "김준호", team_id: 2764, position: "Midfielder" },
  { id: 506304, name: "Hong Ji-Woo", korean_name: "홍지우", team_id: 2764, position: "Midfielder" },
  { id: 18900, name: "Ki Sung-Yueng", korean_name: "기성용", team_id: 2764, position: "Midfielder" },
  { id: 453314, name: "Hwang Seo-Woong", korean_name: "황서웅", team_id: 2764, position: "Midfielder" },
  { id: 453313, name: "Kim Dong-Jin", korean_name: "김동진", team_id: 2764, position: "Midfielder" },
  { id: 457024, name: "Kim Dong-Min", korean_name: "김동민", team_id: 2764, position: "Midfielder" },
  { id: 34429, name: "Kim In-Sung", korean_name: "김인성", team_id: 2764, position: "Attacker" },
  { id: 277197, name: "Jorge Luiz", korean_name: "조르지 루이스", team_id: 2764, position: "Attacker" },
  { id: 34237, name: "Baek Sung-Dong", korean_name: "백성동", team_id: 2764, position: "Attacker" },
  { id: 453312, name: "Lee Kyu-Min", korean_name: "이규민", team_id: 2764, position: "Attacker" },
  { id: 403332, name: "Kang Hyeon-Je", korean_name: "강현제", team_id: 2764, position: "Attacker" },
  { id: 404922, name: "Kim Beom-Su", korean_name: "김범수", team_id: 2764, position: "Attacker" },
  { id: 304972, name: "Lee Ho-Jae", korean_name: "이호재", team_id: 2764, position: "Attacker" },
  { id: 262604, name: "An Jae-Jun", korean_name: "안재준", team_id: 2764, position: "Attacker" },
  { id: 488847, name: "Su-Been Park", korean_name: "박수빈", team_id: 2764, position: "Attacker" },
  { id: 237096, name: "Hong Yun-Sang", korean_name: "홍윤상", team_id: 2764, position: "Attacker" },
  { id: 506301, name: "Lee Heon-Jae", korean_name: "이헌재", team_id: 2764, position: "Attacker" },
  { id: 34629, name: "Jo Seong-Joon", korean_name: "조성준", team_id: 2764, position: "Attacker" },
  { id: 34569, name: "Wanderson", korean_name: "반데르손", team_id: 2764, position: "Attacker" },
  { id: 506302, name: "Cho Sang-Hyeok", korean_name: "조상혁", team_id: 2764, position: "Attacker" },
  { id: 506303, name: "Baek Seung-Won", korean_name: "백승원", team_id: 2764, position: "Attacker" },
  { id: 550407, name: "Han Hyeon-Seo", korean_name: "한현서", team_id: 2764, position: undefined },
  { id: 568649, name: "S. Park", korean_name: "박수빈", team_id: 2764, position: undefined },
];

// Suwon City FC (Team ID: 2756) - 57명
export const SUWON_CITY_FC_PLAYERS: PlayerMapping[] = [
  { id: 455322, name: "Hwang Ju-Ho", korean_name: "황주호", team_id: 2756, position: "Goalkeeper" },
  { id: 34013, name: "Ahn Joon-Soo", korean_name: "안준수", team_id: 2756, position: "Goalkeeper" },
  { id: 506298, name: "Baek Seung-Min", korean_name: "백승민", team_id: 2756, position: "Goalkeeper" },
  { id: 510577, name: "Joo Ho-Yeon", korean_name: "주호연", team_id: 2756, position: "Goalkeeper" },
  { id: 0, name: "Moon Jung-Woo", korean_name: "문정우", team_id: 2756, position: "Goalkeeper" },
  { id: 34380, name: "Lee Yong", korean_name: "이용", team_id: 2756, position: "Defender" },
  { id: 34455, name: "Kim Tae-Han", korean_name: "김태한", team_id: 2756, position: "Defender" },
  { id: 408844, name: "Lee Hyun-Yong", korean_name: "이현용", team_id: 2756, position: "Defender" },
  { id: 33754, name: "Choi Kyu-Baek", korean_name: "최규백", team_id: 2756, position: "Defender" },
  { id: 356250, name: "Hwang In-Taek", korean_name: "황인택", team_id: 2756, position: "Defender" },
  { id: 34309, name: "Lee Zi-Sol", korean_name: "이지솔", team_id: 2756, position: "Defender" },
  { id: 99565, name: "Seo Jae-Min", korean_name: "서재민", team_id: 2756, position: "Defender" },
  { id: 308264, name: "Jang Young-Woo", korean_name: "장영우", team_id: 2756, position: "Defender" },
  { id: 506296, name: "Kwon Do-Yeong", korean_name: "권도영", team_id: 2756, position: "Defender" },
  { id: 453880, name: "Kim Dae-Hyun", korean_name: "김대현", team_id: 2756, position: "Defender" },
  { id: 224634, name: "Kim Jae-Sung", korean_name: "김재성", team_id: 2756, position: "Defender" },
  { id: 34229, name: "Kim Ju-Yeop", korean_name: "김주엽", team_id: 2756, position: "Defender" },
  { id: 99199, name: "Ahn Hyun-Beom", korean_name: "안현범", team_id: 2756, position: "Defender" },
  { id: 453881, name: "Han Sang-Kyu", korean_name: "한상규", team_id: 2756, position: "Defender" },
  { id: 506297, name: "Kim Eun-Gyeom", korean_name: "김은겸", team_id: 2756, position: "Defender" },
  { id: 34635, name: "Lee Jae-Won", korean_name: "이재원", team_id: 2756, position: "Midfielder" },
  { id: 57187, name: "M. Ofkir", korean_name: "오프키르", team_id: 2756, position: "Midfielder" },
  { id: 304970, name: "Roh Kyung-Ho", korean_name: "노경호", team_id: 2756, position: "Midfielder" },
  { id: 162990, name: "L. Abanda", korean_name: "아반다", team_id: 2756, position: "Midfielder" },
  { id: 34554, name: "Yoon Bit-Garam", korean_name: "윤빛가람", team_id: 2756, position: "Midfielder" },
  { id: 9541, name: "Andrigo", korean_name: "안드리고", team_id: 2756, position: "Midfielder" },
  { id: 453319, name: "Jo Jun-Hyun", korean_name: "조준현", team_id: 2756, position: "Midfielder" },
  { id: 34353, name: "Han Chan-Hee", korean_name: "한찬희", team_id: 2756, position: "Midfielder" },
  { id: 34387, name: "Jang Yun-Ho", korean_name: "장윤호", team_id: 2756, position: "Midfielder" },
  { id: 357210, name: "Park Cheol-Woo", korean_name: "박철우", team_id: 2756, position: "Midfielder" },
  { id: 453320, name: "Sin Il-Yeon", korean_name: "신일연", team_id: 2756, position: "Midfielder" },
  { id: 442962, name: "Kim Do-Yoon", korean_name: "김도윤", team_id: 2756, position: "Midfielder" },
  { id: 506295, name: "Choi San", korean_name: "최산", team_id: 2756, position: "Midfielder" },
  { id: 34128, name: "Lee Si-Young", korean_name: "이시영", team_id: 2756, position: "Midfielder" },
  { id: 195491, name: "Luan Dias", korean_name: "루안 디아스", team_id: 2756, position: "Midfielder" },
  { id: 453879, name: "Kim Won-Hyung", korean_name: "김원형", team_id: 2756, position: "Midfielder" },
  { id: 458258, name: "Lee Joseph", korean_name: "이조셉", team_id: 2756, position: "Midfielder" },
  { id: 510576, name: "Lee Si-Myeong", korean_name: "이시명", team_id: 2756, position: "Midfielder" },
  { id: 453321, name: "Lee Yun-Gun", korean_name: "이윤건", team_id: 2756, position: "Midfielder" },
  { id: 506294, name: "Yang Woo-Jin", korean_name: "양우진", team_id: 2756, position: "Midfielder" },
  { id: 506293, name: "Yeom Do-Hyun", korean_name: "염도현", team_id: 2756, position: "Midfielder" },
  { id: 41455, name: "P. Sabbag", korean_name: "사바그", team_id: 2756, position: "Attacker" },
  { id: 34803, name: "Lee Joon-Suk", korean_name: "이준석", team_id: 2756, position: "Attacker" },
  { id: 359514, name: "Park Yong-Hui", korean_name: "박용희", team_id: 2756, position: "Attacker" },
  { id: 453318, name: "Jung Seung-Bae", korean_name: "정승배", team_id: 2756, position: "Attacker" },
  { id: 430110, name: "Kang Min-Sung", korean_name: "강민성", team_id: 2756, position: "Attacker" },
  { id: 405568, name: "Choi Chi-Ung", korean_name: "최치웅", team_id: 2756, position: "Attacker" },
  { id: 411146, name: "Lee Taek-Geun", korean_name: "이택근", team_id: 2756, position: "Attacker" },
  { id: 408846, name: "Lee Dae-Gwang", korean_name: "이대광", team_id: 2756, position: "Attacker" },
  { id: 34144, name: "Willyan", korean_name: "윌리안", team_id: 2756, position: "Attacker" },
  { id: 9292, name: "Anderson Oliveira", korean_name: "안데르손 올리베이라", team_id: 2756, position: "Attacker" },
  { id: 34367, name: "Kim Gyeong-Min", korean_name: "김경민", team_id: 2756, position: "Attacker" },
  { id: 506292, name: "Baek Kyung", korean_name: "백경", team_id: 2756, position: "Attacker" },
  { id: 506291, name: "Kwon Gi-Hyun", korean_name: "권기현", team_id: 2756, position: "Attacker" },
  { id: 550368, name: "Lee Hyeon-yong", korean_name: "이현용", team_id: 2756, position: undefined },
  { id: 550409, name: "Jang Young-Woo", korean_name: "장영우", team_id: 2756, position: undefined },
  { id: 550442, name: "K. Kyeong-min", korean_name: "김경민", team_id: 2756, position: undefined },
];

// Ulsan Hyundai FC (Team ID: 2767) - 41명
export const ULSAN_HYUNDAI_FC_PLAYERS: PlayerMapping[] = [
  { id: 2890, name: "Jo Hyeon-Woo", korean_name: "조현우", team_id: 2767, position: "Goalkeeper" },
  { id: 34409, name: "Moon Jung-In", korean_name: "문정인", team_id: 2767, position: "Goalkeeper" },
  { id: 508421, name: "Ryu Seong-Min", korean_name: "류성민", team_id: 2767, position: "Goalkeeper" },
  { id: 356377, name: "Moon Hyun-Ho", korean_name: "문현호", team_id: 2767, position: "Goalkeeper" },
  { id: 197986, name: "Cho Hyun-Taek", korean_name: "조현택", team_id: 2767, position: "Defender" },
  { id: 404921, name: "Seo Myeong-Kwan", korean_name: "서명관", team_id: 2767, position: "Defender" },
  { id: 34547, name: "Kang Sang-Woo", korean_name: "강상우", team_id: 2767, position: "Defender" },
  { id: 2895, name: "Jung Seung-Hyun", korean_name: "정승현", team_id: 2767, position: "Defender" },
  { id: 2898, name: "Kim Young-Gwon", korean_name: "김영권", team_id: 2767, position: "Defender" },
  { id: 34504, name: "Yoon Jong-Gyu", korean_name: "윤종규", team_id: 2767, position: "Defender" },
  { id: 509168, name: "Jung Seong-Bin", korean_name: "정성빈", team_id: 2767, position: "Defender" },
  { id: 34474, name: "Park Min-Seo", korean_name: "박민서", team_id: 2767, position: "Defender" },
  { id: 34647, name: "Lee Jae-Ik", korean_name: "이재익", team_id: 2767, position: "Defender" },
  { id: 457280, name: "Yoon Jae-Seok", korean_name: "윤재석", team_id: 2767, position: "Defender" },
  { id: 40914, name: "M. Trojak", korean_name: "트로약", team_id: 2767, position: "Defender" },
  { id: 33331, name: "Hwang Seok-Ho", korean_name: "황석호", team_id: 2767, position: "Defender" },
  { id: 34586, name: "Sim Sang-Min", korean_name: "심상민", team_id: 2767, position: "Defender" },
  { id: 409426, name: "Choi Seok-Hyun", korean_name: "최석현", team_id: 2767, position: "Defender" },
  { id: 2903, name: "Jung Woo-Young", korean_name: "정우영", team_id: 2767, position: "Midfielder" },
  { id: 48124, name: "D. Bojanić", korean_name: "보야니치", team_id: 2767, position: "Midfielder" },
  { id: 34695, name: "Ko Seung-Beom", korean_name: "고승범", team_id: 2767, position: "Midfielder" },
  { id: 34431, name: "Lee Dong-Gyeong", korean_name: "이동경", team_id: 2767, position: "Midfielder" },
  { id: 2907, name: "Lee Jin-Hyun", korean_name: "이진현", team_id: 2767, position: "Midfielder" },
  { id: 34149, name: "Lee Hui-Gyun", korean_name: "이희균", team_id: 2767, position: "Midfielder" },
  { id: 47706, name: "G. Ludwigson", korean_name: "루드빅손", team_id: 2767, position: "Midfielder" },
  { id: 34618, name: "Kim Min-Hyeok", korean_name: "김민혁", team_id: 2767, position: "Midfielder" },
  { id: 34550, name: "Lee Gyu-Sung", korean_name: "이규성", team_id: 2767, position: "Midfielder" },
  { id: 453317, name: "Park Sang-Jun", korean_name: "박상준", team_id: 2767, position: "Midfielder" },
  { id: 2905, name: "Lee Chung-Yong", korean_name: "이청용", team_id: 2767, position: "Midfielder" },
  { id: 126665, name: "M. Lacava", korean_name: "라카바", team_id: 2767, position: "Midfielder" },
  { id: 403577, name: "Lee Jae-Wook", korean_name: "이재욱", team_id: 2767, position: "Midfielder" },
  { id: 303441, name: "Choi Kang-min", korean_name: "최강민", team_id: 2767, position: "Midfielder" },
  { id: 34548, name: "Kim Min-Woo", korean_name: "김민우", team_id: 2767, position: "Midfielder" },
  { id: 41468, name: "G. Arabidze", korean_name: "아라비제", team_id: 2767, position: "Attacker" },
  { id: 13089, name: "Marcão", korean_name: "마르상", team_id: 2767, position: "Attacker" },
  { id: 34132, name: "Um Won-Sang", korean_name: "엄원상", team_id: 2767, position: "Attacker" },
  { id: 224658, name: "Heo Yool", korean_name: "허율", team_id: 2767, position: "Attacker" },
  { id: 403576, name: "Jang Si-Young", korean_name: "장시영", team_id: 2767, position: "Attacker" },
  { id: 238541, name: "Yago Cariello", korean_name: "야고 카리엘로", team_id: 2767, position: "Attacker" },
  { id: 423703, name: "Back In-Woo", korean_name: "백인우", team_id: 2767, position: "Attacker" },
  { id: 146018, name: "Erick Farias", korean_name: "에릭 파리아스", team_id: 2767, position: "Attacker" },
];

// K리그1 Part 2 전체 선수 (완성!)
export const K_LEAGUE1_PART2_PLAYERS: PlayerMapping[] = [
  ...FC_SEOUL_PLAYERS,
  ...GANGWON_FC_PLAYERS,
  ...GIMCHEON_SANGMU_FC_PLAYERS,
  ...GWANGJU_FC_PLAYERS,
  ...JEJU_UNITED_FC_PLAYERS,
  ...JEONBUK_MOTORS_PLAYERS,
  ...POHANG_STEELERS_PLAYERS,
  ...SUWON_CITY_FC_PLAYERS,
  ...ULSAN_HYUNDAI_FC_PLAYERS,
];

