import { PlayerMapping } from './index';
import { K_LEAGUE1_PART2_PLAYERS } from './k-league1-part2';

// K리그1 선수 매핑 데이터 (536명, 12개 팀)

// Daegu FC (Team ID: 2747) - 50명
export const DAEGU_FC_PLAYERS: PlayerMapping[] = [
  { id: 34445, name: "Choi Young-Eun", korean_name: "최영은", team_id: 2747, position: "Goalkeeper" },
  { id: 34410, name: "Oh Seung-Hoon", korean_name: "오승훈", team_id: 2747, position: "Goalkeeper" },
  { id: 402846, name: "Han Tae-Hui", korean_name: "한태희", team_id: 2747, position: "Goalkeeper" },
  { id: 453062, name: "Park Sang-young", korean_name: "박상영", team_id: 2747, position: "Goalkeeper" },
  { id: 509169, name: "Park Man-Ho", korean_name: "박만호", team_id: 2747, position: "Goalkeeper" },
  { id: 34771, name: "Jeong Woo-Jae", korean_name: "정우재", team_id: 2747, position: "Defender" },
  { id: 46229, name: "Caio Marcelo", korean_name: "카이오 마르셀로", team_id: 2747, position: "Defender" },
  { id: 34450, name: "Hong Jeong-Woon", korean_name: "홍정운", team_id: 2747, position: "Defender" },
  { id: 34482, name: "Kim Jin-Hyuk", korean_name: "김진혁", team_id: 2747, position: "Defender" },
  { id: 356254, name: "Lee Won-Woo", korean_name: "이원우", team_id: 2747, position: "Defender" },
  { id: 34452, name: "Jang Sung-won", korean_name: "장성원", team_id: 2747, position: "Defender" },
  { id: 356255, name: "Park Jae-Hyun", korean_name: "박재현", team_id: 2747, position: "Defender" },
  { id: 453305, name: "Sim Yeon-Won", korean_name: "심연원", team_id: 2747, position: "Defender" },
  { id: 509173, name: "Lee Rim", korean_name: "이림", team_id: 2747, position: "Defender" },
  { id: 453877, name: "Park Jin-Young", korean_name: "박진영", team_id: 2747, position: "Defender" },
  { id: 454030, name: "Kim Hyeon-Jun", korean_name: "김현준", team_id: 2747, position: "Defender" },
  { id: 34727, name: "Woo Joo-Seong", korean_name: "우주성", team_id: 2747, position: "Defender" },
  { id: 402848, name: "Yoo Ji-Un", korean_name: "유지운", team_id: 2747, position: "Defender" },
  { id: 402847, name: "Jung Yoon-Seo", korean_name: "정윤서", team_id: 2747, position: "Defender" },
  { id: 509170, name: "Lee Je-Wook", korean_name: "이제욱", team_id: 2747, position: "Defender" },
  { id: 408841, name: "Yoon Tae-Min", korean_name: "윤태민", team_id: 2747, position: "Defender" },
  { id: 356104, name: "Hwang Jae-Won", korean_name: "황재원", team_id: 2747, position: "Midfielder" },
  { id: 319944, name: "Geovani", korean_name: "제오바니", team_id: 2747, position: "Midfielder" },
  { id: 41215, name: "Bruno Lamas", korean_name: "브루노 라마스", team_id: 2747, position: "Midfielder" },
  { id: 453302, name: "Jung Jae-Sang", korean_name: "정재상", team_id: 2747, position: "Midfielder" },
  { id: 453304, name: "Son Seung-Min", korean_name: "손승민", team_id: 2747, position: "Midfielder" },
  { id: 453306, name: "Jung Heon-Taek", korean_name: "정헌택", team_id: 2747, position: "Midfielder" },
  { id: 356229, name: "Han Jong-Mu", korean_name: "한종무", team_id: 2747, position: "Midfielder" },
  { id: 34479, name: "Jeong Chi-In", korean_name: "정치인", team_id: 2747, position: "Midfielder" },
  { id: 33052, name: "K. Yoshino", korean_name: "요시노", team_id: 2747, position: "Midfielder" },
  { id: 34549, name: "Lee Chan-Dong", korean_name: "이찬동", team_id: 2747, position: "Midfielder" },
  { id: 307126, name: "Jeong-Hyun Kim", korean_name: "김정현", team_id: 2747, position: "Midfielder" },
  { id: 34495, name: "Jung Hyun-Cheol", korean_name: "정현철", team_id: 2747, position: "Midfielder" },
  { id: 48956, name: "Lee Yong-Rae", korean_name: "이용래", team_id: 2747, position: "Midfielder" },
  { id: 9812, name: "Jatobá", korean_name: "자토바", team_id: 2747, position: "Midfielder" },
  { id: 255188, name: "Ji-Woong Kim", korean_name: "김지웅", team_id: 2747, position: "Midfielder" },
  { id: 453061, name: "Kwon Kwang-Deok", korean_name: "권광덕", team_id: 2747, position: "Midfielder" },
  { id: 509172, name: "Sung Kwon-Suk", korean_name: "성권석", team_id: 2747, position: "Midfielder" },
  { id: 34476, name: "Edgar", korean_name: "에드가르", team_id: 2747, position: "Attacker" },
  { id: 34484, name: "Cesinha", korean_name: "세징야", team_id: 2747, position: "Attacker" },
  { id: 459969, name: "Kwon Tae-Young", korean_name: "권태영", team_id: 2747, position: "Attacker" },
  { id: 356258, name: "Jeon Yong-Jun", korean_name: "전용준", team_id: 2747, position: "Attacker" },
  { id: 99323, name: "Park Dae-Hoon", korean_name: "박대훈", team_id: 2747, position: "Attacker" },
  { id: 509171, name: "Kim Min-Joon", korean_name: "김민준", team_id: 2747, position: "Attacker" },
  { id: 453876, name: "Han Seo-Jin", korean_name: "한서진", team_id: 2747, position: "Attacker" },
  { id: 509174, name: "I. Osei", korean_name: "오세이", team_id: 2747, position: "Attacker" },
  { id: 453303, name: "Jung Eun-Woo", korean_name: "정은우", team_id: 2747, position: "Attacker" },
  { id: 455181, name: "Kim Min-Young", korean_name: "김민영", team_id: 2747, position: "Attacker" },
  { id: 550453, name: "Jeong Heon-taek", korean_name: "정헌택", team_id: 2747, position: undefined },
  { id: 547312, name: "Woo Ju-Seong", korean_name: "우주성", team_id: 2747, position: undefined },
];

// Daejeon Citizen (Team ID: 2750) - 38명
export const DAEJEON_CITIZEN_PLAYERS: PlayerMapping[] = [
  { id: 34757, name: "Lee Chang-Geun", korean_name: "이창근", team_id: 2750, position: "Goalkeeper" },
  { id: 306606, name: "Lee Jun-Seo", korean_name: "이준서", team_id: 2750, position: "Goalkeeper" },
  { id: 33721, name: "Kyung-Tae Lee", korean_name: "이경태", team_id: 2750, position: "Goalkeeper" },
  { id: 34787, name: "Jeong San", korean_name: "정산", team_id: 2750, position: "Goalkeeper" },
  { id: 458255, name: "Kim Min-Soo", korean_name: "김민수", team_id: 2750, position: "Goalkeeper" },
  { id: 178707, name: "Park Kyu-Hyun", korean_name: "박규현", team_id: 2750, position: "Defender" },
  { id: 34590, name: "Ha Chang-Rae", korean_name: "하창래", team_id: 2750, position: "Defender" },
  { id: 34421, name: "Lim Jong-Eun", korean_name: "임종은", team_id: 2750, position: "Defender" },
  { id: 34772, name: "Kang Yun-Sung", korean_name: "강윤성", team_id: 2750, position: "Defender" },
  { id: 34420, name: "Lee Myung-Jae", korean_name: "이명재", team_id: 2750, position: "Defender" },
  { id: 357219, name: "Yeo Seung-Won", korean_name: "여승원", team_id: 2750, position: "Defender" },
  { id: 33300, name: "Oh Jae-Suk", korean_name: "오재석", team_id: 2750, position: "Defender" },
  { id: 358433, name: "Bae Seo-Joon", korean_name: "배서준", team_id: 2750, position: "Defender" },
  { id: 329544, name: "Kim Min-woo", korean_name: "김민우", team_id: 2750, position: "Defender" },
  { id: 2912, name: "Kim Moon-Hwan", korean_name: "김문환", team_id: 2750, position: "Defender" },
  { id: 55958, name: "A. Krivotsyuk", korean_name: "크리보추크", team_id: 2750, position: "Defender" },
  { id: 506288, name: "Jo Hyeon-Woo", korean_name: "조현우", team_id: 2750, position: "Defender" },
  { id: 279820, name: "Victor Bobsin", korean_name: "빅토르 보브신", team_id: 2750, position: "Midfielder" },
  { id: 34736, name: "Kim Jun-Bum", korean_name: "김준범", team_id: 2750, position: "Midfielder" },
  { id: 228827, name: "Choi Geon-Joo", korean_name: "최건주", team_id: 2750, position: "Midfielder" },
  { id: 357382, name: "Lim Yu-Seok", korean_name: "임유석", team_id: 2750, position: "Midfielder" },
  { id: 265710, name: "Lee Soon-Min", korean_name: "이순민", team_id: 2750, position: "Midfielder" },
  { id: 453966, name: "Kim Han-seo", korean_name: "김한서", team_id: 2750, position: "Midfielder" },
  { id: 34658, name: "Kim Hyeon-Ug", korean_name: "김현욱", team_id: 2750, position: "Midfielder" },
  { id: 358335, name: "Jun-Gyu Lee", korean_name: "이준규", team_id: 2750, position: "Midfielder" },
  { id: 157814, name: "João Victor", korean_name: "주앙 빅토르", team_id: 2750, position: "Midfielder" },
  { id: 408843, name: "Jeong Jin-Woo", korean_name: "정진우", team_id: 2750, position: "Midfielder" },
  { id: 404193, name: "Kim Gyeong-Hwan", korean_name: "김경환", team_id: 2750, position: "Midfielder" },
  { id: 106557, name: "Kelvin", korean_name: "켈빈", team_id: 2750, position: "Attacker" },
  { id: 91772, name: "M. Ishida", korean_name: "이시다", team_id: 2750, position: "Attacker" },
  { id: 40813, name: "V. Gutkovskis", korean_name: "구트코프스키스", team_id: 2750, position: "Attacker" },
  { id: 34427, name: "Joo Min-Kyu", korean_name: "주민규", team_id: 2750, position: "Attacker" },
  { id: 34595, name: "Kim Seung-Dae", korean_name: "김승대", team_id: 2750, position: "Attacker" },
  { id: 357222, name: "Jung Woo-Bin", korean_name: "정우빈", team_id: 2750, position: "Attacker" },
  { id: 34355, name: "Jeong Jae-Hee", korean_name: "정재희", team_id: 2750, position: "Attacker" },
  { id: 518075, name: "Kim Hyeon-Oh", korean_name: "김현오", team_id: 2750, position: "Attacker" },
  { id: 550445, name: "K. Lee", korean_name: "이경태", team_id: 2750, position: undefined },
  { id: 550438, name: "Kim Han-Seo", korean_name: "김한서", team_id: 2750, position: undefined },
];

// FC Anyang (Team ID: 2748) - 40명
export const FC_ANYANG_PLAYERS: PlayerMapping[] = [
  { id: 92473, name: "Lee Yun-Oh", korean_name: "이윤오", team_id: 2748, position: "Goalkeeper" },
  { id: 34674, name: "Kim Da-Sol", korean_name: "김다솔", team_id: 2748, position: "Goalkeeper" },
  { id: 34370, name: "Hwang Byeong-Geun", korean_name: "황병근", team_id: 2748, position: "Goalkeeper" },
  { id: 404916, name: "Kim Sung-Dong", korean_name: "김성동", team_id: 2748, position: "Goalkeeper" },
  { id: 457276, name: "Kim Min-Ho", korean_name: "김민호", team_id: 2748, position: "Defender" },
  { id: 506290, name: "Kim Ji-Hoon", korean_name: "김지훈", team_id: 2748, position: "Defender" },
  { id: 34605, name: "Lee Chang-Yong", korean_name: "이창용", team_id: 2748, position: "Defender" },
  { id: 34230, name: "Kim Young-Chan", korean_name: "김영찬", team_id: 2748, position: "Defender" },
  { id: 356122, name: "Park Jong-Hyeon", korean_name: "박종현", team_id: 2748, position: "Defender" },
  { id: 34670, name: "Kang Ji-Hoon", korean_name: "강지훈", team_id: 2748, position: "Defender" },
  { id: 34197, name: "Lee Sang-Yong", korean_name: "이상용", team_id: 2748, position: "Defender" },
  { id: 99201, name: "Kim Dong-Jin", korean_name: "김동진", team_id: 2748, position: "Defender" },
  { id: 2899, name: "Kwon Kyung-Won", korean_name: "권경원", team_id: 2748, position: "Defender" },
  { id: 34558, name: "Lee Tae-Hee", korean_name: "이태희", team_id: 2748, position: "Defender" },
  { id: 34636, name: "Im Seung-Kyum", korean_name: "임승겸", team_id: 2748, position: "Defender" },
  { id: 34614, name: "Ju Hyun-Woo", korean_name: "주현우", team_id: 2748, position: "Defender" },
  { id: 9718, name: "Matheus Oliveira", korean_name: "마테우스 올리베이라", team_id: 2748, position: "Midfielder" },
  { id: 34617, name: "Kim Jung-Hyun", korean_name: "김정현", team_id: 2748, position: "Midfielder" },
  { id: 128538, name: "Han Ka-ram", korean_name: "한가람", team_id: 2748, position: "Midfielder" },
  { id: 34664, name: "Lee Min-Soo", korean_name: "이민수", team_id: 2748, position: "Midfielder" },
  { id: 457278, name: "Park Jeong-Hun", korean_name: "박정훈", team_id: 2748, position: "Midfielder" },
  { id: 411320, name: "Choe Gyu-Hyeon", korean_name: "최규현", team_id: 2748, position: "Midfielder" },
  { id: 9645, name: "Eduardo", korean_name: "에두아르도", team_id: 2748, position: "Midfielder" },
  { id: 34138, name: "Lim Min-Hyeok", korean_name: "임민혁", team_id: 2748, position: "Midfielder" },
  { id: 404917, name: "Moon Seong-Woo", korean_name: "문성우", team_id: 2748, position: "Midfielder" },
  { id: 37877, name: "T. Oude Kotte", korean_name: "오우데 코테", team_id: 2748, position: "Midfielder" },
  { id: 357191, name: "Jeon Bo-Min", korean_name: "전보민", team_id: 2748, position: "Midfielder" },
  { id: 506289, name: "Jang Jung-Woo", korean_name: "장정우", team_id: 2748, position: "Midfielder" },
  { id: 9621, name: "Bruno Mota", korean_name: "브루노 모타", team_id: 2748, position: "Attacker" },
  { id: 35821, name: "Yago César", korean_name: "야고 세사르", team_id: 2748, position: "Attacker" },
  { id: 404918, name: "Choi Sung-Bum", korean_name: "최성범", team_id: 2748, position: "Attacker" },
  { id: 457277, name: "Lee Dong-Hyun", korean_name: "이동현", team_id: 2748, position: "Attacker" },
  { id: 146429, name: "Woon Kim", korean_name: "김운", team_id: 2748, position: "Attacker" },
  { id: 34428, name: "Kim Bo-Kyung", korean_name: "김보경", team_id: 2748, position: "Attacker" },
  { id: 40211, name: "I. Jukić", korean_name: "유키치", team_id: 2748, position: "Attacker" },
  { id: 463586, name: "Chae Hyun-Woo", korean_name: "채현우", team_id: 2748, position: "Attacker" },
  { id: 550366, name: "J. h. Kim", korean_name: "김정현", team_id: 2748, position: undefined },
  { id: 550380, name: "Choe Gyu-hyeon", korean_name: "최규현", team_id: 2748, position: undefined },
  { id: 550388, name: "Ju Hyun-Woo", korean_name: "주현우", team_id: 2748, position: undefined },
  { id: 550444, name: "I. Jukic", korean_name: "유키치", team_id: 2748, position: undefined },
];

// K리그1 전체 선수 (536명, 12개 팀) - 완성!
export const K_LEAGUE1_PLAYERS: PlayerMapping[] = [
  ...DAEGU_FC_PLAYERS,
  ...DAEJEON_CITIZEN_PLAYERS,
  ...FC_ANYANG_PLAYERS,
  ...K_LEAGUE1_PART2_PLAYERS,
];

