import { PlayerMapping } from './index';

// 라리가 선수 매핑 데이터 Part 2 (나머지 14개 팀)

// Elche (Team ID: 797) - 46명
export const ELCHE_PLAYERS: PlayerMapping[] = [
  { id: 315604, name: "Alejandro Iturbe Encabo", korean_name: "알레한드로 이투르베", team_id: 797, position: "Goalkeeper" },
  { id: 46961, name: "Edgar Badia", korean_name: "에드가르 바디아", team_id: 797, position: "Goalkeeper" },
  { id: 126, name: "Ignacio Peña Sotorres", korean_name: "이냐키 페냐", team_id: 797, position: "Goalkeeper" },
  { id: 11346, name: "M. Dituro", korean_name: "마티아스 디투로", team_id: 797, position: "Goalkeeper" },
  { id: 131551, name: "Miguel San Román", korean_name: "미겔 산 로만", team_id: 797, position: "Goalkeeper" },
  { id: 486863, name: "Owen Bosch", korean_name: "오웬 보슈", team_id: 797, position: "Goalkeeper" },
  { id: 497515, name: "A. Niculăesei", korean_name: "알렉스 니쿨라에세이", team_id: 797, position: "Defender" },
  { id: 8746, name: "Bambo Diaby", korean_name: "밤보 디아비", team_id: 797, position: "Defender" },
  { id: 47378, name: "Bigas", korean_name: "비가스", team_id: 797, position: "Defender" },
  { id: 46651, name: "Clerc", korean_name: "클레르크", team_id: 797, position: "Defender" },
  { id: 126640, name: "D. Affengruber", korean_name: "다니엘 아펜그루버", team_id: 797, position: "Defender" },
  { id: 386859, name: "Héctor Fort García", korean_name: "엑토르 포르트", team_id: 797, position: "Defender" },
  { id: 46771, name: "Jairo Izquierdo", korean_name: "하이로 이스키에르도", team_id: 797, position: "Defender" },
  { id: 189866, name: "John Nwankwo", korean_name: "존 은완크워", team_id: 797, position: "Defender" },
  { id: 157146, name: "Léo Pétrot", korean_name: "레오 페트로", team_id: 797, position: "Defender" },
  { id: 1691, name: "Mario Gaspar", korean_name: "마리오 가스파르", team_id: 797, position: "Defender" },
  { id: 436785, name: "Matia Barzic Gutiérrez", korean_name: "마티아 바르직", team_id: 797, position: "Defender" },
  { id: 496576, name: "Nico Salvador", korean_name: "니코 살바도르", team_id: 797, position: "Defender" },
  { id: 162058, name: "Víctor Chust García", korean_name: "빅토르 추스트", team_id: 797, position: "Defender" },
  { id: 46711, name: "Aleix Febas", korean_name: "알레이스 페바스", team_id: 797, position: "Midfielder" },
  { id: 448243, name: "Ali Houary", korean_name: "알리 후아리", team_id: 797, position: "Midfielder" },
  { id: 182661, name: "Álvaro Núñez", korean_name: "알바로 누녜스", team_id: 797, position: "Midfielder" },
  { id: 508284, name: "Antonio Martinez Bastida", korean_name: "안토니오 마르티네스", team_id: 797, position: "Midfielder" },
  { id: 46896, name: "Cristian Salvador", korean_name: "크리스티안 살바도르", team_id: 797, position: "Midfielder" },
  { id: 311345, name: "Federico Redondo Solari", korean_name: "페데리코 레돈도", team_id: 797, position: "Midfielder" },
  { id: 161963, name: "Germán Valera", korean_name: "헤르만 발레라", team_id: 797, position: "Midfielder" },
  { id: 18821, name: "Grady George Diangana", korean_name: "그래디 디안가나", team_id: 797, position: "Midfielder" },
  { id: 46973, name: "Josan", korean_name: "호산", team_id: 797, position: "Midfielder" },
  { id: 187318, name: "Marc Aguado", korean_name: "마르크 아구아도", team_id: 797, position: "Midfielder" },
  { id: 462697, name: "Mario", korean_name: "마리오", team_id: 797, position: "Midfielder" },
  { id: 271580, name: "Martim Carvalho Neto", korean_name: "마르팀 카르발류", team_id: 797, position: "Midfielder" },
  { id: 153372, name: "N. Castro", korean_name: "니콜라스 카스트로", team_id: 797, position: "Midfielder" },
  { id: 75414, name: "N. Fernández Mercau", korean_name: "니콜라스 페르난데스", team_id: 797, position: "Midfielder" },
  { id: 483121, name: "Nicolás González", korean_name: "니콜라스 곤살레스", team_id: 797, position: "Midfielder" },
  { id: 47057, name: "Raúl Guti", korean_name: "라울 구티", team_id: 797, position: "Midfielder" },
  { id: 341371, name: "Rodrigo Mendoza", korean_name: "로드리고 멘도사", team_id: 797, position: "Midfielder" },
  { id: 439293, name: "Adam Boayar", korean_name: "아담 보야르", team_id: 797, position: "Attacker" },
  { id: 343202, name: "Álvaro Daniel Rodríguez Muñoz", korean_name: "알바로 로드리게스", team_id: 797, position: "Attacker" },
  { id: 2063, name: "André Miguel Valente da Silva", korean_name: "안드레 실바", team_id: 797, position: "Attacker" },
  { id: 448244, name: "Didac Castellá", korean_name: "디닥 카스테야", team_id: 797, position: "Attacker" },
  { id: 333368, name: "Héctor Peña", korean_name: "엑토르 페냐", team_id: 797, position: "Attacker" },
  { id: 119223, name: "Mourad", korean_name: "무라드", team_id: 797, position: "Attacker" },
  { id: 47496, name: "Óscar Plano", korean_name: "오스카르 플라노", team_id: 797, position: "Attacker" },
  { id: 157194, name: "Pejiño", korean_name: "페히뇨", team_id: 797, position: "Attacker" },
  { id: 47013, name: "Rafael Mir Vicente", korean_name: "라파엘 미르", team_id: 797, position: "Attacker" },
  { id: 284415, name: "Yago Alonso", korean_name: "야고 알론소", team_id: 797, position: "Attacker" },
];

// Espanyol (Team ID: 540) - 27명
export const ESPANYOL_PLAYERS: PlayerMapping[] = [
  { id: 182735, name: "Ángel Fortuño", korean_name: "안헬 포르투뇨", team_id: 540, position: "Goalkeeper" },
  { id: 2813, name: "M. Dmitrović", korean_name: "마르코 드미트로비치", team_id: 540, position: "Goalkeeper" },
  { id: 162585, name: "Pol Tristán", korean_name: "폴 트리스탄", team_id: 540, position: "Goalkeeper" },
  { id: 184420, name: "Carlos Romero", korean_name: "카를로스 로메로", team_id: 540, position: "Defender" },
  { id: 282054, name: "Clemens Riedel", korean_name: "클레멘스 리델", team_id: 540, position: "Defender" },
  { id: 47478, name: "Fernando Calero", korean_name: "페르난도 칼레로", team_id: 540, position: "Defender" },
  { id: 184407, name: "José Salinas", korean_name: "호세 살리나스", team_id: 540, position: "Defender" },
  { id: 47249, name: "L. Cabrera", korean_name: "레안드로 카브레라", team_id: 540, position: "Defender" },
  { id: 47256, name: "Miguel Rubio", korean_name: "미겔 루비오", team_id: 540, position: "Defender" },
  { id: 286601, name: "O. El Hilali", korean_name: "오마르 엘 힐랄리", team_id: 540, position: "Defender" },
  { id: 46734, name: "Pablo Ramón", korean_name: "파블로 라몬", team_id: 540, position: "Defender" },
  { id: 450716, name: "Roger Hinojo", korean_name: "로헤르 이노호", team_id: 540, position: "Defender" },
  { id: 199824, name: "Rubén Sánchez", korean_name: "루벤 산체스", team_id: 540, position: "Defender" },
  { id: 48555, name: "Charles Monginda Pickel", korean_name: "샤를 피켈", team_id: 540, position: "Midfielder" },
  { id: 46799, name: "Edu Expósito", korean_name: "에두 엑스포시토", team_id: 540, position: "Midfielder" },
  { id: 388495, name: "Javier Hernandez", korean_name: "하비에르 에르난데스", team_id: 540, position: "Midfielder" },
  { id: 47349, name: "Javi Puado", korean_name: "하비 푸아도", team_id: 540, position: "Midfielder" },
  { id: 47398, name: "Pere Milla", korean_name: "페레 미야", team_id: 540, position: "Midfielder" },
  { id: 127426, name: "Pol Lozano", korean_name: "폴 로사노", team_id: 540, position: "Midfielder" },
  { id: 438284, name: "Rafel Bauzà", korean_name: "라펠 바우사", team_id: 540, position: "Midfielder" },
  { id: 187987, name: "Ramón Terrats", korean_name: "라몬 테라츠", team_id: 540, position: "Midfielder" },
  { id: 273732, name: "T. Dolan", korean_name: "타일러 돌란", team_id: 540, position: "Midfielder" },
  { id: 297742, name: "Antoniu Roca", korean_name: "안토니우 로카", team_id: 540, position: "Attacker" },
  { id: 182674, name: "Jofre Carreras", korean_name: "조프레 카레라스", team_id: 540, position: "Attacker" },
  { id: 47396, name: "Kike García", korean_name: "키케 가르시아", team_id: 540, position: "Attacker" },
  { id: 359603, name: "Luca Warrick Daeovie Koleosho", korean_name: "루카 콜레오쇼", team_id: 540, position: "Attacker" },
  { id: 312990, name: "Roberto Fernández", korean_name: "로베르토 페르난데스", team_id: 540, position: "Attacker" },
];

// Getafe (Team ID: 546) - 32명
export const GETAFE_PLAYERS: PlayerMapping[] = [
  { id: 47247, name: "David Soria", korean_name: "다비드 소리아", team_id: 546, position: "Goalkeeper" },
  { id: 482071, name: "Diego Ferrer Martínez", korean_name: "디에고 페레르", team_id: 546, position: "Goalkeeper" },
  { id: 66491, name: "J. Letáček", korean_name: "이리 레타체크", team_id: 546, position: "Goalkeeper" },
  { id: 432080, name: "Jorge Benito de Valle Martín", korean_name: "호르헤 베니토", team_id: 546, position: "Goalkeeper" },
  { id: 46813, name: "A. Abqar", korean_name: "압델카데르 압카르", team_id: 546, position: "Defender" },
  { id: 47407, name: "Allan Roméo Nyom", korean_name: "알랑 뇸", team_id: 546, position: "Defender" },
  { id: 471478, name: "Davinchi", korean_name: "다빈치", team_id: 546, position: "Defender" },
  { id: 47250, name: "D. Dakonam", korean_name: "제이 다코남", team_id: 546, position: "Defender" },
  { id: 18867, name: "Diego Rico", korean_name: "디에고 리코", team_id: 546, position: "Defender" },
  { id: 46795, name: "Domingos Duarte", korean_name: "도밍고스 두아르테", team_id: 546, position: "Defender" },
  { id: 119742, name: "Juan Iglesias", korean_name: "후안 이글레시아스", team_id: 546, position: "Defender" },
  { id: 18794, name: "Kiko Femenía", korean_name: "키코 페메니아", team_id: 546, position: "Defender" },
  { id: 297235, name: "Marc Vilaplana", korean_name: "마르크 비라플라나", team_id: 546, position: "Defender" },
  { id: 41976, name: "Y. Neyou", korean_name: "예바 네유", team_id: 546, position: "Defender" },
  { id: 439617, name: "Z. Tassounte", korean_name: "자카리아 타수네", team_id: 546, position: "Defender" },
  { id: 465838, name: "Alberto Risco", korean_name: "알베르토 리스코", team_id: 546, position: "Midfielder" },
  { id: 47306, name: "Álex Sola", korean_name: "알렉스 솔라", team_id: 546, position: "Midfielder" },
  { id: 46860, name: "Javi Muñoz", korean_name: "하비 무뇨스", team_id: 546, position: "Midfielder" },
  { id: 47085, name: "Luis Milla", korean_name: "루이스 미야", team_id: 546, position: "Midfielder" },
  { id: 47258, name: "M. Arambarri", korean_name: "마우로 아람바리", team_id: 546, position: "Midfielder" },
  { id: 343205, name: "Mario Martín", korean_name: "마리오 마르틴", team_id: 546, position: "Midfielder" },
  { id: 284441, name: "Abu Kamara", korean_name: "아부 카마라", team_id: 546, position: "Attacker" },
  { id: 394573, name: "Adrian Liso", korean_name: "아드리안 리소", team_id: 546, position: "Attacker" },
  { id: 184459, name: "Álex Sancris", korean_name: "알렉스 산크리스", team_id: 546, position: "Attacker" },
  { id: 47472, name: "Borja Mayoral", korean_name: "보르하 마요랄", team_id: 546, position: "Attacker" },
  { id: 403554, name: "Christantus Uche", korean_name: "크리스탄투스 우체", team_id: 546, position: "Attacker" },
  { id: 309364, name: "Coba", korean_name: "코바", team_id: 546, position: "Attacker" },
  { id: 333369, name: "Joselu", korean_name: "호셀루", team_id: 546, position: "Attacker" },
  { id: 47320, name: "Juanmi", korean_name: "후안미", team_id: 546, position: "Attacker" },
  { id: 270516, name: "Peter", korean_name: "페테르", team_id: 546, position: "Attacker" },
  { id: 546852, name: "Alex Sancris", korean_name: "알렉스 산크리스", team_id: 546, position: undefined },
  { id: 551462, name: "M. Aleksandrov", korean_name: "마르틴 알렉산드로프", team_id: 546, position: undefined },
];

// Girona (Team ID: 547) - 36명
export const GIRONA_PLAYERS: PlayerMapping[] = [
  { id: 442861, name: "Aleksandar Metodiev Andreev", korean_name: "알렉산다르 안드레예프", team_id: 547, position: "Goalkeeper" },
  { id: 1305, name: "Dominik Livaković", korean_name: "도미니크 리바코비치", team_id: 547, position: "Goalkeeper" },
  { id: 47153, name: "Juan Carlos", korean_name: "후안 카를로스", team_id: 547, position: "Goalkeeper" },
  { id: 158, name: "P. Gazzaniga", korean_name: "파울로 가차니가", team_id: 547, position: "Goalkeeper" },
  { id: 432476, name: "V. Krapyvtsov", korean_name: "블라디슬라프 크라피프초프", team_id: 547, position: "Goalkeeper" },
  { id: 162434, name: "Alejandro Francés", korean_name: "알레한드로 프란세스", team_id: 547, position: "Defender" },
  { id: 47334, name: "David López", korean_name: "다비드 로페스", team_id: 547, position: "Defender" },
  { id: 531, name: "D. Blind", korean_name: "달리 블린트", team_id: 547, position: "Defender" },
  { id: 491106, name: "Gibert Jordana", korean_name: "질베르트 호르다나", team_id: 547, position: "Defender" },
  { id: 66407, name: "L. Krejčí", korean_name: "라디슬라프 크레이치", team_id: 547, position: "Defender" },
  { id: 162032, name: "Miguel Gutiérrez", korean_name: "미겔 구티에레스", team_id: 547, position: "Defender" },
  { id: 414359, name: "Vitor Nunes", korean_name: "비토르 누네스", team_id: 547, position: "Defender" },
  { id: 47547, name: "Alexandre Moreno Lopera", korean_name: "알렉상드레 모레노", team_id: 547, position: "Midfielder" },
  { id: 283668, name: "Arnau Martínez", korean_name: "아르나우 마르티네스", team_id: 547, position: "Midfielder" },
  { id: 20, name: "A. Witsel", korean_name: "악셀 비첼", team_id: 547, position: "Midfielder" },
  { id: 129678, name: "Azzedine Ounahi", korean_name: "아제딘 우나히", team_id: 547, position: "Midfielder" },
  { id: 2061, name: "Bryan Gil Salvatierra", korean_name: "브라이언 힐", team_id: 547, position: "Midfielder" },
  { id: 547, name: "D. van de Beek", korean_name: "도니 판 더 베이크", team_id: 547, position: "Midfielder" },
  { id: 313025, name: "Hugo Rincón", korean_name: "우고 린콘", team_id: 547, position: "Midfielder" },
  { id: 1700, name: "Iván Martín", korean_name: "이반 마르틴", team_id: 547, position: "Midfielder" },
  { id: 306727, name: "J. Solis", korean_name: "하비에르 솔리스", team_id: 547, position: "Midfielder" },
  { id: 439305, name: "Lancinet Kourouma Kourouma", korean_name: "란시네 쿠루마", team_id: 547, position: "Midfielder" },
  { id: 45, name: "T. Lemar", korean_name: "토마 르마르", team_id: 547, position: "Midfielder" },
  { id: 2182, name: "V. Tsygankov", korean_name: "빅토르 치간코프", team_id: 547, position: "Midfielder" },
  { id: 2449, name: "Y. Herrera", korean_name: "양헬 에레라", team_id: 547, position: "Midfielder" },
  { id: 155, name: "Abel Ruiz", korean_name: "아벨 루이스", team_id: 547, position: "Attacker" },
  { id: 109564, name: "B. Miovski", korean_name: "보얀 미오프스키", team_id: 547, position: "Attacker" },
  { id: 2617, name: "C. Stuani", korean_name: "크리스티안 스투아니", team_id: 547, position: "Attacker" },
  { id: 297304, name: "Dawda Camara Sankharé", korean_name: "다우다 카마라", team_id: 547, position: "Attacker" },
  { id: 553313, name: "Javier Sarasa", korean_name: "하비에르 사라사", team_id: 547, position: "Attacker" },
  { id: 339105, name: "Joel Roca", korean_name: "조엘 로카", team_id: 547, position: "Attacker" },
  { id: 455366, name: "P. Ba", korean_name: "파페 바", team_id: 547, position: "Attacker" },
  { id: 47520, name: "Portu", korean_name: "포르투", team_id: 547, position: "Attacker" },
  { id: 161670, name: "Vladyslav Vanat", korean_name: "블라디슬라프 바나트", team_id: 547, position: "Attacker" },
  { id: 281795, name: "Y. Asprilla", korean_name: "야세르 아스프리야", team_id: 547, position: "Attacker" },
  { id: 551459, name: "L. Kourouma", korean_name: "란시네 쿠루마", team_id: 547, position: undefined },
];

// Levante (Team ID: 539) - 42명
export const LEVANTE_PLAYERS: PlayerMapping[] = [
  { id: 163630, name: "Alfonso Pastor", korean_name: "알폰소 파스토르", team_id: 539, position: "Goalkeeper" },
  { id: 450562, name: "Cayetano Romero Molina", korean_name: "카예타노 로메로", team_id: 539, position: "Goalkeeper" },
  { id: 2741, name: "Mathew David Ryan", korean_name: "매튜 라이언", team_id: 539, position: "Goalkeeper" },
  { id: 286611, name: "Pablo Cuñat Campos", korean_name: "파블로 쿠냣", team_id: 539, position: "Goalkeeper" },
  { id: 338295, name: "Primo", korean_name: "프리모", team_id: 539, position: "Goalkeeper" },
  { id: 316517, name: "Alan Agustín Matturro Romero", korean_name: "알란 마투로", team_id: 539, position: "Defender" },
  { id: 388013, name: "Andrés García", korean_name: "안드레스 가르시아", team_id: 539, position: "Defender" },
  { id: 438662, name: "Borja Cortina", korean_name: "보르하 코르티나", team_id: 539, position: "Defender" },
  { id: 734, name: "Dela", korean_name: "델라", team_id: 539, position: "Defender" },
  { id: 104832, name: "Diego Pampín", korean_name: "디에고 팜핀", team_id: 539, position: "Defender" },
  { id: 504605, name: "Ignacio Pérez Gómez", korean_name: "이그나시오 페레스", team_id: 539, position: "Defender" },
  { id: 47253, name: "Ignasi Miquel", korean_name: "이그나시 미켈", team_id: 539, position: "Defender" },
  { id: 1118, name: "Jeremy Isaiah Richard Toljan", korean_name: "제레미 톨얀", team_id: 539, position: "Defender" },
  { id: 408320, name: "Jorge Cabello", korean_name: "호르헤 카베요", team_id: 539, position: "Defender" },
  { id: 64309, name: "Manuel Sánchez de la Peña", korean_name: "마누 산체스", team_id: 539, position: "Defender" },
  { id: 129786, name: "Manu Sánchez", korean_name: "마누 산체스", team_id: 539, position: "Defender" },
  { id: 417560, name: "Marcos Navarro", korean_name: "마르코스 나바로", team_id: 539, position: "Defender" },
  { id: 407597, name: "Martín Wilhelm Krug", korean_name: "마르틴 크루그", team_id: 539, position: "Defender" },
  { id: 421807, name: "Matías Agustín Moreno", korean_name: "마티아스 모레노", team_id: 539, position: "Defender" },
  { id: 514270, name: "Nacho Pérez", korean_name: "나초 페레스", team_id: 539, position: "Defender" },
  { id: 0, name: "SellÃ©s", korean_name: "세예스", team_id: 539, position: "Defender" },
  { id: 46941, name: "Unai Elgezabal", korean_name: "우나이 엘게사발", team_id: 539, position: "Defender" },
  { id: 46790, name: "Víctor García Raja", korean_name: "빅토르 가르시아", team_id: 539, position: "Defender" },
  { id: 47540, name: "Ángel Algobia", korean_name: "안헬 알고비아", team_id: 539, position: "Midfielder" },
  { id: 47225, name: "Brugui", korean_name: "브루기", team_id: 539, position: "Midfielder" },
  { id: 182770, name: "Carlos Álvarez", korean_name: "카를로스 알바레스", team_id: 539, position: "Midfielder" },
  { id: 119795, name: "G. Kochorashvili", korean_name: "기오르기 코초라슈빌리", team_id: 539, position: "Midfielder" },
  { id: 1699, name: "Iborra", korean_name: "이보라", team_id: 539, position: "Midfielder" },
  { id: 338871, name: "Joan Ruiz Agustina", korean_name: "조안 루이스", team_id: 539, position: "Midfielder" },
  { id: 182603, name: "Jon Ander Olasagasti Imizcoz", korean_name: "존 안데르 올라사가스티", team_id: 539, position: "Midfielder" },
  { id: 125239, name: "Kervin Fabián Arriaga Villanueva", korean_name: "케르빈 아리아가", team_id: 539, position: "Midfielder" },
  { id: 106727, name: "Oriol Rey", korean_name: "오리올 레이", team_id: 539, position: "Midfielder" },
  { id: 104949, name: "Pablo Martínez", korean_name: "파블로 마르티네스", team_id: 539, position: "Midfielder" },
  { id: 182150, name: "Sergio Lozano", korean_name: "세르히오 로사노", team_id: 539, position: "Midfielder" },
  { id: 182639, name: "Unai Vencedor Paris", korean_name: "우나이 벤세도르", team_id: 539, position: "Midfielder" },
  { id: 445025, name: "Víctor Fernández", korean_name: "빅토르 페르난데스", team_id: 539, position: "Midfielder" },
  { id: 450497, name: "Carlos Espí", korean_name: "카를로스 에스피", team_id: 539, position: "Attacker" },
  { id: 9823, name: "Fabrício", korean_name: "파브리시우", team_id: 539, position: "Attacker" },
  { id: 20817, name: "Goduine Koyalipou", korean_name: "고두인 코얄리푸", team_id: 539, position: "Attacker" },
  { id: 192032, name: "Iván Romero", korean_name: "이반 로메로", team_id: 539, position: "Attacker" },
  { id: 47467, name: "José Luis Morales", korean_name: "호세 루이스 모랄레스", team_id: 539, position: "Attacker" },
  { id: 463279, name: "Paco Cortés", korean_name: "파코 코르테스", team_id: 539, position: "Attacker" },
];

// Mallorca (Team ID: 798) - 29명
export const MALLORCA_PLAYERS: PlayerMapping[] = [
  { id: 47399, name: "Iván Cuéllar", korean_name: "이반 쿠에야르", team_id: 798, position: "Goalkeeper" },
  { id: 152955, name: "L. Bergström", korean_name: "레오 베리스트룀", team_id: 798, position: "Goalkeeper" },
  { id: 179139, name: "Leo Román", korean_name: "레오 로만", team_id: 798, position: "Goalkeeper" },
  { id: 335697, name: "David López", korean_name: "다비드 로페스", team_id: 798, position: "Defender" },
  { id: 462277, name: "I. Salhi", korean_name: "이사 살히", team_id: 798, position: "Defender" },
  { id: 64268, name: "J. Mojica", korean_name: "요한 모히카", team_id: 798, position: "Defender" },
  { id: 551463, name: "J. Olaizola", korean_name: "호르디 올라이솔라", team_id: 798, position: "Defender" },
  { id: 30924, name: "Marash Kumbulla", korean_name: "마라시 쿰불라", team_id: 798, position: "Defender" },
  { id: 108519, name: "Mateu Morey", korean_name: "마테우 모레이", team_id: 798, position: "Defender" },
  { id: 46738, name: "M. Valjent", korean_name: "마르틴 발옌트", team_id: 798, position: "Defender" },
  { id: 26302, name: "Pablo Maffeo", korean_name: "파블로 마페오", team_id: 798, position: "Defender" },
  { id: 46733, name: "Raíllo", korean_name: "라이요", team_id: 798, position: "Defender" },
  { id: 920, name: "Toni Lato", korean_name: "토니 라토", team_id: 798, position: "Defender" },
  { id: 107194, name: "Antonio Sánchez", korean_name: "안토니오 산체스", team_id: 798, position: "Midfielder" },
  { id: 46742, name: "Dani Rodríguez", korean_name: "다니 로드리게스", team_id: 798, position: "Midfielder" },
  { id: 47336, name: "Darder", korean_name: "다르데르", team_id: 798, position: "Midfielder" },
  { id: 297646, name: "D. Luna", korean_name: "디에고 루나", team_id: 798, position: "Midfielder" },
  { id: 1701, name: "Manu Morlanes", korean_name: "마누 모를라네스", team_id: 798, position: "Midfielder" },
  { id: 482473, name: "Marc Domenech", korean_name: "마르크 도메네크", team_id: 798, position: "Midfielder" },
  { id: 411424, name: "Miquel Salas", korean_name: "미켈 살라스", team_id: 798, position: "Midfielder" },
  { id: 414, name: "Omar Mascarell", korean_name: "오마르 마스카렐", team_id: 798, position: "Midfielder" },
  { id: 285909, name: "Pablo Torre", korean_name: "파블로 토레", team_id: 798, position: "Midfielder" },
  { id: 190485, name: "Samú Costa", korean_name: "사무 코스타", team_id: 798, position: "Midfielder" },
  { id: 25375, name: "T. Asano", korean_name: "아사노 다쿠마", team_id: 798, position: "Midfielder" },
  { id: 46751, name: "Abdón Prats", korean_name: "압돈 프라츠", team_id: 798, position: "Attacker" },
  { id: 491248, name: "Jan Virgili Tenas", korean_name: "얀 비르힐리", team_id: 798, position: "Attacker" },
  { id: 293604, name: "Javi Llabrés", korean_name: "하비 야브레스", team_id: 798, position: "Attacker" },
  { id: 313059, name: "M. Joseph", korean_name: "마크 조셉", team_id: 798, position: "Attacker" },
  { id: 50048, name: "V. Muriqi", korean_name: "베다트 무리키", team_id: 798, position: "Attacker" },
];

// Osasuna (Team ID: 727) - 26명
export const OSASUNA_PLAYERS: PlayerMapping[] = [
  { id: 47448, name: "Aitor Fernández", korean_name: "아이토르 페르난데스", team_id: 727, position: "Goalkeeper" },
  { id: 348029, name: "D. Stamatakis", korean_name: "디미트리스 스타마타키스", team_id: 727, position: "Goalkeeper" },
  { id: 46646, name: "Sergio Herrera", korean_name: "세르히오 에레라", team_id: 727, position: "Goalkeeper" },
  { id: 47533, name: "Catena", korean_name: "카테나", team_id: 727, position: "Defender" },
  { id: 279822, name: "F. Boyomo", korean_name: "플라비앙 보요모", team_id: 727, position: "Defender" },
  { id: 182592, name: "Jorge Herrando", korean_name: "호르헤 에란도", team_id: 727, position: "Defender" },
  { id: 46967, name: "Juan Cruz", korean_name: "후안 크루스", team_id: 727, position: "Defender" },
  { id: 332304, name: "Raúl Chasco Ruiz", korean_name: "라울 차스코", team_id: 727, position: "Defender" },
  { id: 181259, name: "Abel Bretones", korean_name: "아벨 브레토네스", team_id: 727, position: "Midfielder" },
  { id: 381197, name: "Asier Osambela", korean_name: "아시에르 오삼벨라", team_id: 727, position: "Midfielder" },
  { id: 288800, name: "Iker Benito", korean_name: "이케르 베니토", team_id: 727, position: "Midfielder" },
  { id: 182621, name: "Iker Muñoz", korean_name: "이케르 무뇨스", team_id: 727, position: "Midfielder" },
  { id: 1825, name: "Lucas Torró", korean_name: "루카스 토로", team_id: 727, position: "Midfielder" },
  { id: 429553, name: "Mauro Echegoyen", korean_name: "마우로 에체고옌", team_id: 727, position: "Midfielder" },
  { id: 47574, name: "Moi Gómez", korean_name: "모이 고메스", team_id: 727, position: "Midfielder" },
  { id: 46662, name: "Moncayola", korean_name: "몬카욜라", team_id: 727, position: "Midfielder" },
  { id: 46658, name: "Rubén García", korean_name: "루벤 가르시아", team_id: 727, position: "Midfielder" },
  { id: 21701, name: "V. Rosier", korean_name: "발랑탱 로지에", team_id: 727, position: "Midfielder" },
  { id: 46746, name: "A. Budimir", korean_name: "안테 부디미르", team_id: 727, position: "Attacker" },
  { id: 67939, name: "Aimar Oroz", korean_name: "아이마르 오로스", team_id: 727, position: "Attacker" },
  { id: 186824, name: "Ander Yoldi", korean_name: "안데르 욜디", team_id: 727, position: "Attacker" },
  { id: 46667, name: "Kike Barja", korean_name: "키케 바르하", team_id: 727, position: "Attacker" },
  { id: 391819, name: "Martin Pedroarena", korean_name: "마르틴 페드로아레나", team_id: 727, position: "Attacker" },
  { id: 146751, name: "Raúl García", korean_name: "라울 가르시아", team_id: 727, position: "Attacker" },
  { id: 37938, name: "Sheraldo Rudi Becker", korean_name: "셰랄도 베커", team_id: 727, position: "Attacker" },
  { id: 338751, name: "Víctor Muñoz", korean_name: "빅토르 무뇨스", team_id: 727, position: "Attacker" },
];

// Oviedo (Team ID: 718) - 45명
export const OVIEDO_PLAYERS: PlayerMapping[] = [
  { id: 46673, name: "Aarón Escandell", korean_name: "아론 에스칸델", team_id: 718, position: "Goalkeeper" },
  { id: 42642, name: "Horaţiu Alexandru Moldovan", korean_name: "호라티우 몰도반", team_id: 718, position: "Goalkeeper" },
  { id: 297243, name: "Miguel Narváez", korean_name: "미겔 나르바에스", team_id: 718, position: "Goalkeeper" },
  { id: 485035, name: "Adrián Lopes", korean_name: "아드리안 로페스", team_id: 718, position: "Defender" },
  { id: 46996, name: "Álvaro Lemos", korean_name: "알바로 레모스", team_id: 718, position: "Defender" },
  { id: 384207, name: "C. Eze", korean_name: "칼빈 에제", team_id: 718, position: "Defender" },
  { id: 371738, name: "C. González", korean_name: "크리스티안 곤살레스", team_id: 718, position: "Defender" },
  { id: 46966, name: "Dani Calvo", korean_name: "다니 칼보", team_id: 718, position: "Defender" },
  { id: 47429, name: "David Costas", korean_name: "다비드 코스타스", team_id: 718, position: "Defender" },
  { id: 41970, name: "David Mota Veiga Teixeira Carmo", korean_name: "다비드 카르무", team_id: 718, position: "Defender" },
  { id: 885, name: "Eric Bertrand Bailly", korean_name: "에릭 바이", team_id: 718, position: "Defender" },
  { id: 438118, name: "Jaime Vázquez", korean_name: "하이메 바스케스", team_id: 718, position: "Defender" },
  { id: 182636, name: "Javier López Carballo", korean_name: "하비에르 로페스", team_id: 718, position: "Defender" },
  { id: 131548, name: "Lucas Ahijado", korean_name: "루카스 아히하도", team_id: 718, position: "Defender" },
  { id: 402580, name: "Marco Esteban", korean_name: "마르코 에스테반", team_id: 718, position: "Defender" },
  { id: 46657, name: "Nacho Vidal", korean_name: "나초 비달", team_id: 718, position: "Defender" },
  { id: 107140, name: "Oier Luengo", korean_name: "오이에르 루엥고", team_id: 718, position: "Defender" },
  { id: 385405, name: "Omar Falah", korean_name: "오마르 팔라", team_id: 718, position: "Defender" },
  { id: 181474, name: "Alberto del Moral", korean_name: "알베르토 델 모랄", team_id: 718, position: "Midfielder" },
  { id: 182486, name: "Alberto Reina Campos", korean_name: "알베르토 레이나", team_id: 718, position: "Midfielder" },
  { id: 286564, name: "Álex Cardero", korean_name: "알렉스 카르데로", team_id: 718, position: "Midfielder" },
  { id: 46862, name: "Borja Sánchez", korean_name: "보르하 산체스", team_id: 718, position: "Midfielder" },
  { id: 191184, name: "Brandon Dominguès", korean_name: "브랑동 도밍게스", team_id: 718, position: "Midfielder" },
  { id: 46919, name: "César de la Hoz", korean_name: "세사르 데 라 오스", team_id: 718, position: "Midfielder" },
  { id: 298065, name: "Diego Tejón", korean_name: "디에고 테혼", team_id: 718, position: "Midfielder" },
  { id: 755, name: "Jaime Seoane", korean_name: "하이메 세오아네", team_id: 718, position: "Midfielder" },
  { id: 443152, name: "José Luis Pereda López", korean_name: "호세 루이스 페레다", team_id: 718, position: "Midfielder" },
  { id: 3608, name: "K. Sibo", korean_name: "칼루 시보", team_id: 718, position: "Midfielder" },
  { id: 2922, name: "Leander Dendoncker", korean_name: "레안데르 덴동케르", team_id: 718, position: "Midfielder" },
  { id: 38699, name: "Luka Ilić", korean_name: "루카 일리치", team_id: 718, position: "Midfielder" },
  { id: 19613, name: "Oviemuno Dominic Ejaria", korean_name: "도미닉 에하리아", team_id: 718, position: "Midfielder" },
  { id: 295223, name: "R. Alhassane", korean_name: "라힘 알하산", team_id: 718, position: "Midfielder" },
  { id: 1695, name: "Santi Cazorla", korean_name: "산티 카소를라", team_id: 718, position: "Midfielder" },
  { id: 30927, name: "S. Colombatto", korean_name: "산티아고 콜롬바토", team_id: 718, position: "Midfielder" },
  { id: 184194, name: "Álex Forés Mendoza", korean_name: "알렉스 포레스", team_id: 718, position: "Attacker" },
  { id: 182668, name: "Álex Millán", korean_name: "알렉스 미얀", team_id: 718, position: "Attacker" },
  { id: 42754, name: "D. Paraschiv", korean_name: "다니엘 파라스키브", team_id: 718, position: "Attacker" },
  { id: 51530, name: "F. Viñas", korean_name: "페드로 비냐스", team_id: 718, position: "Attacker" },
  { id: 20844, name: "H. Hassan", korean_name: "하킴 하산", team_id: 718, position: "Attacker" },
  { id: 266202, name: "I. Chaira", korean_name: "일리아스 차이라", team_id: 718, position: "Attacker" },
  { id: 2461, name: "José Salomón Rondón Giménez", korean_name: "살로몬 론돈", team_id: 718, position: "Attacker" },
  { id: 2762, name: "Josip Brekalo", korean_name: "요시프 브레칼로", team_id: 718, position: "Attacker" },
  { id: 438123, name: "Lamine Gueye", korean_name: "라민 게예", team_id: 718, position: "Attacker" },
  { id: 308282, name: "Santi Miguélez", korean_name: "산티 미겔레스", team_id: 718, position: "Attacker" },
  { id: 527133, name: "Cheli", korean_name: "첼리", team_id: 718, position: undefined },
];

// Rayo Vallecano (Team ID: 728) - 30명
export const RAYO_VALLECANO_PLAYERS: PlayerMapping[] = [
  { id: 11379, name: "A. Batalla", korean_name: "아우구스토 바타야", team_id: 728, position: "Goalkeeper" },
  { id: 478244, name: "Adrián Molina Colorado", korean_name: "아드리안 몰리나", team_id: 728, position: "Goalkeeper" },
  { id: 156488, name: "Dani Cárdenas", korean_name: "다니 카르데나스", team_id: 728, position: "Goalkeeper" },
  { id: 285505, name: "Juan Pedro Gil Bueno", korean_name: "후안 페드로 길", team_id: 728, position: "Goalkeeper" },
  { id: 46759, name: "A. Espino", korean_name: "알폰소 에스피노", team_id: 728, position: "Defender" },
  { id: 15900, name: "A. Mumin", korean_name: "압둘 무민", team_id: 728, position: "Defender" },
  { id: 1703, name: "A. Rațiu", korean_name: "안드레이 라치우", team_id: 728, position: "Defender" },
  { id: 18895, name: "F. Lejeune", korean_name: "플로리안 르죈", team_id: 728, position: "Defender" },
  { id: 20520, name: "I. Balliu", korean_name: "이반 바유", team_id: 728, position: "Defender" },
  { id: 314006, name: "J. Vertrouwd", korean_name: "요르단 베르트라우트", team_id: 728, position: "Defender" },
  { id: 1847, name: "Luiz Felipe", korean_name: "루이스 펠리페", team_id: 728, position: "Defender" },
  { id: 478243, name: "Marco de las Sías López", korean_name: "마르코 데 라스 시아스", team_id: 728, position: "Defender" },
  { id: 358431, name: "Nobel Mendy", korean_name: "노벨 멘디", team_id: 728, position: "Defender" },
  { id: 41552, name: "P. Ciss", korean_name: "파테 시스", team_id: 728, position: "Defender" },
  { id: 333292, name: "Pelayo Fernández", korean_name: "펠라요 페르난데스", team_id: 728, position: "Defender" },
  { id: 181734, name: "Pep Chavarría", korean_name: "펩 차바리아", team_id: 728, position: "Defender" },
  { id: 47543, name: "Álvaro García", korean_name: "알바로 가르시아", team_id: 728, position: "Midfielder" },
  { id: 333378, name: "Diego Méndez", korean_name: "디에고 멘데스", team_id: 728, position: "Midfielder" },
  { id: 162931, name: "Fran Pérez", korean_name: "프란 페레스", team_id: 728, position: "Midfielder" },
  { id: 47414, name: "Gumbau", korean_name: "검바우", team_id: 728, position: "Midfielder" },
  { id: 131546, name: "Isi Palazón", korean_name: "이시 팔라손", team_id: 728, position: "Midfielder" },
  { id: 128582, name: "Jorge de Frutos", korean_name: "호르헤 데 프루토스", team_id: 728, position: "Midfielder" },
  { id: 47109, name: "Óscar Valentín", korean_name: "오스카르 발렌틴", team_id: 728, position: "Midfielder" },
  { id: 47557, name: "Ó. Trejo", korean_name: "오스카르 트레호", team_id: 728, position: "Midfielder" },
  { id: 46887, name: "Pedro Díaz", korean_name: "페드로 디아스", team_id: 728, position: "Midfielder" },
  { id: 122657, name: "R. Nteka", korean_name: "란디 은테카", team_id: 728, position: "Midfielder" },
  { id: 439633, name: "Samu Becerra", korean_name: "사무 베세라", team_id: 728, position: "Midfielder" },
  { id: 47285, name: "Unai López", korean_name: "우나이 로페스", team_id: 728, position: "Midfielder" },
  { id: 91745, name: "Alexandre Zurawski", korean_name: "알렉상드르 주라프스키", team_id: 728, position: "Attacker" },
  { id: 52, name: "Sergio Camello", korean_name: "세르히오 카메요", team_id: 728, position: "Attacker" },
];

// Real Betis (Team ID: 543) - 37명
export const REAL_BETIS_PLAYERS: PlayerMapping[] = [
  { id: 18812, name: "Adrián", korean_name: "아드리안", team_id: 543, position: "Goalkeeper" },
  { id: 46990, name: "Álvaro Vallés", korean_name: "알바로 바예스", team_id: 543, position: "Goalkeeper" },
  { id: 392455, name: "Germán García Fernández", korean_name: "헤르만 가르시아", team_id: 543, position: "Goalkeeper" },
  { id: 456619, name: "Manuel González Pallarés", korean_name: "마누엘 곤살레스", team_id: 543, position: "Goalkeeper" },
  { id: 1557, name: "Pau López", korean_name: "파우 로페스", team_id: 543, position: "Goalkeeper" },
  { id: 47119, name: "Aitor Ruibal", korean_name: "아이토르 루이발", team_id: 543, position: "Defender" },
  { id: 289554, name: "Darling Bladi", korean_name: "달링 블라디", team_id: 543, position: "Defender" },
  { id: 47302, name: "Diego Llorente", korean_name: "디에고 요렌테", team_id: 543, position: "Defender" },
  { id: 347886, name: "Félix Martí Garreta", korean_name: "펠릭스 마르티", team_id: 543, position: "Defender" },
  { id: 1439, name: "Héctor Bellerín", korean_name: "엑토르 베예린", team_id: 543, position: "Defender" },
  { id: 1564, name: "Junior Firpo", korean_name: "주니오르 피르포", team_id: 543, position: "Defender" },
  { id: 1561, name: "Marc Bartra", korean_name: "마르크 바르트라", team_id: 543, position: "Defender" },
  { id: 195100, name: "Natan", korean_name: "나탕", team_id: 543, position: "Defender" },
  { id: 1631, name: "R. Rodríguez", korean_name: "히카르도 로드리게스", team_id: 543, position: "Defender" },
  { id: 355004, name: "V. Gómez", korean_name: "빅토르 고메스", team_id: 543, position: "Defender" },
  { id: 181421, name: "A. Ezzalzouli", korean_name: "아브데 에잘줄리", team_id: 543, position: "Midfielder" },
  { id: 9971, name: "Antony Matheus dos Santos", korean_name: "안토니", team_id: 543, position: "Midfielder" },
  { id: 351131, name: "Daniel Pérez Guerrero", korean_name: "다니엘 페레스", team_id: 543, position: "Midfielder" },
  { id: 477231, name: "Emmanuel Mawuli Mensah", korean_name: "엠마누엘 멘사", team_id: 543, position: "Midfielder" },
  { id: 1578, name: "G. Lo Celso", korean_name: "조반니 로 첼소", team_id: 543, position: "Midfielder" },
  { id: 128985, name: "Iker Losada", korean_name: "이케르 로사다", team_id: 543, position: "Midfielder" },
  { id: 745, name: "Isco", korean_name: "이스코", team_id: 543, position: "Midfielder" },
  { id: 450714, name: "Ivan Corralejo", korean_name: "이반 코랄레호", team_id: 543, position: "Midfielder" },
  { id: 47341, name: "Marc Roca", korean_name: "마르크 로카", team_id: 543, position: "Midfielder" },
  { id: 353803, name: "Mawuli Kwame Mensah Vadze", korean_name: "마울리 멘사", team_id: 543, position: "Midfielder" },
  { id: 300885, name: "N. Deossa", korean_name: "니콜라스 데오사", team_id: 543, position: "Midfielder" },
  { id: 1697, name: "Pablo Fornals", korean_name: "파블로 포르날스", team_id: 543, position: "Midfielder" },
  { id: 136117, name: "Rodrigo Riquelme", korean_name: "로드리고 리켈메", team_id: 543, position: "Midfielder" },
  { id: 286084, name: "Sergi Altimira", korean_name: "세르지 알티미라", team_id: 543, position: "Midfielder" },
  { id: 74, name: "Sofyan Amrabat", korean_name: "소피안 암라바트", team_id: 543, position: "Midfielder" },
  { id: 334574, name: "Ángel Ortiz", korean_name: "안헬 오르티스", team_id: 543, position: "Attacker" },
  { id: 3033, name: "C. Bakambu", korean_name: "세드릭 바캄부", team_id: 543, position: "Attacker" },
  { id: 47582, name: "C. Hernández", korean_name: "치미 에르난데스", team_id: 543, position: "Attacker" },
  { id: 47579, name: "E. Ávila", korean_name: "에세키엘 아빌라", team_id: 543, position: "Attacker" },
  { id: 443163, name: "Pablo García Fernández", korean_name: "파블로 가르시아", team_id: 543, position: "Attacker" },
  { id: 548853, name: "D. Bladi", korean_name: "달링 블라디", team_id: 543, position: undefined },
  { id: 544644, name: "J. A. Morante", korean_name: "호세 안토니오 모란테", team_id: 543, position: undefined },
];

// Real Sociedad (Team ID: 548) - 34명
export const REAL_SOCIEDAD_PLAYERS: PlayerMapping[] = [
  { id: 337843, name: "Aitor Fraga Torres", korean_name: "아이토르 프라가", team_id: 548, position: "Goalkeeper" },
  { id: 47269, name: "Álex Remiro", korean_name: "알렉스 레미로", team_id: 548, position: "Goalkeeper" },
  { id: 189831, name: "Arana", korean_name: "아라나", team_id: 548, position: "Goalkeeper" },
  { id: 431160, name: "Theo Mickael Kevin Folgado", korean_name: "테오 폴가도", team_id: 548, position: "Goalkeeper" },
  { id: 189832, name: "Unai Marrero", korean_name: "우나이 마레로", team_id: 548, position: "Goalkeeper" },
  { id: 47303, name: "Aihen Muñoz", korean_name: "아이엔 무뇨스", team_id: 548, position: "Defender" },
  { id: 1902, name: "D. Ćaleta-Car", korean_name: "두예 칼레타카르", team_id: 548, position: "Defender" },
  { id: 47298, name: "Elustondo", korean_name: "엘루스톤도", team_id: 548, position: "Defender" },
  { id: 2202, name: "H. Traoré", korean_name: "아메드 트라오레", team_id: 548, position: "Defender" },
  { id: 199044, name: "J. Aramburu", korean_name: "존 아람부루", team_id: 548, position: "Defender" },
  { id: 405073, name: "Jon Martín", korean_name: "존 마르틴", team_id: 548, position: "Defender" },
  { id: 182546, name: "Jon Pacheco", korean_name: "존 파체코", team_id: 548, position: "Defender" },
  { id: 349063, name: "Luken Beitia Aguirregomezcorta", korean_name: "루켄 베이티아", team_id: 548, position: "Defender" },
  { id: 737, name: "Odriozola", korean_name: "오드리오솔라", team_id: 548, position: "Defender" },
  { id: 23, name: "Sergio Gómez", korean_name: "세르히오 고메스", team_id: 548, position: "Defender" },
  { id: 47314, name: "Zubeldia", korean_name: "주벨디아", team_id: 548, position: "Defender" },
  { id: 353634, name: "Alex Douma Johan Lebarbier", korean_name: "알렉스 레바르비에", team_id: 548, position: "Midfielder" },
  { id: 268960, name: "A. Zakharyan", korean_name: "아르센 자하리안", team_id: 548, position: "Midfielder" },
  { id: 47317, name: "Barrenetxea", korean_name: "바레네체아", team_id: 548, position: "Midfielder" },
  { id: 183744, name: "Beñat Turrientes", korean_name: "베냣 투리엔테스", team_id: 548, position: "Midfielder" },
  { id: 47440, name: "Brais Méndez", korean_name: "브라이스 멘데스", team_id: 548, position: "Midfielder" },
  { id: 930, name: "Carlos Soler Barragán", korean_name: "카를로스 솔레르", team_id: 548, position: "Midfielder" },
  { id: 925, name: "Gonçalo Guedes", korean_name: "곤살루 게데스", team_id: 548, position: "Midfielder" },
  { id: 287654, name: "Jon Gorrotxategi", korean_name: "존 고로차테기", team_id: 548, position: "Midfielder" },
  { id: 7332, name: "L. Sučić", korean_name: "루카 수치치", team_id: 548, position: "Midfielder" },
  { id: 288384, name: "Mikel Goti", korean_name: "미켈 고티", team_id: 548, position: "Midfielder" },
  { id: 290106, name: "Pablo Marín", korean_name: "파블로 마린", team_id: 548, position: "Midfielder" },
  { id: 183699, name: "Urko González", korean_name: "우르코 곤살레스", team_id: 548, position: "Midfielder" },
  { id: 402168, name: "Arkaitz Mariezkurrena", korean_name: "아르카이츠 마리에스쿠레나", team_id: 548, position: "Attacker" },
  { id: 183748, name: "Jon Karrikaburu", korean_name: "존 카리카부루", team_id: 548, position: "Attacker" },
  { id: 47323, name: "Mikel Oyarzabal", korean_name: "미켈 오야르사발", team_id: 548, position: "Attacker" },
  { id: 61774, name: "O. Óskarsson", korean_name: "오르리 오스카르손", team_id: 548, position: "Attacker" },
  { id: 32862, name: "T. Kubo", korean_name: "쿠보 다케후사", team_id: 548, position: "Attacker" },
  { id: 31406, name: "U. Sadiq", korean_name: "우마르 사디크", team_id: 548, position: "Attacker" },
];

// Sevilla (Team ID: 536) - 36명
export const SEVILLA_PLAYERS: PlayerMapping[] = [
  { id: 308346, name: "Alberto Flores", korean_name: "알베르토 플로레스", team_id: 536, position: "Goalkeeper" },
  { id: 47016, name: "Álvaro Fernández", korean_name: "알바로 페르난데스", team_id: 536, position: "Goalkeeper" },
  { id: 557, name: "Odysseas Vlachodimos", korean_name: "오디세아스 블라호디모스", team_id: 536, position: "Goalkeeper" },
  { id: 19172, name: "Ø. Nyland", korean_name: "오르잔 뉘란", team_id: 536, position: "Goalkeeper" },
  { id: 290686, name: "Rafael Romero", korean_name: "라파엘 로메로", team_id: 536, position: "Goalkeeper" },
  { id: 47329, name: "Adrià Pedrosa", korean_name: "아드리아 페드로사", team_id: 536, position: "Defender" },
  { id: 338902, name: "Andrés Castrín", korean_name: "안드레스 카스트린", team_id: 536, position: "Defender" },
  { id: 2280, name: "César Azpilicueta Tanco", korean_name: "세사르 아스필리쿠에타", team_id: 536, position: "Defender" },
  { id: 41208, name: "Fábio Rafael Rodrigues Cardoso", korean_name: "파비우 카르도소", team_id: 536, position: "Defender" },
  { id: 125331, name: "F. Gattoni", korean_name: "페데리코 가토니", team_id: 536, position: "Defender" },
  { id: 341453, name: "Joaquín Martínez Gauna", korean_name: "호아킨 마르티네스", team_id: 536, position: "Defender" },
  { id: 195923, name: "José Ángel Carmona", korean_name: "호세 안헬 카르모나", team_id: 536, position: "Defender" },
  { id: 297311, name: "Kike Salas", korean_name: "키케 살라스", team_id: 536, position: "Defender" },
  { id: 433, name: "Marcão", korean_name: "마르상", team_id: 536, position: "Defender" },
  { id: 197196, name: "Ramón Martínez", korean_name: "라몬 마르티네스", team_id: 536, position: "Defender" },
  { id: 133110, name: "T. Nianzou", korean_name: "탕기 니안주", team_id: 536, position: "Defender" },
  { id: 2924, name: "A. Januzaj", korean_name: "아드난 야누자이", team_id: 536, position: "Midfielder" },
  { id: 910, name: "Alexis Alejandro Sánchez Sánchez", korean_name: "알렉시스 산체스", team_id: 536, position: "Midfielder" },
  { id: 21087, name: "Batista Adélino Mendy", korean_name: "밥티스트 멘디", team_id: 536, position: "Midfielder" },
  { id: 957, name: "D. Sow", korean_name: "제레 소", team_id: 536, position: "Midfielder" },
  { id: 443593, name: "Eduardo Altozano Agudo", korean_name: "에두아르도 알토사노", team_id: 536, position: "Midfielder" },
  { id: 11421, name: "G. Suazo", korean_name: "가브리엘 수아소", team_id: 536, position: "Midfielder" },
  { id: 47389, name: "Joan Jordán", korean_name: "호안 호르단", team_id: 536, position: "Midfielder" },
  { id: 182772, name: "Juanlu Sánchez", korean_name: "후안루 산체스", team_id: 536, position: "Midfielder" },
  { id: 21004, name: "L. Agoumé", korean_name: "루시앙 아구메", team_id: 536, position: "Midfielder" },
  { id: 331607, name: "Manu Bueno", korean_name: "마누 부에노", team_id: 536, position: "Midfielder" },
  { id: 1489, name: "N. Gudelj", korean_name: "네만야 구델", team_id: 536, position: "Midfielder" },
  { id: 48471, name: "R. Vargas", korean_name: "루벤 바르가스", team_id: 536, position: "Midfielder" },
  { id: 340152, name: "S. Idumbo-Muzambo", korean_name: "사이몽 이둠보", team_id: 536, position: "Midfielder" },
  { id: 57446, name: "A. Adams", korean_name: "아쉐 아담스", team_id: 536, position: "Attacker" },
  { id: 437594, name: "Alejandro Costa Quijano", korean_name: "알레한드로 코스타", team_id: 536, position: "Attacker" },
  { id: 119213, name: "Alfon González", korean_name: "알폰 곤살레스", team_id: 536, position: "Attacker" },
  { id: 39121, name: "C. Ejuke", korean_name: "치데라 에주케", team_id: 536, position: "Attacker" },
  { id: 185398, name: "Isaac", korean_name: "이사크", team_id: 536, position: "Attacker" },
  { id: 438263, name: "Miguel Ángel", korean_name: "미겔 안헬", team_id: 536, position: "Attacker" },
  { id: 162126, name: "Peque Fernández", korean_name: "페케 페르난데스", team_id: 536, position: "Attacker" },
];

// Valencia (Team ID: 532) - 28명
export const VALENCIA_PLAYERS: PlayerMapping[] = [
  { id: 913, name: "Cristian Rivero", korean_name: "크리스티안 리베로", team_id: 532, position: "Goalkeeper" },
  { id: 183848, name: "Julen Agirrezabala", korean_name: "훌렌 아기레사발라", team_id: 532, position: "Goalkeeper" },
  { id: 47527, name: "S. Dimitrievski", korean_name: "스톨레 디미트리예프스키", team_id: 532, position: "Goalkeeper" },
  { id: 333672, name: "César Tárrega", korean_name: "세사르 타레가", team_id: 532, position: "Defender" },
  { id: 181582, name: "Copete", korean_name: "코페테", team_id: 532, position: "Defender" },
  { id: 47251, name: "D. Foulquier", korean_name: "디미트리 풀키에", team_id: 532, position: "Defender" },
  { id: 48372, name: "E. Cömert", korean_name: "에라이 쾨메르트", team_id: 532, position: "Defender" },
  { id: 162175, name: "Jesús Vázquez", korean_name: "헤수스 바스케스", team_id: 532, position: "Defender" },
  { id: 918, name: "José Gayà", korean_name: "호세 가야", team_id: 532, position: "Defender" },
  { id: 916, name: "M. Diakhaby", korean_name: "무쿠타르 디아카비", team_id: 532, position: "Defender" },
  { id: 315701, name: "Rubo Iranzo", korean_name: "루보 이란소", team_id: 532, position: "Defender" },
  { id: 1482, name: "Thierry Correia", korean_name: "티에리 코레이아", team_id: 532, position: "Defender" },
  { id: 41157, name: "André Almeida", korean_name: "안드레 알메이다", team_id: 532, position: "Midfielder" },
  { id: 21153, name: "B. Santamaría", korean_name: "밥티스트 산타마리아", team_id: 532, position: "Midfielder" },
  { id: 162127, name: "Diego López", korean_name: "디에고 로페스", team_id: 532, position: "Midfielder" },
  { id: 48465, name: "F. Ugrinic", korean_name: "파비안 우그리니치", team_id: 532, position: "Midfielder" },
  { id: 297743, name: "Javier Navarro Girona", korean_name: "하비에르 나바로", team_id: 532, position: "Midfielder" },
  { id: 315699, name: "Javi Guerra", korean_name: "하비 게라", team_id: 532, position: "Midfielder" },
  { id: 406043, name: "Lucas Nuñez Ramirez", korean_name: "루카스 누녜스", team_id: 532, position: "Midfielder" },
  { id: 46933, name: "Luis Rioja", korean_name: "루이스 리오하", team_id: 532, position: "Midfielder" },
  { id: 47463, name: "Pepelu", korean_name: "페펠루", team_id: 532, position: "Midfielder" },
  { id: 406045, name: "Aimar Blázquez", korean_name: "아이마르 블라스케스", team_id: 532, position: "Attacker" },
  { id: 1708, name: "Dani Raba", korean_name: "다니 라바", team_id: 532, position: "Attacker" },
  { id: 439578, name: "David Otorbi", korean_name: "다비드 오토르비", team_id: 532, position: "Attacker" },
  { id: 47264, name: "Hugo Duro", korean_name: "우고 두로", team_id: 532, position: "Attacker" },
  { id: 138776, name: "Largie Ramazani", korean_name: "라르지 라마자니", team_id: 532, position: "Attacker" },
  { id: 6010, name: "Lucas Beltrán", korean_name: "루카스 벨트란", team_id: 532, position: "Attacker" },
  { id: 406046, name: "Pablo López", korean_name: "파블로 로페스", team_id: 532, position: "Attacker" },
];

// Villarreal (Team ID: 533) - 36명
export const VILLARREAL_PLAYERS: PlayerMapping[] = [
  { id: 162473, name: "Arnau Tenas Ureña", korean_name: "아르나우 테나스", team_id: 533, position: "Goalkeeper" },
  { id: 122956, name: "Diego Conde", korean_name: "디에고 콘데", team_id: 533, position: "Goalkeeper" },
  { id: 278619, name: "Luíz Júnior", korean_name: "루이스 주니오르", team_id: 533, position: "Goalkeeper" },
  { id: 302277, name: "Rubén Gómez", korean_name: "루벤 고메스", team_id: 533, position: "Goalkeeper" },
  { id: 162122, name: "Adrià Alti", korean_name: "아드리아 알티", team_id: 533, position: "Defender" },
  { id: 330443, name: "Ismael Sierra Arnal", korean_name: "이스마엘 시에라", team_id: 533, position: "Defender" },
  { id: 166, name: "J. Foyth", korean_name: "후안 포이트", team_id: 533, position: "Defender" },
  { id: 484474, name: "J. Valou", korean_name: "조르단 발루", team_id: 533, position: "Defender" },
  { id: 21997, name: "Logan Costa", korean_name: "로간 코스타", team_id: 533, position: "Defender" },
  { id: 435552, name: "Pau Navarro", korean_name: "파우 나바로", team_id: 533, position: "Defender" },
  { id: 1702, name: "Pedraza", korean_name: "페드라사", team_id: 533, position: "Defender" },
  { id: 237066, name: "Rafa Marín", korean_name: "라파 마린", team_id: 533, position: "Defender" },
  { id: 336671, name: "Renato da Palma Veiga", korean_name: "레나투 베이가", team_id: 533, position: "Defender" },
  { id: 70500, name: "Sergi Cardona", korean_name: "세르지 카르도나", team_id: 533, position: "Defender" },
  { id: 311773, name: "S. Mouriño", korean_name: "세르히오 모리뇨", team_id: 533, position: "Defender" },
  { id: 288112, name: "Willy Kambwala Ndengushi", korean_name: "윌리 캄왈라", team_id: 533, position: "Defender" },
  { id: 928, name: "Dani Parejo", korean_name: "다니 파레호", team_id: 533, position: "Midfielder" },
  { id: 1461, name: "Denis Suárez", korean_name: "데니스 수아레스", team_id: 533, position: "Midfielder" },
  { id: 290740, name: "Ilias Akhomach", korean_name: "일리아스 아코마크", team_id: 533, position: "Midfielder" },
  { id: 697, name: "Manor Solomon", korean_name: "마노르 솔로몬", team_id: 533, position: "Midfielder" },
  { id: 20696, name: "P. Gueye", korean_name: "파페 게예", team_id: 533, position: "Midfielder" },
  { id: 47541, name: "Santi Comesaña", korean_name: "산티 코메사냐", team_id: 533, position: "Midfielder" },
  { id: 51016, name: "T. Buchanan", korean_name: "타조나 부캐넌", team_id: 533, position: "Midfielder" },
  { id: 49, name: "T. Partey", korean_name: "토마스 파테이", team_id: 533, position: "Midfielder" },
  { id: 184226, name: "Yeremy Pino", korean_name: "예레미 피노", team_id: 533, position: "Midfielder" },
  { id: 182519, name: "Alberto Moleiro", korean_name: "알베르토 몰레이로", team_id: 533, position: "Attacker" },
  { id: 83, name: "Arnaut Danjuma Adam Groeneveld", korean_name: "아르나우트 단주마", team_id: 533, position: "Attacker" },
  { id: 18906, name: "Ayoze Pérez", korean_name: "아요세 페레스", team_id: 533, position: "Attacker" },
  { id: 378284, name: "Etta Eyong", korean_name: "에타 에용", team_id: 533, position: "Attacker" },
  { id: 180496, name: "Georges Mikautadze", korean_name: "조르주 미카우타제", team_id: 533, position: "Attacker" },
  { id: 1707, name: "Gerard Moreno", korean_name: "제라르드 모레노", team_id: 533, position: "Attacker" },
  { id: 514913, name: "Hugo López Cortés", korean_name: "우고 로페스", team_id: 533, position: "Attacker" },
  { id: 418188, name: "Mahamoud Barry", korean_name: "마하무드 바리", team_id: 533, position: "Attacker" },
  { id: 3246, name: "N. Pépé", korean_name: "니콜라 페페", team_id: 533, position: "Attacker" },
  { id: 411702, name: "Pau Cabanes", korean_name: "파우 카바네스", team_id: 533, position: "Attacker" },
  { id: 351587, name: "Tanitoluwa Oluwatimikhin Oluwaseyi", korean_name: "타니 올루왈세이", team_id: 533, position: "Attacker" },
];

// 라리가 Part 2 전체 선수 (완성!)
export const LALIGA_PART2_PLAYERS: PlayerMapping[] = [
  ...ELCHE_PLAYERS,
  ...ESPANYOL_PLAYERS,
  ...GETAFE_PLAYERS,
  ...GIRONA_PLAYERS,
  ...LEVANTE_PLAYERS,
  ...MALLORCA_PLAYERS,
  ...OSASUNA_PLAYERS,
  ...OVIEDO_PLAYERS,
  ...RAYO_VALLECANO_PLAYERS,
  ...REAL_BETIS_PLAYERS,
  ...REAL_SOCIEDAD_PLAYERS,
  ...SEVILLA_PLAYERS,
  ...VALENCIA_PLAYERS,
  ...VILLARREAL_PLAYERS,
];


