import { PlayerMapping } from './index';
import { LALIGA_PART2_PLAYERS } from './laliga-part2';

// 라리가 선수 매핑 데이터 (632명, 20개 팀)

// Alaves (Team ID: 542) - 27명
export const ALAVES_PLAYERS: PlayerMapping[] = [
  { id: 377215, name: "G. Swiderski", korean_name: "그제고시 스비데르스키", team_id: 542, position: "Goalkeeper" },
  { id: 46987, name: "Raúl Fernández", korean_name: "라울 페르난데스", team_id: 542, position: "Goalkeeper" },
  { id: 439032, name: "Rubén Montero Fernández", korean_name: "루벤 몬테로", team_id: 542, position: "Goalkeeper" },
  { id: 47353, name: "Sivera", korean_name: "시베라", team_id: 542, position: "Goalkeeper" },
  { id: 387530, name: "Carlos Ballestero García", korean_name: "카를로스 바예스테로", team_id: 542, position: "Defender" },
  { id: 6638, name: "F. Garcés", korean_name: "페르난도 가르세스", team_id: 542, position: "Defender" },
  { id: 18740, name: "Jonny", korean_name: "조니", team_id: 542, position: "Defender" },
  { id: 70476, name: "M. Diarra", korean_name: "무사 디아라", team_id: 542, position: "Defender" },
  { id: 41412, name: "N. Maraš", korean_name: "네만야 마라시", team_id: 542, position: "Defender" },
  { id: 6233, name: "N. Tenaglia", korean_name: "나우엘 테나글리아", team_id: 542, position: "Defender" },
  { id: 128951, name: "Víctor Parada", korean_name: "빅토르 파라다", team_id: 542, position: "Defender" },
  { id: 361384, name: "Yusi", korean_name: "유시", team_id: 542, position: "Defender" },
  { id: 162686, name: "Antonio Blanco", korean_name: "안토니오 블랑코", team_id: 542, position: "Midfielder" },
  { id: 183751, name: "A. Rebbach", korean_name: "아민 레바크", team_id: 542, position: "Midfielder" },
  { id: 266658, name: "Calebe", korean_name: "칼레베", team_id: 542, position: "Midfielder" },
  { id: 143, name: "Carles Aleñá", korean_name: "카를레스 알레냐", team_id: 542, position: "Midfielder" },
  { id: 6085, name: "C. Benavídez", korean_name: "카를로스 베나비데스", team_id: 542, position: "Midfielder" },
  { id: 47309, name: "Guevara", korean_name: "게바라", team_id: 542, position: "Midfielder" },
  { id: 104821, name: "Jon Guridi", korean_name: "존 구리디", team_id: 542, position: "Midfielder" },
  { id: 315586, name: "Lander Pinillos", korean_name: "란데르 피니요스", team_id: 542, position: "Midfielder" },
  { id: 608, name: "Lucas Ariel Boyé", korean_name: "루카스 보예", team_id: 542, position: "Midfielder" },
  { id: 139001, name: "Pablo Ibáñez", korean_name: "파블로 이바녜스", team_id: 542, position: "Midfielder" },
  { id: 187214, name: "Carlos Vicente", korean_name: "카를로스 비센테", team_id: 542, position: "Attacker" },
  { id: 565586, name: "D. Morcillo", korean_name: "다니 모르시요", team_id: 542, position: "Attacker" },
  { id: 760, name: "M. Díaz", korean_name: "마누엘 디아스", team_id: 542, position: "Attacker" },
  { id: 47181, name: "Toni Martínez", korean_name: "토니 마르티네스", team_id: 542, position: "Attacker" },
  { id: 551461, name: "R. Montero", korean_name: "루벤 몬테로", team_id: 542, position: undefined },
];

// Athletic Club (Team ID: 531) - 35명
export const ATHLETIC_CLUB_PLAYERS: PlayerMapping[] = [
  { id: 312468, name: "Álex Padilla", korean_name: "알렉스 파디야", team_id: 531, position: "Goalkeeper" },
  { id: 437637, name: "Mikel Santos", korean_name: "미켈 산토스", team_id: 531, position: "Goalkeeper" },
  { id: 47270, name: "Unai Simón", korean_name: "우나이 시몬", team_id: 531, position: "Goalkeeper" },
  { id: 336998, name: "A. Boiro", korean_name: "아이토르 보이로", team_id: 531, position: "Defender" },
  { id: 384262, name: "Aimar Duñabeitia Madariaga", korean_name: "아이마르 두냐베이티아", team_id: 531, position: "Defender" },
  { id: 183849, name: "Aitor Paredes", korean_name: "아이토르 파레데스", team_id: 531, position: "Defender" },
  { id: 622, name: "Aymeric Jean Louis Gérard Alph Laporte", korean_name: "아이메릭 라포르트", team_id: 531, position: "Defender" },
  { id: 47278, name: "Dani Vivian", korean_name: "다니 비비안", team_id: 531, position: "Defender" },
  { id: 47299, name: "Gorosabel", korean_name: "고로사벨", team_id: 531, position: "Defender" },
  { id: 407677, name: "Iker Monreal Agundez", korean_name: "이케르 몬레알", team_id: 531, position: "Defender" },
  { id: 182181, name: "Jesús Areso", korean_name: "헤수스 아레소", team_id: 531, position: "Defender" },
  { id: 344838, name: "Johaneko Louis-Jean", korean_name: "조하네코 루이스장", team_id: 531, position: "Defender" },
  { id: 335490, name: "Jon de Luis", korean_name: "존 데 루이스", team_id: 531, position: "Defender" },
  { id: 47276, name: "Lekue", korean_name: "레쿠에", team_id: 531, position: "Defender" },
  { id: 332305, name: "Unai Eguíluz", korean_name: "우나이 에길루스", team_id: 531, position: "Defender" },
  { id: 47271, name: "Yeray", korean_name: "예라이", team_id: 531, position: "Defender" },
  { id: 47273, name: "Yuri", korean_name: "유리", team_id: 531, position: "Defender" },
  { id: 543467, name: "Adrian Perez", korean_name: "아드리안 페레스", team_id: 531, position: "Midfielder" },
  { id: 332309, name: "Alejandro Rego", korean_name: "알레한드로 레고", team_id: 531, position: "Midfielder" },
  { id: 182617, name: "Beñat Prados", korean_name: "베냣 프라도스", team_id: 531, position: "Midfielder" },
  { id: 47291, name: "Gorka Guruzeta", korean_name: "고르카 구루제타", team_id: 531, position: "Midfielder" },
  { id: 543466, name: "Ibon Sánchez", korean_name: "이본 산체스", team_id: 531, position: "Midfielder" },
  { id: 383780, name: "Mikel Jauregizar", korean_name: "미켈 하우레기자르", team_id: 531, position: "Midfielder" },
  { id: 47418, name: "Mikel Vesga", korean_name: "미켈 베스가", team_id: 531, position: "Midfielder" },
  { id: 286593, name: "Nico Serrano", korean_name: "니코 세라노", team_id: 531, position: "Midfielder" },
  { id: 128398, name: "Oihan Sancet", korean_name: "오이한 산체트", team_id: 531, position: "Midfielder" },
  { id: 84086, name: "Robert Navarro", korean_name: "로베르트 나바로", team_id: 531, position: "Midfielder" },
  { id: 47007, name: "Ruíz de Galarreta", korean_name: "루이스 데 갈라레타", team_id: 531, position: "Midfielder" },
  { id: 332308, name: "Unai Gómez", korean_name: "우나이 고메스", team_id: 531, position: "Midfielder" },
  { id: 30510, name: "Álex Berenguer", korean_name: "알렉스 베렝게르", team_id: 531, position: "Attacker" },
  { id: 47294, name: "I. Williams", korean_name: "이냐키 윌리엄스", team_id: 531, position: "Attacker" },
  { id: 288525, name: "Malcom Adu", korean_name: "말컴 아두", team_id: 531, position: "Attacker" },
  { id: 287680, name: "Maroan Sannadi", korean_name: "마로안 산나디", team_id: 531, position: "Attacker" },
  { id: 183799, name: "Nico Williams", korean_name: "니코 윌리엄스", team_id: 531, position: "Attacker" },
  { id: 183776, name: "Urko Izeta", korean_name: "우르코 이제타", team_id: 531, position: "Attacker" },
];

// Atletico Madrid (Team ID: 530) - 32명
export const ATLETICO_MADRID_PLAYERS: PlayerMapping[] = [
  { id: 2465, name: "J. Musso", korean_name: "후안 무소", team_id: 530, position: "Goalkeeper" },
  { id: 29, name: "J. Oblak", korean_name: "얀 오블라크", team_id: 530, position: "Goalkeeper" },
  { id: 393198, name: "Salvador Esquivel", korean_name: "살바도르 에스키벨", team_id: 530, position: "Goalkeeper" },
  { id: 133, name: "C. Lenglet", korean_name: "클레망 랑글레", team_id: 530, position: "Defender" },
  { id: 30399, name: "D. Hancko", korean_name: "다비드 한츠코", team_id: 530, position: "Defender" },
  { id: 338508, name: "Ilias Kostis", korean_name: "일리아스 코스티스", team_id: 530, position: "Defender" },
  { id: 47566, name: "Javi Galán", korean_name: "하비 갈란", team_id: 530, position: "Defender" },
  { id: 31, name: "J. Giménez", korean_name: "호세 히메네스", team_id: 530, position: "Defender" },
  { id: 753, name: "Marcos Llorente", korean_name: "마르코스 요렌테", team_id: 530, position: "Defender" },
  { id: 295793, name: "Marc Pubill", korean_name: "마르크 푸비야", team_id: 530, position: "Defender" },
  { id: 162012, name: "M. Ruggeri", korean_name: "마르코스 루게리", team_id: 530, position: "Defender" },
  { id: 6503, name: "N. Molina", korean_name: "나우엘 몰리나", team_id: 530, position: "Defender" },
  { id: 47301, name: "Robin Le Normand", korean_name: "로빈 르 노르망", team_id: 530, position: "Defender" },
  { id: 336590, name: "Aitor Gismera Monge", korean_name: "아이토르 지스메라", team_id: 530, position: "Midfielder" },
  { id: 451594, name: "Alejandro Monserrate Pueyo", korean_name: "알레한드로 몬세라테", team_id: 530, position: "Midfielder" },
  { id: 182219, name: "Álex Baena", korean_name: "알렉스 바에나", team_id: 530, position: "Midfielder" },
  { id: 67972, name: "C. Gallagher", korean_name: "코너 갤러거", team_id: 530, position: "Midfielder" },
  { id: 133185, name: "J. Cardoso", korean_name: "조니 카르도소", team_id: 530, position: "Midfielder" },
  { id: 50, name: "Koke", korean_name: "코케", team_id: 530, position: "Midfielder" },
  { id: 26315, name: "Nicolás Iván González", korean_name: "니콜라스 곤살레스", team_id: 530, position: "Midfielder" },
  { id: 336594, name: "Pablo Barrios", korean_name: "파블로 바리오스", team_id: 530, position: "Midfielder" },
  { id: 2472, name: "R. De Paul", korean_name: "로드리고 데 파울", team_id: 530, position: "Midfielder" },
  { id: 6067, name: "T. Almada", korean_name: "티아고 알마다", team_id: 530, position: "Midfielder" },
  { id: 443748, name: "Taufik Seidu Zanzi Awudu", korean_name: "타우피크 세이두", team_id: 530, position: "Midfielder" },
  { id: 56, name: "A. Griezmann", korean_name: "앙투안 그리즈만", team_id: 530, position: "Attacker" },
  { id: 8492, name: "A. Sørloth", korean_name: "알렉산데르 쇠를로트", team_id: 530, position: "Attacker" },
  { id: 324750, name: "Carlos Martín", korean_name: "카를로스 마르틴", team_id: 530, position: "Attacker" },
  { id: 30543, name: "G. Raspadori", korean_name: "자코모 라스파도리", team_id: 530, position: "Attacker" },
  { id: 323935, name: "G. Simeone", korean_name: "조반니 시메오네", team_id: 530, position: "Attacker" },
  { id: 6009, name: "J. Álvarez", korean_name: "훌리안 알바레스", team_id: 530, position: "Attacker" },
  { id: 443668, name: "Rayane Belid", korean_name: "라야네 벨리드", team_id: 530, position: "Attacker" },
  { id: 548867, name: "T. Seidu", korean_name: "타우피크 세이두", team_id: 530, position: undefined },
];

// Barcelona (Team ID: 529) - 30명
export const BARCELONA_PLAYERS: PlayerMapping[] = [
  { id: 383647, name: "D. Kochen", korean_name: "디에고 코첸", team_id: 529, position: "Goalkeeper" },
  { id: 543468, name: "Eder Aller", korean_name: "에데르 아예르", team_id: 529, position: "Goalkeeper" },
  { id: 182718, name: "Joan García", korean_name: "조안 가르시아", team_id: 529, position: "Goalkeeper" },
  { id: 127, name: "M. ter Stegen", korean_name: "마르크안드레 테어 슈테겐", team_id: 529, position: "Goalkeeper" },
  { id: 851, name: "W. Szczęsny", korean_name: "보이치에흐 슈체스니", team_id: 529, position: "Goalkeeper" },
  { id: 2282, name: "A. Christensen", korean_name: "안드레아스 크리스텐센", team_id: 529, position: "Defender" },
  { id: 161928, name: "Alejandro Balde", korean_name: "알레한드로 발데", team_id: 529, position: "Defender" },
  { id: 619, name: "Eric García", korean_name: "에릭 가르시아", team_id: 529, position: "Defender" },
  { id: 181701, name: "Gerard Martín Langreo", korean_name: "제라르드 마르틴", team_id: 529, position: "Defender" },
  { id: 2670, name: "Íñigo Martínez Berridi", korean_name: "이니고 마르티네스", team_id: 529, position: "Defender" },
  { id: 1257, name: "J. Koundé", korean_name: "쥘 쿤데", team_id: 529, position: "Defender" },
  { id: 491250, name: "Jofre Torrents", korean_name: "조프레 토렌츠", team_id: 529, position: "Defender" },
  { id: 396623, name: "Pau Cubarsí Paredes", korean_name: "파우 쿠바르시", team_id: 529, position: "Defender" },
  { id: 101814, name: "R. Araújo", korean_name: "로날드 아라우호", team_id: 529, position: "Defender" },
  { id: 1323, name: "Dani Olmo", korean_name: "다니 올모", team_id: 529, position: "Midfielder" },
  { id: 538, name: "F. de Jong", korean_name: "프렌키 데 용", team_id: 529, position: "Midfielder" },
  { id: 340626, name: "Fermín", korean_name: "페르민 로페스", team_id: 529, position: "Midfielder" },
  { id: 931, name: "Ferran Torres", korean_name: "페란 토레스", team_id: 529, position: "Midfielder" },
  { id: 296667, name: "Gavi", korean_name: "가비", team_id: 529, position: "Midfielder" },
  { id: 441232, name: "Guille Fernández", korean_name: "기예 페르난데스", team_id: 529, position: "Midfielder" },
  { id: 386828, name: "Lamine Yamal", korean_name: "라민 야말", team_id: 529, position: "Midfielder" },
  { id: 433396, name: "Marc Bernal Casas", korean_name: "마르크 베르날", team_id: 529, position: "Midfielder" },
  { id: 329728, name: "Marc Casadó", korean_name: "마르크 카사도", team_id: 529, position: "Midfielder" },
  { id: 909, name: "M. Rashford", korean_name: "마커스 래시포드", team_id: 529, position: "Midfielder" },
  { id: 133609, name: "Pedri", korean_name: "페드리", team_id: 529, position: "Midfielder" },
  { id: 491087, name: "Pedro Fernández", korean_name: "페드로 페르난데스", team_id: 529, position: "Midfielder" },
  { id: 1496, name: "Raphinha", korean_name: "하피냐", team_id: 529, position: "Midfielder" },
  { id: 521, name: "R. Lewandowski", korean_name: "로베르트 레반도프스키", team_id: 529, position: "Attacker" },
  { id: 338958, name: "Roony Bardghji", korean_name: "루니 바르드지", team_id: 529, position: "Attacker" },
  { id: 445973, name: "Toni Fernández", korean_name: "토니 페르난데스", team_id: 529, position: "Attacker" },
];

// Celta Vigo (Team ID: 538) - 30명
export const CELTA_VIGO_PLAYERS: PlayerMapping[] = [
  { id: 30765, name: "I. Radu", korean_name: "이온 라두", team_id: 538, position: "Goalkeeper" },
  { id: 47427, name: "Iván Villar", korean_name: "이반 비야르", team_id: 538, position: "Goalkeeper" },
  { id: 182730, name: "Marc Vidal", korean_name: "마르크 비달", team_id: 538, position: "Goalkeeper" },
  { id: 286559, name: "Carlos Domínguez", korean_name: "카를로스 도밍게스", team_id: 538, position: "Defender" },
  { id: 47988, name: "C. Starfelt", korean_name: "칼 스타르펠트", team_id: 538, position: "Defender" },
  { id: 1926, name: "J. Aidoo", korean_name: "조셉 아이두", team_id: 538, position: "Defender" },
  { id: 384135, name: "Javi Rodríguez", korean_name: "하비 로드리게스", team_id: 538, position: "Defender" },
  { id: 182638, name: "Manu Fernández", korean_name: "마누 페르난데스", team_id: 538, position: "Defender" },
  { id: 2278, name: "Marcos Alonso", korean_name: "마르코스 알론소", team_id: 538, position: "Defender" },
  { id: 21584, name: "M. Ristić", korean_name: "미하일로 리스티치", team_id: 538, position: "Defender" },
  { id: 329722, name: "Yoel Lago", korean_name: "요엘 라고", team_id: 538, position: "Defender" },
  { id: 286796, name: "Damián Rodríguez", korean_name: "다미안 로드리게스", team_id: 538, position: "Midfielder" },
  { id: 570, name: "F. Cervi", korean_name: "프랑코 세르비", team_id: 538, position: "Midfielder" },
  { id: 47435, name: "Fran Beltrán", korean_name: "프란 벨트란", team_id: 538, position: "Midfielder" },
  { id: 329720, name: "Hugo Álvarez", korean_name: "우고 알바레스", team_id: 538, position: "Midfielder" },
  { id: 313651, name: "Hugo Sotelo", korean_name: "우고 소텔로", team_id: 538, position: "Midfielder" },
  { id: 162123, name: "I. Moriba", korean_name: "일라익스 모리바", team_id: 538, position: "Midfielder" },
  { id: 179955, name: "Javi Rueda", korean_name: "하비 루에다", team_id: 538, position: "Midfielder" },
  { id: 19026, name: "L. de la Torre", korean_name: "란니 데 라 토레", team_id: 538, position: "Midfielder" },
  { id: 333502, name: "Miguel Román", korean_name: "미겔 로만", team_id: 538, position: "Midfielder" },
  { id: 162712, name: "Óscar Mingueza", korean_name: "오스카르 밍게사", team_id: 538, position: "Midfielder" },
  { id: 157988, name: "Sergio Carreira", korean_name: "세르히오 카레이라", team_id: 538, position: "Midfielder" },
  { id: 47348, name: "Borja Iglesias", korean_name: "보르하 이글레시아스", team_id: 538, position: "Attacker" },
  { id: 286639, name: "Bryan Zaragoza", korean_name: "브라얀 사라고사", team_id: 538, position: "Attacker" },
  { id: 122734, name: "Ferran Jutglà", korean_name: "페란 유트글라", team_id: 538, position: "Attacker" },
  { id: 47445, name: "Iago Aspas", korean_name: "이아고 아스파스", team_id: 538, position: "Attacker" },
  { id: 351913, name: "J. El Abdellaoui", korean_name: "자크 엘 압델라우이", team_id: 538, position: "Attacker" },
  { id: 320517, name: "Pablo Durán", korean_name: "파블로 두란", team_id: 538, position: "Attacker" },
  { id: 304383, name: "T. Allende", korean_name: "타소스 알렌데", team_id: 538, position: "Attacker" },
  { id: 269163, name: "W. Swedberg", korean_name: "빌마르 스베드베리", team_id: 538, position: "Attacker" },
];

// Real Madrid (Team ID: 541) - 31명
export const REAL_MADRID_PLAYERS: PlayerMapping[] = [
  { id: 47400, name: "A. Lunin", korean_name: "안드리 루닌", team_id: 541, position: "Goalkeeper" },
  { id: 396475, name: "Francisco Javier González Pérez", korean_name: "프란시스코 곤살레스", team_id: 541, position: "Goalkeeper" },
  { id: 386872, name: "Sergio Mestre Sánchez", korean_name: "세르히오 메스트레", team_id: 541, position: "Goalkeeper" },
  { id: 730, name: "T. Courtois", korean_name: "티보 쿠르투아", team_id: 541, position: "Goalkeeper" },
  { id: 284300, name: "Álvaro Fernández", korean_name: "알바로 페르난데스", team_id: 541, position: "Defender" },
  { id: 2285, name: "A. Rüdiger", korean_name: "안토니오 뤼디거", team_id: 541, position: "Defender" },
  { id: 505, name: "D. Alaba", korean_name: "다비드 알라바", team_id: 541, position: "Defender" },
  { id: 733, name: "Dani Carvajal", korean_name: "다니 카르바할", team_id: 541, position: "Defender" },
  { id: 330436, name: "David Jiménez Corredor", korean_name: "다비드 히메네스", team_id: 541, position: "Defender" },
  { id: 361497, name: "D. Huijsen", korean_name: "딘 하위센", team_id: 541, position: "Defender" },
  { id: 372, name: "Éder Militão", korean_name: "에데르 밀리탕", team_id: 541, position: "Defender" },
  { id: 653, name: "F. Mendy", korean_name: "페를랑 멘디", team_id: 541, position: "Defender" },
  { id: 736, name: "Fran García", korean_name: "프란 가르시아", team_id: 541, position: "Defender" },
  { id: 756, name: "F. Valverde", korean_name: "페데리코 발베르데", team_id: 541, position: "Defender" },
  { id: 341640, name: "Raúl Asencio", korean_name: "라울 아센시오", team_id: 541, position: "Defender" },
  { id: 283, name: "T. Alexander-Arnold", korean_name: "트렌트 알렉산더아놀드", team_id: 541, position: "Defender" },
  { id: 291964, name: "A. Güler", korean_name: "아르다 귈러", team_id: 541, position: "Midfielder" },
  { id: 1271, name: "A. Tchouaméni", korean_name: "오렐리앙 추아메니", team_id: 541, position: "Midfielder" },
  { id: 748, name: "Dani Ceballos", korean_name: "다니 세바요스", team_id: 541, position: "Midfielder" },
  { id: 2207, name: "E. Camavinga", korean_name: "에두아르도 카마빙가", team_id: 541, position: "Midfielder" },
  { id: 449249, name: "Franco Mastantuono", korean_name: "프랑코 마스탄투오노", team_id: 541, position: "Midfielder" },
  { id: 129718, name: "J. Bellingham", korean_name: "주드 벨링엄", team_id: 541, position: "Midfielder" },
  { id: 409218, name: "Roberto MartÃ­n", korean_name: "로베르토 마르틴", team_id: 541, position: "Midfielder" },
  { id: 10009, name: "Rodrygo", korean_name: "호드리구", team_id: 541, position: "Midfielder" },
  { id: 762, name: "Vinícius Júnior", korean_name: "비니시우스 주니어", team_id: 541, position: "Midfielder" },
  { id: 744, name: "Brahim Díaz", korean_name: "브라힘 디아스", team_id: 541, position: "Attacker" },
  { id: 441497, name: "Daniel Yañez", korean_name: "다니엘 야녜스", team_id: 541, position: "Attacker" },
  { id: 377122, name: "Endrick", korean_name: "엔드릭", team_id: 541, position: "Attacker" },
  { id: 336711, name: "Gonzalo García", korean_name: "곤살로 가르시아", team_id: 541, position: "Attacker" },
  { id: 278, name: "Kylian Mbappé", korean_name: "킬리안 음바페", team_id: 541, position: "Attacker" },
  { id: 544044, name: "J. Navarro Jimenez", korean_name: "후안 나바로", team_id: 541, position: undefined },
];

// 라리가 전체 선수 (632명, 20개 팀) - 완성!
export const LALIGA_PLAYERS: PlayerMapping[] = [
  ...ALAVES_PLAYERS,
  ...ATHLETIC_CLUB_PLAYERS,
  ...ATLETICO_MADRID_PLAYERS,
  ...BARCELONA_PLAYERS,
  ...CELTA_VIGO_PLAYERS,
  ...REAL_MADRID_PLAYERS,
  ...LALIGA_PART2_PLAYERS, // 나머지 14개 팀 포함
];
