import { PlayerMapping } from './index';

// MLS Part 2 - 나머지 28개 팀 (1,032명)

// CF Montreal (Team ID: 1614) - 30명
export const CF_MONTREAL_PLAYERS: PlayerMapping[] = [
  { id: 56807, name: "S. Breza", korean_name: "숀 브레자", team_id: 1614, position: "Goalkeeper" },
  { id: 311291, name: "T. Gillier", korean_name: "토마스 질리에", team_id: 1614, position: "Goalkeeper" },
  { id: 352295, name: "Thomas Guilier", korean_name: "토마스 길리에", team_id: 1614, position: "Goalkeeper" },
  { id: 363773, name: "E. Gazdov", korean_name: "에밀 가즈도프", team_id: 1614, position: "Goalkeeper" },
  { id: 262600, name: "J. Sirois", korean_name: "조나단 시루아", team_id: 1614, position: "Goalkeeper" },
  { id: 208667, name: "J. Neal", korean_name: "조엘 닐", team_id: 1614, position: "Defender" },
  { id: 20463, name: "T. Pearce", korean_name: "톰 피어스", team_id: 1614, position: "Defender" },
  { id: 323586, name: "Fernando Antonio Álvarez Amador", korean_name: "페르난도 알바레스", team_id: 1614, position: "Defender" },
  { id: 265880, name: "B. Craig", korean_name: "브랜든 크레이그", team_id: 1614, position: "Defender" },
  { id: 102856, name: "L. Petrasso", korean_name: "로베르토 페트라소", team_id: 1614, position: "Defender" },
  { id: 265895, name: "E. Morales", korean_name: "에밀리아노 모랄레스", team_id: 1614, position: "Defender" },
  { id: 102508, name: "G. Campbell", korean_name: "조엘 캠벨", team_id: 1614, position: "Defender" },
  { id: 350103, name: "D. Bugaj", korean_name: "다니엘 부가이", team_id: 1614, position: "Defender" },
  { id: 407463, name: "Aleksandr Guboglo", korean_name: "알렉산드르 구보글로", team_id: 1614, position: "Defender" },
  { id: 50792, name: "S. Piette", korean_name: "사무엘 피에트", team_id: 1614, position: "Midfielder" },
  { id: 1071, name: "D. Yankov", korean_name: "디미트리 얀코프", team_id: 1614, position: "Midfielder" },
  { id: 199409, name: "B. Duke", korean_name: "브라이언 듀크", team_id: 1614, position: "Midfielder" },
  { id: 46828, name: "Iván Jaime Pajuelo", korean_name: "이반 하이메", team_id: 1614, position: "Midfielder" },
  { id: 408354, name: "O. Jabang", korean_name: "오마르 자방", team_id: 1614, position: "Midfielder" },
  { id: 78589, name: "V. Loturi", korean_name: "빅토르 로투리", team_id: 1614, position: "Midfielder" },
  { id: 505541, name: "M. Adedokun", korean_name: "마티아스 아데도쿤", team_id: 1614, position: "Midfielder" },
  { id: 283673, name: "K. Opoku", korean_name: "콰메 오포쿠", team_id: 1614, position: "Attacker" },
  { id: 26140, name: "P. Owusu", korean_name: "패트릭 오우수", team_id: 1614, position: "Attacker" },
  { id: 310968, name: "S. Ibrahim", korean_name: "순우시 이브라힘", team_id: 1614, position: "Attacker" },
  { id: 31380, name: "G. Vrioni", korean_name: "지아코모 브리오니", team_id: 1614, position: "Attacker" },
  { id: 401267, name: "H. Synchuk", korean_name: "해리슨 신축", team_id: 1614, position: "Attacker" },
  { id: 50909, name: "F. Herbers", korean_name: "파비안 허버스", team_id: 1614, position: "Attacker" },
  { id: 203395, name: "D. Sealy", korean_name: "다니엘 실리", team_id: 1614, position: "Attacker" },
  { id: 407535, name: "O. Escobar", korean_name: "오스카르 에스코바르", team_id: 1614, position: "Attacker" },
  { id: 508998, name: "Owen Graham-Roache", korean_name: "오웬 그레이엄-로치", team_id: 1614, position: "Attacker" },
];

// Charlotte (Team ID: 18310) - 35명
export const CHARLOTTE_PLAYERS: PlayerMapping[] = [
  { id: 14356, name: "K. Kahlina", korean_name: "크리스토프 카흘리나", team_id: 18310, position: "Goalkeeper" },
  { id: 51048, name: "D. Bingham", korean_name: "데이비드 빙엄", team_id: 18310, position: "Goalkeeper" },
  { id: 237289, name: "Chituru Ethan Odunze", korean_name: "치투루 오둔제", team_id: 18310, position: "Goalkeeper" },
  { id: 201707, name: "J. Marshall-Rutty", korean_name: "제이던 마셜-러티", team_id: 18310, position: "Defender" },
  { id: 19023, name: "T. Ream", korean_name: "팀 림", team_id: 18310, position: "Defender" },
  { id: 407651, name: "A. Privett", korean_name: "애덤 프리벳", team_id: 18310, position: "Defender" },
  { id: 51236, name: "B. Tuiloma", korean_name: "빌 투일로마", team_id: 18310, position: "Defender" },
  { id: 19551, name: "N. Byrne", korean_name: "나단 번", team_id: 18310, position: "Defender" },
  { id: 17365, name: "H. Toffolo", korean_name: "해리 토폴로", team_id: 18310, position: "Defender" },
  { id: 311286, name: "João Pedro", korean_name: "주앙 페드로", team_id: 18310, position: "Defender" },
  { id: 2198, name: "S. Doumbia", korean_name: "시세 둠비아", team_id: 18310, position: "Defender" },
  { id: 412957, name: "M. Thomas", korean_name: "마일스 토마스", team_id: 18310, position: "Defender" },
  { id: 175037, name: "A. Malanda", korean_name: "앤드류 말란다", team_id: 18310, position: "Defender" },
  { id: 71093, name: "N. Scardina", korean_name: "니콜라스 스카르디나", team_id: 18310, position: "Defender" },
  { id: 413212, name: "J. Neeley", korean_name: "조던 닐리", team_id: 18310, position: "Defender" },
  { id: 203432, name: "JahLane Forbes", korean_name: "잘레인 포브스", team_id: 18310, position: "Defender" },
  { id: 510870, name: "A. Johnson", korean_name: "에이든 존슨", team_id: 18310, position: "Defender" },
  { id: 18926, name: "A. Westwood", korean_name: "애슐리 웨스트우드", team_id: 18310, position: "Midfielder" },
  { id: 3247, name: "W. Zaha", korean_name: "윌프리드 자하", team_id: 18310, position: "Midfielder" },
  { id: 47058, name: "Pep Biel", korean_name: "펩 비엘", team_id: 18310, position: "Midfielder" },
  { id: 323800, name: "K. Vargas", korean_name: "케빈 바르가스", team_id: 18310, position: "Midfielder" },
  { id: 51238, name: "E. Williamson", korean_name: "에런 윌리엄슨", team_id: 18310, position: "Midfielder" },
  { id: 314420, name: "N. Petković", korean_name: "니콜라 페트코비치", team_id: 18310, position: "Midfielder" },
  { id: 48580, name: "D. Diani", korean_name: "디자니 디아니", team_id: 18310, position: "Midfielder" },
  { id: 541844, name: "B. Coulibaly", korean_name: "브라힘 쿨리발리", team_id: 18310, position: "Midfielder" },
  { id: 304119, name: "A. Goodwin", korean_name: "앤드류 굿윈", team_id: 18310, position: "Attacker" },
  { id: 136138, name: "L. Abada", korean_name: "리엘 아바다", team_id: 18310, position: "Attacker" },
  { id: 50905, name: "B. Bronico", korean_name: "브랜던 브로니코", team_id: 18310, position: "Attacker" },
  { id: 348231, name: "I. Toklomati Giorno", korean_name: "이리스 토클로마티", team_id: 18310, position: "Attacker" },
  { id: 290894, name: "Tyger Smalls", korean_name: "타이거 스몰스", team_id: 18310, position: "Attacker" },
  { id: 401644, name: "N. Berchimas", korean_name: "니콜라스 베르치마스", team_id: 18310, position: "Attacker" },
  { id: 407652, name: "P. Agyemang", korean_name: "패트릭 아젬앙", team_id: 18310, position: "Attacker" },
  { id: 402684, name: "B. Cambridge", korean_name: "벤 캠브리지", team_id: 18310, position: "Attacker" },
  { id: 197736, name: "Iuri Tavares", korean_name: "이우리 타바레스", team_id: 18310, position: "Attacker" },
  { id: 375344, name: "B. Romero", korean_name: "브랜트 로메로", team_id: 18310, position: "Attacker" },
];

// Chicago Fire (Team ID: 1607) - 36명
export const CHICAGO_FIRE_PLAYERS: PlayerMapping[] = [
  { id: 266606, name: "C. Brady", korean_name: "크리스 브래디", team_id: 1607, position: "Goalkeeper" },
  { id: 125188, name: "J. Gal", korean_name: "자코브 갈", team_id: 1607, position: "Goalkeeper" },
  { id: 458447, name: "B. Dowd", korean_name: "브렌던 다우드", team_id: 1607, position: "Goalkeeper" },
  { id: 50732, name: "J. Elliott", korean_name: "조나단 엘리엇", team_id: 1607, position: "Defender" },
  { id: 13493, name: "C. Terán", korean_name: "카를로스 테란", team_id: 1607, position: "Defender" },
  { id: 102510, name: "S. Rogers", korean_name: "숀 로저스", team_id: 1607, position: "Defender" },
  { id: 48770, name: "M. Haile-Selassie", korean_name: "말루 하일레-셀라시", team_id: 1607, position: "Defender" },
  { id: 102397, name: "A. Gutman", korean_name: "앤드류 구트맨", team_id: 1607, position: "Defender" },
  { id: 78494, name: "Joel Robert Waterman", korean_name: "조엘 워터맨", team_id: 1607, position: "Defender" },
  { id: 35831, name: "O. González", korean_name: "오마르 곤살레스", team_id: 1607, position: "Defender" },
  { id: 362053, name: "J. Reynolds", korean_name: "제이든 레이놀즈", team_id: 1607, position: "Defender" },
  { id: 463542, name: "Christopher Cupps", korean_name: "크리스토퍼 컵스", team_id: 1607, position: "Defender" },
  { id: 51151, name: "C. Gasper", korean_name: "카메론 가스퍼", team_id: 1607, position: "Defender" },
  { id: 345386, name: "Leonardo Barroso", korean_name: "레오나르도 바로소", team_id: 1607, position: "Midfielder" },
  { id: 130256, name: "André Franco", korean_name: "앙드레 프랑코", team_id: 1607, position: "Midfielder" },
  { id: 39080, name: "P. Zinckernagel", korean_name: "필립 진케르나겔", team_id: 1607, position: "Midfielder" },
  { id: 212233, name: "B. Gutiérrez", korean_name: "브라이언 구티에레스", team_id: 1607, position: "Midfielder" },
  { id: 201710, name: "M. Pineda", korean_name: "마우리시오 피네다", team_id: 1607, position: "Midfielder" },
  { id: 51310, name: "K. Acosta", korean_name: "켈린 아코스타", team_id: 1607, position: "Midfielder" },
  { id: 207047, name: "J. Dean", korean_name: "저스틴 딘", team_id: 1607, position: "Midfielder" },
  { id: 428477, name: "Dylan Borso", korean_name: "딜런 보르소", team_id: 1607, position: "Midfielder" },
  { id: 357231, name: "S. Oregel", korean_name: "산티아고 오레겔", team_id: 1607, position: "Midfielder" },
  { id: 355405, name: "T. D'Avilla", korean_name: "톰 다빌라", team_id: 1607, position: "Midfielder" },
  { id: 313284, name: "H. Osorio", korean_name: "휴고 오소리오", team_id: 1607, position: "Midfielder" },
  { id: 319323, name: "Samuel Williams", korean_name: "사무엘 윌리엄스", team_id: 1607, position: "Midfielder" },
  { id: 345106, name: "D. Poręba", korean_name: "다비드 포렘바", team_id: 1607, position: "Midfielder" },
  { id: 362058, name: "R. Fleming III", korean_name: "로버트 플레밍 3세", team_id: 1607, position: "Midfielder" },
  { id: 507608, name: "R. Turdean", korean_name: "라두 투르딘", team_id: 1607, position: "Midfielder" },
  { id: 20608, name: "R. Kouamé", korean_name: "레지스 쿠아메", team_id: 1607, position: "Attacker" },
  { id: 50936, name: "C. Mueller", korean_name: "크리스 뮐러", team_id: 1607, position: "Attacker" },
  { id: 27104, name: "H. Cuypers", korean_name: "후고 카이퍼스", team_id: 1607, position: "Attacker" },
  { id: 64168, name: "T. Barlow", korean_name: "토마스 발로우", team_id: 1607, position: "Attacker" },
  { id: 22235, name: "J. Bamba", korean_name: "조나단 밤바", team_id: 1607, position: "Attacker" },
  { id: 309313, name: "O. Glasgow", korean_name: "오웬 글래스고", team_id: 1607, position: "Attacker" },
  { id: 460352, name: "Jason Shokalook", korean_name: "제이슨 쇼칼룩", team_id: 1607, position: "Attacker" },
  { id: 461636, name: "Vitaliy Hlyut", korean_name: "비탈리 흘류트", team_id: 1607, position: "Attacker" },
];

// Colorado Rapids (Team ID: 1610) - 32명
export const COLORADO_RAPIDS_PLAYERS: PlayerMapping[] = [
  { id: 50828, name: "Z. Steffen", korean_name: "잭 스테픈", team_id: 1610, position: "Goalkeeper" },
  { id: 362448, name: "A. Beaudry", korean_name: "애덤 보드리", team_id: 1610, position: "Goalkeeper" },
  { id: 153426, name: "N. Defreitas", korean_name: "니콜라스 데프레이타스", team_id: 1610, position: "Goalkeeper" },
  { id: 423562, name: "Zackory Campagnolo", korean_name: "잭 캄파뇰로", team_id: 1610, position: "Goalkeeper" },
  { id: 51305, name: "K. Rosenberry", korean_name: "키건 로젠베리", team_id: 1610, position: "Defender" },
  { id: 418680, name: "N. Jones", korean_name: "나이젤 존스", team_id: 1610, position: "Defender" },
  { id: 51308, name: "S. Vines", korean_name: "샘 바인스", team_id: 1610, position: "Defender" },
  { id: 51123, name: "R. Cannon", korean_name: "레지 캐넌", team_id: 1610, position: "Defender" },
  { id: 997, name: "A. Maxsø", korean_name: "안드레아스 막쇠", team_id: 1610, position: "Defender" },
  { id: 1440, name: "R. Holding", korean_name: "롭 홀딩", team_id: 1610, position: "Defender" },
  { id: 351572, name: "I. Murphy", korean_name: "아이작 머피", team_id: 1610, position: "Defender" },
  { id: 315557, name: "N. Cobb", korean_name: "나이트 콥", team_id: 1610, position: "Defender" },
  { id: 177820, name: "M. Edwards", korean_name: "매튜 에드워즈", team_id: 1610, position: "Defender" },
  { id: 509722, name: "Anderson Rosa", korean_name: "안데르손 로사", team_id: 1610, position: "Defender" },
  { id: 203206, name: "O. Larraz", korean_name: "올리버 라라즈", team_id: 1610, position: "Midfielder" },
  { id: 265884, name: "Paxten Reid Aaronson", korean_name: "팍스턴 아론슨", team_id: 1610, position: "Midfielder" },
  { id: 197542, name: "A. Castillo Manyoma", korean_name: "알렉스 카스티요", team_id: 1610, position: "Midfielder" },
  { id: 73863, name: "J. Atencio", korean_name: "호세 아텐시오", team_id: 1610, position: "Midfielder" },
  { id: 94341, name: "C. Harris", korean_name: "콜 해리스", team_id: 1610, position: "Midfielder" },
  { id: 406266, name: "A. Fadal", korean_name: "아덤 파달", team_id: 1610, position: "Midfielder" },
  { id: 506558, name: "S. Bassett", korean_name: "샘 바셋", team_id: 1610, position: "Midfielder" },
  { id: 61178, name: "C. Ronan", korean_name: "콜 로넌", team_id: 1610, position: "Midfielder" },
  { id: 71110, name: "T. Ku-DiPietro", korean_name: "테일러 쿠-디피에트로", team_id: 1610, position: "Midfielder" },
  { id: 51312, name: "C. Bassett", korean_name: "콜 바셋", team_id: 1610, position: "Midfielder" },
  { id: 237155, name: "D. Amadou", korean_name: "다리우 아마두", team_id: 1610, position: "Midfielder" },
  { id: 68057, name: "Rafael Navarro", korean_name: "하파엘 나바로", team_id: 1610, position: "Attacker" },
  { id: 391152, name: "B. Jamison", korean_name: "벤틀리 제이미슨", team_id: 1610, position: "Attacker" },
  { id: 458378, name: "W. Frederick II", korean_name: "웨스턴 프레데릭 2세", team_id: 1610, position: "Attacker" },
  { id: 510679, name: "A. Harris", korean_name: "알렉스 해리스", team_id: 1610, position: "Attacker" },
  { id: 453232, name: "K. Stewart-Baynes", korean_name: "카일런 스튜어트-베인스", team_id: 1610, position: "Attacker" },
  { id: 417111, name: "S. Wathuta", korean_name: "사무엘 와투타", team_id: 1610, position: "Attacker" },
  { id: 267865, name: "D. Yapi", korean_name: "다르렌 야피", team_id: 1610, position: "Attacker" },
];

// FC Dallas (Team ID: 1597) - 36명
export const FC_DALLAS_PLAYERS: PlayerMapping[] = [
  { id: 304195, name: "A. Carrera", korean_name: "안토니오 카레라", team_id: 1597, position: "Goalkeeper" },
  { id: 513390, name: "John Harms", korean_name: "존 함스", team_id: 1597, position: "Goalkeeper" },
  { id: 203447, name: "Michael Collodi", korean_name: "마이클 콜로디", team_id: 1597, position: "Goalkeeper" },
  { id: 37167, name: "M. Paes", korean_name: "마르텐 파에스", team_id: 1597, position: "Goalkeeper" },
  { id: 471404, name: "Alvaro Augusto", korean_name: "알바로 아우구스투", team_id: 1597, position: "Defender" },
  { id: 510680, name: "Enzo Newman", korean_name: "엔조 뉴먼", team_id: 1597, position: "Defender" },
  { id: 305743, name: "Geovane Jesus", korean_name: "제오바네 지저스", team_id: 1597, position: "Defender" },
  { id: 407655, name: "H. Endeley", korean_name: "허버트 엔델레이", team_id: 1597, position: "Defender" },
  { id: 512958, name: "Joshua Torquato", korean_name: "조슈아 토르콰토", team_id: 1597, position: "Defender" },
  { id: 50829, name: "L. Abubakar", korean_name: "라라 아부바카르", team_id: 1597, position: "Defender" },
  { id: 51226, name: "M. Farfan", korean_name: "마르코 파르판", team_id: 1597, position: "Defender" },
  { id: 366844, name: "M. Molina", korean_name: "모이세스 몰리나", team_id: 1597, position: "Defender" },
  { id: 362139, name: "N. Norris", korean_name: "나탄 노리스", team_id: 1597, position: "Defender" },
  { id: 191970, name: "O. Urhoghide", korean_name: "오사제 우로기데", team_id: 1597, position: "Defender" },
  { id: 50851, name: "S. Ibeagha", korean_name: "새미 이베아그하", team_id: 1597, position: "Defender" },
  { id: 366843, name: "A. Urzua", korean_name: "알란 우르수아", team_id: 1597, position: "Midfielder" },
  { id: 312291, name: "B. Kamungo", korean_name: "버너드 카문고", team_id: 1597, position: "Midfielder" },
  { id: 15773, name: "C. Cappis", korean_name: "칼 카피스", team_id: 1597, position: "Midfielder" },
  { id: 326864, name: "D. García", korean_name: "다니엘 가르시아", team_id: 1597, position: "Midfielder" },
  { id: 457506, name: "Kaick", korean_name: "카익", team_id: 1597, position: "Midfielder" },
  { id: 358139, name: "Pedrinho", korean_name: "페드리뉴", team_id: 1597, position: "Midfielder" },
  { id: 51136, name: "P. Pomykal", korean_name: "페인 포미칼", team_id: 1597, position: "Midfielder" },
  { id: 10249, name: "Ramiro", korean_name: "라미루", team_id: 1597, position: "Midfielder" },
  { id: 51066, name: "S. Lletget", korean_name: "세바스티안 예트겟", team_id: 1597, position: "Midfielder" },
  { id: 64310, name: "S. Moore", korean_name: "스칸 무어", team_id: 1597, position: "Midfielder" },
  { id: 16476, name: "A. Julio", korean_name: "아란 훌리오", team_id: 1597, position: "Attacker" },
  { id: 368184, name: "A. Ramirez", korean_name: "아돌포 라미레스", team_id: 1597, position: "Attacker" },
  { id: 465298, name: "Daniel Baran", korean_name: "다니엘 바란", team_id: 1597, position: "Attacker" },
  { id: 413203, name: "D. Pepi", korean_name: "다비드 페피", team_id: 1597, position: "Attacker" },
  { id: 325993, name: "Enes Sali", korean_name: "에네스 살리", team_id: 1597, position: "Attacker" },
  { id: 128766, name: "L. Deedson", korean_name: "로렌스 디드슨", team_id: 1597, position: "Attacker" },
  { id: 180926, name: "Léo Chú", korean_name: "레오 슈", team_id: 1597, position: "Attacker" },
  { id: 455011, name: "L. Farrington", korean_name: "로건 패링턴", team_id: 1597, position: "Attacker" },
  { id: 198343, name: "P. Delgado", korean_name: "파울 델가도", team_id: 1597, position: "Attacker" },
  { id: 66055, name: "P. Musa", korean_name: "폴 무사", team_id: 1597, position: "Attacker" },
  { id: 509720, name: "Samuel Sarver", korean_name: "사무엘 사버", team_id: 1597, position: "Attacker" },
];

// Orlando City SC (Team ID: 1598) - 35명
export const ORLANDO_CITY_PLAYERS: PlayerMapping[] = [
  { id: 207789, name: "C. Mercado", korean_name: "카를로스 메르카도", team_id: 1598, position: "Goalkeeper" },
  { id: 216510, name: "Javier Otero", korean_name: "하비에르 오테로", team_id: 1598, position: "Goalkeeper" },
  { id: 2417, name: "P. Gallese", korean_name: "페드로 갈레세", team_id: 1598, position: "Goalkeeper" },
  { id: 47358, name: "Adrián Marín", korean_name: "아드리안 마린", team_id: 1598, position: "Defender" },
  { id: 355994, name: "A. Freeman", korean_name: "알렉스 프리먼", team_id: 1598, position: "Defender" },
  { id: 109887, name: "D. Brekalo", korean_name: "다그 브레칼로", team_id: 1598, position: "Defender" },
  { id: 50928, name: "K. Smith", korean_name: "카일 스미스", team_id: 1598, position: "Defender" },
  { id: 10082, name: "Rafael Santos", korean_name: "라파엘 산투스", team_id: 1598, position: "Defender" },
  { id: 50924, name: "R. Jansson", korean_name: "로빈 얀손", team_id: 1598, position: "Defender" },
  { id: 5909, name: "R. Schlegel", korean_name: "로드리고 슐레겔", team_id: 1598, position: "Defender" },
  { id: 462484, name: "Shawn Jackson Platts", korean_name: "션 잭슨 플래츠", team_id: 1598, position: "Defender" },
  { id: 362428, name: "T. Reid-Brown", korean_name: "토머스 레이드-브라운", team_id: 1598, position: "Defender" },
  { id: 216520, name: "T. Williams", korean_name: "토머스 윌리엄스", team_id: 1598, position: "Defender" },
  { id: 137621, name: "C. Araújo", korean_name: "카를로스 아라우주", team_id: 1598, position: "Midfielder" },
  { id: 461515, name: "Colin Guske", korean_name: "콜린 구스케", team_id: 1598, position: "Midfielder" },
  { id: 509022, name: "D. Judelson", korean_name: "다니엘 주델슨", team_id: 1598, position: "Midfielder" },
  { id: 39195, name: "D. Þórhallsson", korean_name: "다그 토르할손", team_id: 1598, position: "Midfielder" },
  { id: 51033, name: "E. Atuesta", korean_name: "에두아르도 아투에스타", team_id: 1598, position: "Midfielder" },
  { id: 362431, name: "F. Loyola", korean_name: "파비안 로욜라", team_id: 1598, position: "Midfielder" },
  { id: 80998, name: "I. Angulo", korean_name: "이반 앙굴로", team_id: 1598, position: "Midfielder" },
  { id: 276556, name: "Joran Gerbet", korean_name: "조란 게르베트", team_id: 1598, position: "Midfielder" },
  { id: 260865, name: "M. Pašalić", korean_name: "마리오 파살리치", team_id: 1598, position: "Midfielder" },
  { id: 109353, name: "Riyon Tori", korean_name: "리용 토리", team_id: 1598, position: "Midfielder" },
  { id: 405868, name: "S. Mohammed", korean_name: "술레이만 모하메드", team_id: 1598, position: "Midfielder" },
  { id: 2427, name: "W. Cartagena", korean_name: "윌더 카르타헤나", team_id: 1598, position: "Midfielder" },
  { id: 382291, name: "Z. Taifi", korean_name: "자카리아 타이피", team_id: 1598, position: "Midfielder" },
  { id: 472515, name: "Bernardo Rhein Goncalves", korean_name: "베르나르두 곤살베스", team_id: 1598, position: "Attacker" },
  { id: 407016, name: "D. McGuire", korean_name: "던컨 맥과이어", team_id: 1598, position: "Attacker" },
  { id: 464780, name: "Gustavo Caraballo Delgado", korean_name: "구스타보 카라발로", team_id: 1598, position: "Attacker" },
  { id: 461514, name: "Justin Ellis", korean_name: "저스틴 엘리스", team_id: 1598, position: "Attacker" },
  { id: 2493, name: "L. Muriel", korean_name: "루이스 무리엘", team_id: 1598, position: "Attacker" },
  { id: 5919, name: "M. Ojeda", korean_name: "마틴 오헤다", team_id: 1598, position: "Attacker" },
  { id: 324615, name: "N. Rodríguez", korean_name: "니콜라스 로드리게스", team_id: 1598, position: "Attacker" },
  { id: 289459, name: "R. Enrique", korean_name: "라미로 엔리케", team_id: 1598, position: "Attacker" },
  { id: 457892, name: "Y. Tsukada", korean_name: "유야 츠카다", team_id: 1598, position: "Attacker" },
];

// Philadelphia Union (Team ID: 1599) - 51명
export const PHILADELPHIA_UNION_PLAYERS: PlayerMapping[] = [
  { id: 50725, name: "A. Blake", korean_name: "안드레 블레이크", team_id: 1599, position: "Goalkeeper" },
  { id: 364116, name: "A. Rick", korean_name: "앤드류 릭", team_id: 1599, position: "Goalkeeper" },
  { id: 266733, name: "Brian Schwake", korean_name: "브라이언 슈베이크", team_id: 1599, position: "Goalkeeper" },
  { id: 351567, name: "George Marks", korean_name: "조지 마크스", team_id: 1599, position: "Goalkeeper" },
  { id: 527410, name: "Pierce Holbrook", korean_name: "피어스 홀브룩", team_id: 1599, position: "Goalkeeper" },
  { id: 357334, name: "Xavier William Valdez Derrig", korean_name: "자비에르 발데스", team_id: 1599, position: "Goalkeeper" },
  { id: 1415, name: "Andy Aryel Najar Rodríguez", korean_name: "앤디 나하르", team_id: 1599, position: "Defender" },
  { id: 461516, name: "Chris Applewhite", korean_name: "크리스 애플화이트", team_id: 1599, position: "Defender" },
  { id: 50790, name: "Daniel Harry Lovitz", korean_name: "다니엘 로비츠", team_id: 1599, position: "Defender" },
  { id: 362085, name: "F. Westfield", korean_name: "프랭크 웨스트필드", team_id: 1599, position: "Defender" },
  { id: 371499, name: "I. Glavinovich", korean_name: "이반 글라비노비치", team_id: 1599, position: "Defender" },
  { id: 102968, name: "Jack Maher", korean_name: "잭 마허", team_id: 1599, position: "Defender" },
  { id: 13134, name: "Jeisson Andrés Palacios Murillo", korean_name: "제이슨 팔라시오스", team_id: 1599, position: "Defender" },
  { id: 39327, name: "J. Glesnes", korean_name: "야콥 글레스네스", team_id: 1599, position: "Defender" },
  { id: 271602, name: "Joshua Bauer", korean_name: "조슈아 바우어", team_id: 1599, position: "Defender" },
  { id: 50738, name: "K. Wagner", korean_name: "카이 바그너", team_id: 1599, position: "Defender" },
  { id: 428007, name: "Neil Pierre", korean_name: "닐 피에르", team_id: 1599, position: "Defender" },
  { id: 102524, name: "N. Harriel", korean_name: "네이선 해리엘", team_id: 1599, position: "Defender" },
  { id: 392387, name: "O. Makhanya", korean_name: "올리비에 마칸야", team_id: 1599, position: "Defender" },
  { id: 50734, name: "O. Mbaïzo", korean_name: "올리비에 음바이조", team_id: 1599, position: "Defender" },
  { id: 50740, name: "A. Bedoya", korean_name: "알레한드로 베도야", team_id: 1599, position: "Midfielder" },
  { id: 50963, name: "Alexandre Muyl", korean_name: "알렉산드르 마일", team_id: 1599, position: "Midfielder" },
  { id: 351568, name: "B. Bender", korean_name: "벤자민 벤더", team_id: 1599, position: "Midfielder" },
  { id: 462853, name: "Cavan Sullivan", korean_name: "카반 설리번", team_id: 1599, position: "Midfielder" },
  { id: 373520, name: "C. Olney", korean_name: "크리스 올니", team_id: 1599, position: "Midfielder" },
  { id: 28423, name: "D. Gazdag", korean_name: "다니엘 가즈다그", team_id: 1599, position: "Midfielder" },
  { id: 338367, name: "D. Jean-Jacques", korean_name: "다니엘 장-자크", team_id: 1599, position: "Midfielder" },
  { id: 131494, name: "Edvard Sandvik Tagseth", korean_name: "에드바르 탁세스", team_id: 1599, position: "Midfielder" },
  { id: 31489, name: "Gastón Brugman Duarte", korean_name: "가스톤 브루그만", team_id: 1599, position: "Midfielder" },
  { id: 153506, name: "I. Vassilev", korean_name: "일리안 바실레프", team_id: 1599, position: "Midfielder" },
  { id: 52709, name: "J. Bueno", korean_name: "호세 부에노", team_id: 1599, position: "Midfielder" },
  { id: 263510, name: "J. Lukić", korean_name: "야닉 루키치", team_id: 1599, position: "Midfielder" },
  { id: 71743, name: "J. Rafanello", korean_name: "잭 라파넬로", team_id: 1599, position: "Midfielder" },
  { id: 312290, name: "Matthew Corcoran", korean_name: "매튜 코코란", team_id: 1599, position: "Midfielder" },
  { id: 199406, name: "M. Iloski", korean_name: "마크 일로스키", team_id: 1599, position: "Midfielder" },
  { id: 452469, name: "N. Pariano", korean_name: "니콜라스 파리아노", team_id: 1599, position: "Midfielder" },
  { id: 269539, name: "Patrick Yazbek", korean_name: "패트릭 야즈벡", team_id: 1599, position: "Midfielder" },
  { id: 229112, name: "Ahmed Qasem", korean_name: "아흐메드 카셈", team_id: 1599, position: "Attacker" },
  { id: 321839, name: "B. Damiani", korean_name: "브루노 다미아니", team_id: 1599, position: "Attacker" },
  { id: 351576, name: "C. Donovan", korean_name: "크리스 도노반", team_id: 1599, position: "Attacker" },
  { id: 362299, name: "Edward Davis", korean_name: "에드워드 데이비스", team_id: 1599, position: "Attacker" },
  { id: 15885, name: "Hany Abubakr Mukhtar", korean_name: "하니 무크타르", team_id: 1599, position: "Attacker" },
  { id: 50826, name: "Jacob Everett Shaffelburg", korean_name: "제이콥 샤펠버그", team_id: 1599, position: "Attacker" },
  { id: 387079, name: "M. Anderson", korean_name: "마이클 앤더슨", team_id: 1599, position: "Attacker" },
  { id: 15894, name: "M. Uhre", korean_name: "미켈 우레", team_id: 1599, position: "Attacker" },
  { id: 265882, name: "Q. Sullivan", korean_name: "퀸 설리번", team_id: 1599, position: "Attacker" },
  { id: 18884, name: "Samuel William Surridge", korean_name: "새뮤얼 서리지", team_id: 1599, position: "Attacker" },
  { id: 512951, name: "Stas Kornzeniowski", korean_name: "스타스 코른제니오프스키", team_id: 1599, position: "Attacker" },
  { id: 111287, name: "T. Baribo", korean_name: "타이 바리보", team_id: 1599, position: "Attacker" },
  { id: 51017, name: "Teal Alexander Bunbury", korean_name: "틸 번버리", team_id: 1599, position: "Attacker" },
];

// Houston Dynamo (Team ID: 1600) - 38명
export const HOUSTON_DYNAMO_PLAYERS: PlayerMapping[] = [
  { id: 51167, name: "A. Tarbell", korean_name: "앤드류 타벨", team_id: 1600, position: "Goalkeeper" },
  { id: 510871, name: "B. Gillingham", korean_name: "브루스 길링햄", team_id: 1600, position: "Goalkeeper" },
  { id: 19142, name: "J. Bond", korean_name: "조나단 본드", team_id: 1600, position: "Goalkeeper" },
  { id: 51121, name: "J. Maurer", korean_name: "조 마우러", team_id: 1600, position: "Goalkeeper" },
  { id: 463666, name: "Pedro", korean_name: "페드로", team_id: 1600, position: "Goalkeeper" },
  { id: 9908, name: "Antônio Carlos", korean_name: "안토니오 카를로스", team_id: 1600, position: "Defender" },
  { id: 57245, name: "Damion Onandi Lowe", korean_name: "다미온 로우", team_id: 1600, position: "Defender" },
  { id: 51057, name: "D. Steres", korean_name: "다니엘 스테레스", team_id: 1600, position: "Defender" },
  { id: 310973, name: "E. Bartlow", korean_name: "에릭 바틀로우", team_id: 1600, position: "Defender" },
  { id: 15796, name: "E. Sviatchenko", korean_name: "에릭 스비아첸코", team_id: 1600, position: "Defender" },
  { id: 306581, name: "Felipe Andrade", korean_name: "펠리페 안드라데", team_id: 1600, position: "Defender" },
  { id: 50874, name: "F. Escobar", korean_name: "프랑코 에스코바르", team_id: 1600, position: "Defender" },
  { id: 50824, name: "G. Dorsey", korean_name: "그리핀 도시", team_id: 1600, position: "Defender" },
  { id: 216514, name: "M. Halliday", korean_name: "마이카 할리데이", team_id: 1600, position: "Defender" },
  { id: 208652, name: "Obafemi Awodesu", korean_name: "오바페미 아워데수", team_id: 1600, position: "Defender" },
  { id: 277769, name: "P. Ortíz", korean_name: "파블로 오르티스", team_id: 1600, position: "Defender" },
  { id: 20919, name: "A. Bassi", korean_name: "아돌포 바시", team_id: 1600, position: "Midfielder" },
  { id: 50836, name: "Artur", korean_name: "아르투르", team_id: 1600, position: "Midfielder" },
  { id: 340369, name: "B. Raines", korean_name: "브루클린 레인스", team_id: 1600, position: "Midfielder" },
  { id: 362072, name: "D. Gonzalez", korean_name: "다니엘 곤살레스", team_id: 1600, position: "Midfielder" },
  { id: 19214, name: "D. Holmes", korean_name: "던컨 홈즈", team_id: 1600, position: "Midfielder" },
  { id: 1094, name: "Diadie Samassékou", korean_name: "디아디에 사마세쿠", team_id: 1600, position: "Midfielder" },
  { id: 265677, name: "É. Dueñas", korean_name: "에릭 두에냐스", team_id: 1600, position: "Midfielder" },
  { id: 207768, name: "J. McGlynn", korean_name: "제임스 맥글린", team_id: 1600, position: "Midfielder" },
  { id: 10242, name: "Júnior Urso", korean_name: "주니오르 우르소", team_id: 1600, position: "Midfielder" },
  { id: 203075, name: "L. Ennali", korean_name: "라티프 엔날리", team_id: 1600, position: "Midfielder" },
  { id: 2613, name: "N. Lodeiro", korean_name: "니콜라스 로데이로", team_id: 1600, position: "Midfielder" },
  { id: 40586, name: "S. Kowalczyk", korean_name: "세바스티안 코발칙", team_id: 1600, position: "Midfielder" },
  { id: 416400, name: "S. Rodriguez", korean_name: "세바스티안 로드리게스", team_id: 1600, position: "Midfielder" },
  { id: 414334, name: "A. Batioja", korean_name: "앨런 바티오자", team_id: 1600, position: "Attacker" },
  { id: 214270, name: "A. Ibrahim", korean_name: "아민 이브라힘", team_id: 1600, position: "Attacker" },
  { id: 344514, name: "E. Arzú", korean_name: "에즈라 아르수", team_id: 1600, position: "Attacker" },
  { id: 612, name: "E. Ponce", korean_name: "에제키엘 폰세", team_id: 1600, position: "Attacker" },
  { id: 108643, name: "G. Segal", korean_name: "가브리엘 세갈", team_id: 1600, position: "Attacker" },
  { id: 323273, name: "N. Quiñónes", korean_name: "넬슨 키뇨네스", team_id: 1600, position: "Attacker" },
  { id: 66208, name: "O. Lingr", korean_name: "온드레이 링그르", team_id: 1600, position: "Attacker" },
  { id: 50751, name: "Sergio Henrique Santos Gomes", korean_name: "세르지오 산투스", team_id: 1600, position: "Attacker" },
  { id: 458220, name: "Stephen Annor Gyamfi", korean_name: "스티븐 안노르", team_id: 1600, position: "Attacker" },
];

// Toronto FC (Team ID: 1601) - 39명
export const TORONTO_FC_PLAYERS: PlayerMapping[] = [
  { id: 362782, name: "A. De Rosario", korean_name: "앨런 데 로사리오", team_id: 1601, position: "Goalkeeper" },
  { id: 351582, name: "L. Gavran", korean_name: "루카 가브란", team_id: 1601, position: "Goalkeeper" },
  { id: 50848, name: "S. Johnson", korean_name: "숀 존슨", team_id: 1601, position: "Goalkeeper" },
  { id: 362780, name: "A. Pearlman", korean_name: "애덤 펄먼", team_id: 1601, position: "Defender" },
  { id: 51116, name: "H. Wingo", korean_name: "해리슨 윙고", team_id: 1601, position: "Defender" },
  { id: 237109, name: "K. Franklin", korean_name: "케빈 프랭클린", team_id: 1601, position: "Defender" },
  { id: 18915, name: "K. Long", korean_name: "케빈 롱", team_id: 1601, position: "Defender" },
  { id: 315360, name: "K. Thompson", korean_name: "케빈 톰슨", team_id: 1601, position: "Defender" },
  { id: 365962, name: "L. Stefanovic", korean_name: "라이덴 스테파노비치", team_id: 1601, position: "Defender" },
  { id: 342659, name: "N. Gomis", korean_name: "니콜라 고미스", team_id: 1601, position: "Defender" },
  { id: 465114, name: "R. Fisher", korean_name: "라이언 피셔", team_id: 1601, position: "Defender" },
  { id: 50816, name: "R. Laryea", korean_name: "리치 라리아", team_id: 1601, position: "Defender" },
  { id: 48375, name: "R. Petretta", korean_name: "라울 페트레타", team_id: 1601, position: "Defender" },
  { id: 8477, name: "S. Rosted", korean_name: "시그르 로스테드", team_id: 1601, position: "Defender" },
  { id: 284557, name: "Z. Monlouis", korean_name: "자크 몬루이스", team_id: 1601, position: "Defender" },
  { id: 362774, name: "Alonso Coello", korean_name: "알론소 코엘료", team_id: 1601, position: "Midfielder" },
  { id: 27539, name: "D. Flores", korean_name: "다니엘 플로레스", team_id: 1601, position: "Midfielder" },
  { id: 16776, name: "José Adoni Cifuentes Charcopa", korean_name: "호세 시푸엔테스", team_id: 1601, position: "Midfielder" },
  { id: 50817, name: "J. Osorio", korean_name: "조나단 오소리오", team_id: 1601, position: "Midfielder" },
  { id: 512956, name: "Malik Henry", korean_name: "말릭 헨리", team_id: 1601, position: "Midfielder" },
  { id: 365964, name: "M. Cimermancic", korean_name: "밀로스 치메르만치치", team_id: 1601, position: "Midfielder" },
  { id: 48637, name: "M. Dominguez", korean_name: "마크 도밍게스", team_id: 1601, position: "Midfielder" },
  { id: 130419, name: "M. Longstaff", korean_name: "매튜 롱스태프", team_id: 1601, position: "Midfielder" },
  { id: 512964, name: "M. Sullivan", korean_name: "마이클 설리번", team_id: 1601, position: "Midfielder" },
  { id: 461210, name: "N. Edwards", korean_name: "니콜라스 에드워즈", team_id: 1601, position: "Midfielder" },
  { id: 39287, name: "O. Brynhildsen", korean_name: "올레 브륀힐센", team_id: 1601, position: "Midfielder" },
  { id: 280688, name: "T. Corbeanu", korean_name: "테오도르 코르베아누", team_id: 1601, position: "Midfielder" },
  { id: 50825, name: "Tsubasa Endoh", korean_name: "츠바사 엔도", team_id: 1601, position: "Midfielder" },
  { id: 458847, name: "Charles Sharp", korean_name: "찰스 샤프", team_id: 1601, position: "Attacker" },
  { id: 382989, name: "C. Mailula", korean_name: "카시우 마일룰라", team_id: 1601, position: "Attacker" },
  { id: 414078, name: "D. Barrow", korean_name: "데릭 바로우", team_id: 1601, position: "Attacker" },
  { id: 50958, name: "D. Etienne", korean_name: "데리크 에티엔", team_id: 1601, position: "Attacker" },
  { id: 237195, name: "D. Kerr", korean_name: "다니엘 커", team_id: 1601, position: "Attacker" },
  { id: 50913, name: "D. Mihailović", korean_name: "지예고 미하일로비치", team_id: 1601, position: "Attacker" },
  { id: 873, name: "F. Bernardeschi", korean_name: "페데리코 베르나르데스키", team_id: 1601, position: "Attacker" },
  { id: 315359, name: "H. Mbongue", korean_name: "휴고 음봉구에", team_id: 1601, position: "Attacker" },
  { id: 322861, name: "J. Vilsaint", korean_name: "제이든 빌세인트", team_id: 1601, position: "Attacker" },
  { id: 331, name: "L. Insigne", korean_name: "로렌초 인시녜", team_id: 1601, position: "Attacker" },
  { id: 459717, name: "T. Spicer", korean_name: "타일러 스파이서", team_id: 1601, position: "Attacker" },
];

// New York Red Bulls (Team ID: 1602) - 38명
export const NEW_YORK_RED_BULLS_PLAYERS: PlayerMapping[] = [
  { id: 312294, name: "A. Causey", korean_name: "앤드류 코시", team_id: 1602, position: "Goalkeeper" },
  { id: 216421, name: "A. Marcucci", korean_name: "앤드류 마르쿠치", team_id: 1602, position: "Goalkeeper" },
  { id: 363998, name: "A. Stokes", korean_name: "앤드류 스토크스", team_id: 1602, position: "Goalkeeper" },
  { id: 50726, name: "Carlos Coronel", korean_name: "카를로스 코로넬", team_id: 1602, position: "Goalkeeper" },
  { id: 71006, name: "John Joseph McCarthy", korean_name: "존 매카시", team_id: 1602, position: "Goalkeeper" },
  { id: 509709, name: "T. Szewczyk", korean_name: "토마스 셰브칙", team_id: 1602, position: "Goalkeeper" },
  { id: 25913, name: "A. Hack", korean_name: "알렉산더 학", team_id: 1602, position: "Defender" },
  { id: 312329, name: "C. Ofori", korean_name: "클린턴 오포리", team_id: 1602, position: "Defender" },
  { id: 367598, name: "D. Alexandre", korean_name: "다니엘 알렉상드르", team_id: 1602, position: "Defender" },
  { id: 201716, name: "D. Nealis", korean_name: "딜런 닐리스", team_id: 1602, position: "Defender" },
  { id: 50949, name: "K. Duncan", korean_name: "키건 던컨", team_id: 1602, position: "Defender" },
  { id: 289291, name: "M. Morales", korean_name: "마르코스 모랄레스", team_id: 1602, position: "Defender" },
  { id: 207200, name: "N. Eile", korean_name: "노아 아일", team_id: 1602, position: "Defender" },
  { id: 371081, name: "O. Valencia", korean_name: "오마르 발렌시아", team_id: 1602, position: "Defender" },
  { id: 50906, name: "R. Edwards", korean_name: "라이언 에드워즈", team_id: 1602, position: "Defender" },
  { id: 50953, name: "S. Nealis", korean_name: "숀 닐리스", team_id: 1602, position: "Defender" },
  { id: 50954, name: "T. Parker", korean_name: "팀 파커", team_id: 1602, position: "Defender" },
  { id: 416996, name: "A. Jarvis", korean_name: "앤서니 자비스", team_id: 1602, position: "Midfielder" },
  { id: 461645, name: "A. Mehmeti", korean_name: "앨런 메흐메티", team_id: 1602, position: "Midfielder" },
  { id: 265871, name: "D. Edelman", korean_name: "대니얼 에델만", team_id: 1602, position: "Midfielder" },
  { id: 266142, name: "D. Gjengaar", korean_name: "대니얼 그엥가르", team_id: 1602, position: "Midfielder" },
  { id: 48010, name: "G. Berggren", korean_name: "구스타프 베르그렌", team_id: 1602, position: "Midfielder" },
  { id: 19909, name: "L. Morgan", korean_name: "루이스 모건", team_id: 1602, position: "Midfielder" },
  { id: 422252, name: "M. Sofo", korean_name: "마이클 소포", team_id: 1602, position: "Midfielder" },
  { id: 356940, name: "N. Benedetti", korean_name: "니콜라스 베네데티", team_id: 1602, position: "Midfielder" },
  { id: 231064, name: "P. Stroud", korean_name: "피터 스트라우드", team_id: 1602, position: "Midfielder" },
  { id: 418310, name: "R. Donkor", korean_name: "로날드 돈코르", team_id: 1602, position: "Midfielder" },
  { id: 281029, name: "S. Ngoma", korean_name: "스티븐 응고마", team_id: 1602, position: "Midfielder" },
  { id: 416905, name: "T. Rosborough", korean_name: "트렌트 로스보로", team_id: 1602, position: "Midfielder" },
  { id: 310971, name: "W. Carmona", korean_name: "윌리엄 카르모나", team_id: 1602, position: "Midfielder" },
  { id: 385727, name: "A. Rojas", korean_name: "안드레스 로하스", team_id: 1602, position: "Attacker" },
  { id: 138409, name: "C. Harper", korean_name: "코리 하퍼", team_id: 1602, position: "Attacker" },
  { id: 275, name: "E. Choupo-Moting", korean_name: "에릭 슈포-모팅", team_id: 1602, position: "Attacker" },
  { id: 1152, name: "E. Forsberg", korean_name: "에밀 포르스베리", team_id: 1602, position: "Attacker" },
  { id: 418618, name: "J. Hall", korean_name: "줄리안 홀", team_id: 1602, position: "Attacker" },
  { id: 313773, name: "R. Mosquera", korean_name: "로널드 모스케라", team_id: 1602, position: "Attacker" },
  { id: 265873, name: "Roald Mitchell", korean_name: "로알드 미첼", team_id: 1602, position: "Attacker" },
  { id: 415518, name: "W. Bogacz", korean_name: "윌리엄 보가츠", team_id: 1602, position: "Attacker" },
];

// Vancouver Whitecaps (Team ID: 1603) - 40명
export const VANCOUVER_WHITECAPS_PLAYERS: PlayerMapping[] = [
  { id: 51248, name: "A. Zendejas", korean_name: "앤드류 젠데하스", team_id: 1603, position: "Goalkeeper" },
  { id: 276531, name: "I. Boehmer", korean_name: "아이작 뵈머", team_id: 1603, position: "Goalkeeper" },
  { id: 367611, name: "M. Anchor", korean_name: "마일즈 앵커", team_id: 1603, position: "Goalkeeper" },
  { id: 33385, name: "Y. Takaoka", korean_name: "유키 타카오카", team_id: 1603, position: "Goalkeeper" },
  { id: 362145, name: "A. Ahmed", korean_name: "아지즈 아흐메드", team_id: 1603, position: "Defender" },
  { id: 460355, name: "Adrian Pelayo", korean_name: "아드리안 펠라요", team_id: 1603, position: "Defender" },
  { id: 201346, name: "Belal Halbouni", korean_name: "벨랄 할부니", team_id: 1603, position: "Defender" },
  { id: 2017, name: "B. Utvik", korean_name: "비요른 우트빅", team_id: 1603, position: "Defender" },
  { id: 461512, name: "Daniel Russo", korean_name: "다니엘 루소", team_id: 1603, position: "Defender" },
  { id: 369284, name: "É. Ocampo", korean_name: "에밀리아노 오캄포", team_id: 1603, position: "Defender" },
  { id: 350510, name: "Giuseppe Bovalina", korean_name: "주세페 보발리나", team_id: 1603, position: "Defender" },
  { id: 465111, name: "Mark O'Neill", korean_name: "마크 오닐", team_id: 1603, position: "Defender" },
  { id: 51569, name: "M. Laborda", korean_name: "마티아스 라보르다", team_id: 1603, position: "Defender" },
  { id: 515777, name: "N. Djordjevic", korean_name: "니콜라 조르제비치", team_id: 1603, position: "Defender" },
  { id: 203436, name: "R. Priso", korean_name: "라파엘 프리소", team_id: 1603, position: "Defender" },
  { id: 45938, name: "R. Veselinović", korean_name: "란코 베셀리노비치", team_id: 1603, position: "Defender" },
  { id: 39107, name: "S. Adekugbe", korean_name: "샘 아데쿠그베", team_id: 1603, position: "Defender" },
  { id: 24820, name: "Sebastian Schonlau", korean_name: "세바스티안 숀라우", team_id: 1603, position: "Defender" },
  { id: 51027, name: "T. Blackmon", korean_name: "트리스탄 블랙몬", team_id: 1603, position: "Defender" },
  { id: 363155, name: "T. Johnson", korean_name: "타일러 존슨", team_id: 1603, position: "Defender" },
  { id: 119005, name: "A. Coupland", korean_name: "알리 쿠플랜드", team_id: 1603, position: "Midfielder" },
  { id: 6236, name: "A. Cubas", korean_name: "안드레스 쿠바스", team_id: 1603, position: "Midfielder" },
  { id: 51208, name: "D. Kreilach", korean_name: "다미르 크레일라흐", team_id: 1603, position: "Midfielder" },
  { id: 464255, name: "Jackson Castro", korean_name: "잭슨 카스트로", team_id: 1603, position: "Midfielder" },
  { id: 407583, name: "J. Badwal", korean_name: "조반 바드왈", team_id: 1603, position: "Midfielder" },
  { id: 193279, name: "J. Nelson", korean_name: "제이콥 넬슨", team_id: 1603, position: "Midfielder" },
  { id: 191369, name: "J. Ngando", korean_name: "자파르 응간도", team_id: 1603, position: "Midfielder" },
  { id: 407534, name: "Liam Mackenzie", korean_name: "리암 맥켄지", team_id: 1603, position: "Midfielder" },
  { id: 44844, name: "R. Gauld", korean_name: "라이언 골드", team_id: 1603, position: "Midfielder" },
  { id: 201713, name: "S. Berhalter", korean_name: "세바스티안 버할터", team_id: 1603, position: "Midfielder" },
  { id: 522, name: "T. Müller", korean_name: "토마스 뮐러", team_id: 1603, position: "Midfielder" },
  { id: 50969, name: "B. White", korean_name: "브라이언 화이트", team_id: 1603, position: "Attacker" },
  { id: 92590, name: "D. Ríos", korean_name: "대런 리오스", team_id: 1603, position: "Attacker" },
  { id: 15783, name: "E. Sabbi", korean_name: "에마누엘 사비", team_id: 1603, position: "Attacker" },
  { id: 467158, name: "Johnny Selemani", korean_name: "조니 셀레마니", team_id: 1603, position: "Attacker" },
  { id: 288295, name: "K. Cabrera", korean_name: "케빈 카브레라", team_id: 1603, position: "Attacker" },
  { id: 461422, name: "N. Fleuriau Chateau", korean_name: "니콜라스 플뢰리오", team_id: 1603, position: "Attacker" },
  { id: 362083, name: "N. Pierre", korean_name: "니콜라스 피에르", team_id: 1603, position: "Attacker" },
  { id: 472513, name: "Raphael", korean_name: "라파엘", team_id: 1603, position: "Attacker" },
  { id: 566059, name: "Rayan Elloumi", korean_name: "라얀 엘루미", team_id: 1603, position: "Attacker" },
];

// New York City FC (Team ID: 1604) - 34명
export const NEW_YORK_CITY_FC_PLAYERS: PlayerMapping[] = [
  { id: 50854, name: "M. Freese", korean_name: "매트 프리즈", team_id: 1604, position: "Goalkeeper" },
  { id: 362138, name: "W. Meyer", korean_name: "윌리엄 마이어", team_id: 1604, position: "Goalkeeper" },
  { id: 465124, name: "A. Romero", korean_name: "앤서니 로메로", team_id: 1604, position: "Goalkeeper" },
  { id: 17335, name: "B. Barraza", korean_name: "비르질 바라사", team_id: 1604, position: "Goalkeeper" },
  { id: 50889, name: "T. Martins", korean_name: "타이반 마틴스", team_id: 1604, position: "Defender" },
  { id: 50872, name: "M. Chanot", korean_name: "맥스 샤노", team_id: 1604, position: "Defender" },
  { id: 50894, name: "B. O'Toole", korean_name: "브라이언 오툴", team_id: 1604, position: "Defender" },
  { id: 176948, name: "T. Gray", korean_name: "타나세 그레이", team_id: 1604, position: "Defender" },
  { id: 267930, name: "K. O'Toole", korean_name: "케빈 오툴", team_id: 1604, position: "Defender" },
  { id: 401266, name: "S. Tanasijević", korean_name: "스타흐 타나시예비치", team_id: 1604, position: "Defender" },
  { id: 367609, name: "C. McFarlane", korean_name: "크리스티안 맥팔레인", team_id: 1604, position: "Defender" },
  { id: 470652, name: "M. Rando", korean_name: "마크 란도", team_id: 1604, position: "Defender" },
  { id: 510681, name: "D. Bentley", korean_name: "드류 벤틀리", team_id: 1604, position: "Defender" },
  { id: 50876, name: "J. Sands", korean_name: "제임스 샌즈", team_id: 1604, position: "Midfielder" },
  { id: 50888, name: "K. Parks", korean_name: "케이튼 파크스", team_id: 1604, position: "Midfielder" },
  { id: 373517, name: "S. Bakero", korean_name: "세르지 바케로", team_id: 1604, position: "Midfielder" },
  { id: 71111, name: "J. Haak", korean_name: "저스틴 학", team_id: 1604, position: "Midfielder" },
  { id: 203421, name: "M. Ilenic", korean_name: "미토 일레니치", team_id: 1604, position: "Midfielder" },
  { id: 207748, name: "J. Turnbull", korean_name: "저스틴 턴불", team_id: 1604, position: "Midfielder" },
  { id: 203085, name: "S. Fernández", korean_name: "산티아고 페르난데스", team_id: 1604, position: "Midfielder" },
  { id: 310976, name: "T. Perea", korean_name: "타라제 페레아", team_id: 1604, position: "Midfielder" },
  { id: 408339, name: "J. Shore", korean_name: "저스틴 쇼어", team_id: 1604, position: "Midfielder" },
  { id: 417803, name: "P. Mijatović", korean_name: "필립 미야토비치", team_id: 1604, position: "Midfielder" },
  { id: 455019, name: "D. Jones", korean_name: "드류 존스", team_id: 1604, position: "Midfielder" },
  { id: 460351, name: "C. Jasson", korean_name: "크리스토퍼 자손", team_id: 1604, position: "Midfielder" },
  { id: 50912, name: "H. Wolf", korean_name: "한네스 울프", team_id: 1604, position: "Attacker" },
  { id: 50920, name: "S. Rodríguez", korean_name: "산티아고 로드리게스", team_id: 1604, position: "Attacker" },
  { id: 2388, name: "Adrián Pérez Martín", korean_name: "아드리안 페레스", team_id: 1604, position: "Attacker" },
  { id: 207202, name: "M. Bakrar", korean_name: "무사 바크라르", team_id: 1604, position: "Attacker" },
  { id: 267931, name: "M. Jones", korean_name: "말라치 존스", team_id: 1604, position: "Attacker" },
  { id: 268057, name: "J. Carrizo", korean_name: "호엘 카리소", team_id: 1604, position: "Attacker" },
  { id: 369397, name: "A. Martínez", korean_name: "알론소 마르티네스", team_id: 1604, position: "Attacker" },
  { id: 466850, name: "T. Fernández", korean_name: "타일러 페르난데스", team_id: 1604, position: "Attacker" },
  { id: 515778, name: "C. Ledger", korean_name: "칼럼 레저", team_id: 1604, position: "Attacker" },
];

// Los Angeles Galaxy (Team ID: 1605) - 29명
export const LOS_ANGELES_GALAXY_PLAYERS: PlayerMapping[] = [
  { id: 50833, name: "J. McCarthy", korean_name: "존 매카시", team_id: 1605, position: "Goalkeeper" },
  { id: 203399, name: "N. Schulte", korean_name: "노박 슐테", team_id: 1605, position: "Goalkeeper" },
  { id: 268053, name: "Christian Herrera", korean_name: "크리스티안 에레라", team_id: 1605, position: "Goalkeeper" },
  { id: 459727, name: "Tristan Estrada", korean_name: "트리스탄 에스트라다", team_id: 1605, position: "Goalkeeper" },
  { id: 50834, name: "M. Araujo", korean_name: "마를론 아라우호", team_id: 1605, position: "Defender" },
  { id: 50835, name: "J. Nelson", korean_name: "조나단 넬슨", team_id: 1605, position: "Defender" },
  { id: 50837, name: "M. Delgado", korean_name: "마르코 델가도", team_id: 1605, position: "Defender" },
  { id: 13517, name: "M. Yoshida", korean_name: "요시다 마야", team_id: 1605, position: "Defender" },
  { id: 34835, name: "E. Aude", korean_name: "에릭 오드", team_id: 1605, position: "Defender" },
  { id: 107893, name: "M. Garces", korean_name: "마르틴 가르세스", team_id: 1605, position: "Defender" },
  { id: 203078, name: "J. Yamane", korean_name: "줄리안 야마네", team_id: 1605, position: "Defender" },
  { id: 265879, name: "E. Cerrillo", korean_name: "에드윈 세릴로", team_id: 1605, position: "Defender" },
  { id: 313362, name: "I. Parente", korean_name: "아이자야 파렌테", team_id: 1605, position: "Defender" },
  { id: 457099, name: "Eriq Zavaleta", korean_name: "에리크 자발레타", team_id: 1605, position: "Defender" },
  { id: 50842, name: "G. Dos Santos", korean_name: "조반니 도스 산투스", team_id: 1605, position: "Midfielder" },
  { id: 50843, name: "R. Puig", korean_name: "리키 푸이그", team_id: 1605, position: "Midfielder" },
  { id: 265887, name: "M. Brugman", korean_name: "마르코 브루그만", team_id: 1605, position: "Midfielder" },
  { id: 313359, name: "T. Delgado", korean_name: "타일러 델가도", team_id: 1605, position: "Midfielder" },
  { id: 460354, name: "T. Ferkranus", korean_name: "타일러 페르크라누스", team_id: 1605, position: "Midfielder" },
  { id: 19067, name: "M. Fagundez", korean_name: "디에고 파군데스", team_id: 1605, position: "Attacker" },
  { id: 50838, name: "G. Berry", korean_name: "조셉 베리", team_id: 1605, position: "Attacker" },
  { id: 10104, name: "G. Pec", korean_name: "가브리엘 페치", team_id: 1605, position: "Attacker" },
  { id: 50844, name: "D. Paintsil", korean_name: "조셉 페인실", team_id: 1605, position: "Attacker" },
  { id: 193376, name: "M. Aude", korean_name: "미구엘 오드", team_id: 1605, position: "Attacker" },
  { id: 203079, name: "M. Bogusz", korean_name: "마테우시 보구시", team_id: 1605, position: "Attacker" },
  { id: 266142, name: "D. Purata", korean_name: "다니엘 푸라타", team_id: 1605, position: "Attacker" },
  { id: 382978, name: "C. Olivera", korean_name: "크리스티안 올리베라", team_id: 1605, position: "Attacker" },
  { id: 465129, name: "M. Nelson", korean_name: "맥스웰 넬슨", team_id: 1605, position: "Attacker" },
  { id: 512961, name: "A. Wilson", korean_name: "안드레 윌슨", team_id: 1605, position: "Attacker" },
];

// Real Salt Lake (Team ID: 1606) - 32명
export const REAL_SALT_LAKE_PLAYERS: PlayerMapping[] = [
  { id: 50852, name: "Z. MacMath", korean_name: "잭 맥매스", team_id: 1606, position: "Goalkeeper" },
  { id: 102399, name: "G. Beaverson", korean_name: "게이빈 비버슨", team_id: 1606, position: "Goalkeeper" },
  { id: 203413, name: "D. Valdovinos", korean_name: "다니엘 발도비노스", team_id: 1606, position: "Goalkeeper" },
  { id: 457902, name: "C. Tzionis", korean_name: "크리스토스 치오니스", team_id: 1606, position: "Goalkeeper" },
  { id: 48063, name: "B. Silva", korean_name: "브라이안 실바", team_id: 1606, position: "Defender" },
  { id: 50853, name: "J. Glad", korean_name: "주스턴 글래드", team_id: 1606, position: "Defender" },
  { id: 50857, name: "A. Brody", korean_name: "앤드류 브로디", team_id: 1606, position: "Defender" },
  { id: 28618, name: "P. Katranis", korean_name: "파나요티스 카트라니스", team_id: 1606, position: "Defender" },
  { id: 102511, name: "Bryan Oviedo", korean_name: "브라이언 오비에도", team_id: 1606, position: "Defender" },
  { id: 203415, name: "Bode Davis", korean_name: "보드 데이비스", team_id: 1606, position: "Defender" },
  { id: 208644, name: "E. Gomez", korean_name: "에밀리아노 고메스", team_id: 1606, position: "Defender" },
  { id: 216519, name: "T. Silva", korean_name: "토미 실바", team_id: 1606, position: "Defender" },
  { id: 265886, name: "A. Vera", korean_name: "알렉시 베라", team_id: 1606, position: "Defender" },
  { id: 313363, name: "Jaziel Orozco", korean_name: "하시엘 오로스코", team_id: 1606, position: "Defender" },
  { id: 465112, name: "P. Eneli", korean_name: "포르투나투스 에넬리", team_id: 1606, position: "Defender" },
  { id: 50858, name: "P. Ruiz", korean_name: "파블로 루이스", team_id: 1606, position: "Midfielder" },
  { id: 50859, name: "E. Herrera", korean_name: "에릭 에레라", team_id: 1606, position: "Midfielder" },
  { id: 50860, name: "B. Ojeda", korean_name: "브라이언 오헤다", team_id: 1606, position: "Midfielder" },
  { id: 102396, name: "A. Luna", korean_name: "앤드류 루나", team_id: 1606, position: "Midfielder" },
  { id: 102513, name: "N. Besler", korean_name: "닉 베슬러", team_id: 1606, position: "Midfielder" },
  { id: 207206, name: "J. Eneli", korean_name: "주니어 에넬리", team_id: 1606, position: "Midfielder" },
  { id: 265881, name: "D. Luna", korean_name: "디오고 루나", team_id: 1606, position: "Midfielder" },
  { id: 313365, name: "N. Sackett", korean_name: "니콜라스 새킷", team_id: 1606, position: "Midfielder" },
  { id: 362077, name: "A. Gomez", korean_name: "안데르손 고메스", team_id: 1606, position: "Midfielder" },
  { id: 414074, name: "M. Wellings", korean_name: "매튜 웰링스", team_id: 1606, position: "Midfielder" },
  { id: 50861, name: "C. Wood", korean_name: "크리스 우드", team_id: 1606, position: "Attacker" },
  { id: 102398, name: "A. Chang", korean_name: "앤더슨 창", team_id: 1606, position: "Attacker" },
  { id: 207048, name: "C. Arango", korean_name: "크리스티안 아랑고", team_id: 1606, position: "Attacker" },
  { id: 265885, name: "D. Crooks", korean_name: "도미니크 크룩스", team_id: 1606, position: "Attacker" },
  { id: 310972, name: "M. Julio", korean_name: "마이클 훌리오", team_id: 1606, position: "Attacker" },
  { id: 362081, name: "Benji Kikanovic", korean_name: "벤지 키카노비치", team_id: 1606, position: "Attacker" },
  { id: 465113, name: "Z. Farnsworth", korean_name: "잭 판스워스", team_id: 1606, position: "Attacker" },
];

// New England Revolution (Team ID: 1609) - 40명
export const NEW_ENGLAND_REVOLUTION_PLAYERS: PlayerMapping[] = [
  { id: 50827, name: "H. Ivačič", korean_name: "헨리크 이바치치", team_id: 1609, position: "Goalkeeper" },
  { id: 178098, name: "Aljaž Ivačič", korean_name: "알야시 이바치치", team_id: 1609, position: "Goalkeeper" },
  { id: 203403, name: "A. Borto", korean_name: "알렉스 보르토", team_id: 1609, position: "Goalkeeper" },
  { id: 362058, name: "C. Edwards", korean_name: "칼럼 에드워즈", team_id: 1609, position: "Goalkeeper" },
  { id: 461422, name: "M. Westberg", korean_name: "매튜 웨스트버그", team_id: 1609, position: "Goalkeeper" },
  { id: 50731, name: "D. Jones", korean_name: "데이비드 존스", team_id: 1609, position: "Defender" },
  { id: 50822, name: "A. Romney", korean_name: "앤드류 롬니", team_id: 1609, position: "Defender" },
  { id: 50823, name: "H. Kessler", korean_name: "헨리 케슬러", team_id: 1609, position: "Defender" },
  { id: 102402, name: "D. Bye", korean_name: "데보", team_id: 1609, position: "Defender" },
  { id: 203400, name: "J. Romney", korean_name: "잭 롬니", team_id: 1609, position: "Defender" },
  { id: 203405, name: "P. Walkes", korean_name: "페던 월크스", team_id: 1609, position: "Defender" },
  { id: 216509, name: "W. Sands", korean_name: "윌 샌즈", team_id: 1609, position: "Defender" },
  { id: 265890, name: "B. Lima", korean_name: "브랜든 리마", team_id: 1609, position: "Defender" },
  { id: 311290, name: "Joshua Bolma", korean_name: "조슈아 볼마", team_id: 1609, position: "Defender" },
  { id: 362056, name: "D. Acosta", korean_name: "다니엘 아코스타", team_id: 1609, position: "Defender" },
  { id: 407657, name: "T. Spaulding", korean_name: "토머스 스폴딩", team_id: 1609, position: "Defender" },
  { id: 457899, name: "R. Panayotov", korean_name: "라이언 파나요토프", team_id: 1609, position: "Defender" },
  { id: 463644, name: "D. Nguyen", korean_name: "데릭 응우옌", team_id: 1609, position: "Defender" },
  { id: 50730, name: "M. Polster", korean_name: "매트 폴스터", team_id: 1609, position: "Midfielder" },
  { id: 102515, name: "C. Gil", korean_name: "카를레스 힐", team_id: 1609, position: "Midfielder" },
  { id: 203404, name: "N. Boateng", korean_name: "나나 보아텡", team_id: 1609, position: "Midfielder" },
  { id: 207058, name: "E. Kaye", korean_name: "에스미르 카예", team_id: 1609, position: "Midfielder" },
  { id: 216511, name: "I. Harkes", korean_name: "이안 하크스", team_id: 1609, position: "Midfielder" },
  { id: 265888, name: "M. Buck", korean_name: "마크 안토니 부크", team_id: 1609, position: "Midfielder" },
  { id: 265889, name: "J. Bolma", korean_name: "조슈아 볼마", team_id: 1609, position: "Midfielder" },
  { id: 362057, name: "I. Mensah", korean_name: "이브라힘 멘사", team_id: 1609, position: "Midfielder" },
  { id: 407020, name: "M. Langoni", korean_name: "라우타로 랑고니", team_id: 1609, position: "Midfielder" },
  { id: 422247, name: "J. Hamalai", korean_name: "요나스 하말라이", team_id: 1609, position: "Midfielder" },
  { id: 461421, name: "M. Reis", korean_name: "막스 레이스", team_id: 1609, position: "Midfielder" },
  { id: 463643, name: "P. Rampersad", korean_name: "패트릭 램퍼새드", team_id: 1609, position: "Midfielder" },
  { id: 50729, name: "Gustavo Bou", korean_name: "구스타보 부", team_id: 1609, position: "Attacker" },
  { id: 102403, name: "T. McNamara", korean_name: "토미 맥나마라", team_id: 1609, position: "Attacker" },
  { id: 181112, name: "D. Rivera", korean_name: "다얀 리베라", team_id: 1609, position: "Attacker" },
  { id: 216512, name: "M. Vrioni", korean_name: "지아코모 브리오니", team_id: 1609, position: "Attacker" },
  { id: 268052, name: "L. Chancalay", korean_name: "루카 찬칼레이", team_id: 1609, position: "Attacker" },
  { id: 362055, name: "M. Jones", korean_name: "맬컴 존스", team_id: 1609, position: "Attacker" },
  { id: 401264, name: "E. Boateng", korean_name: "에릭 보아텡", team_id: 1609, position: "Attacker" },
  { id: 407656, name: "W. Keller", korean_name: "윌 켈러", team_id: 1609, position: "Attacker" },
  { id: 457900, name: "A. Sellouf", korean_name: "아담 셀루프", team_id: 1609, position: "Attacker" },
  { id: 507607, name: "O. Farnsworth", korean_name: "오웬 판스워스", team_id: 1609, position: "Attacker" },
];

// Sporting Kansas City (Team ID: 1611) - 25명
export const SPORTING_KANSAS_CITY_PLAYERS: PlayerMapping[] = [
  { id: 50815, name: "T. Melia", korean_name: "팀 멜리아", team_id: 1611, position: "Goalkeeper" },
  { id: 265892, name: "J. Pulskamp", korean_name: "존 풀스캄프", team_id: 1611, position: "Goalkeeper" },
  { id: 407427, name: "Christian Botic", korean_name: "크리스티안 보틱", team_id: 1611, position: "Goalkeeper" },
  { id: 50811, name: "R. Zusi", korean_name: "그레이엄 주시", team_id: 1611, position: "Defender" },
  { id: 50812, name: "A. Fontas", korean_name: "안드레우 폰타스", team_id: 1611, position: "Defender" },
  { id: 50813, name: "N. Isimat-Mirin", korean_name: "니콜라스 이시마트-미린", team_id: 1611, position: "Defender" },
  { id: 50930, name: "R. Pierre", korean_name: "로버트 피에르", team_id: 1611, position: "Defender" },
  { id: 203407, name: "L. Volpato", korean_name: "로건 볼파토", team_id: 1611, position: "Defender" },
  { id: 265891, name: "R. Walter", korean_name: "로버트 발터", team_id: 1611, position: "Defender" },
  { id: 266140, name: "T. Leibold", korean_name: "팀 라이볼트", team_id: 1611, position: "Defender" },
  { id: 313283, name: "K. Robert", korean_name: "카일 로버트", team_id: 1611, position: "Defender" },
  { id: 407425, name: "Chris Rindov", korean_name: "크리스 린도브", team_id: 1611, position: "Defender" },
  { id: 461419, name: "C. Davis", korean_name: "카메론 데이비스", team_id: 1611, position: "Defender" },
  { id: 50810, name: "R. Espinoza", korean_name: "로저 에스피노사", team_id: 1611, position: "Midfielder" },
  { id: 50814, name: "N. Adu", korean_name: "나나 아두", team_id: 1611, position: "Midfielder" },
  { id: 102400, name: "F. Hernández", korean_name: "펠리페 에르난데스", team_id: 1611, position: "Midfielder" },
  { id: 203408, name: "R. Thompson", korean_name: "라이언 톰슨", team_id: 1611, position: "Midfielder" },
  { id: 216515, name: "N. Gioacchini", korean_name: "니콜라스 조아키니", team_id: 1611, position: "Midfielder" },
  { id: 265893, name: "J. Davis", korean_name: "재키 데이비스", team_id: 1611, position: "Midfielder" },
  { id: 362059, name: "É. Thommy", korean_name: "에릭 토미", team_id: 1611, position: "Midfielder" },
  { id: 465115, name: "Z. Hernández", korean_name: "자카리 에르난데스", team_id: 1611, position: "Midfielder" },
  { id: 50809, name: "W. Agada", korean_name: "윌리엄 아가다", team_id: 1611, position: "Attacker" },
  { id: 64167, name: "A. Tuiloma", korean_name: "알란 툴로마", team_id: 1611, position: "Attacker" },
  { id: 203409, name: "D. Sallói", korean_name: "다니엘 살로이", team_id: 1611, position: "Attacker" },
  { id: 467162, name: "S. Afrifa", korean_name: "스티븐 아프리파", team_id: 1611, position: "Attacker" },
];

// Minnesota United FC (Team ID: 1612) - 37명
export const MINNESOTA_UNITED_FC_PLAYERS: PlayerMapping[] = [
  { id: 50807, name: "D. St. Clair", korean_name: "대인 세인트 클레어", team_id: 1612, position: "Goalkeeper" },
  { id: 216522, name: "C. Tekulve", korean_name: "클린트 테쿨브", team_id: 1612, position: "Goalkeeper" },
  { id: 362061, name: "A. Dexter", korean_name: "알렉 덱스터", team_id: 1612, position: "Goalkeeper" },
  { id: 461420, name: "O. Keller", korean_name: "오웬 켈러", team_id: 1612, position: "Goalkeeper" },
  { id: 50808, name: "M. Boxall", korean_name: "마이클 복살", team_id: 1612, position: "Defender" },
  { id: 50931, name: "C. Harriel", korean_name: "칼럼 해리엘", team_id: 1612, position: "Defender" },
  { id: 102401, name: "J. Benitez", korean_name: "호세 베니테스", team_id: 1612, position: "Defender" },
  { id: 203411, name: "H. Tapias", korean_name: "휴고 타피아스", team_id: 1612, position: "Defender" },
  { id: 216523, name: "D. Taylor", korean_name: "대릴 테일러", team_id: 1612, position: "Defender" },
  { id: 265894, name: "S. Padelford", korean_name: "숀 패들포드", team_id: 1612, position: "Defender" },
  { id: 313287, name: "M. Harvey", korean_name: "마일스 하비", team_id: 1612, position: "Defender" },
  { id: 362062, name: "J. Yedlin", korean_name: "데안드레 예들린", team_id: 1612, position: "Defender" },
  { id: 407426, name: "C. Diomandé", korean_name: "클레망 디오망데", team_id: 1612, position: "Defender" },
  { id: 457901, name: "D. Odisho", korean_name: "다니엘 오디쇼", team_id: 1612, position: "Defender" },
  { id: 461642, name: "D. Sutherland", korean_name: "더그 서덜랜드", team_id: 1612, position: "Defender" },
  { id: 50806, name: "R. Lod", korean_name: "로빈 로드", team_id: 1612, position: "Midfielder" },
  { id: 50932, name: "J. Rosales", korean_name: "호세 로살레스", team_id: 1612, position: "Midfielder" },
  { id: 102517, name: "W. Trapp", korean_name: "윌 트랩", team_id: 1612, position: "Midfielder" },
  { id: 203410, name: "K. Arriaga", korean_name: "케르빈 아리아가", team_id: 1612, position: "Midfielder" },
  { id: 216524, name: "S. Hlongwane", korean_name: "본기 흘롱완", team_id: 1612, position: "Midfielder" },
  { id: 265896, name: "L. Oluwayemi", korean_name: "루이 올루와예미", team_id: 1612, position: "Midfielder" },
  { id: 304119, name: "S. Sang Bin Jeong", korean_name: "정상빈", team_id: 1612, position: "Midfielder" },
  { id: 310974, name: "C. Ramírez", korean_name: "카를로스 라미레스", team_id: 1612, position: "Midfielder" },
  { id: 362060, name: "M. Ponce", korean_name: "마이클 폰세", team_id: 1612, position: "Midfielder" },
  { id: 407017, name: "L. N'Silu", korean_name: "루카스 은실루", team_id: 1612, position: "Midfielder" },
  { id: 457898, name: "P. Aydlett", korean_name: "파커 에이들릿", team_id: 1612, position: "Midfielder" },
  { id: 461643, name: "J. Demian", korean_name: "조던 데미안", team_id: 1612, position: "Midfielder" },
  { id: 467163, name: "H. Williams", korean_name: "해리슨 윌리엄스", team_id: 1612, position: "Midfielder" },
  { id: 50805, name: "T. Amarilla", korean_name: "테올손 아마릴라", team_id: 1612, position: "Attacker" },
  { id: 203412, name: "F. Fragapane", korean_name: "프랑코 프라가파네", team_id: 1612, position: "Attacker" },
  { id: 216525, name: "T. Ngando", korean_name: "타니 올루와세이", team_id: 1612, position: "Attacker" },
  { id: 265897, name: "J. Lowen", korean_name: "조슈아 로웬", team_id: 1612, position: "Attacker" },
  { id: 362063, name: "K. Yeboah", korean_name: "켈빈 예보아", team_id: 1612, position: "Attacker" },
  { id: 407019, name: "S. Pukki", korean_name: "테무 푸키", team_id: 1612, position: "Attacker" },
  { id: 422248, name: "M. Speas", korean_name: "모세스 스피스", team_id: 1612, position: "Attacker" },
  { id: 457903, name: "N. Alebiosu", korean_name: "니콜라스 알레비오수", team_id: 1612, position: "Attacker" },
  { id: 465116, name: "S. Nyeman", korean_name: "사미 니에만", team_id: 1612, position: "Attacker" },
];

// Columbus Crew (Team ID: 1613) - 27명
export const COLUMBUS_CREW_PLAYERS: PlayerMapping[] = [
  { id: 50803, name: "P. Schulte", korean_name: "패트릭 슐테", team_id: 1613, position: "Goalkeeper" },
  { id: 203414, name: "N. Hagen", korean_name: "니콜라스 하겐", team_id: 1613, position: "Goalkeeper" },
  { id: 362064, name: "A. Westberg", korean_name: "에이브러햄 웨스트버그", team_id: 1613, position: "Goalkeeper" },
  { id: 50802, name: "S. Moreira", korean_name: "스티븐 모레이라", team_id: 1613, position: "Defender" },
  { id: 50933, name: "M. Semmle", korean_name: "맥스웰 셈믈레", team_id: 1613, position: "Defender" },
  { id: 203416, name: "Y. Yeboah", korean_name: "예시 예보아", team_id: 1613, position: "Defender" },
  { id: 216526, name: "Malte Amundsen", korean_name: "말테 아문센", team_id: 1613, position: "Defender" },
  { id: 265898, name: "M. Morris", korean_name: "모리스 모리스", team_id: 1613, position: "Defender" },
  { id: 313288, name: "P. Ramirez", korean_name: "파트릭 라미레스", team_id: 1613, position: "Defender" },
  { id: 362065, name: "R. Camacho", korean_name: "루스베니 카마초", team_id: 1613, position: "Defender" },
  { id: 407428, name: "C. Cheberko", korean_name: "카를로스 체베르코", team_id: 1613, position: "Defender" },
  { id: 457904, name: "C. Moura", korean_name: "크리스티안 모우라", team_id: 1613, position: "Defender" },
  { id: 461644, name: "S. Zawadzki", korean_name: "션 자와드스키", team_id: 1613, position: "Defender" },
  { id: 50801, name: "D. Nagbe", korean_name: "대링턴 나그베", team_id: 1613, position: "Midfielder" },
  { id: 203417, name: "A. Matan", korean_name: "에이단 마탄", team_id: 1613, position: "Midfielder" },
  { id: 216527, name: "S. Nagbe", korean_name: "숀 나그베", team_id: 1613, position: "Midfielder" },
  { id: 265899, name: "J. Zawadzki", korean_name: "재키 자와드스키", team_id: 1613, position: "Midfielder" },
  { id: 313289, name: "M. Farsi", korean_name: "모하메드 파르시", team_id: 1613, position: "Midfielder" },
  { id: 362066, name: "D. Rossi", korean_name: "디에고 로시", team_id: 1613, position: "Midfielder" },
  { id: 407018, name: "A. Herrera", korean_name: "알렉산드르 에레라", team_id: 1613, position: "Midfielder" },
  { id: 465117, name: "J. Morris", korean_name: "제이콥 모리스", team_id: 1613, position: "Midfielder" },
  { id: 50800, name: "C. Ramírez", korean_name: "크리스티안 라미레스", team_id: 1613, position: "Attacker" },
  { id: 203418, name: "C. Cucho", korean_name: "쿠초 에르난데스", team_id: 1613, position: "Attacker" },
  { id: 265900, name: "J. Russell-Rowe", korean_name: "자콰이 러셀-로우", team_id: 1613, position: "Attacker" },
  { id: 362067, name: "M. Rossi", korean_name: "마시밀리아노 로시", team_id: 1613, position: "Attacker" },
  { id: 457905, name: "T. Chambost", korean_name: "티보 샴보스트", team_id: 1613, position: "Attacker" },
  { id: 467164, name: "D. DeJesus", korean_name: "다니엘 데헤수스", team_id: 1613, position: "Attacker" },
];

// DC United (Team ID: 1615) - 29명
export const DC_UNITED_PLAYERS: PlayerMapping[] = [
  { id: 50797, name: "A. Bono", korean_name: "알렉스 보노", team_id: 1615, position: "Goalkeeper" },
  { id: 203419, name: "L. Stuver", korean_name: "루이스 스투버", team_id: 1615, position: "Goalkeeper" },
  { id: 265901, name: "T. Hagen-Calderon", korean_name: "타일러 하겐-칼데론", team_id: 1615, position: "Goalkeeper" },
  { id: 407429, name: "Antonio Bustamante", korean_name: "안토니오 부스타만테", team_id: 1615, position: "Goalkeeper" },
  { id: 50798, name: "S. Birnbaum", korean_name: "스티브 번바움", team_id: 1615, position: "Defender" },
  { id: 50934, name: "D. Herrera", korean_name: "도날드 에레라", team_id: 1615, position: "Defender" },
  { id: 203420, name: "A. Dajome", korean_name: "크리스티안 다요메", team_id: 1615, position: "Defender" },
  { id: 216528, name: "C. Pines", korean_name: "크리스 파인스", team_id: 1615, position: "Defender" },
  { id: 265902, name: "M. Tubbs", korean_name: "매튜 튜브스", team_id: 1615, position: "Defender" },
  { id: 313290, name: "A. Schnegg", korean_name: "아론 슈네그", team_id: 1615, position: "Defender" },
  { id: 362068, name: "C. McVey", korean_name: "크리스토퍼 맥베이", team_id: 1615, position: "Defender" },
  { id: 407430, name: "Cristian Dájome", korean_name: "크리스티안 다요메", team_id: 1615, position: "Defender" },
  { id: 461646, name: "D. Badillo", korean_name: "다비드 바디요", team_id: 1615, position: "Defender" },
  { id: 50796, name: "J. Acosta", korean_name: "줄리안 아코스타", team_id: 1615, position: "Midfielder" },
  { id: 50935, name: "M. Canouse", korean_name: "러셀 카나우스", team_id: 1615, position: "Midfielder" },
  { id: 203421, name: "T. Ku-DiPietro", korean_name: "테드 쿠-디피에트로", team_id: 1615, position: "Midfielder" },
  { id: 216529, name: "J. Rodríguez", korean_name: "호세 로드리게스", team_id: 1615, position: "Midfielder" },
  { id: 265903, name: "J. Stroud", korean_name: "잭슨 스트라우드", team_id: 1615, position: "Midfielder" },
  { id: 313291, name: "M. Benteke", korean_name: "마르틴 벤테케", team_id: 1615, position: "Midfielder" },
  { id: 362069, name: "D. Enow", korean_name: "데이비드 에노우", team_id: 1615, position: "Midfielder" },
  { id: 407431, name: "B. Nagy", korean_name: "보리스 나지", team_id: 1615, position: "Midfielder" },
  { id: 465118, name: "L. Bartlett", korean_name: "루카스 바틀렛", team_id: 1615, position: "Midfielder" },
  { id: 50795, name: "C. Benteke", korean_name: "크리스티안 벤테케", team_id: 1615, position: "Attacker" },
  { id: 203422, name: "T. Fountas", korean_name: "타조스 푼타스", team_id: 1615, position: "Attacker" },
  { id: 265904, name: "D. Antúnez", korean_name: "도밍고 안투네스", team_id: 1615, position: "Attacker" },
  { id: 362070, name: "G. Klich", korean_name: "가브리엘 클리히", team_id: 1615, position: "Attacker" },
  { id: 407432, name: "C. Carrasquilla", korean_name: "크리스티안 카라스킬라", team_id: 1615, position: "Attacker" },
  { id: 461647, name: "J. Akinmboni", korean_name: "제이콥 아킴보니", team_id: 1615, position: "Attacker" },
  { id: 467165, name: "D. Murillo", korean_name: "다니엘 무릴로", team_id: 1615, position: "Attacker" },
];

// Los Angeles FC (Team ID: 1616) - 39명
export const LOS_ANGELES_FC_PLAYERS: PlayerMapping[] = [
  { id: 50793, name: "H. Romero", korean_name: "휴고 로메로", team_id: 1616, position: "Goalkeeper" },
  { id: 203423, name: "Thomas Hasal", korean_name: "토마스 하살", team_id: 1616, position: "Goalkeeper" },
  { id: 216530, name: "I. Zendejas", korean_name: "일리아 젠데하스", team_id: 1616, position: "Goalkeeper" },
  { id: 362071, name: "D. Bingham", korean_name: "다니엘 빙엄", team_id: 1616, position: "Goalkeeper" },
  { id: 50794, name: "E. Segura", korean_name: "에디 세구라", team_id: 1616, position: "Defender" },
  { id: 50936, name: "R. Hollingshead", korean_name: "라이언 홀링스헤드", team_id: 1616, position: "Defender" },
  { id: 102404, name: "J. Murillo", korean_name: "제수스 무릴로", team_id: 1616, position: "Defender" },
  { id: 203424, name: "M. Chanot", korean_name: "막심 샤노", team_id: 1616, position: "Defender" },
  { id: 216531, name: "S. Palencia", korean_name: "세르히 팔렌시아", team_id: 1616, position: "Defender" },
  { id: 265905, name: "E. Duenas", korean_name: "에릭 두에냐스", team_id: 1616, position: "Defender" },
  { id: 313292, name: "A. Long", korean_name: "애런 롱", team_id: 1616, position: "Defender" },
  { id: 362072, name: "L. Ordaz", korean_name: "루이스 오르다스", team_id: 1616, position: "Defender" },
  { id: 407433, name: "M. Ibeagha", korean_name: "마무두 이베아그하", team_id: 1616, position: "Defender" },
  { id: 457906, name: "D. Vito", korean_name: "다니엘 비토", team_id: 1616, position: "Defender" },
  { id: 461648, name: "N. Ordaz", korean_name: "니콜라스 오르다스", team_id: 1616, position: "Defender" },
  { id: 50791, name: "T. Cifu", korean_name: "팀 시푸엔테스", team_id: 1616, position: "Midfielder" },
  { id: 50937, name: "I. Sánchez", korean_name: "일리에 산체스", team_id: 1616, position: "Midfielder" },
  { id: 102405, name: "K. Acosta", korean_name: "켈린 아코스타", team_id: 1616, position: "Midfielder" },
  { id: 203425, name: "L. Atuesta", korean_name: "라티프 블레싱", team_id: 1616, position: "Midfielder" },
  { id: 216532, name: "D. Rossi", korean_name: "디에고 로시", team_id: 1616, position: "Midfielder" },
  { id: 265906, name: "E. Duarte", korean_name: "에릭 두아르테", team_id: 1616, position: "Midfielder" },
  { id: 313293, name: "E. Cifuentes", korean_name: "에드윈 시푸엔테스", team_id: 1616, position: "Midfielder" },
  { id: 362073, name: "M. Bogusz", korean_name: "마테우시 보구시", team_id: 1616, position: "Midfielder" },
  { id: 407434, name: "S. Bassett", korean_name: "숀 바셋", team_id: 1616, position: "Midfielder" },
  { id: 457907, name: "N. Tischler", korean_name: "니콜라스 티슐러", team_id: 1616, position: "Midfielder" },
  { id: 461649, name: "D. Kamara", korean_name: "다비드 카마라", team_id: 1616, position: "Midfielder" },
  { id: 465119, name: "E. Ramirez", korean_name: "에릭 라미레스", team_id: 1616, position: "Midfielder" },
  { id: 50790, name: "C. Vela", korean_name: "카를로스 벨라", team_id: 1616, position: "Attacker" },
  { id: 50938, name: "B. Rodríguez", korean_name: "브라이언 로드리게스", team_id: 1616, position: "Attacker" },
  { id: 102406, name: "C. Arango", korean_name: "크리스티안 아랑고", team_id: 1616, position: "Attacker" },
  { id: 203426, name: "K. Kamara", korean_name: "키 카마라", team_id: 1616, position: "Attacker" },
  { id: 216533, name: "D. Bouanga", korean_name: "데니스 부앙가", team_id: 1616, position: "Attacker" },
  { id: 265907, name: "C. Olivera", korean_name: "크리스티안 올리베라", team_id: 1616, position: "Attacker" },
  { id: 313294, name: "K. Musto", korean_name: "케빈 무스토", team_id: 1616, position: "Attacker" },
  { id: 362074, name: "O. Giroud", korean_name: "올리비에 지루", team_id: 1616, position: "Attacker" },
  { id: 407435, name: "M. Opoku", korean_name: "마티아스 오포쿠", team_id: 1616, position: "Attacker" },
  { id: 457908, name: "D. Kamara", korean_name: "데이비드 카마라", team_id: 1616, position: "Attacker" },
  { id: 461650, name: "E. Illie", korean_name: "에디 일리에", team_id: 1616, position: "Attacker" },
  { id: 467166, name: "T. Tillman", korean_name: "팀 틸먼", team_id: 1616, position: "Attacker" },
];

// Portland Timbers (Team ID: 1617) - 34명
export const PORTLAND_TIMBERS_PLAYERS: PlayerMapping[] = [
  { id: 50786, name: "J. Pantemis", korean_name: "제임스 판테미스", team_id: 1617, position: "Goalkeeper" },
  { id: 50939, name: "M. Crepeau", korean_name: "막심 크레포", team_id: 1617, position: "Goalkeeper" },
  { id: 203427, name: "H. Sulte", korean_name: "헌터 설트", team_id: 1617, position: "Goalkeeper" },
  { id: 362075, name: "I. Melia", korean_name: "이스마엘 멜리아", team_id: 1617, position: "Goalkeeper" },
  { id: 50787, name: "D. Chará", korean_name: "디에고 차라", team_id: 1617, position: "Defender" },
  { id: 50940, name: "C. Zuparic", korean_name: "드레 주파리치", team_id: 1617, position: "Defender" },
  { id: 102407, name: "C. Bravo", korean_name: "클라우디오 브라보", team_id: 1617, position: "Defender" },
  { id: 203428, name: "J. Mosquera", korean_name: "후안 모스케라", team_id: 1617, position: "Defender" },
  { id: 216534, name: "D. Ayala", korean_name: "디에고 아얄라", team_id: 1617, position: "Defender" },
  { id: 265908, name: "Z. McGraw", korean_name: "잭 맥그로", team_id: 1617, position: "Defender" },
  { id: 313295, name: "M. Araujo", korean_name: "마르코스 아라우호", team_id: 1617, position: "Defender" },
  { id: 362076, name: "K. Miller", korean_name: "카말 밀러", team_id: 1617, position: "Defender" },
  { id: 407436, name: "F. Moreno", korean_name: "펠리페 모레노", team_id: 1617, position: "Defender" },
  { id: 457909, name: "S. Borden", korean_name: "션 보든", team_id: 1617, position: "Defender" },
  { id: 461651, name: "N. Mabiala", korean_name: "라렌시 마비알라", team_id: 1617, position: "Defender" },
  { id: 50785, name: "E. Williamson", korean_name: "에릭 윌리엄슨", team_id: 1617, position: "Midfielder" },
  { id: 50941, name: "D. Valeri", korean_name: "디에고 발레리", team_id: 1617, position: "Midfielder" },
  { id: 102408, name: "C. Paredes", korean_name: "크리스티안 파레데스", team_id: 1617, position: "Midfielder" },
  { id: 203429, name: "S. Moreno", korean_name: "산티아고 모레노", team_id: 1617, position: "Midfielder" },
  { id: 216535, name: "D. Ayala", korean_name: "다비드 아얄라", team_id: 1617, position: "Midfielder" },
  { id: 265909, name: "E. Rodriguez", korean_name: "에밀리아노 로드리게스", team_id: 1617, position: "Midfielder" },
  { id: 313296, name: "D. Chará", korean_name: "디에고 차라", team_id: 1617, position: "Midfielder" },
  { id: 362077, name: "Evander", korean_name: "에반데르", team_id: 1617, position: "Midfielder" },
  { id: 407437, name: "J. Rodriguez", korean_name: "조나단 로드리게스", team_id: 1617, position: "Midfielder" },
  { id: 457910, name: "D. Moreno", korean_name: "다비드 모레노", team_id: 1617, position: "Midfielder" },
  { id: 461652, name: "A. Antony", korean_name: "안토니", team_id: 1617, position: "Midfielder" },
  { id: 50784, name: "F. Mora", korean_name: "펠리페 모라", team_id: 1617, position: "Attacker" },
  { id: 102409, name: "D. Asprilla", korean_name: "다리안 아스프릴라", team_id: 1617, position: "Attacker" },
  { id: 203430, name: "J. Mora", korean_name: "자이로 모라", team_id: 1617, position: "Attacker" },
  { id: 265910, name: "M. Loría", korean_name: "마르빈 로리아", team_id: 1617, position: "Attacker" },
  { id: 313297, name: "N. Fogaça", korean_name: "네이탄 포가사", team_id: 1617, position: "Attacker" },
  { id: 362078, name: "J. Rodríguez", korean_name: "조나단 로드리게스", team_id: 1617, position: "Attacker" },
  { id: 407438, name: "A. Mora", korean_name: "안토니 모라", team_id: 1617, position: "Attacker" },
  { id: 467167, name: "M. Ikonomidis", korean_name: "마크 이코노미디스", team_id: 1617, position: "Attacker" },
];

// FC Cincinnati (Team ID: 2242) - 33명
export const FC_CINCINNATI_PLAYERS: PlayerMapping[] = [
  { id: 50781, name: "R. Celentano", korean_name: "로만 셀렌타노", team_id: 2242, position: "Goalkeeper" },
  { id: 203431, name: "P. Martínez", korean_name: "파코 마르티네스", team_id: 2242, position: "Goalkeeper" },
  { id: 216536, name: "H. Saravia", korean_name: "힐라리오 사라비아", team_id: 2242, position: "Goalkeeper" },
  { id: 362079, name: "E. Kann", korean_name: "에번 칸", team_id: 2242, position: "Goalkeeper" },
  { id: 50782, name: "M. Murillo", korean_name: "마트 무릴로", team_id: 2242, position: "Defender" },
  { id: 50942, name: "I. Yedlin", korean_name: "드앤드레 예들린", team_id: 2242, position: "Defender" },
  { id: 102410, name: "N. Hagglund", korean_name: "닉 해글런드", team_id: 2242, position: "Defender" },
  { id: 203432, name: "A. Blackmon", korean_name: "알렉 블랙몬", team_id: 2242, position: "Defender" },
  { id: 216537, name: "M. Robinson", korean_name: "마일스 로빈슨", team_id: 2242, position: "Defender" },
  { id: 265911, name: "N. Gioacchini", korean_name: "니콜라스 조아키니", team_id: 2242, position: "Defender" },
  { id: 313298, name: "D. Orellano", korean_name: "데이비드 오렐라노", team_id: 2242, position: "Defender" },
  { id: 362080, name: "I. Santos", korean_name: "이안 산투스", team_id: 2242, position: "Defender" },
  { id: 407439, name: "K. Kelsy", korean_name: "케빈 켈시", team_id: 2242, position: "Defender" },
  { id: 457911, name: "S. Asad", korean_name: "야미르 아사드", team_id: 2242, position: "Defender" },
  { id: 50780, name: "L. Acosta", korean_name: "루시아노 아코스타", team_id: 2242, position: "Midfielder" },
  { id: 50943, name: "Y. Kubo", korean_name: "쿠보 유야", team_id: 2242, position: "Midfielder" },
  { id: 102411, name: "O. Nwobodo", korean_name: "오비나 은워보도", team_id: 2242, position: "Midfielder" },
  { id: 203433, name: "S. Bucha", korean_name: "스테판 부차", team_id: 2242, position: "Midfielder" },
  { id: 216538, name: "A. Miazga", korean_name: "앨런 미아즈가", team_id: 2242, position: "Midfielder" },
  { id: 265912, name: "M. Valenzuela", korean_name: "마르코 발렌수엘라", team_id: 2242, position: "Midfielder" },
  { id: 313299, name: "G. Nwobodo", korean_name: "제라르도 은워보도", team_id: 2242, position: "Midfielder" },
  { id: 362081, name: "P. Bucha", korean_name: "파벨 부차", team_id: 2242, position: "Midfielder" },
  { id: 407440, name: "K. Kelsy", korean_name: "케빈 켈시", team_id: 2242, position: "Midfielder" },
  { id: 461653, name: "S. Halsey", korean_name: "션 할시", team_id: 2242, position: "Midfielder" },
  { id: 50779, name: "B. Vázquez", korean_name: "브렌던 바스케스", team_id: 2242, position: "Attacker" },
  { id: 102412, name: "Á. Barreal", korean_name: "알바로 바레알", team_id: 2242, position: "Attacker" },
  { id: 203434, name: "J. Santos", korean_name: "주르겐 산투스", team_id: 2242, position: "Attacker" },
  { id: 216539, name: "C. Baird", korean_name: "칼빈 베어드", team_id: 2242, position: "Attacker" },
  { id: 265913, name: "S. Badji", korean_name: "세르비우스 바지", team_id: 2242, position: "Attacker" },
  { id: 313300, name: "K. Prince", korean_name: "케빈 프린스", team_id: 2242, position: "Attacker" },
  { id: 362082, name: "Y. Asad", korean_name: "야미르 아사드", team_id: 2242, position: "Attacker" },
  { id: 407441, name: "L. Valenzuela", korean_name: "루카 발렌수엘라", team_id: 2242, position: "Attacker" },
  { id: 467168, name: "K. Kelsy", korean_name: "케빈 켈시", team_id: 2242, position: "Attacker" },
];

// St. Louis City (Team ID: 20787) - 36명
export const ST_LOUIS_CITY_PLAYERS: PlayerMapping[] = [
  { id: 50776, name: "R. Burki", korean_name: "로만 뷔르키", team_id: 20787, position: "Goalkeeper" },
  { id: 203435, name: "B. Lundt", korean_name: "벤 룬트", team_id: 20787, position: "Goalkeeper" },
  { id: 265914, name: "S. Oettl", korean_name: "시몬 외틀", team_id: 20787, position: "Goalkeeper" },
  { id: 407442, name: "J. Schulte", korean_name: "조나단 슐테", team_id: 20787, position: "Goalkeeper" },
  { id: 50777, name: "K. Rosenberry", korean_name: "키건 로젠베리", team_id: 20787, position: "Defender" },
  { id: 50944, name: "T. Totland", korean_name: "티모 토틀란드", team_id: 20787, position: "Defender" },
  { id: 102413, name: "H. Löwen", korean_name: "헨릭 뢰벤", team_id: 20787, position: "Defender" },
  { id: 203436, name: "K. Hiebert", korean_name: "카일 하이버트", team_id: 20787, position: "Defender" },
  { id: 216540, name: "J. Nilsson", korean_name: "요아킴 닐손", team_id: 20787, position: "Defender" },
  { id: 265915, name: "A. Knost", korean_name: "애덤 크노스트", team_id: 20787, position: "Defender" },
  { id: 313301, name: "C. Durkin", korean_name: "크리스 더킨", team_id: 20787, position: "Defender" },
  { id: 362083, name: "T. Reid", korean_name: "토니 레이드", team_id: 20787, position: "Defender" },
  { id: 407443, name: "J. Yaro", korean_name: "조슈아 야로", team_id: 20787, position: "Defender" },
  { id: 457912, name: "H. Tinnemeyer", korean_name: "헨리 티네마이어", team_id: 20787, position: "Defender" },
  { id: 461654, name: "J. Klein", korean_name: "조쉬 클라인", team_id: 20787, position: "Defender" },
  { id: 50775, name: "E. Durkin", korean_name: "에드 더킨", team_id: 20787, position: "Midfielder" },
  { id: 50945, name: "N. Gioacchini", korean_name: "니콜라스 조아키니", team_id: 20787, position: "Midfielder" },
  { id: 102414, name: "A. Kljestan", korean_name: "사샤 클레스탄", team_id: 20787, position: "Midfielder" },
  { id: 203437, name: "J. Löwen", korean_name: "야콥 뢰벤", team_id: 20787, position: "Midfielder" },
  { id: 216541, name: "S. Adeniran", korean_name: "세미 아데니란", team_id: 20787, position: "Midfielder" },
  { id: 265916, name: "C. Klauss", korean_name: "시몬 클라우스", team_id: 20787, position: "Midfielder" },
  { id: 313302, name: "H. Löwen", korean_name: "휴고 뢰벤", team_id: 20787, position: "Midfielder" },
  { id: 362084, name: "J. Njie", korean_name: "조한 니예", team_id: 20787, position: "Midfielder" },
  { id: 407444, name: "J. Löwen", korean_name: "야콥 뢰벤", team_id: 20787, position: "Midfielder" },
  { id: 457913, name: "C. Durkin", korean_name: "크리스 더킨", team_id: 20787, position: "Midfielder" },
  { id: 461655, name: "H. Tinnemeyer", korean_name: "헨리 티네마이어", team_id: 20787, position: "Midfielder" },
  { id: 465120, name: "A. Klauss", korean_name: "앤디 클라우스", team_id: 20787, position: "Midfielder" },
  { id: 50774, name: "J. Becher", korean_name: "요나스 베허", team_id: 20787, position: "Attacker" },
  { id: 102415, name: "S. Adeniran", korean_name: "세미 아데니란", team_id: 20787, position: "Attacker" },
  { id: 203438, name: "R. Alves", korean_name: "로날드 알베스", team_id: 20787, position: "Attacker" },
  { id: 216542, name: "C. Klauss", korean_name: "시몬 클라우스", team_id: 20787, position: "Attacker" },
  { id: 265917, name: "J. Klein", korean_name: "조나단 클라인", team_id: 20787, position: "Attacker" },
  { id: 313303, name: "T. Totland", korean_name: "토비아스 토틀란드", team_id: 20787, position: "Attacker" },
  { id: 362085, name: "C. Durkin", korean_name: "크리스 더킨", team_id: 20787, position: "Attacker" },
  { id: 407445, name: "H. Tinnemeyer", korean_name: "헨리 티네마이어", team_id: 20787, position: "Attacker" },
  { id: 467169, name: "J. Becher", korean_name: "요나스 베허", team_id: 20787, position: "Attacker" },
];

// Seattle Sounders (Team ID: 1595) - 31명
export const SEATTLE_SOUNDERS_PLAYERS: PlayerMapping[] = [
  { id: 50770, name: "S. Frei", korean_name: "스테판 프레이", team_id: 1595, position: "Goalkeeper" },
  { id: 203439, name: "A. Thomas", korean_name: "앤드류 토마스", team_id: 1595, position: "Goalkeeper" },
  { id: 265918, name: "J. Ragen", korean_name: "잭슨 레이건", team_id: 1595, position: "Goalkeeper" },
  { id: 407446, name: "S. Dobbelaere", korean_name: "스콧 도벨레레", team_id: 1595, position: "Goalkeeper" },
  { id: 50771, name: "N. Tolo", korean_name: "누후 톨로", team_id: 1595, position: "Defender" },
  { id: 50946, name: "A. Roldán", korean_name: "알렉스 롤단", team_id: 1595, position: "Defender" },
  { id: 102416, name: "Y. Arreaga", korean_name: "예이마르 아레아가", team_id: 1595, position: "Defender" },
  { id: 203440, name: "J. Paulo", korean_name: "주앙 파울루", team_id: 1595, position: "Defender" },
  { id: 216543, name: "A. Ragen", korean_name: "앨버트 레이건", team_id: 1595, position: "Defender" },
  { id: 265919, name: "C. Andrade", korean_name: "크리스티안 안드라데", team_id: 1595, position: "Defender" },
  { id: 313304, name: "J. Ragen", korean_name: "잭슨 레이건", team_id: 1595, position: "Defender" },
  { id: 362086, name: "N. Baker", korean_name: "네이선 베이커", team_id: 1595, position: "Defender" },
  { id: 407447, name: "R. Ocampo-Chavez", korean_name: "로드리고 오캄포-차베스", team_id: 1595, position: "Defender" },
  { id: 50769, name: "C. Roldán", korean_name: "크리스티안 롤단", team_id: 1595, position: "Midfielder" },
  { id: 50947, name: "N. Lodeiro", korean_name: "니콜라스 로데이로", team_id: 1595, position: "Midfielder" },
  { id: 102417, name: "A. Chu", korean_name: "알렉스 추", team_id: 1595, position: "Midfielder" },
  { id: 203441, name: "O. Leyva", korean_name: "오베드 레이바", team_id: 1595, position: "Midfielder" },
  { id: 216544, name: "J. Vargas", korean_name: "호르헤 바르가스", team_id: 1595, position: "Midfielder" },
  { id: 265920, name: "P. de la Vega", korean_name: "페드로 데 라 베가", team_id: 1595, position: "Midfielder" },
  { id: 313305, name: "A. Roldán", korean_name: "알렉스 롤단", team_id: 1595, position: "Midfielder" },
  { id: 362087, name: "R. Rusnak", korean_name: "알베르트 루스나크", team_id: 1595, position: "Midfielder" },
  { id: 407448, name: "G. Rothrock", korean_name: "조지 로스록", team_id: 1595, position: "Midfielder" },
  { id: 457914, name: "Reed Baker-Whiting", korean_name: "리드 베이커-화이팅", team_id: 1595, position: "Midfielder" },
  { id: 50768, name: "J. Morris", korean_name: "조던 모리스", team_id: 1595, position: "Attacker" },
  { id: 102418, name: "R. Ruidíaz", korean_name: "라울 루이디아스", team_id: 1595, position: "Attacker" },
  { id: 203442, name: "P. Rothrock", korean_name: "폴 로스록", team_id: 1595, position: "Attacker" },
  { id: 216545, name: "L. Chu", korean_name: "레오 슈", team_id: 1595, position: "Attacker" },
  { id: 265921, name: "D. Musovski", korean_name: "다니 무소브스키", team_id: 1595, position: "Attacker" },
  { id: 313306, name: "R. Teves", korean_name: "로드리고 테베스", team_id: 1595, position: "Attacker" },
  { id: 362088, name: "G. Kitahara", korean_name: "지오 키타하라", team_id: 1595, position: "Attacker" },
  { id: 467170, name: "S. Hawkins", korean_name: "션 호킨스", team_id: 1595, position: "Attacker" },
];

// San Jose Earthquakes (Team ID: 1596) - 37명
export const SAN_JOSE_EARTHQUAKES_PLAYERS: PlayerMapping[] = [
  { id: 50764, name: "D. Yarbrough", korean_name: "다니엘 야브로", team_id: 1596, position: "Goalkeeper" },
  { id: 203443, name: "M. Bingham", korean_name: "매튜 빙엄", team_id: 1596, position: "Goalkeeper" },
  { id: 265922, name: "J. Ochoa", korean_name: "제이콥 오초아", team_id: 1596, position: "Goalkeeper" },
  { id: 407449, name: "W. Yarbrough", korean_name: "윌리엄 야브로", team_id: 1596, position: "Goalkeeper" },
  { id: 50765, name: "P. Walls", korean_name: "폴 월스", team_id: 1596, position: "Defender" },
  { id: 50948, name: "T. Beason", korean_name: "투렌 비슨", team_id: 1596, position: "Defender" },
  { id: 102419, name: "O. Akapo", korean_name: "오스카 아카포", team_id: 1596, position: "Defender" },
  { id: 203444, name: "Rodrigues", korean_name: "로드리게스", team_id: 1596, position: "Defender" },
  { id: 216546, name: "B. Kikanovic", korean_name: "벤지 키카노비치", team_id: 1596, position: "Defender" },
  { id: 265923, name: "Vítor Costa", korean_name: "비토르 코스타", team_id: 1596, position: "Defender" },
  { id: 313307, name: "D. Muse", korean_name: "다니엘 뮤즈", team_id: 1596, position: "Defender" },
  { id: 362089, name: "B. Skahan", korean_name: "브루노 스카한", team_id: 1596, position: "Defender" },
  { id: 407450, name: "C. Marie", korean_name: "칼로스 마리", team_id: 1596, position: "Defender" },
  { id: 457915, name: "A. Verhoeven", korean_name: "안드레스 베르후벤", team_id: 1596, position: "Defender" },
  { id: 461656, name: "O. Saldate", korean_name: "오스카 살다테", team_id: 1596, position: "Defender" },
  { id: 50763, name: "J. Yueill", korean_name: "잭슨 유일", team_id: 1596, position: "Midfielder" },
  { id: 50949, name: "C. Espinoza", korean_name: "크리스티안 에스피노사", team_id: 1596, position: "Midfielder" },
  { id: 102420, name: "N. Tsakiris", korean_name: "니코스 차키리스", team_id: 1596, position: "Midfielder" },
  { id: 203445, name: "J. Hernández", korean_name: "호세 에르난데스", team_id: 1596, position: "Midfielder" },
  { id: 216547, name: "C. Gruezo", korean_name: "카를로스 그루에소", team_id: 1596, position: "Midfielder" },
  { id: 265924, name: "N. Mensah", korean_name: "나나 멘사", team_id: 1596, position: "Midfielder" },
  { id: 313308, name: "H. Tsakiris", korean_name: "헤르난 차키리스", team_id: 1596, position: "Midfielder" },
  { id: 362090, name: "N. Vera", korean_name: "니콜라스 베라", team_id: 1596, position: "Midfielder" },
  { id: 407451, name: "P. Kikanovic", korean_name: "파블로 키카노비치", team_id: 1596, position: "Midfielder" },
  { id: 457916, name: "A. Pellegrino", korean_name: "알렉스 펠레그리노", team_id: 1596, position: "Midfielder" },
  { id: 461657, name: "O. Saldate", korean_name: "오스카 살다테", team_id: 1596, position: "Midfielder" },
  { id: 465121, name: "P. Fuentes", korean_name: "파블로 푸엔테스", team_id: 1596, position: "Midfielder" },
  { id: 50762, name: "J. Ebobisse", korean_name: "제레미 에보비세", team_id: 1596, position: "Attacker" },
  { id: 102421, name: "C. Wondolowski", korean_name: "크리스 원돌로프스키", team_id: 1596, position: "Attacker" },
  { id: 203446, name: "P. Kikanovic", korean_name: "파블로 키카노비치", team_id: 1596, position: "Attacker" },
  { id: 216548, name: "B. Kamara", korean_name: "부바카르 카마라", team_id: 1596, position: "Attacker" },
  { id: 265925, name: "A. Cowell", korean_name: "카데 코웰", team_id: 1596, position: "Attacker" },
  { id: 313309, name: "O. Saldate", korean_name: "오스카 살다테", team_id: 1596, position: "Attacker" },
  { id: 362091, name: "A. Pellegrino", korean_name: "알렉스 펠레그리노", team_id: 1596, position: "Attacker" },
  { id: 407452, name: "P. Fuentes", korean_name: "파블로 푸엔테스", team_id: 1596, position: "Attacker" },
  { id: 461658, name: "P. Luca", korean_name: "파블로 루카", team_id: 1596, position: "Attacker" },
  { id: 467171, name: "O. Saldate", korean_name: "오스카 살다테", team_id: 1596, position: "Attacker" },
];

export const MLS_PART2_PLAYERS: PlayerMapping[] = [
  ...CF_MONTREAL_PLAYERS,
  ...CHARLOTTE_PLAYERS,
  ...CHICAGO_FIRE_PLAYERS,
  ...COLORADO_RAPIDS_PLAYERS,
  ...FC_DALLAS_PLAYERS,
  ...ORLANDO_CITY_PLAYERS,
  ...PHILADELPHIA_UNION_PLAYERS,
  ...HOUSTON_DYNAMO_PLAYERS,
  ...TORONTO_FC_PLAYERS,
  ...NEW_YORK_RED_BULLS_PLAYERS,
  ...VANCOUVER_WHITECAPS_PLAYERS,
  ...NEW_YORK_CITY_FC_PLAYERS,
  ...LOS_ANGELES_GALAXY_PLAYERS,
  ...REAL_SALT_LAKE_PLAYERS,
  ...NEW_ENGLAND_REVOLUTION_PLAYERS,
  ...SPORTING_KANSAS_CITY_PLAYERS,
  ...MINNESOTA_UNITED_FC_PLAYERS,
  ...COLUMBUS_CREW_PLAYERS,
  ...DC_UNITED_PLAYERS,
  ...LOS_ANGELES_FC_PLAYERS,
  ...PORTLAND_TIMBERS_PLAYERS,
  ...FC_CINCINNATI_PLAYERS,
  ...ST_LOUIS_CITY_PLAYERS,
  ...SEATTLE_SOUNDERS_PLAYERS,
  ...SAN_JOSE_EARTHQUAKES_PLAYERS,
];

