import { PlayerMapping } from './index';

// AC Milan (Team ID: 489) - 31명
export const AC_MILAN_PLAYERS: PlayerMapping[] = [
  { id: 386298, name: "L. Torriani", korean_name: "로렌초 토리아니", team_id: 489, position: "Goalkeeper" },
  { id: 22221, name: "M. Maignan", korean_name: "미케 메냥", team_id: 489, position: "Goalkeeper" },
  { id: 484293, name: "M. Pittarella", korean_name: "마르코 피타렐라", team_id: 489, position: "Goalkeeper" },
  { id: 30394, name: "P. Terracciano", korean_name: "피에트로 테라치아노", team_id: 489, position: "Goalkeeper" },
  { id: 330437, name: "Álex Jiménez", korean_name: "알렉스 히메네스", team_id: 489, position: "Defender" },
  { id: 394740, name: "D. Odogu", korean_name: "다비드 오도구", team_id: 489, position: "Defender" },
  { id: 19209, name: "F. Tomori", korean_name: "피키요 토모리", team_id: 489, position: "Defender" },
  { id: 162141, name: "K. De Winter", korean_name: "카이 데 빈터", team_id: 489, position: "Defender" },
  { id: 56473, name: "M. Gabbia", korean_name: "마테오 가비아", team_id: 489, position: "Defender" },
  { id: 45826, name: "S. Pavlović", korean_name: "스트라히냐 파블로비치", team_id: 489, position: "Defender" },
  { id: 396380, name: "Z. Athekame", korean_name: "지다네 아테카메", team_id: 489, position: "Defender" },
  { id: 264705, name: "A. Jashari", korean_name: "알톤 야샤리", team_id: 489, position: "Midfielder" },
  { id: 272, name: "A. Rabiot", korean_name: "아드리앙 라비오", team_id: 489, position: "Midfielder" },
  { id: 1417, name: "A. Saelemaekers", korean_name: "알렉시스 살레마커르스", team_id: 489, position: "Midfielder" },
  { id: 374359, name: "D. Bartesaghi", korean_name: "다비데 바르테사기", team_id: 489, position: "Midfielder" },
  { id: 3173, name: "I. Bennacer", korean_name: "이스마엘 벤나세르", team_id: 489, position: "Midfielder" },
  { id: 754, name: "L. Modrić", korean_name: "루카 모드리치", team_id: 489, position: "Midfielder" },
  { id: 46731, name: "P. Estupiñán", korean_name: "페르비스 에스투피냔", team_id: 489, position: "Midfielder" },
  { id: 2292, name: "R. Loftus-Cheek", korean_name: "루벤 로프터스-칙", team_id: 489, position: "Midfielder" },
  { id: 31056, name: "S. Ricci", korean_name: "사무엘레 리치", team_id: 489, position: "Midfielder" },
  { id: 1265, name: "Y. Adli", korean_name: "야신 아들리", team_id: 489, position: "Midfielder" },
  { id: 22254, name: "Y. Fofana", korean_name: "유수프 포파나", team_id: 489, position: "Midfielder" },
  { id: 530000, name: "C. Balentien", korean_name: "크리스티앙 발렌티엔", team_id: 489, position: "Attacker" },
  { id: 269, name: "C. Nkunku", korean_name: "크리스토퍼 은쿤쿠", team_id: 489, position: "Attacker" },
  { id: 17, name: "C. Pulišić", korean_name: "크리스티안 풀리시치", team_id: 489, position: "Attacker" },
  { id: 336928, name: "Manuel Valletta", korean_name: "마누엘 발레타", team_id: 489, position: "Attacker" },
  { id: 22236, name: "Rafael Leão", korean_name: "하파엘 레앙", team_id: 489, position: "Attacker" },
  { id: 1696, name: "S. Chukwueze", korean_name: "사무엘 추크우에제", team_id: 489, position: "Attacker" },
  { id: 94562, name: "S. Giménez", korean_name: "산티아고 히메네스", team_id: 489, position: "Attacker" },
  { id: 528408, name: "C. Balentien", korean_name: "크리스티앙 발렌티엔", team_id: 489, position: null },
  { id: 495478, name: "Alessio Marcaccini", korean_name: "알레시오 마르카치니", team_id: 489, position: null },
];

// AS Roma (Team ID: 497) - 34명
export const AS_ROMA_PLAYERS: PlayerMapping[] = [
  { id: 495478, name: "Alessio Marcaccini", korean_name: "알레시오 마르카치니", team_id: 497, position: "Goalkeeper" },
  { id: 81012, name: "D. Vásquez", korean_name: "다비드 바스케스", team_id: 497, position: "Goalkeeper" },
  { id: 483676, name: "Giorgio De Marzi", korean_name: "조르조 데 마르치", team_id: 497, position: "Goalkeeper" },
  { id: 556, name: "M. Svilar", korean_name: "밀레 스빌라르", team_id: 497, position: "Goalkeeper" },
  { id: 30418, name: "P. Gollini", korean_name: "피에를루이지 골리니", team_id: 497, position: "Goalkeeper" },
  { id: 452423, name: "R. Żelezny", korean_name: "랄프 젤레즈니", team_id: 497, position: "Goalkeeper" },
  { id: 227, name: "Angeliño", korean_name: "안헬리뇨", team_id: 497, position: "Defender" },
  { id: 162451, name: "A. Salah-Eddine", korean_name: "안와르 살라에딘", team_id: 497, position: "Defender" },
  { id: 446067, name: "Buba Sangaré", korean_name: "부바 상가레", team_id: 497, position: "Defender" },
  { id: 342019, name: "D. Ghilardi", korean_name: "다니엘 길라르디", team_id: 497, position: "Defender" },
  { id: 162452, name: "D. Rensch", korean_name: "데비 렌쉬", team_id: 497, position: "Defender" },
  { id: 1807, name: "E. Ndicka", korean_name: "에반 은디카", team_id: 497, position: "Defender" },
  { id: 30425, name: "G. Mancini", korean_name: "잔루카 만치니", team_id: 497, position: "Defender" },
  { id: 2669, name: "Hermoso", korean_name: "마리오 에르모소", team_id: 497, position: "Defender" },
  { id: 384543, name: "J. Ziółkowski", korean_name: "야쿱 지올코브스키", team_id: 497, position: "Defender" },
  { id: 22222, name: "Z. Çelik", korean_name: "제키 첼리크", team_id: 497, position: "Defender" },
  { id: 394183, name: "A. Romano", korean_name: "안드레아 로마노", team_id: 497, position: "Midfielder" },
  { id: 778, name: "B. Cristante", korean_name: "브리안 크리스탄테", team_id: 497, position: "Midfielder" },
  { id: 286475, name: "E. Bove", korean_name: "에디오아르도 보베", team_id: 497, position: "Midfielder" },
  { id: 158059, name: "E. Darboe", korean_name: "에브리마 다르보에", team_id: 497, position: "Midfielder" },
  { id: 1600, name: "K. Tsimikas", korean_name: "코스타스 치미카스", team_id: 497, position: "Midfielder" },
  { id: 782, name: "L. Pellegrini", korean_name: "로렌초 펠레그리니", team_id: 497, position: "Midfielder" },
  { id: 22147, name: "M. Koné", korean_name: "마누 코네", team_id: 497, position: "Midfielder" },
  { id: 277003, name: "N. El Aynaoui", korean_name: "니콜로 엘 아이나우이", team_id: 497, position: "Midfielder" },
  { id: 356888, name: "N. Pisilli", korean_name: "니콜로 피실리", team_id: 497, position: "Midfielder" },
  { id: 349001, name: "Wesley", korean_name: "웨슬리", team_id: 497, position: "Midfielder" },
  { id: 484027, name: "A. Arena", korean_name: "안드레아 아레나", team_id: 497, position: "Attacker" },
  { id: 15811, name: "A. Dovbyk", korean_name: "아르템 도비크", team_id: 497, position: "Attacker" },
  { id: 129643, name: "E. Ferguson", korean_name: "에반 퍼거슨", team_id: 497, position: "Attacker" },
  { id: 983, name: "L. Bailey", korean_name: "레온 베일리", team_id: 497, position: "Attacker" },
  { id: 323936, name: "M. Soulé", korean_name: "마티아스 술레", team_id: 497, position: "Attacker" },
  { id: 875, name: "P. Dybala", korean_name: "파울로 디발라", team_id: 497, position: "Attacker" },
  { id: 791, name: "S. El Shaarawy", korean_name: "스테판 엘 샤라위", team_id: 497, position: "Attacker" },
  { id: 288769, name: "T. Baldanzi", korean_name: "토마소 발단치", team_id: 497, position: "Attacker" },
];

// Atalanta (Team ID: 499) - 31명
export const ATALANTA_PLAYERS: PlayerMapping[] = [
  { id: 30419, name: "F. Rossi", korean_name: "프란체스코 로시", team_id: 499, position: "Goalkeeper" },
  { id: 30417, name: "M. Carnesecchi", korean_name: "마르코 카르네세키", team_id: 499, position: "Goalkeeper" },
  { id: 31069, name: "M. Sportiello", korean_name: "마르코 스포르티엘로", team_id: 499, position: "Goalkeeper" },
  { id: 30421, name: "B. Djimsiti", korean_name: "베라트 지심시티", team_id: 499, position: "Defender" },
  { id: 289761, name: "G. Scalvini", korean_name: "조르조 스칼비니", team_id: 499, position: "Defender" },
  { id: 453906, name: "H. Ahanor", korean_name: "할렘 아하노르", team_id: 499, position: "Defender" },
  { id: 137976, name: "I. Hien", korean_name: "이사크 히엔", team_id: 499, position: "Defender" },
  { id: 530, name: "M. Bakker", korean_name: "미첼 바커", team_id: 499, position: "Defender" },
  { id: 48119, name: "O. Kossounou", korean_name: "우스마네 코수누", team_id: 499, position: "Defender" },
  { id: 400530, name: "R. Obriċ", korean_name: "로렌초 오브리치", team_id: 499, position: "Defender" },
  { id: 1442, name: "S. Kolašinac", korean_name: "세아드 콜라시나츠", team_id: 499, position: "Defender" },
  { id: 2286, name: "D. Zappacosta", korean_name: "다비데 자파코스타", team_id: 499, position: "Midfielder" },
  { id: 10097, name: "Éderson", korean_name: "에데르손", team_id: 499, position: "Midfielder" },
  { id: 264857, name: "L. Bernasconi", korean_name: "루카 베르나스코니", team_id: 499, position: "Midfielder" },
  { id: 1639, name: "M. Brescianini", korean_name: "마르코 브레샤니니", team_id: 499, position: "Midfielder" },
  { id: 30432, name: "M. de Roon", korean_name: "마르텐 데 론", team_id: 499, position: "Midfielder" },
  { id: 2763, name: "M. Pašalić", korean_name: "마리오 파살리치", team_id: 499, position: "Midfielder" },
  { id: 203474, name: "N. Zalewski", korean_name: "니콜라 잘레브스키", team_id: 499, position: "Midfielder" },
  { id: 91422, name: "R. Bellanova", korean_name: "라울 벨라노바", team_id: 499, position: "Midfielder" },
  { id: 162106, name: "Y. Musah", korean_name: "유누스 무사", team_id: 499, position: "Midfielder" },
  { id: 18767, name: "A. Lookman", korean_name: "아데몰라 룩맨", team_id: 499, position: "Attacker" },
  { id: 147859, name: "C. De Ketelaere", korean_name: "샤를 데 케텔레레", team_id: 499, position: "Attacker" },
  { id: 134926, name: "D. Maldini", korean_name: "다니엘 말디니", team_id: 499, position: "Attacker" },
  { id: 194750, name: "E. Touré", korean_name: "엘 빌랄 투레", team_id: 499, position: "Attacker" },
  { id: 30544, name: "G. Scamacca", korean_name: "잔루카 스카마카", team_id: 499, position: "Attacker" },
  { id: 458409, name: "H. Camara", korean_name: "하사네 카마라", team_id: 499, position: "Attacker" },
  { id: 199837, name: "K. Sulemana", korean_name: "캄알딘 술레마나", team_id: 499, position: "Attacker" },
  { id: 178749, name: "L. Samardžić", korean_name: "라자르 사마르지치", team_id: 499, position: "Attacker" },
  { id: 66817, name: "N. Krstović", korean_name: "니콜라 크르스토비치", team_id: 499, position: "Attacker" },
  { id: 127055, name: "A. Arena", korean_name: "안드레아 아레나", team_id: 499, position: null },
  { id: 180982, name: "A. Lind", korean_name: "안데르스 린드", team_id: 499, position: null },
];

// Bologna (Team ID: 500) - 34명
export const BOLOGNA_PLAYERS: PlayerMapping[] = [
  { id: 31098, name: "F. Ravaglia", korean_name: "페데리코 라발리아", team_id: 500, position: "Goalkeeper" },
  { id: 2998, name: "Ł. Skorupski", korean_name: "우카시 스코룹스키", team_id: 500, position: "Goalkeeper" },
  { id: 446089, name: "M. Pessina", korean_name: "마테오 페시나", team_id: 500, position: "Goalkeeper" },
  { id: 416518, name: "U. Happonen", korean_name: "우르호 하포넨", team_id: 500, position: "Goalkeeper" },
  { id: 394947, name: "B. Tomašević", korean_name: "브루노 토마셰비치", team_id: 500, position: "Defender" },
  { id: 30553, name: "C. Lykogiannis", korean_name: "차랄람보스 리코지아니스", team_id: 500, position: "Defender" },
  { id: 47985, name: "E. Holm", korean_name: "에밀 홀름", team_id: 500, position: "Defender" },
  { id: 1929, name: "J. Lucumí", korean_name: "예손 루쿠미", team_id: 500, position: "Defender" },
  { id: 134, name: "Juan Miranda", korean_name: "후안 미란다", team_id: 500, position: "Defender" },
  { id: 30498, name: "L. De Silvestri", korean_name: "로렌초 데 실베스트리", team_id: 500, position: "Defender" },
  { id: 287564, name: "M. Vitík", korean_name: "마르틴 비틱", team_id: 500, position: "Defender" },
  { id: 31099, name: "N. Casale", korean_name: "니콜로 카살레", team_id: 500, position: "Defender" },
  { id: 128461, name: "N. Zortea", korean_name: "나디르 조르테아", team_id: 500, position: "Defender" },
  { id: 341974, name: "T. Corazza", korean_name: "토마소 코라차", team_id: 500, position: "Defender" },
  { id: 39254, name: "T. Heggem", korean_name: "토르벨 헤겜", team_id: 500, position: "Defender" },
  { id: 322630, name: "G. Fabbian", korean_name: "조반니 파비안", team_id: 500, position: "Midfielder" },
  { id: 353609, name: "I. Sulemana", korean_name: "이브라히마 술레마나", team_id: 500, position: "Midfielder" },
  { id: 30542, name: "J. Odgaard", korean_name: "옌스 오드고르", team_id: 500, position: "Midfielder" },
  { id: 182280, name: "K. UrbaÅski", korean_name: "카치페르 우르반스키", team_id: 500, position: "Midfielder" },
  { id: 44814, name: "L. Ferguson", korean_name: "루이스 퍼거슨", team_id: 500, position: "Midfielder" },
  { id: 30438, name: "N. Cambiaghi", korean_name: "니콜로 캄비아기", team_id: 500, position: "Midfielder" },
  { id: 1322, name: "N. Moro", korean_name: "니콜라스 모로", team_id: 500, position: "Midfielder" },
  { id: 2807, name: "R. Freuler", korean_name: "레모 프로일러", team_id: 500, position: "Midfielder" },
  { id: 30488, name: "R. Orsolini", korean_name: "리카르도 오르솔리니", team_id: 500, position: "Midfielder" },
  { id: 31273, name: "T. Pobega", korean_name: "토마소 포베가", team_id: 500, position: "Midfielder" },
  { id: 347265, name: "B. Domínguez", korean_name: "벤자민 도밍게스", team_id: 500, position: "Attacker" },
  { id: 1863, name: "C. Immobile", korean_name: "치로 임모빌레", team_id: 500, position: "Attacker" },
  { id: 873, name: "F. Bernardeschi", korean_name: "페데리코 베르나르데스키", team_id: 500, position: "Attacker" },
  { id: 48079, name: "J. Karlsson", korean_name: "예스페르 칼손", team_id: 500, position: "Attacker" },
  { id: 278095, name: "J. Rowe", korean_name: "조나탄 로우", team_id: 500, position: "Attacker" },
  { id: 50798, name: "O. Okwonkwo", korean_name: "오르지 오크원코", team_id: 500, position: "Attacker" },
  { id: 311067, name: "S. Castro", korean_name: "산티아고 카스트로", team_id: 500, position: "Attacker" },
  { id: 93016, name: "T. Dallinga", korean_name: "톰 달링가", team_id: 500, position: "Attacker" },
  { id: 32225, name: "E. Dubickas", korean_name: "에길레 두비카스", team_id: 500, position: null },
];

// Cagliari (Team ID: 490) - 57명
export const CAGLIARI_PLAYERS: PlayerMapping[] = [
  { id: 31601, name: "B. Radunović", korean_name: "보리스 라두노비치", team_id: 490, position: "Goalkeeper" },
  { id: 30731, name: "E. Caprile", korean_name: "엘리아 카프릴레", team_id: 490, position: "Goalkeeper" },
  { id: 351324, name: "Eldin Lolic", korean_name: "엘딘 롤리치", team_id: 490, position: "Goalkeeper" },
  { id: 135863, name: "G. Ciocci", korean_name: "주세페 초치", team_id: 490, position: "Goalkeeper" },
  { id: 327774, name: "Lorenzo Palmisani", korean_name: "로렌초 팔미사니", team_id: 490, position: "Goalkeeper" },
  { id: 30882, name: "Matteo Pisseri", korean_name: "마테오 피세리", team_id: 490, position: "Goalkeeper" },
  { id: 342311, name: "V. Iliev", korean_name: "빅토르 일리예프", team_id: 490, position: "Goalkeeper" },
  { id: 485289, name: "V. Sarno", korean_name: "빈첸초 사르노", team_id: 490, position: "Goalkeeper" },
  { id: 56287, name: "A. Di Pardo", korean_name: "알레산드로 디 파르도", team_id: 490, position: "Defender" },
  { id: 371955, name: "Antoni Tymoteusz Franke", korean_name: "안토니 프랑케", team_id: 490, position: "Defender" },
  { id: 321744, name: "A. Obert", korean_name: "아담 오베르트", team_id: 490, position: "Defender" },
  { id: 379504, name: "Gabriele Bracaglia", korean_name: "가브리엘레 브라칼리아", team_id: 490, position: "Defender" },
  { id: 353613, name: "Gabriele Calvani", korean_name: "가브리엘레 칼바니", team_id: 490, position: "Defender" },
  { id: 162570, name: "Giorgio Cittadini", korean_name: "조르조 치타디니", team_id: 490, position: "Defender" },
  { id: 200, name: "G. Zappa", korean_name: "가브리엘레 자파", team_id: 490, position: "Defender" },
  { id: 325899, name: "Jérémy Henry Oyono Omva Torque", korean_name: "제레미 오요노", team_id: 490, position: "Defender" },
  { id: 415155, name: "J. Rodríguez", korean_name: "호세 로드리게스", team_id: 490, position: "Defender" },
  { id: 485286, name: "M. Obleac", korean_name: "마테오 오블레아크", team_id: 490, position: "Defender" },
  { id: 384422, name: "Nicola Pintus", korean_name: "니콜라 핀투스", team_id: 490, position: "Defender" },
  { id: 383026, name: "Riyad Idrissi", korean_name: "리야드 이드리시", team_id: 490, position: "Defender" },
  { id: 319, name: "S. Luperto", korean_name: "세바스티아노 루페르토", team_id: 490, position: "Defender" },
  { id: 2484, name: "Y. Mina", korean_name: "예리 미나", team_id: 490, position: "Defender" },
  { id: 41964, name: "Zé Pedro", korean_name: "제 페드루", team_id: 490, position: "Defender" },
  { id: 527685, name: "Abdoulie Ndow", korean_name: "압둘리에 은도우", team_id: 490, position: "Midfielder" },
  { id: 30561, name: "A. Deiola", korean_name: "알레산드로 데이올라", team_id: 490, position: "Midfielder" },
  { id: 56278, name: "Edoardo Masciangelo", korean_name: "에도아르도 마샤넬로", team_id: 490, position: "Midfielder" },
  { id: 447068, name: "Filippo Grosso", korean_name: "필리포 그로소", team_id: 490, position: "Midfielder" },
  { id: 325, name: "G. Gaetano", korean_name: "지안루카 가에타노", team_id: 490, position: "Midfielder" },
  { id: 32011, name: "Giacomo Calò", korean_name: "자코모 칼로", team_id: 490, position: "Midfielder" },
  { id: 311251, name: "Giorgi Kvernadze", korean_name: "기오르기 크베르나제", team_id: 490, position: "Midfielder" },
  { id: 204088, name: "Ilias Koutsoupias", korean_name: "일리아스 쿠초우피아스", team_id: 490, position: "Midfielder" },
  { id: 417892, name: "J. Liteta", korean_name: "장-루이 리테타", team_id: 490, position: "Midfielder" },
  { id: 30780, name: "L. Mazzitelli", korean_name: "루카 마치텔리", team_id: 490, position: "Midfielder" },
  { id: 30505, name: "M. Adopo", korean_name: "미셸 아도포", team_id: 490, position: "Midfielder" },
  { id: 422153, name: "Matteo Cichella", korean_name: "마테오 치켈라", team_id: 490, position: "Midfielder" },
  { id: 31734, name: "M. Felici", korean_name: "마테오 펠리치", team_id: 490, position: "Midfielder" },
  { id: 56851, name: "M. Folorunsho", korean_name: "마이클 폴로룬소", team_id: 490, position: "Midfielder" },
  { id: 383018, name: "M. Palestra", korean_name: "마테오 팔레스트라", team_id: 490, position: "Midfielder" },
  { id: 309388, name: "M. Prati", korean_name: "마테오 프라티", team_id: 490, position: "Midfielder" },
  { id: 2055, name: "M. Rog", korean_name: "마르코 로그", team_id: 490, position: "Midfielder" },
  { id: 329550, name: "N. Cavuoti", korean_name: "니콜로 카부오티", team_id: 490, position: "Midfielder" },
  { id: 528342, name: "Toci Matteo", korean_name: "마테오 토치", team_id: 490, position: "Midfielder" },
  { id: 30509, name: "A. Belotti", korean_name: "안드레아 벨로티", team_id: 490, position: "Attacker" },
  { id: 394170, name: "Adrian Raychev", korean_name: "아드리안 라이체프", team_id: 490, position: "Attacker" },
  { id: 414388, name: "Alejandro Gabriel Cichero Terrero", korean_name: "알레한드로 치체로", team_id: 490, position: "Attacker" },
  { id: 341987, name: "A. Vinciguerra", korean_name: "안토니오 빈치구에라", team_id: 490, position: "Attacker" },
  { id: 441551, name: "Damar Dixon O'Neill", korean_name: "다마르 오닐", team_id: 490, position: "Attacker" },
  { id: 134432, name: "Edoardo Vergani", korean_name: "에도아르도 베르가니", team_id: 490, position: "Attacker" },
  { id: 31499, name: "G. Borrelli", korean_name: "주세페 보렐리", team_id: 490, position: "Attacker" },
  { id: 30573, name: "L. Pavoletti", korean_name: "레오나르도 파볼레티", team_id: 490, position: "Attacker" },
  { id: 468711, name: "Nicola Grandu", korean_name: "니콜라 그란두", team_id: 490, position: "Attacker" },
  { id: 215, name: "S. Esposito", korean_name: "세바스티아노 에스포지토", team_id: 490, position: "Attacker" },
  { id: 336567, name: "S. Kılıçsoy", korean_name: "셈페르 킬리크소이", team_id: 490, position: "Attacker" },
  { id: 140831, name: "Zito Luvumbo", korean_name: "지투 루붐보", team_id: 490, position: "Attacker" },
  { id: 551413, name: "J. Liteta", korean_name: "장-루이 리테타", team_id: 490, position: null },
  { id: 530281, name: "Muhammed Colley", korean_name: "무하메드 콜리", team_id: 490, position: null },
];

// Como (Team ID: 895) - 40명
export const COMO_PLAYERS: PlayerMapping[] = [
  { id: 463951, name: "Henrique Menke", korean_name: "엔리케 멘케", team_id: 895, position: "Goalkeeper" },
  { id: 8574, name: "J. Butez", korean_name: "장 부테즈", team_id: 895, position: "Goalkeeper" },
  { id: 31719, name: "M. Vigorito", korean_name: "마이클 비고리토", team_id: 895, position: "Goalkeeper" },
  { id: 207804, name: "N. Čavlina", korean_name: "니콜라 차블리나", team_id: 895, position: "Goalkeeper" },
  { id: 193328, name: "N. Törnqvist", korean_name: "닐스 퇴른크비스트", team_id: 895, position: "Goalkeeper" },
  { id: 32034, name: "A. Dossena", korean_name: "알베르토 도세나", team_id: 895, position: "Defender" },
  { id: 288, name: "Alberto Moreno", korean_name: "알베르토 모레노", team_id: 895, position: "Defender" },
  { id: 336560, name: "Álex Valle", korean_name: "알렉스 바예", team_id: 895, position: "Defender" },
  { id: 21090, name: "Diego Carlos", korean_name: "디에구 카를루스", team_id: 895, position: "Defender" },
  { id: 31073, name: "E. Goldaniga", korean_name: "에디 골다니가", team_id: 895, position: "Defender" },
  { id: 469318, name: "Fellipe Jack", korean_name: "펠리페 잭", team_id: 895, position: "Defender" },
  { id: 14266, name: "I. Smolčić", korean_name: "이반 스몰치치", team_id: 895, position: "Defender" },
  { id: 129119, name: "I. Van der Brempt", korean_name: "이냐시오 반 데르 브렘프트", team_id: 895, position: "Defender" },
  { id: 386305, name: "Jacobo Ramón Naveros", korean_name: "야코보 나베로스", team_id: 895, position: "Defender" },
  { id: 26301, name: "M. Kempf", korean_name: "마르크 켐프", team_id: 895, position: "Defender" },
  { id: 8586, name: "M. Vojvoda", korean_name: "메르기 보이보다", team_id: 895, position: "Defender" },
  { id: 711, name: "S. Posch", korean_name: "슈테판 포쉬", team_id: 895, position: "Defender" },
  { id: 136017, name: "T. Cassandro", korean_name: "티모테오 카산드로", team_id: 895, position: "Defender" },
  { id: 30513, name: "B. Kone", korean_name: "베른 코네", team_id: 895, position: "Midfielder" },
  { id: 172, name: "D. Alli", korean_name: "델레 알리", team_id: 895, position: "Midfielder" },
  { id: 354533, name: "J. Addai", korean_name: "조던 아다이", team_id: 895, position: "Midfielder" },
  { id: 443162, name: "Jesús Rodríguez", korean_name: "헤수스 로드리게스", team_id: 895, position: "Midfielder" },
  { id: 162266, name: "L. da Cunha", korean_name: "루카스 다 쿠냐", team_id: 895, position: "Midfielder" },
  { id: 554467, name: "Lorenzo Bonsignori Goggi", korean_name: "로렌초 본시뇨리", team_id: 895, position: "Midfielder" },
  { id: 295026, name: "M. Baturina", korean_name: "마르틴 바투리나", team_id: 895, position: "Midfielder" },
  { id: 659, name: "M. Caqueret", korean_name: "막심 카케레", team_id: 895, position: "Midfielder" },
  { id: 288699, name: "M. Perrone", korean_name: "마시모 페로네", team_id: 895, position: "Midfielder" },
  { id: 38753, name: "N. Kühn", korean_name: "니콜라스 퀸", team_id: 895, position: "Midfielder" },
  { id: 350037, name: "N. Paz", korean_name: "니코 파스", team_id: 895, position: "Midfielder" },
  { id: 137, name: "Sergi Roberto", korean_name: "세르히 로베르토", team_id: 895, position: "Midfielder" },
  { id: 178709, name: "Y. Engelhardt", korean_name: "얀 엥겔하르트", team_id: 895, position: "Midfielder" },
  { id: 30570, name: "A. Cerri", korean_name: "알베르토 체리", team_id: 895, position: "Attacker" },
  { id: 106257, name: "A. Gabrielloni", korean_name: "알레산드로 가브리엘로니", team_id: 895, position: "Attacker" },
  { id: 409411, name: "Ali Jasim", korean_name: "알리 자심", team_id: 895, position: "Attacker" },
  { id: 59, name: "Álvaro Morata", korean_name: "알바로 모라타", team_id: 895, position: "Attacker" },
  { id: 400948, name: "Assane Diao", korean_name: "아산 디아오", team_id: 895, position: "Attacker" },
  { id: 161590, name: "Iván Azón", korean_name: "이반 아손", team_id: 895, position: "Attacker" },
  { id: 152609, name: "S. Ballet", korean_name: "스테판 발레", team_id: 895, position: "Attacker" },
  { id: 26845, name: "T. Douvikas", korean_name: "타소스 두비카스", team_id: 895, position: "Attacker" },
];

// Cremonese (Team ID: 520) - 37명
export const CREMONESE_PLAYERS: PlayerMapping[] = [
  { id: 441550, name: "Adrián Malovec", korean_name: "아드리안 말로베츠", team_id: 520, position: "Goalkeeper" },
  { id: 30441, name: "E. Audero", korean_name: "에밀 아우데로", team_id: 520, position: "Goalkeeper" },
  { id: 31038, name: "G. Saro", korean_name: "자코모 사로", team_id: 520, position: "Goalkeeper" },
  { id: 342995, name: "L. Nava", korean_name: "루카 나바", team_id: 520, position: "Goalkeeper" },
  { id: 30915, name: "M. Silvestri", korean_name: "마르코 실베스트리", team_id: 520, position: "Goalkeeper" },
  { id: 127035, name: "F. Baschirotto", korean_name: "페데리코 바스키로토", team_id: 520, position: "Defender" },
  { id: 30397, name: "F. Ceccherini", korean_name: "페데리코 체케리니", team_id: 520, position: "Defender" },
  { id: 385788, name: "F. Folino", korean_name: "프란체스코 폴리노", team_id: 520, position: "Defender" },
  { id: 264472, name: "F. Terracciano", korean_name: "필리포 테라치아노", team_id: 520, position: "Defender" },
  { id: 30775, name: "G. Pezzella", korean_name: "주세페 페첼라", team_id: 520, position: "Defender" },
  { id: 237266, name: "L. Moretti", korean_name: "로렌초 모레티", team_id: 520, position: "Defender" },
  { id: 30530, name: "L. Sernicola", korean_name: "레오나르도 세르니콜라", team_id: 520, position: "Defender" },
  { id: 30919, name: "M. Bianchetti", korean_name: "마테오 비앙케티", team_id: 520, position: "Defender" },
  { id: 237249, name: "M. Faye", korean_name: "미켈 파예", team_id: 520, position: "Defender" },
  { id: 342651, name: "R. Floriani Mussolini", korean_name: "로마노 플로리아니", team_id: 520, position: "Defender" },
  { id: 126980, name: "T. Barbieri", korean_name: "토마소 바르비에리", team_id: 520, position: "Defender" },
  { id: 342073, name: "Y. Rocchetti", korean_name: "얀 로케티", team_id: 520, position: "Defender" },
  { id: 31021, name: "A. Grassi", korean_name: "알베르토 그라시", team_id: 520, position: "Midfielder" },
  { id: 48555, name: "C. Pickel", korean_name: "샤를 피켈", team_id: 520, position: "Midfielder" },
  { id: 361412, name: "D. Lordkipanidze", korean_name: "다비트 로르드키파니제", team_id: 520, position: "Midfielder" },
  { id: 2057, name: "F. Vázquez", korean_name: "프랑코 바스케스", team_id: 520, position: "Midfielder" },
  { id: 202086, name: "J. Sarmiento", korean_name: "헤레미 사르미엔토", team_id: 520, position: "Midfielder" },
  { id: 31211, name: "J. Vandeputte", korean_name: "요나탄 반데푸테", team_id: 520, position: "Midfielder" },
  { id: 31614, name: "M. Castagnetti", korean_name: "미켈레 카스타네티", team_id: 520, position: "Midfielder" },
  { id: 126889, name: "M. Collocolo", korean_name: "마누엘 콜로콜로", team_id: 520, position: "Midfielder" },
  { id: 6383, name: "M. Payero", korean_name: "마르틴 파예로", team_id: 520, position: "Midfielder" },
  { id: 30875, name: "M. Valoti", korean_name: "마테오 발로티", team_id: 520, position: "Midfielder" },
  { id: 266813, name: "W. Bondo", korean_name: "워렌 본도", team_id: 520, position: "Midfielder" },
  { id: 2522, name: "A. Sanabria", korean_name: "안토니오 사나브리아", team_id: 520, position: "Attacker" },
  { id: 31219, name: "A. Zerbin", korean_name: "알레시오 제르빈", team_id: 520, position: "Attacker" },
  { id: 36986, name: "D. Johnsen", korean_name: "데니스 욘센", team_id: 520, position: "Attacker" },
  { id: 30848, name: "D. Okereke", korean_name: "다비드 오케레케", team_id: 520, position: "Attacker" },
  { id: 31436, name: "F. Bonazzoli", korean_name: "페데리코 보나촐리", team_id: 520, position: "Attacker" },
  { id: 102447, name: "F. Moumbagna", korean_name: "프랑크 모움바냐", team_id: 520, position: "Attacker" },
  { id: 1652, name: "F. Tsadjout", korean_name: "펠릭스 차주트", team_id: 520, position: "Attacker" },
  { id: 18788, name: "J. Vardy", korean_name: "제이미 바디", team_id: 520, position: "Attacker" },
  { id: 31853, name: "M. De Luca", korean_name: "마누엘 데 루카", team_id: 520, position: "Attacker" },
];

// Fiorentina (Team ID: 502) - 34명
export const FIORENTINA_PLAYERS: PlayerMapping[] = [
  { id: 882, name: "David de Gea", korean_name: "다비드 데 헤아", team_id: 502, position: "Goalkeeper" },
  { id: 31352, name: "L. Lezzerini", korean_name: "루카 레체리니", team_id: 502, position: "Goalkeeper" },
  { id: 15843, name: "O. Christensen", korean_name: "올리버 크리스텐센", team_id: 502, position: "Goalkeeper" },
  { id: 383267, name: "T. Martinelli", korean_name: "토마소 마르티넬리", team_id: 502, position: "Goalkeeper" },
  { id: 71455, name: "D. Krastev", korean_name: "딤 크라스테프", team_id: 502, position: "Defender" },
  { id: 441290, name: "E. Košpo", korean_name: "에밀 코슈포", team_id: 502, position: "Defender" },
  { id: 448977, name: "E. Kouadio", korean_name: "에마뉘엘 쿠아디오", team_id: 502, position: "Defender" },
  { id: 136087, name: "F. Parisi", korean_name: "파비아노 파리시", team_id: 502, position: "Defender" },
  { id: 31642, name: "L. Ranieri", korean_name: "루카 라니에리", team_id: 502, position: "Defender" },
  { id: 1084, name: "M. Pongračić", korean_name: "마린 퐁그라치치", team_id: 502, position: "Defender" },
  { id: 180510, name: "M. Viti", korean_name: "마티아 비티", team_id: 502, position: "Defender" },
  { id: 437093, name: "N. Fortini", korean_name: "니콜로 포르티니", team_id: 502, position: "Defender" },
  { id: 46792, name: "Pablo Marí", korean_name: "파블로 마리", team_id: 502, position: "Defender" },
  { id: 396637, name: "P. Comuzzo", korean_name: "피에트로 코무초", team_id: 502, position: "Defender" },
  { id: 30803, name: "A. Barák", korean_name: "안토닌 바락", team_id: 502, position: "Midfielder" },
  { id: 302432, name: "A. Bianco", korean_name: "알레산드로 비앙코", team_id: 502, position: "Midfielder" },
  { id: 314231, name: "A. Richardson", korean_name: "아리코 리처드슨", team_id: 502, position: "Midfielder" },
  { id: 19053, name: "A. Sabiri", korean_name: "압델하미드 사비리", team_id: 502, position: "Midfielder" },
  { id: 311083, name: "C. Ndour", korean_name: "셰리프 은두르", team_id: 502, position: "Midfielder" },
  { id: 41144, name: "Dodô", korean_name: "도도", team_id: 502, position: "Midfielder" },
  { id: 881, name: "H. Nicolussi", korean_name: "한스 니콜루시", team_id: 502, position: "Midfielder" },
  { id: 6010, name: "L. Beltrán", korean_name: "루카스 벨트란", team_id: 502, position: "Midfielder" },
  { id: 876, name: "N. Fagioli", korean_name: "니콜로 파지올리", team_id: 502, position: "Midfielder" },
  { id: 30422, name: "R. Gosens", korean_name: "로빈 고젠스", team_id: 502, position: "Midfielder" },
  { id: 30810, name: "R. Mandragora", korean_name: "롤란도 만드라고라", team_id: 502, position: "Midfielder" },
  { id: 1014, name: "S. Sohm", korean_name: "산드로 좀", team_id: 502, position: "Midfielder" },
  { id: 138815, name: "T. Lamptey", korean_name: "타리크 램프티", team_id: 502, position: "Midfielder" },
  { id: 2799, name: "A. Guðmundsson", korean_name: "알베르트 그뷔드뮌손", team_id: 502, position: "Attacker" },
  { id: 790, name: "E. Džeko", korean_name: "에딘 제코", team_id: 502, position: "Attacker" },
  { id: 340700, name: "J. Fazzini", korean_name: "자코포 파치니", team_id: 502, position: "Attacker" },
  { id: 22229, name: "J. Ikoné", korean_name: "조나탕 이코네", team_id: 502, position: "Attacker" },
  { id: 877, name: "M. Kean", korean_name: "모이스 킨", team_id: 502, position: "Attacker" },
  { id: 437094, name: "R. Braschi", korean_name: "리날도 브라스키", team_id: 502, position: "Attacker" },
  { id: 30440, name: "R. Piccoli", korean_name: "로베르토 피콜리", team_id: 502, position: "Attacker" },
];

// Genoa (Team ID: 495) - 33명
export const GENOA_PLAYERS: PlayerMapping[] = [
  { id: 45083, name: "B. Siegrist", korean_name: "베토 시그리스트", team_id: 495, position: "Goalkeeper" },
  { id: 31445, name: "D. Sommariva", korean_name: "다니엘레 솜마리바", team_id: 495, position: "Goalkeeper" },
  { id: 395788, name: "E. Lysionok", korean_name: "에고르 리시오노크", team_id: 495, position: "Goalkeeper" },
  { id: 31631, name: "N. Leali", korean_name: "니콜라 레알리", team_id: 495, position: "Goalkeeper" },
  { id: 25914, name: "Aarón Martín", korean_name: "아론 마르틴", team_id: 495, position: "Defender" },
  { id: 281826, name: "A. Marcandalli", korean_name: "안드레아 마르칸달리", team_id: 495, position: "Defender" },
  { id: 31521, name: "A. Vogliacco", korean_name: "알레산드로 볼리아코", team_id: 495, position: "Defender" },
  { id: 35544, name: "J. Vásquez", korean_name: "요한 바스케스", team_id: 495, position: "Defender" },
  { id: 18967, name: "L. Østigård", korean_name: "레오 외스티고르", team_id: 495, position: "Defender" },
  { id: 89520, name: "M. Ellertsson", korean_name: "미카엘 엘레르트손", team_id: 495, position: "Defender" },
  { id: 387128, name: "S. Otoa", korean_name: "사무엘 오토아", team_id: 495, position: "Defender" },
  { id: 31137, name: "S. Sabelli", korean_name: "스테파노 사벨리", team_id: 495, position: "Defender" },
  { id: 263177, name: "A. Grønbæk", korean_name: "알베르트 그뢴백", team_id: 495, position: "Midfielder" },
  { id: 284570, name: "B. Norton-Cuffy", korean_name: "브룩 노턴-커피", team_id: 495, position: "Midfielder" },
  { id: 437091, name: "C. Papadopoulos", korean_name: "콘스탄티노스 파파도풀로스", team_id: 495, position: "Midfielder" },
  { id: 39286, name: "E. Bohinen", korean_name: "에밀 보히넨", team_id: 495, position: "Midfielder" },
  { id: 382947, name: "H. Cuenca", korean_name: "엑토르 쿠엔카", team_id: 495, position: "Midfielder" },
  { id: 41748, name: "J. Onana", korean_name: "장 오나나", team_id: 495, position: "Midfielder" },
  { id: 56396, name: "Junior Messias", korean_name: "주니오르 메시아스", team_id: 495, position: "Midfielder" },
  { id: 15881, name: "M. Frendrup", korean_name: "모르텐 프렌드루프", team_id: 495, position: "Midfielder" },
  { id: 36980, name: "M. Thorsby", korean_name: "모르텐 토르스비", team_id: 495, position: "Midfielder" },
  { id: 44439, name: "N. Stanciu", korean_name: "니콜라에 스탄치우", team_id: 495, position: "Midfielder" },
  { id: 281096, name: "P. Masini", korean_name: "피에트로 마시니", team_id: 495, position: "Midfielder" },
  { id: 1938, name: "R. Malinovskyi", korean_name: "루슬란 말리노프스키", team_id: 495, position: "Midfielder" },
  { id: 341646, name: "V. Carboni", korean_name: "발렌틴 카르보니", team_id: 495, position: "Midfielder" },
  { id: 281408, name: "Vítinha", korean_name: "비티냐", team_id: 495, position: "Midfielder" },
  { id: 3430, name: "C. Ekuban", korean_name: "케일럽 에쿠반", team_id: 495, position: "Attacker" },
  { id: 310109, name: "D. Ankeye", korean_name: "다비드 안케예", team_id: 495, position: "Attacker" },
  { id: 451504, name: "J. Ekhator", korean_name: "제이콥 에카토르", team_id: 495, position: "Attacker" },
  { id: 263481, name: "L. Colombo", korean_name: "로렌초 콜롬보", team_id: 495, position: "Attacker" },
  { id: 452033, name: "L. Venturino", korean_name: "루카 벤투리노", team_id: 495, position: "Attacker" },
  { id: 665, name: "M. Cornet", korean_name: "막스웰 코르네", team_id: 495, position: "Attacker" },
  { id: 348533, name: "S. Fini", korean_name: "스테파노 피니", team_id: 495, position: "Attacker" },
];

// Inter (Team ID: 505) - 28명
export const INTER_PLAYERS: PlayerMapping[] = [
  { id: 46988, name: "Josep Martínez", korean_name: "조셉 마르티네스", team_id: 505, position: "Goalkeeper" },
  { id: 91488, name: "R. Di Gennaro", korean_name: "라파엘레 디 젠나로", team_id: 505, position: "Goalkeeper" },
  { id: 2802, name: "Y. Sommer", korean_name: "얀 좀머", team_id: 505, position: "Goalkeeper" },
  { id: 31009, name: "A. Bastoni", korean_name: "알레산드로 바스토니", team_id: 505, position: "Defender" },
  { id: 2725, name: "B. Pavard", korean_name: "뱅자맹 파바르", team_id: 505, position: "Defender" },
  { id: 10238, name: "Carlos Augusto", korean_name: "카를로스 아우구스토", team_id: 505, position: "Defender" },
  { id: 1836, name: "F. Acerbi", korean_name: "프란체스코 아체르비", team_id: 505, position: "Defender" },
  { id: 5, name: "M. Akanji", korean_name: "마누엘 아칸지", team_id: 505, position: "Defender" },
  { id: 887, name: "M. Darmian", korean_name: "마테오 다르미안", team_id: 505, position: "Defender" },
  { id: 194, name: "S. de Vrij", korean_name: "스테판 데 브라이", team_id: 505, position: "Defender" },
  { id: 311360, name: "T. Palacios", korean_name: "토마스 팔라시오스", team_id: 505, position: "Defender" },
  { id: 24953, name: "Y. Bisseck", korean_name: "얀 아우렐 비세크", team_id: 505, position: "Defender" },
  { id: 270509, name: "A. Diouf", korean_name: "압둘라예 디우프", team_id: 505, position: "Midfielder" },
  { id: 226, name: "D. Dumfries", korean_name: "덴젤 둠프리스", team_id: 505, position: "Midfielder" },
  { id: 31173, name: "D. Frattesi", korean_name: "다비데 프라테시", team_id: 505, position: "Midfielder" },
  { id: 31010, name: "F. Dimarco", korean_name: "페데리코 디마르코", team_id: 505, position: "Midfielder" },
  { id: 1640, name: "H. Çalhanoğlu", korean_name: "하칸 찰하노글루", team_id: 505, position: "Midfielder" },
  { id: 1457, name: "H. Mkhitaryan", korean_name: "헨리크 미키타리안", team_id: 505, position: "Midfielder" },
  { id: 30558, name: "N. Barella", korean_name: "니콜로 바렐라", team_id: 505, position: "Midfielder" },
  { id: 348205, name: "P. Sučić", korean_name: "페타르 수치치", team_id: 505, position: "Midfielder" },
  { id: 329, name: "P. Zieliński", korean_name: "피오트르 지엘린스키", team_id: 505, position: "Midfielder" },
  { id: 275651, name: "A. Bonny", korean_name: "앙제-요안 보니", team_id: 505, position: "Attacker" },
  { id: 345808, name: "F. Esposito", korean_name: "프란체스코 에스포시토", team_id: 505, position: "Attacker" },
  { id: 217, name: "Lautaro Martínez", korean_name: "라우타로 마르티네스", team_id: 505, position: "Attacker" },
  { id: 10077, name: "Luis Henrique", korean_name: "루이스 엔리케", team_id: 505, position: "Attacker" },
  { id: 42315, name: "M. Taremi", korean_name: "메흐디 타레미", team_id: 505, position: "Attacker" },
  { id: 21509, name: "M. Thuram", korean_name: "마르쿠스 튀람", team_id: 505, position: "Attacker" },
];

// Juventus, Lazio, Lecce, Napoli, Parma, Pisa, Sassuolo, Torino, Udinese, Verona는 serie-a-part2.ts 파일에 있음

// 세리에 A Part 1 선수
export const SERIE_A_PLAYERS: PlayerMapping[] = [
  ...AC_MILAN_PLAYERS,
  ...AS_ROMA_PLAYERS,
  ...ATALANTA_PLAYERS,
  ...BOLOGNA_PLAYERS,
  ...CAGLIARI_PLAYERS,
  ...COMO_PLAYERS,
  ...CREMONESE_PLAYERS,
  ...FIORENTINA_PLAYERS,
  ...GENOA_PLAYERS,
  ...INTER_PLAYERS,
  // Juventus, Lazio 및 나머지 팀들은 serie-a-part2.ts 참조
];
