// Serie A 나머지 팀들 (Part 2)
import { PlayerMapping } from './index';

// Juventus (Team ID: 496) - 37명
export const JUVENTUS_PLAYERS: PlayerMapping[] = [
  { id: 850, name: "C. Pinsoglio", korean_name: "카를로 핀솔리오", team_id: 496, position: "Goalkeeper" },
  { id: 30670, name: "M. Di Gregorio", korean_name: "미켈레 디 그레고리오", team_id: 496, position: "Goalkeeper" },
  { id: 408319, name: "M. Fuscaldo", korean_name: "마르코 푸스칼도", team_id: 496, position: "Goalkeeper" },
  { id: 849, name: "M. Perin", korean_name: "마티아 페린", team_id: 496, position: "Goalkeeper" },
  { id: 335099, name: "S. Scaglia", korean_name: "시모네 스칼리아", team_id: 496, position: "Goalkeeper" },
  { id: 30497, name: "Bremer", korean_name: "브레메르", team_id: 496, position: "Defender" },
  { id: 436926, name: "Bruno Martinez", korean_name: "브루노 마르티네스", team_id: 496, position: "Defender" },
  { id: 861, name: "D. Rugani", korean_name: "다니엘레 루가니", team_id: 496, position: "Defender" },
  { id: 286595, name: "Facundo González", korean_name: "파쿤도 곤살레스", team_id: 496, position: "Defender" },
  { id: 268341, name: "F. Gatti", korean_name: "페데리코 가티", team_id: 496, position: "Defender" },
  { id: 436925, name: "Javier Gil", korean_name: "하비에르 길", team_id: 496, position: "Defender" },
  { id: 41734, name: "João Mário", korean_name: "주앙 마리우", team_id: 496, position: "Defender" },
  { id: 335101, name: "J. Rouhi", korean_name: "요나스 로우히", team_id: 496, position: "Defender" },
  { id: 19263, name: "L. Kelly", korean_name: "리암 켈리", team_id: 496, position: "Defender" },
  { id: 181806, name: "N. Savona", korean_name: "니콜로 사보나", team_id: 496, position: "Defender" },
  { id: 415064, name: "Pedro Felipe de Jesus Gomes", korean_name: "페드로 펠리페", team_id: 496, position: "Defender" },
  { id: 1479, name: "Tiago Djaló", korean_name: "티아구 잘로", team_id: 496, position: "Defender" },
  { id: 127011, name: "A. Cambiaso", korean_name: "안드레아 캄비아소", team_id: 496, position: "Midfielder" },
  { id: 150, name: "Arthur", korean_name: "아르투르", team_id: 496, position: "Midfielder" },
  { id: 1821, name: "F. Kostić", korean_name: "필립 코스티치", team_id: 496, position: "Midfielder" },
  { id: 181808, name: "F. Miretti", korean_name: "파비오 미레티", team_id: 496, position: "Midfielder" },
  { id: 125674, name: "J. Cabal", korean_name: "후안 카발", team_id: 496, position: "Midfielder" },
  { id: 116, name: "K. Thuram", korean_name: "쿠스마누엘 튀람", team_id: 496, position: "Midfielder" },
  { id: 30533, name: "M. Locatelli", korean_name: "마누엘 로카텔리", team_id: 496, position: "Midfielder" },
  { id: 162188, name: "P. Kalulu", korean_name: "피에르 칼룰루", team_id: 496, position: "Midfielder" },
  { id: 36899, name: "T. Koopmeiners", korean_name: "테운 코프마이너스", team_id: 496, position: "Midfielder" },
  { id: 339872, name: "Vasilije Adžić", korean_name: "바실리예 아지치", team_id: 496, position: "Midfielder" },
  { id: 415, name: "W. McKennie", korean_name: "웨스턴 매케니", team_id: 496, position: "Midfielder" },
  { id: 333, name: "A. Milik", korean_name: "아르카디우시 밀리크", team_id: 496, position: "Attacker" },
  { id: 30415, name: "D. Vlahović", korean_name: "두산 블라호비치", team_id: 496, position: "Attacker" },
  { id: 48392, name: "E. Zhegrova", korean_name: "엘돈 제그로바", team_id: 496, position: "Attacker" },
  { id: 161585, name: "Francisco Conceição", korean_name: "프란시스쿠 콘세이상", team_id: 496, position: "Attacker" },
  { id: 8489, name: "J. David", korean_name: "조나탄 다비드", team_id: 496, position: "Attacker" },
  { id: 339883, name: "K. Yıldız", korean_name: "케난 일디즈", team_id: 496, position: "Attacker" },
  { id: 86, name: "L. Openda", korean_name: "로이스 오펜다", team_id: 496, position: "Attacker" },
  { id: 26315, name: "N. González", korean_name: "니콜라스 곤살레스", team_id: 496, position: "Attacker" },
  { id: 557072, name: "Pedro Felipe", korean_name: "페드로 펠리페", team_id: 496, position: null },
];

// Lazio (Team ID: 487) - 33명
export const LAZIO_PLAYERS: PlayerMapping[] = [
  { id: 63934, name: "A. Furlanetto", korean_name: "알레산드로 푸를라네토", team_id: 487, position: "Goalkeeper" },
  { id: 26644, name: "C. Mandas", korean_name: "크리스토스 만다스", team_id: 487, position: "Goalkeeper" },
  { id: 31037, name: "I. Provedel", korean_name: "이반 프로베델", team_id: 487, position: "Goalkeeper" },
  { id: 1844, name: "A. Marušić", korean_name: "아담 마루시치", team_id: 487, position: "Defender" },
  { id: 1632, name: "A. Romagnoli", korean_name: "알레시오 로마뇰리", team_id: 487, position: "Defender" },
  { id: 45798, name: "D. Kamenović", korean_name: "달코 카메노비치", team_id: 487, position: "Defender" },
  { id: 317, name: "E. Hysaj", korean_name: "엘세이드 히사이", team_id: 487, position: "Defender" },
  { id: 30554, name: "L. Pellegrini", korean_name: "루카 펠레그리니", team_id: 487, position: "Defender" },
  { id: 162952, name: "Mario Gila", korean_name: "마리오 힐라", team_id: 487, position: "Defender" },
  { id: 41577, name: "Nuno Tavares", korean_name: "누누 타바레스", team_id: 487, position: "Defender" },
  { id: 350857, name: "O. Provstgaard", korean_name: "올리버 프로프스트고르", team_id: 487, position: "Defender" },
  { id: 1841, name: "Patric", korean_name: "파트리크", team_id: 487, position: "Defender" },
  { id: 1775, name: "S. Gigot", korean_name: "사무엘 지고", team_id: 487, position: "Defender" },
  { id: 22015, name: "B. Dia", korean_name: "불라예 디아", team_id: 487, position: "Midfielder" },
  { id: 1852, name: "D. Cataldi", korean_name: "다니엘레 카탈디", team_id: 487, position: "Midfielder" },
  { id: 144740, name: "F. Dele-Bashiru", korean_name: "피즐리 델레-바시루", team_id: 487, position: "Midfielder" },
  { id: 286474, name: "M. Cancellieri", korean_name: "마테오 칸첼리에리", team_id: 487, position: "Midfielder" },
  { id: 30859, name: "M. Fares", korean_name: "모하메드 파레스", team_id: 487, position: "Midfielder" },
  { id: 1454, name: "M. Guendouzi", korean_name: "마테오 강두지", team_id: 487, position: "Midfielder" },
  { id: 30866, name: "M. Lazzari", korean_name: "마누엘 라차리", team_id: 487, position: "Midfielder" },
  { id: 211, name: "M. Vecino", korean_name: "마티아스 베치노", team_id: 487, position: "Midfielder" },
  { id: 30937, name: "M. Zaccagni", korean_name: "마티아 자카니", team_id: 487, position: "Midfielder" },
  { id: 30784, name: "N. Rovella", korean_name: "니콜로 로벨라", team_id: 487, position: "Midfielder" },
  { id: 2299, name: "Pedro", korean_name: "페드로", team_id: 487, position: "Midfielder" },
  { id: 470737, name: "P. Pinelli", korean_name: "파올로 피넬리", team_id: 487, position: "Midfielder" },
  { id: 333116, name: "R. Belahyane", korean_name: "레다 벨라얀", team_id: 487, position: "Midfielder" },
  { id: 1266, name: "T. Bašić", korean_name: "티예고 바시치", team_id: 487, position: "Midfielder" },
  { id: 483662, name: "V. Farcomeni", korean_name: "비토리오 파르코메니", team_id: 487, position: "Midfielder" },
  { id: 307103, name: "D. González", korean_name: "다미안 곤살레스", team_id: 487, position: "Attacker" },
  { id: 135519, name: "G. Isaksen", korean_name: "구스타프 이삭센", team_id: 487, position: "Attacker" },
  { id: 436193, name: "S. Fernandes", korean_name: "사무엘 페르난데스", team_id: 487, position: "Attacker" },
  { id: 133729, name: "T. Noslin", korean_name: "티요 노슬린", team_id: 487, position: "Attacker" },
  { id: 50856, name: "V. Castellanos", korean_name: "발렌틴 카스테야노스", team_id: 487, position: "Attacker" },
];

// Lecce (Team ID: 867) - 34명
export const LECCE_PLAYERS: PlayerMapping[] = [
  { id: 495, name: "C. Früchtl", korean_name: "크리스티안 프뤼히틀", team_id: 867, position: "Goalkeeper" },
  { id: 156619, name: "J. Samooja", korean_name: "야스페르 사모야", team_id: 867, position: "Goalkeeper" },
  { id: 446138, name: "P. Penev", korean_name: "페타르 페네프", team_id: 867, position: "Goalkeeper" },
  { id: 56459, name: "W. Falcone", korean_name: "빈체 팔코네", team_id: 867, position: "Goalkeeper" },
  { id: 31543, name: "A. Gallo", korean_name: "안토니노 갈로", team_id: 867, position: "Defender" },
  { id: 19738, name: "C. Ndaba", korean_name: "칼랭 은다바", team_id: 867, position: "Defender" },
  { id: 161702, name: "Danilo Veiga", korean_name: "다닐루 베이가", team_id: 867, position: "Defender" },
  { id: 21636, name: "F. Guilbert", korean_name: "프레데릭 길베르", team_id: 867, position: "Defender" },
  { id: 23253, name: "G. Jean", korean_name: "가스파르 장", team_id: 867, position: "Defender" },
  { id: 203219, name: "J. Siebert", korean_name: "요나스 시베르트", team_id: 867, position: "Defender" },
  { id: 291589, name: "Kialonda Gaspar", korean_name: "키알론다 가스파르", team_id: 867, position: "Defender" },
  { id: 458543, name: "M. Pérez", korean_name: "마테오 페레스", team_id: 867, position: "Defender" },
  { id: 482309, name: "Owen Kouassi", korean_name: "오웬 쿠아시", team_id: 867, position: "Defender" },
  { id: 455316, name: "Tiago Gabriel", korean_name: "티아구 가브리엘", team_id: 867, position: "Defender" },
  { id: 181218, name: "Álex Sala", korean_name: "알렉스 살라", team_id: 867, position: "Midfielder" },
  { id: 190958, name: "B. Pierret", korean_name: "발톤 피에레", team_id: 867, position: "Midfielder" },
  { id: 153021, name: "E. Mömmö", korean_name: "에도 묨무", team_id: 867, position: "Midfielder" },
  { id: 40563, name: "F. Marchwiński", korean_name: "필립 마르친스키", team_id: 867, position: "Midfielder" },
  { id: 136016, name: "H. Rafia", korean_name: "함자 라피아", team_id: 867, position: "Midfielder" },
  { id: 118956, name: "L. Banda", korean_name: "라미네 반다", team_id: 867, position: "Midfielder" },
  { id: 1748, name: "L. Coulibaly", korean_name: "라싸나 쿨리발리", team_id: 867, position: "Midfielder" },
  { id: 335071, name: "M. Berisha", korean_name: "메돈 베리샤", team_id: 867, position: "Midfielder" },
  { id: 197779, name: "M. Kaba", korean_name: "무사 카바", team_id: 867, position: "Midfielder" },
  { id: 340179, name: "N. Kovač ", korean_name: "니콜라 코바치", team_id: 867, position: "Midfielder" },
  { id: 387537, name: "Olaf Gorter", korean_name: "올라프 고르터", team_id: 867, position: "Midfielder" },
  { id: 22016, name: "R. Oudin", korean_name: "레미 우딘", team_id: 867, position: "Midfielder" },
  { id: 56560, name: "Y. Maleh", korean_name: "유수프 말레", team_id: 867, position: "Midfielder" },
  { id: 15673, name: "Y. Ramadani", korean_name: "일리르 라마다니", team_id: 867, position: "Midfielder" },
  { id: 28744, name: "Þ. Helgason", korean_name: "토르드 헬가손", team_id: 867, position: "Midfielder" },
  { id: 436260, name: "F. Camarda", korean_name: "프란체스코 카마르다", team_id: 867, position: "Attacker" },
  { id: 8643, name: "K. N'Dri", korean_name: "크리스티앙 은드리", team_id: 867, position: "Attacker" },
  { id: 428278, name: "M. Jović", korean_name: "마르코 요비치", team_id: 867, position: "Attacker" },
  { id: 264122, name: "N. Štulić", korean_name: "니콜라 스툴리치", team_id: 867, position: "Attacker" },
  { id: 31507, name: "R. Sottil", korean_name: "리카르도 소틸", team_id: 867, position: "Attacker" },
  { id: 6662, name: "S. Pierotti", korean_name: "산티아고 피에로티", team_id: 867, position: "Attacker" },
  { id: 47182, name: "Tete Morente", korean_name: "테테 모렌테", team_id: 867, position: "Attacker" },
];

// Napoli (Team ID: 492) - 29명
export const NAPOLI_PLAYERS: PlayerMapping[] = [
  { id: 312, name: "A. Meret", korean_name: "알렉스 메레", team_id: 492, position: "Goalkeeper" },
  { id: 355007, name: "Arda Yazıcı", korean_name: "아르다 야즈즈", team_id: 492, position: "Goalkeeper" },
  { id: 529998, name: "M. Ferrante", korean_name: "마티아스 페란테", team_id: 492, position: "Goalkeeper" },
  { id: 32172, name: "N. Contini", korean_name: "니키타 콘티니", team_id: 492, position: "Goalkeeper" },
  { id: 31156, name: "V. Milinković-Savić", korean_name: "바냐 밀린코비치-사비치", team_id: 492, position: "Goalkeeper" },
  { id: 31226, name: "A. Buongiorno", korean_name: "알레산드로 부온조르노", team_id: 492, position: "Defender" },
  { id: 1314, name: "Amir Rrahmani", korean_name: "아미르 라마니", team_id: 492, position: "Defender" },
  { id: 31042, name: "G. Di Lorenzo", korean_name: "조반니 디 로렌초", team_id: 492, position: "Defender" },
  { id: 774, name: "Juan Jesus", korean_name: "주앙 지저스", team_id: 492, position: "Defender" },
  { id: 862, name: "L. Spinazzola", korean_name: "레오나르도 스피나촐라", team_id: 492, position: "Defender" },
  { id: 388547, name: "Luca Marianucci", korean_name: "루카 마리아누치", team_id: 492, position: "Defender" },
  { id: 162032, name: "Miguel Gutiérrez", korean_name: "미겔 구티에레스", team_id: 492, position: "Defender" },
  { id: 47254, name: "M. Olivera", korean_name: "마티아스 올리베라", team_id: 492, position: "Defender" },
  { id: 31390, name: "P. Mazzocchi", korean_name: "파스콸레 마초키", team_id: 492, position: "Defender" },
  { id: 37604, name: "S. Beukema", korean_name: "샘 베우케마", team_id: 492, position: "Defender" },
  { id: 347395, name: "A. Vergara", korean_name: "안토니오 베르가라", team_id: 492, position: "Midfielder" },
  { id: 3406, name: "A. Zambo Anguissa", korean_name: "안드레-프랑크 잠보 앙기사", team_id: 492, position: "Midfielder" },
  { id: 130423, name: "B. Gilmour", korean_name: "빌리 길모어", team_id: 492, position: "Midfielder" },
  { id: 341914, name: "C. Saco", korean_name: "첼리오 사코", team_id: 492, position: "Midfielder" },
  { id: 552, name: "David Neres", korean_name: "다비드 네레스", team_id: 492, position: "Midfielder" },
  { id: 1358, name: "E. Elmas", korean_name: "엘리프 엘마스", team_id: 492, position: "Midfielder" },
  { id: 629, name: "K. De Bruyne", korean_name: "케빈 더 브라위너", team_id: 492, position: "Midfielder" },
  { id: 335102, name: "L. Hasa", korean_name: "루이스 하사", team_id: 492, position: "Midfielder" },
  { id: 219, name: "M. Politano", korean_name: "마테오 폴리타노", team_id: 492, position: "Midfielder" },
  { id: 47439, name: "S. Lobotka", korean_name: "스타니슬라프 로보트카", team_id: 492, position: "Midfielder" },
  { id: 903, name: "S. McTominay", korean_name: "스콧 맥토미네이", team_id: 492, position: "Midfielder" },
  { id: 341912, name: "G. Ambrosino", korean_name: "주세페 암브로시노", team_id: 492, position: "Attacker" },
  { id: 199089, name: "L. Lucca", korean_name: "로렌초 루카", team_id: 492, position: "Attacker" },
  { id: 544, name: "N. Lang", korean_name: "노아 랑", team_id: 492, position: "Attacker" },
  { id: 288006, name: "R. Højlund", korean_name: "라스무스 회율룬", team_id: 492, position: "Attacker" },
  { id: 907, name: "R. Lukaku", korean_name: "로멜루 루카쿠", team_id: 492, position: "Attacker" },
  { id: 528492, name: "Ferrante Mathias", korean_name: "페란테 마티아스", team_id: 492, position: null },
];

// Parma (Team ID: 523) - 31명
export const PARMA_PLAYERS: PlayerMapping[] = [
  { id: 180762, name: "E. Corvi", korean_name: "엔리코 코르비", team_id: 523, position: "Goalkeeper" },
  { id: 237268, name: "F. Rinaldi", korean_name: "파비오 리날디", team_id: 523, position: "Goalkeeper" },
  { id: 470961, name: "G. Astaldi", korean_name: "지울리오 아스탈디", team_id: 523, position: "Goalkeeper" },
  { id: 199578, name: "Z. Suzuki", korean_name: "제온 스즈키", team_id: 523, position: "Goalkeeper" },
  { id: 348568, name: "A. Circati", korean_name: "알레산드로 치르카티", team_id: 523, position: "Defender" },
  { id: 203483, name: "A. N'Diaye", korean_name: "아마두 은디아예", team_id: 523, position: "Defender" },
  { id: 180763, name: "B. Balogh", korean_name: "보트온드 발로그", team_id: 523, position: "Defender" },
  { id: 30420, name: "E. Del Prato", korean_name: "엔리코 델 프라토", team_id: 523, position: "Defender" },
  { id: 6221, name: "L. Valenti", korean_name: "리카르도 발렌티", team_id: 523, position: "Defender" },
  { id: 323369, name: "M. Løvik", korean_name: "마티아스 뢰비크", team_id: 523, position: "Defender" },
  { id: 428237, name: "M. Troilo", korean_name: "마테오 트로일로", team_id: 523, position: "Defender" },
  { id: 470975, name: "N. Trabucchi", korean_name: "니콜로 트라부키", team_id: 523, position: "Defender" },
  { id: 348309, name: "P. Amoran", korean_name: "피에르 아모란", team_id: 523, position: "Defender" },
  { id: 628, name: "Adrián Bernabé", korean_name: "아드리안 베르나베", team_id: 523, position: "Midfielder" },
  { id: 362061, name: "B. Cremaschi", korean_name: "브루노 크레마스키", team_id: 523, position: "Midfielder" },
  { id: 362752, name: "C. Ordoñez", korean_name: "세사르 오르도녜스", team_id: 523, position: "Midfielder" },
  { id: 446006, name: "E. Plicco", korean_name: "에마누엘레 플리코", team_id: 523, position: "Midfielder" },
  { id: 91358, name: "E. Valeri", korean_name: "엔리코 발레리", team_id: 523, position: "Midfielder" },
  { id: 1208, name: "Hernani", korean_name: "에르나니", team_id: 523, position: "Midfielder" },
  { id: 308836, name: "M. Keita", korean_name: "만델라 케이타", team_id: 523, position: "Midfielder" },
  { id: 6409, name: "N. Estévez", korean_name: "나우엘 에스테베스", team_id: 523, position: "Midfielder" },
  { id: 161569, name: "O. Sørensen", korean_name: "올리버 소렌센", team_id: 523, position: "Midfielder" },
  { id: 499380, name: "S. Britschgi", korean_name: "스벤 브리치기", team_id: 523, position: "Midfielder" },
  { id: 40592, name: "A. Benedyczak", korean_name: "아드리안 베네디차크", team_id: 523, position: "Attacker" },
  { id: 289304, name: "A. Joujou", korean_name: "아민 주주", team_id: 523, position: "Attacker" },
  { id: 72388, name: "G. Charpentier", korean_name: "가브리엘 샤르팡티에", team_id: 523, position: "Attacker" },
  { id: 161859, name: "G. Oristanio", korean_name: "가에타노 오리스타니오", team_id: 523, position: "Attacker" },
  { id: 191979, name: "J. Ondrejka", korean_name: "얀 온드레이카", team_id: 523, position: "Attacker" },
  { id: 292172, name: "Mateo Pellegrino", korean_name: "마테오 펠레그리노", team_id: 523, position: "Attacker" },
  { id: 31692, name: "M. Đurić", korean_name: "밀란 주리치", team_id: 523, position: "Attacker" },
  { id: 292543, name: "M. Frigan", korean_name: "마테오 프리간", team_id: 523, position: "Attacker" },
  { id: 48193, name: "P. Almqvist", korean_name: "폰투스 알름크비스트", team_id: 523, position: "Attacker" },
  { id: 1649, name: "P. Cutrone", korean_name: "파트리크 쿠트로네", team_id: 523, position: "Attacker" },
  { id: 201466, name: "T. Begić", korean_name: "테오 베기치", team_id: 523, position: "Attacker" },
];

// Pisa (Team ID: 801) - 39명
export const PISA_PLAYERS: PlayerMapping[] = [
  { id: 30733, name: "A. Šemper", korean_name: "에이드리언 셈페르", team_id: 801, position: "Goalkeeper" },
  { id: 374142, name: "A. Vuković", korean_name: "알렉산다르 부코비치", team_id: 801, position: "Goalkeeper" },
  { id: 30792, name: "Nícolas", korean_name: "니콜라스", team_id: 801, position: "Goalkeeper" },
  { id: 50054, name: "S. Scuffet", korean_name: "시모네 스쿠페트", team_id: 801, position: "Goalkeeper" },
  { id: 30469, name: "A. Calabresi", korean_name: "안토니오 칼라브레시", team_id: 801, position: "Defender" },
  { id: 31604, name: "A. Caracciolo", korean_name: "안토니오 카라치올로", team_id: 801, position: "Defender" },
  { id: 43129, name: "A. Rus", korean_name: "안주르 루스", team_id: 801, position: "Defender" },
  { id: 485960, name: "D. Denoon", korean_name: "다비드 데눈", team_id: 801, position: "Defender" },
  { id: 341838, name: "G. Bonfanti", korean_name: "조반니 본판티", team_id: 801, position: "Defender" },
  { id: 526688, name: "Jeremy Kandje Mbambi", korean_name: "제레미 칸제 밤비", team_id: 801, position: "Defender" },
  { id: 435548, name: "Mateus Lusuardi", korean_name: "마테우스 루수아르디", team_id: 801, position: "Defender" },
  { id: 526861, name: "M. Casarosa", korean_name: "마테오 카사로사", team_id: 801, position: "Defender" },
  { id: 56275, name: "P. Beruatto", korean_name: "피에트로 베루아토", team_id: 801, position: "Defender" },
  { id: 314, name: "Raúl Albiol", korean_name: "라울 알비올", team_id: 801, position: "Defender" },
  { id: 302069, name: "S. Angori", korean_name: "사무엘레 앙고리", team_id: 801, position: "Defender" },
  { id: 91503, name: "S. Canestrelli", korean_name: "세바스티아노 카네스트렐리", team_id: 801, position: "Defender" },
  { id: 129790, name: "Tomás Esteves", korean_name: "토마스 에스테베스", team_id: 801, position: "Defender" },
  { id: 36910, name: "C. Stengs", korean_name: "칼빈 스텡스", team_id: 801, position: "Midfielder" },
  { id: 408635, name: "E. Akinsanmiro", korean_name: "에보니 아킨산미로", team_id: 801, position: "Midfielder" },
  { id: 497255, name: "G. Maucci", korean_name: "지오반니 마우치", team_id: 801, position: "Midfielder" },
  { id: 325387, name: "G. Piccinini", korean_name: "가브리엘레 피치니니", team_id: 801, position: "Midfielder" },
  { id: 56293, name: "I. Touré", korean_name: "이브라힘 투레", team_id: 801, position: "Midfielder" },
  { id: 364600, name: "İ. Vural", korean_name: "이브라힘 부랄", team_id: 801, position: "Midfielder" },
  { id: 866, name: "J. Cuadrado", korean_name: "후안 쿠아드라도", team_id: 801, position: "Midfielder" },
  { id: 951, name: "M. Aebischer", korean_name: "미셸 아에비셔", team_id: 801, position: "Midfielder" },
  { id: 396767, name: "Mattia Sala", korean_name: "마티아 살라", team_id: 801, position: "Midfielder" },
  { id: 384831, name: "M. Durmush", korean_name: "무라트 두르무슈", team_id: 801, position: "Midfielder" },
  { id: 15723, name: "M. Højholt", korean_name: "마티아스 회욜트", team_id: 801, position: "Midfielder" },
  { id: 30753, name: "M. Léris", korean_name: "메흐디 레리스", team_id: 801, position: "Midfielder" },
  { id: 30723, name: "M. Marin", korean_name: "마리우스 마린", team_id: 801, position: "Midfielder" },
  { id: 335043, name: "Ž. Jevšenak", korean_name: "제스코 예브세나크", team_id: 801, position: "Midfielder" },
  { id: 127055, name: "A. Arena", korean_name: "안토니노 아레나", team_id: 801, position: "Attacker" },
  { id: 180982, name: "A. Lind", korean_name: "알렉산더 린드", team_id: 801, position: "Attacker" },
  { id: 32225, name: "E. Dubickas", korean_name: "에도아르도 두비카스", team_id: 801, position: "Attacker" },
  { id: 91576, name: "E. Giani", korean_name: "에두아르도 지아니", team_id: 801, position: "Attacker" },
  { id: 30755, name: "E. Vignato", korean_name: "에마누엘 비냐토", team_id: 801, position: "Attacker" },
  { id: 331678, name: "H. Meister", korean_name: "헨리크 마이스터", team_id: 801, position: "Attacker" },
  { id: 475089, name: "Lorenzo Tosi", korean_name: "로렌초 토시", team_id: 801, position: "Attacker" },
  { id: 403300, name: "Lorran", korean_name: "로란", team_id: 801, position: "Attacker" },
  { id: 510473, name: "Louis Buffon", korean_name: "루이 뷔퐁", team_id: 801, position: "Attacker" },
  { id: 31318, name: "M'Bala Nzola", korean_name: "음발라 은졸라", team_id: 801, position: "Attacker" },
  { id: 20959, name: "M. Tramoni", korean_name: "마티스 트라모니", team_id: 801, position: "Attacker" },
  { id: 31560, name: "S. Moreo", korean_name: "스테파노 모레오", team_id: 801, position: "Attacker" },
];

// Sassuolo (Team ID: 488) - 33명
export const SASSUOLO_PLAYERS: PlayerMapping[] = [
  { id: 616, name: "A. Murić", korean_name: "아데미르 무리치", team_id: 488, position: "Goalkeeper" },
  { id: 30766, name: "A. Russo", korean_name: "알레산드로 루소", team_id: 488, position: "Goalkeeper" },
  { id: 30518, name: "G. Satalino", korean_name: "주세페 사탈리노", team_id: 488, position: "Goalkeeper" },
  { id: 292519, name: "G. Zacchi", korean_name: "지오반니 자키", team_id: 488, position: "Goalkeeper" },
  { id: 30519, name: "S. Turati", korean_name: "스테파노 투라티", team_id: 488, position: "Goalkeeper" },
  { id: 127802, name: "C. Odenthal", korean_name: "카스페르 오덴탈", team_id: 488, position: "Defender" },
  { id: 342055, name: "E. Pieragnolo", korean_name: "에두아르도 피에라뇰로", team_id: 488, position: "Defender" },
  { id: 41371, name: "Fali Candé", korean_name: "팔리 칸데", team_id: 488, position: "Defender" },
  { id: 342653, name: "F. Missori", korean_name: "피오레 미소리", team_id: 488, position: "Defender" },
  { id: 30556, name: "F. Romagna", korean_name: "필리포 로마냐", team_id: 488, position: "Defender" },
  { id: 135526, name: "J. Doig", korean_name: "조시 도이그", team_id: 488, position: "Defender" },
  { id: 37651, name: "J. Idzes", korean_name: "얀 이제스", team_id: 488, position: "Defender" },
  { id: 40582, name: "S. Walukiewicz", korean_name: "세바스티안 발루키에비치", team_id: 488, position: "Defender" },
  { id: 271350, name: "T. Muharemović", korean_name: "타리크 무하레모비치", team_id: 488, position: "Defender" },
  { id: 128338, name: "W. Coulibaly", korean_name: "우마르 쿨리발리", team_id: 488, position: "Defender" },
  { id: 57899, name: "Yeferson David Paz Paz", korean_name: "예페르손 파스", team_id: 488, position: "Defender" },
  { id: 59513, name: "Y. Paz", korean_name: "예페르손 파스", team_id: 488, position: "Defender" },
  { id: 68407, name: "A. Ghion", korean_name: "안드레아 기온", team_id: 488, position: "Midfielder" },
  { id: 127413, name: "A. Vranckx", korean_name: "아스터 브란크스", team_id: 488, position: "Midfielder" },
  { id: 291780, name: "D. Boloca", korean_name: "다니엘 볼로카", team_id: 488, position: "Midfielder" },
  { id: 281291, name: "E. Iannoni", korean_name: "에도아르도 이안노니", team_id: 488, position: "Midfielder" },
  { id: 56318, name: "F. Caligara", korean_name: "파비오 칼리가라", team_id: 488, position: "Midfielder" },
  { id: 328046, name: "I. Koné", korean_name: "이사 코네", team_id: 488, position: "Midfielder" },
  { id: 39143, name: "K. Thorstvedt", korean_name: "크리스티안 토르스트베트", team_id: 488, position: "Midfielder" },
  { id: 343562, name: "L. Lipani", korean_name: "루카 리파니", team_id: 488, position: "Midfielder" },
  { id: 902, name: "N. Matić", korean_name: "네만야 마티치", team_id: 488, position: "Midfielder" },
  { id: 278190, name: "A. Álvarez", korean_name: "아구스틴 알바레스", team_id: 488, position: "Attacker" },
  { id: 263699, name: "A. Fadera", korean_name: "아민 파데라", team_id: 488, position: "Attacker" },
  { id: 2215, name: "A. Laurienté", korean_name: "아르망 로리엔테", team_id: 488, position: "Attacker" },
  { id: 31094, name: "A. Pinamonti", korean_name: "안드레아 피나몬티", team_id: 488, position: "Attacker" },
  { id: 342035, name: "C. Volpato", korean_name: "크리스티안 볼파토", team_id: 488, position: "Attacker" },
  { id: 30537, name: "D. Berardi", korean_name: "도메니코 베라르디", team_id: 488, position: "Attacker" },
  { id: 31440, name: "L. Moro", korean_name: "루카 모로", team_id: 488, position: "Attacker" },
  { id: 264739, name: "L. Skjellerup", korean_name: "루카스 스켈레루프", team_id: 488, position: "Attacker" },
  { id: 30849, name: "N. Pierini", korean_name: "니콜라 피에리니", team_id: 488, position: "Attacker" },
  { id: 91490, name: "S. Mulattieri", korean_name: "사무엘레 물라티에리", team_id: 488, position: "Attacker" },
  { id: 128478, name: "W. Cheddira", korean_name: "왈리드 체디라", team_id: 488, position: "Attacker" },
];

// Torino (Team ID: 503) - 29명
export const TORINO_PLAYERS: PlayerMapping[] = [
  { id: 30642, name: "A. Paleari", korean_name: "알베르토 팔레아리", team_id: 503, position: "Goalkeeper" },
  { id: 56266, name: "F. Israel", korean_name: "펠리페 이스라엘", team_id: 503, position: "Goalkeeper" },
  { id: 42796, name: "M. Popa", korean_name: "마티아스 포파", team_id: 503, position: "Goalkeeper" },
  { id: 349232, name: "A. Dembélé", korean_name: "알리 뎀벨레", team_id: 503, position: "Defender" },
  { id: 14329, name: "A. Ismajli", korean_name: "아르디안 이스마일리", team_id: 503, position: "Defender" },
  { id: 18799, name: "A. Masina", korean_name: "아담 마시나", team_id: 503, position: "Defender" },
  { id: 22174, name: "A. Tamèze", korean_name: "아드리앙 타메즈", team_id: 503, position: "Defender" },
  { id: 30396, name: "C. Biraghi", korean_name: "크리스티아노 비라기", team_id: 503, position: "Defender" },
  { id: 2553, name: "G. Maripán", korean_name: "기예르모 마리판", team_id: 503, position: "Defender" },
  { id: 156490, name: "N. Nkounkou", korean_name: "니엘스 은쿤쿠", team_id: 503, position: "Defender" },
  { id: 535, name: "P. Schuurs", korean_name: "페르 슈르스", team_id: 503, position: "Defender" },
  { id: 122468, name: "Saúl Coco", korean_name: "사울 코코", team_id: 503, position: "Defender" },
  { id: 268728, name: "S. Sazonov", korean_name: "세바스티안 사조노프", team_id: 503, position: "Defender" },
  { id: 343538, name: "A. Ciammaglichella", korean_name: "알레시오 참말리켈라", team_id: 503, position: "Midfielder" },
  { id: 270507, name: "C. Casadei", korean_name: "체사레 카사데이", team_id: 503, position: "Midfielder" },
  { id: 336573, name: "E. İlkhan", korean_name: "에므라 일칸", team_id: 503, position: "Midfielder" },
  { id: 138777, name: "F. Anjorin", korean_name: "파우스토 안조린", team_id: 503, position: "Midfielder" },
  { id: 343189, name: "G. Gineitis", korean_name: "기도 기네이티스", team_id: 503, position: "Midfielder" },
  { id: 46170, name: "I. Ilić", korean_name: "이반 일리치", team_id: 503, position: "Midfielder" },
  { id: 275776, name: "K. Asllani", korean_name: "크리스티안 아슬라니", team_id: 503, position: "Midfielder" },
  { id: 39362, name: "M. Pedersen", korean_name: "마르쿠스 페데르센", team_id: 503, position: "Midfielder" },
  { id: 842, name: "N. Vlašić", korean_name: "니콜라 블라시치", team_id: 503, position: "Midfielder" },
  { id: 452430, name: "S. Perciun", korean_name: "스테판 페르치운", team_id: 503, position: "Midfielder" },
  { id: 25353, name: "V. Lazaro", korean_name: "발렌티노 라자로", team_id: 503, position: "Midfielder" },
  { id: 383006, name: "A. Njie", korean_name: "알리우 은지에", team_id: 503, position: "Attacker" },
  { id: 19524, name: "C. Adams", korean_name: "체 아담스", team_id: 503, position: "Attacker" },
  { id: 85, name: "C. Ngonge", korean_name: "시릴 은공게", team_id: 503, position: "Attacker" },
  { id: 2495, name: "D. Zapata", korean_name: "두반 사파타", team_id: 503, position: "Attacker" },
  { id: 30414, name: "G. Simeone", korean_name: "조반니 시메오네", team_id: 503, position: "Attacker" },
  { id: 243, name: "Z. Aboukhlal", korean_name: "자카리아 아부클랄", team_id: 503, position: "Attacker" },
  { id: 343332, name: "Zannetos Savva", korean_name: "자네토스 사바", team_id: 503, position: "Attacker" },
  { id: 551411, name: "M. Popa", korean_name: "마티아스 포파", team_id: 503, position: null },
];

// Udinese (Team ID: 494) - 34명
export const UDINESE_PLAYERS: PlayerMapping[] = [
  { id: 418940, name: "A. Nunziante", korean_name: "안젤로 눈치안테", team_id: 494, position: "Goalkeeper" },
  { id: 189, name: "D. Padelli", korean_name: "다니엘레 파델리", team_id: 494, position: "Goalkeeper" },
  { id: 528604, name: "Gioele Venuti", korean_name: "조엘레 베누티", team_id: 494, position: "Goalkeeper" },
  { id: 551412, name: "G. Venuti", korean_name: "조엘레 베누티", team_id: 494, position: "Goalkeeper" },
  { id: 0, name: "G. Venuti", korean_name: "조엘레 베누티", team_id: 494, position: "Goalkeeper" },
  { id: 143648, name: "M. Okoye", korean_name: "매들린 오코예", team_id: 494, position: "Goalkeeper" },
  { id: 197830, name: "R. Sava", korean_name: "라즐란 사바", team_id: 494, position: "Goalkeeper" },
  { id: 506554, name: "C. De Paoli", korean_name: "크리스티안 데 파올리", team_id: 494, position: "Defender" },
  { id: 18797, name: "C. Kabasele", korean_name: "크리스티안 카바셀레", team_id: 494, position: "Defender" },
  { id: 19824, name: "J. Zemura", korean_name: "조던 제무라", team_id: 494, position: "Defender" },
  { id: 36916, name: "K. Ehizibue", korean_name: "킹슬리 에히지부에", team_id: 494, position: "Defender" },
  { id: 422156, name: "M. Palma", korean_name: "마르코 팔마", team_id: 494, position: "Defender" },
  { id: 315249, name: "N. Bertola", korean_name: "니콜라 베르톨라", team_id: 494, position: "Defender" },
  { id: 656, name: "O. Solet", korean_name: "우마르 솔레", team_id: 494, position: "Defender" },
  { id: 318053, name: "S. Goglichidze", korean_name: "슈하 고글리키제", team_id: 494, position: "Defender" },
  { id: 281495, name: "T. Kristensen", korean_name: "토마스 크리스텐센", team_id: 494, position: "Defender" },
  { id: 347644, name: "A. Atta", korean_name: "아브디 아타", team_id: 494, position: "Midfielder" },
  { id: 490138, name: "A. Camara", korean_name: "아미누 카마라", team_id: 494, position: "Midfielder" },
  { id: 162907, name: "A. Zanoli", korean_name: "알레산드로 자놀리", team_id: 494, position: "Midfielder" },
  { id: 22007, name: "H. Kamara", korean_name: "하사네 카마라", team_id: 494, position: "Midfielder" },
  { id: 2990, name: "Idrissa Gana Gueye", korean_name: "이드리사 가나 게예", team_id: 494, position: "Midfielder" },
  { id: 541, name: "J. Ekkelenkamp", korean_name: "위르겐 에켈렌캄프", team_id: 494, position: "Midfielder" },
  { id: 48047, name: "J. Karlström", korean_name: "예스퍼 칼스트룀", team_id: 494, position: "Midfielder" },
  { id: 1939, name: "J. Piotrowski", korean_name: "야쿠프 피오트롭스키", team_id: 494, position: "Midfielder" },
  { id: 343558, name: "L. Miller", korean_name: "루카 밀러", team_id: 494, position: "Midfielder" },
  { id: 179502, name: "M. Ballarini", korean_name: "마테오 발라리니", team_id: 494, position: "Midfielder" },
  { id: 527040, name: "N. Popov", korean_name: "니콜라이 포포프", team_id: 494, position: "Midfielder" },
  { id: 182560, name: "Oier Zarraga", korean_name: "오이에르 사라가", team_id: 494, position: "Midfielder" },
  { id: 142442, name: "Rui Modesto", korean_name: "루이 모데스토", team_id: 494, position: "Midfielder" },
  { id: 7591, name: "S. Lovrić", korean_name: "사니 로브리치", team_id: 494, position: "Midfielder" },
  { id: 40594, name: "A. Buksa", korean_name: "아담 북사", team_id: 494, position: "Attacker" },
  { id: 910, name: "A. Sánchez", korean_name: "알렉시스 산체스", team_id: 494, position: "Attacker" },
  { id: 9975, name: "Brenner", korean_name: "브레네르", team_id: 494, position: "Attacker" },
  { id: 344165, name: "D. Pizarro", korean_name: "다미안 피사로", team_id: 494, position: "Attacker" },
  { id: 493365, name: "G. Vinciati", korean_name: "조반니 빈치아티", team_id: 494, position: "Attacker" },
  { id: 434410, name: "I. Gueye", korean_name: "일리만 게예", team_id: 494, position: "Attacker" },
  { id: 330599, name: "Iker Bravo", korean_name: "이케르 브라보", team_id: 494, position: "Attacker" },
  { id: 19185, name: "K. Davis", korean_name: "켈시 데이비스", team_id: 494, position: "Attacker" },
  { id: 786, name: "N. Zaniolo", korean_name: "니콜로 자니올로", team_id: 494, position: "Attacker" },
  { id: 1134, name: "V. Bayo", korean_name: "비센테 바요", team_id: 494, position: "Attacker" },
  { id: 551410, name: "I. Gueye", korean_name: "일리만 게예", team_id: 494, position: null },
];

// Verona (Team ID: 504) - 34명
export const VERONA_PLAYERS: PlayerMapping[] = [
  { id: 350539, name: "G. Toniolo", korean_name: "잔마르코 토니올로", team_id: 504, position: "Goalkeeper" },
  { id: 30611, name: "L. Montipò", korean_name: "로렌초 몬티포", team_id: 504, position: "Goalkeeper" },
  { id: 546632, name: "Mirko Castagnini", korean_name: "미르코 카스타니니", team_id: 504, position: "Goalkeeper" },
  { id: 31383, name: "S. Perilli", korean_name: "시모네 페릴리", team_id: 504, position: "Goalkeeper" },
  { id: 25061, name: "A. Bella-Kotchap", korean_name: "아를렌 벨라-코차프", team_id: 504, position: "Defender" },
  { id: 343565, name: "A. Kurti", korean_name: "아론 쿠르티", team_id: 504, position: "Defender" },
  { id: 418846, name: "D. De Battisti", korean_name: "다니엘레 데 바티스티", team_id: 504, position: "Defender" },
  { id: 153408, name: "D. Oyegoke", korean_name: "다비드 오예고케", team_id: 504, position: "Defender" },
  { id: 20656, name: "E. Ebosse", korean_name: "엘리 에보세", team_id: 504, position: "Defender" },
  { id: 527889, name: "Fallou Cham", korean_name: "팔루 참", team_id: 504, position: "Defender" },
  { id: 527234, name: "F. Cham", korean_name: "팔루 참", team_id: 504, position: "Defender" },
  { id: 15909, name: "M. Frese", korean_name: "마르쿠스 프레제", team_id: 504, position: "Defender" },
  { id: 311071, name: "N. Valentini", korean_name: "니콜로 발렌티니", team_id: 504, position: "Defender" },
  { id: 368129, name: "T. Slotsager", korean_name: "테스피언 슬롯사예르", team_id: 504, position: "Defender" },
  { id: 47277, name: "Unai Núñez", korean_name: "우나이 누녜스", team_id: 504, position: "Defender" },
  { id: 15912, name: "V. Nelsson", korean_name: "빅토르 넬손", team_id: 504, position: "Defender" },
  { id: 1090, name: "A. Bernede", korean_name: "안토니오 베르네데", team_id: 504, position: "Midfielder" },
  { id: 37437, name: "A. Harroui", korean_name: "아민 하루이", team_id: 504, position: "Midfielder" },
  { id: 42006, name: "Al Musrati", korean_name: "알 무스라티", team_id: 504, position: "Midfielder" },
  { id: 405273, name: "Charlys", korean_name: "샤를리스", team_id: 504, position: "Midfielder" },
  { id: 22239, name: "C. Niasse", korean_name: "셰이크 니아세", team_id: 504, position: "Midfielder" },
  { id: 14327, name: "D. Bradarić", korean_name: "도마고이 브라다리치", team_id: 504, position: "Midfielder" },
  { id: 867, name: "G. Kastanos", korean_name: "그리고리스 카스타노스", team_id: 504, position: "Midfielder" },
  { id: 31678, name: "J. Akpa Akpro", korean_name: "장-다니엘 악파 악프로", team_id: 504, position: "Midfielder" },
  { id: 364415, name: "Jesús Santiago", korean_name: "헤수스 산티아고", team_id: 504, position: "Midfielder" },
  { id: 303362, name: "R. Belghali", korean_name: "라옌 벨갈리", team_id: 504, position: "Midfielder" },
  { id: 203, name: "R. Gagliardini", korean_name: "로베르토 갈리아르디니", team_id: 504, position: "Midfielder" },
  { id: 418, name: "S. Serdar", korean_name: "살리흐 외즈잔", team_id: 504, position: "Midfielder" },
  { id: 194837, name: "T. Suslov", korean_name: "토마시 수슬로프", team_id: 504, position: "Midfielder" },
  { id: 236955, name: "A. Sarr", korean_name: "아비 사르", team_id: 504, position: "Attacker" },
  { id: 343287, name: "D. Livramento", korean_name: "다비드 리브라멘토", team_id: 504, position: "Attacker" },
  { id: 59421, name: "D. Mosquera", korean_name: "다니엘 모스케라", team_id: 504, position: "Attacker" },
  { id: 312615, name: "Giovane", korean_name: "지오바네", team_id: 504, position: "Attacker" },
  { id: 368260, name: "G. Orban", korean_name: "기프트 오르반", team_id: 504, position: "Attacker" },
  { id: 352940, name: "Ioan Vermeșan", korean_name: "요안 베르메샨", team_id: 504, position: "Attacker" },
  { id: 408634, name: "J. Ajayi", korean_name: "제이콥 아자이", team_id: 504, position: "Attacker" },
  { id: 340076, name: "Luca Monticelli", korean_name: "루카 몬티첼리", team_id: 504, position: "Attacker" },
  { id: 395761, name: "M. Lambourde", korean_name: "마틴 람부르드", team_id: 504, position: "Attacker" },
  { id: 180128, name: "S. Mitrović", korean_name: "스테판 미트로비치", team_id: 504, position: "Attacker" },
];

// Serie A Part 2 모든 선수 통합
export const SERIE_A_PART2_PLAYERS: PlayerMapping[] = [
  ...JUVENTUS_PLAYERS,
  ...LAZIO_PLAYERS,
  ...LECCE_PLAYERS,
  ...NAPOLI_PLAYERS,
  ...PARMA_PLAYERS,
  ...PISA_PLAYERS,
  ...SASSUOLO_PLAYERS,
  ...TORINO_PLAYERS,
  ...UDINESE_PLAYERS,
  ...VERONA_PLAYERS,
];

