import { siteUrl } from '@/shared/seo/sitemap';

const DAUM_WEBMASTER_PIN =
  '#DaumWebMasterTool:01765042dd66f6f3757a98813cab0c841580123d8059d5895751b2575132466f:Qc8LDKHH1AV7wtQw2Sv8Rw==';

export const revalidate = 3600;

const publicCrawlerRules = [
  'Allow: /',
  'Allow: /about',
  'Allow: /guide',
  'Allow: /contact',
  'Allow: /boards/',
  'Allow: /livescore/',
  'Allow: /transfers/',
  'Allow: /shop',
  'Allow: /rss.xml',
  'Allow: /sitemap.xml',
  'Allow: /sitemaps/',
  'Allow: /llms.txt',
  'Disallow: /_next/image',
  'Disallow: /signin',
  'Disallow: /signup',
  'Disallow: /social-signup',
  'Disallow: /auth',
  'Disallow: /help',
  'Disallow: /cdn-cgi/',
  'Disallow: /settings',
  'Disallow: /notifications',
  'Disallow: /admin',
  'Disallow: /api/',
  'Disallow: /user/',
  'Disallow: /search',
  'Disallow: /boards/*/create',
  'Disallow: /boards/*/edit',
  'Disallow: /ui',
];

export async function GET() {
  const lines = [
    'User-agent: *',
    'Allow: /',
    'Allow: /livescore/',
    'Disallow: /signin',
    'Disallow: /signup',
    'Disallow: /social-signup',
    'Disallow: /auth',
    'Disallow: /cdn-cgi/',
    'Disallow: /_next/image',
    'Disallow: /help',
    'Disallow: /settings',
    'Disallow: /notifications',
    'Disallow: /admin',
    'Disallow: /api/',
    'Disallow: /user/',
    'Disallow: /search',
    'Disallow: /boards/*/create',
    'Disallow: /boards/*/edit',
    'Disallow: /ui',
    '',
    'User-agent: Googlebot',
    'User-agent: Googlebot-Image',
    'User-agent: Googlebot-News',
    'User-agent: Googlebot-Video',
    'User-agent: Google-InspectionTool',
    'User-agent: GoogleOther',
    'User-agent: GoogleOther-Image',
    'User-agent: GoogleOther-Video',
    'User-agent: AdsBot-Google',
    'User-agent: AdsBot-Google-Mobile',
    'User-agent: Mediapartners-Google',
    'User-agent: APIs-Google',
    'User-agent: Storebot-Google',
    'Allow: /',
    'Allow: /livescore/',
    'Disallow: /signin',
    'Disallow: /signup',
    'Disallow: /social-signup',
    'Disallow: /auth',
    'Disallow: /cdn-cgi/',
    'Disallow: /_next/image',
    'Disallow: /help',
    'Disallow: /settings',
    'Disallow: /notifications',
    'Disallow: /admin',
    'Disallow: /api/',
    'Disallow: /user/',
    'Disallow: /search',
    'Disallow: /boards/*/create',
    'Disallow: /boards/*/edit',
    'Disallow: /ui',
    '',
    'User-agent: YandexBot',
    'Allow: /',
    'Allow: /shop',
    'Disallow: /signin',
    'Disallow: /signup',
    'Disallow: /social-signup',
    'Disallow: /auth',
    'Disallow: /cdn-cgi/',
    'Disallow: /_next/image',
    'Disallow: /help',
    'Disallow: /user/',
    'Disallow: /settings',
    'Disallow: /notifications',
    'Disallow: /admin',
    'Disallow: /api/',
    'Disallow: /search',
    'Disallow: /boards/*/create',
    'Disallow: /boards/*/edit',
    'Disallow: /ui',
    '',
    'User-agent: bingbot',
    'Allow: /',
    'Allow: /shop',
    'Disallow: /signin',
    'Disallow: /signup',
    'Disallow: /social-signup',
    'Disallow: /auth',
    'Disallow: /cdn-cgi/',
    'Disallow: /_next/image',
    'Disallow: /help',
    'Disallow: /user/',
    'Disallow: /settings',
    'Disallow: /notifications',
    'Disallow: /admin',
    'Disallow: /api/',
    'Disallow: /search',
    'Disallow: /boards/*/create',
    'Disallow: /boards/*/edit',
    'Disallow: /ui',
    '',
    'User-agent: Yeti',
    'Allow: /',
    'Allow: /shop',
    'Disallow: /signin',
    'Disallow: /signup',
    'Disallow: /social-signup',
    'Disallow: /auth',
    'Disallow: /cdn-cgi/',
    'Disallow: /_next/image',
    'Disallow: /help',
    'Disallow: /user/',
    'Disallow: /settings',
    'Disallow: /notifications',
    'Disallow: /admin',
    'Disallow: /api/',
    'Disallow: /search',
    'Disallow: /boards/*/create',
    'Disallow: /boards/*/edit',
    'Disallow: /ui',
    '',
    'User-agent: GPTBot',
    ...publicCrawlerRules,
    '',
    'User-agent: ChatGPT-User',
    ...publicCrawlerRules,
    '',
    'User-agent: OAI-SearchBot',
    ...publicCrawlerRules,
    '',
    'User-agent: ClaudeBot',
    'User-agent: Claude-SearchBot',
    'User-agent: PerplexityBot',
    'User-agent: Perplexity-User',
    'User-agent: Google-Extended',
    'User-agent: CCBot',
    'User-agent: Applebot-Extended',
    'User-agent: Bytespider',
    'User-agent: Amazonbot',
    'User-agent: FacebookBot',
    'User-agent: meta-externalagent',
    'User-agent: Meta-ExternalAgent',
    ...publicCrawlerRules,
    '',
    'User-agent: SERankingBot',
    'User-agent: SERankingBacklinksBot',
    'Disallow: /',
    '',
    `Sitemap: ${siteUrl('/sitemap.xml')}`,
    '',
    DAUM_WEBMASTER_PIN,
    '',
  ];

  return new Response(lines.join('\n'), {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
