// 자동생성 파일: 에레디비지에 선수 매핑
// 생성시각: 2025-10-11T09:09:07.856Z

export type PlayerMapping = {
  id: number;
  name: string;
  korean_name: string | null;
  team_id: number;
  position: "Goalkeeper" | "Defender" | "Midfielder" | "Attacker" | undefined;
  number?: number | null;
  age?: number | null;
};

// Ajax (Team ID: 194) - 50명
export const AJAX_PLAYERS: PlayerMapping[] = [
  { id: 41089, name: "Matheus", korean_name: "마테우스", team_id: 194, position: "Goalkeeper", number: 1, age: 33 },
  { id: 162687, name: "Vítězslav Jaroš", korean_name: "비테즐라프 야로시", team_id: 194, position: "Goalkeeper", number: 1, age: 24 },
  { id: 309766, name: "C. Setford", korean_name: "찰리 셋포드", team_id: 194, position: "Goalkeeper", number: 12, age: 21 },
  { id: 394700, name: "Joeri Jesse Heerkens", korean_name: "요에리 예세 헤르켄스", team_id: 194, position: "Goalkeeper", number: 12, age: 19 },
  { id: 47296, name: "G. Rulli", korean_name: "헤로니모 룰리", team_id: 194, position: "Goalkeeper", number: 16, age: 33 },
  { id: 37113, name: "R. Pasveer", korean_name: "렘코 파스페르", team_id: 194, position: "Goalkeeper", number: 22, age: 42 },
  { id: 24894, name: "D. Ramaj", korean_name: "디오니시스 라마이", team_id: 194, position: "Goalkeeper", number: 41, age: 24 },
  { id: 392258, name: "P. Reverson", korean_name: "파울루 레베르손", team_id: 194, position: "Goalkeeper", number: 52, age: 20 },
  { id: 162452, name: "D. Rensch", korean_name: "데빗 렌시", team_id: 194, position: "Defender", number: 2, age: 22 },
  { id: 56283, name: "Lucas Rosa", korean_name: "루카스 호사", team_id: 194, position: "Defender", number: 2, age: 25 },
  { id: 313941, name: "A. Gaaei", korean_name: "안톤 가에이", team_id: 194, position: "Defender", number: 3, age: 23 },
  { id: 341642, name: "J. Hato", korean_name: "요리엘 하토", team_id: 194, position: "Defender", number: 4, age: 19 },
  { id: 38114, name: "Ko Itakura", korean_name: "이타쿠라 코", team_id: 194, position: "Defender", number: 4, age: 28 },
  { id: 80219, name: "J. Medić", korean_name: "요시프 메디치", team_id: 194, position: "Defender", number: 5, age: 27 },
  { id: 36893, name: "O. Wijndal", korean_name: "오웬 베인달", team_id: 194, position: "Defender", number: 5, age: 26 },
  { id: 294684, name: "Y. Baas", korean_name: "요프 바스", team_id: 194, position: "Defender", number: 15, age: 22 },
  { id: 26303, name: "B. Sosa", korean_name: "보르나 소사", team_id: 194, position: "Defender", number: 24, age: 27 },
  { id: 861, name: "D. Rugani", korean_name: "다니엘레 루가니", team_id: 194, position: "Defender", number: 24, age: 31 },
  { id: 443829, name: "J. Mokio", korean_name: "제이 모키오", team_id: 194, position: "Defender", number: 24, age: 17 },
  { id: 453708, name: "L. Jetten", korean_name: "라이언 예텐", team_id: 194, position: "Defender", number: 25, age: 18 },
  { id: 453706, name: "A. Bouwman", korean_name: "아리 바우만", team_id: 194, position: "Defender", number: 30, age: 18 },
  { id: 5962, name: "G. Ávila", korean_name: "가스톤 아빌라", team_id: 194, position: "Defender", number: 32, age: 24 },
  { id: 14701, name: "J. Šutalo", korean_name: "요시프 슈탈로", team_id: 194, position: "Defender", number: 37, age: 25 },
  { id: 292, name: "J. Henderson", korean_name: "조던 헨더슨", team_id: 194, position: "Midfielder", number: 6, age: 35 },
  { id: 264094, name: "B. Tahirović", korean_name: "벤자민 타히로비치", team_id: 194, position: "Midfielder", number: 8, age: 22 },
  { id: 38749, name: "K. Taylor", korean_name: "케네스 테일러", team_id: 194, position: "Midfielder", number: 8, age: 23 },
  { id: 329715, name: "Oscar Gloukh", korean_name: "오스카르 글루크", team_id: 194, position: "Midfielder", number: 10, age: 21 },
  { id: 287109, name: "James McConnell", korean_name: "제임스 맥코넬", team_id: 194, position: "Midfielder", number: 16, age: 21 },
  { id: 25321, name: "D. Klaassen", korean_name: "다비 클라센", team_id: 194, position: "Midfielder", number: 18, age: 32 },
  { id: 37652, name: "B. van den Boomen", korean_name: "브랑코 판 덴 보먼", team_id: 194, position: "Midfielder", number: 21, age: 30 },
  { id: 36895, name: "K. Fitz-Jim", korean_name: "크리스티안 핏츠-짐", team_id: 194, position: "Midfielder", number: 28, age: 22 },
  { id: 469321, name: "Sean Steur", korean_name: "숀 스퇴르", team_id: 194, position: "Midfielder", number: 48, age: 17 },
  { id: 264470, name: "Raul Moro Prescoli", korean_name: "라울 모로 프레스콜리", team_id: 194, position: "Attacker", number: 7, age: 23 },
  { id: 38750, name: "B. Brobbey", korean_name: "브라이언 브로베이", team_id: 194, position: "Attacker", number: 9, age: 23 },
  { id: 282126, name: "Carlos Forbs", korean_name: "카를루스 포르브스", team_id: 194, position: "Attacker", number: 9, age: 21 },
  { id: 550, name: "Kasper Dolberg Rasmussen", korean_name: "카스퍼 돌베르그", team_id: 194, position: "Attacker", number: 9, age: 28 },
  { id: 340153, name: "M. Godts", korean_name: "밀란 고츠", team_id: 194, position: "Attacker", number: 11, age: 20 },
  { id: 2380, name: "C. Akpom", korean_name: "치바 아크폼", team_id: 194, position: "Attacker", number: 17, age: 30 },
  { id: 138753, name: "O. Edvardsen", korean_name: "오슬로 에드바르센", team_id: 194, position: "Attacker", number: 17, age: 26 },
  { id: 474378, name: "Don-Angelo Christoffel Annum-Assamoah Konadu", korean_name: "돈-안젤로 코나두", team_id: 194, position: "Attacker", number: 19, age: 19 },
  { id: 671, name: "B. Traoré", korean_name: "베르트랑 트라오레", team_id: 194, position: "Attacker", number: 20, age: 30 },
  { id: 335335, name: "Julian Dean Rijkhoff", korean_name: "율리안 딘 라이크호프", team_id: 194, position: "Attacker", number: 22, age: 20 },
  { id: 37160, name: "S. Berghuis", korean_name: "스티븐 베르하위스", team_id: 194, position: "Attacker", number: 23, age: 34 },
  { id: 25416, name: "W. Weghorst", korean_name: "바우트 베흐호르스트", team_id: 194, position: "Attacker", number: 25, age: 33 },
  { id: 423802, name: "Gaku Nawata", korean_name: "나와타 가쿠", team_id: 194, position: "Attacker", number: 26, age: 19 },
  { id: 161886, name: "C. Rasmussen", korean_name: "크리스티안 라스무센", team_id: 194, position: "Attacker", number: 29, age: 22 },
  { id: 336578, name: "J. Banel", korean_name: "제이든 바넬", team_id: 194, position: "Attacker", number: 34, age: 21 },
  { id: 244, name: "S. Bergwijn", korean_name: "스티븐 베르흐베인", team_id: 194, position: "Attacker", number: 34, age: 28 },
  { id: 396202, name: "Rayane Bounida", korean_name: "라얀 부니다", team_id: 194, position: "Attacker", number: 43, age: 19 },
  { id: 544045, name: "P. Reverson", korean_name: "파울루 레베르손", team_id: 194, position: undefined, number: 52, age: null },
];

// AZ Alkmaar (Team ID: 201) - 37명
export const AZ_ALKMAAR_PLAYERS: PlayerMapping[] = [
  { id: 340711, name: "R. Owusu-Oduro", korean_name: "롬-메일론 오우수-오두로", team_id: 201, position: "Goalkeeper", number: 1, age: 21 },
  { id: 37602, name: "H. Verhulst", korean_name: "후프 페르훌스트", team_id: 201, position: "Goalkeeper", number: 12, age: 32 },
  { id: 353810, name: "T. Kuijsten", korean_name: "티스 카위스턴", team_id: 201, position: "Goalkeeper", number: 16, age: 20 },
  { id: 278308, name: "D. Deen", korean_name: "다닐 덴", team_id: 201, position: "Goalkeeper", number: 31, age: 22 },
  { id: 224, name: "J. Zoet", korean_name: "예런 조이트", team_id: 201, position: "Goalkeeper", number: 41, age: 34 },
  { id: 338839, name: "W. Goes", korean_name: "볼프 호스", team_id: 201, position: "Defender", number: 3, age: 21 },
  { id: 312838, name: "M. Dekker", korean_name: "막심 데커", team_id: 201, position: "Defender", number: 4, age: 21 },
  { id: 162594, name: "Alexandre Penetra", korean_name: "알렉상드르 페네트라", team_id: 201, position: "Defender", number: 5, age: 24 },
  { id: 390002, name: "Mateo Chávez García", korean_name: "마테오 차베스 가르시아", team_id: 201, position: "Defender", number: 15, age: 21 },
  { id: 199793, name: "S. Maikuma", korean_name: "마이쿠마 세이야", team_id: 201, position: "Defender", number: 16, age: 28 },
  { id: 265782, name: "D. Møller Wolfe", korean_name: "다비드 뫼얼러 볼페", team_id: 201, position: "Defender", number: 18, age: 23 },
  { id: 370475, name: "E. Dijkstra", korean_name: "언 데이크스트라", team_id: 201, position: "Defender", number: 22, age: 19 },
  { id: 364184, name: "Billy van Duijl", korean_name: "빌리 판 다일", team_id: 201, position: "Defender", number: 23, age: 20 },
  { id: 179839, name: "D. Kasius", korean_name: "데니스 카시우스", team_id: 201, position: "Defender", number: 30, age: 23 },
  { id: 93064, name: "M. de Wit", korean_name: "마텐 더 비트", team_id: 201, position: "Defender", number: 34, age: 27 },
  { id: 340710, name: "E. Mastoras", korean_name: "에르네스토 마스토라스", team_id: 201, position: "Midfielder", number: 6, age: 19 },
  { id: 38820, name: "P. Koopmeiners", korean_name: "페어 쿱메이너르스", team_id: 201, position: "Midfielder", number: 6, age: 25 },
  { id: 37154, name: "J. Clasie", korean_name: "요르디 클라시", team_id: 201, position: "Midfielder", number: 8, age: 34 },
  { id: 37438, name: "S. Mijnans", korean_name: "사니 메이난스", team_id: 201, position: "Midfielder", number: 10, age: 25 },
  { id: 379882, name: "J. Oerip", korean_name: "저스틴 외립", team_id: 201, position: "Midfielder", number: 20, age: 19 },
  { id: 340597, name: "D. Kwakman", korean_name: "다비드 크바크만", team_id: 201, position: "Midfielder", number: 21, age: 21 },
  { id: 388786, name: "K. Smit", korean_name: "크리스티안 스미트", team_id: 201, position: "Midfielder", number: 26, age: 19 },
  { id: 446288, name: "K. Boogaard", korean_name: "케스 보가르트", team_id: 201, position: "Midfielder", number: 67, age: 19 },
  { id: 312840, name: "E. Poku", korean_name: "어니스트 포쿠", team_id: 201, position: "Attacker", number: 7, age: 21 },
  { id: 335633, name: "Weslley Pinto Batista", korean_name: "베슬리 핀투 바티스타", team_id: 201, position: "Attacker", number: 7, age: 22 },
  { id: 149551, name: "T. Parrott", korean_name: "트로이 패럿", team_id: 201, position: "Attacker", number: 9, age: 23 },
  { id: 15920, name: "I. Sadiq", korean_name: "우마르 사디크", team_id: 201, position: "Attacker", number: 11, age: 25 },
  { id: 289670, name: "Isak Steiner Jensen", korean_name: "이사크 슈타이너 옌센", team_id: 201, position: "Attacker", number: 17, age: 22 },
  { id: 354533, name: "J. Addai", korean_name: "제이든 아다이", team_id: 201, position: "Attacker", number: 17, age: 20 },
  { id: 266200, name: "M. Lahdo", korean_name: "마헤르 라흐도", team_id: 201, position: "Attacker", number: 23, age: 23 },
  { id: 443587, name: "W. Bouziane", korean_name: "와심 부지안", team_id: 201, position: "Attacker", number: 23, age: 19 },
  { id: 312837, name: "L. Zeefuik", korean_name: "릭키 제퓌크", team_id: 201, position: "Attacker", number: 25, age: 21 },
  { id: 338840, name: "R. Daal", korean_name: "로이 달", team_id: 201, position: "Attacker", number: 27, age: 21 },
  { id: 353898, name: "Matěj Šín", korean_name: "마테이 신", team_id: 201, position: "Attacker", number: 33, age: 21 },
  { id: 342954, name: "M. Meerdink", korean_name: "메스 메이르딩크", team_id: 201, position: "Attacker", number: 35, age: 22 },
  { id: 330261, name: "S. van Duijn", korean_name: "심 판 다인", team_id: 201, position: "Attacker", number: 60, age: 21 },
  { id: 381129, name: "Jasper Hartog", korean_name: "야스퍼 하르토흐", team_id: 201, position: "Attacker", number: 63, age: 19 },
];

// Excelsior (Team ID: 196) - 40명
export const EXCELSIOR_PLAYERS: PlayerMapping[] = [
  { id: 37571, name: "Stijn van Gassel", korean_name: "스테인 판 하설", team_id: 196, position: "Goalkeeper", number: 1, age: 29 },
  { id: 146328, name: "C. Raatsie", korean_name: "카스퍼 라치", team_id: 196, position: "Goalkeeper", number: 16, age: 23 },
  { id: 498931, name: "Tijmen Holla", korean_name: "테이먼 홀라", team_id: 196, position: "Goalkeeper", number: 40, age: 19 },
  { id: 38789, name: "I. Bronkhorst", korean_name: "이케 브론크호르스트", team_id: 196, position: "Defender", number: 2, age: 28 },
  { id: 36972, name: "K. Pierie", korean_name: "케이 피러", team_id: 196, position: "Defender", number: 3, age: 25 },
  { id: 272091, name: "Rick Meissen", korean_name: "릭 메이선", team_id: 196, position: "Defender", number: 3, age: 23 },
  { id: 263735, name: "C. Widell", korean_name: "카스퍼 비델", team_id: 196, position: "Defender", number: 4, age: 22 },
  { id: 325850, name: "Stan Henderikx", korean_name: "스탄 헨데릭스", team_id: 196, position: "Defender", number: 5, age: 22 },
  { id: 265, name: "A. Zagré", korean_name: "아르투르 자그레", team_id: 196, position: "Defender", number: 12, age: 24 },
  { id: 340596, name: "Lewis Schouten", korean_name: "루이스 스하우턴", team_id: 196, position: "Defender", number: 14, age: 21 },
  { id: 37780, name: "Simon Janssen", korean_name: "시몬 얀선", team_id: 196, position: "Defender", number: 15, age: 25 },
  { id: 342946, name: "N. Martens", korean_name: "니크 마르텐스", team_id: 196, position: "Defender", number: 17, age: 21 },
  { id: 356891, name: "S. Loeffen", korean_name: "센 로펀", team_id: 196, position: "Defender", number: 18, age: 21 },
  { id: 371125, name: "K. Nedd", korean_name: "켈빈 네드", team_id: 196, position: "Defender", number: 26, age: 21 },
  { id: 369352, name: "R. Olivacce", korean_name: "리카르도 올리바체", team_id: 196, position: "Defender", number: 28, age: 21 },
  { id: 291777, name: "S. Seymor", korean_name: "숀 세이모어", team_id: 196, position: "Defender", number: 34, age: 23 },
  { id: 126979, name: "Adam Erik Carlén", korean_name: "아담 에릭 카를렌", team_id: 196, position: "Midfielder", number: 6, age: 25 },
  { id: 290543, name: "M. Tielemans", korean_name: "마테이스 틸러만스", team_id: 196, position: "Midfielder", number: 8, age: 23 },
  { id: 321632, name: "N. Naujoks", korean_name: "니콜라스 나우욕스", team_id: 196, position: "Midfielder", number: 10, age: 23 },
  { id: 275169, name: "O. Uddenäs", korean_name: "오스카르 우데네스", team_id: 196, position: "Midfielder", number: 10, age: 23 },
  { id: 349595, name: "Gyan de Regt", korean_name: "지안 더 레흐트", team_id: 196, position: "Midfielder", number: 11, age: 22 },
  { id: 275268, name: "Chris Kevin Nadje", korean_name: "크리스 케빈 나제", team_id: 196, position: "Midfielder", number: 18, age: 24 },
  { id: 319518, name: "L. Hartjes", korean_name: "라스 하르트예스", team_id: 196, position: "Midfielder", number: 20, age: 22 },
  { id: 392432, name: "Chadwick Booth", korean_name: "채드윅 부스", team_id: 196, position: "Midfielder", number: 21, age: 21 },
  { id: 284397, name: "Chadwick Zachary Booth", korean_name: "채드윅 재커리 부스", team_id: 196, position: "Midfielder", number: 21, age: 18 },
  { id: 371231, name: "Irakli Yegoian", korean_name: "이라클리 예고이안", team_id: 196, position: "Midfielder", number: 23, age: 21 },
  { id: 480304, name: "Giulliano Cairo", korean_name: "줄리아누 카이로", team_id: 196, position: "Midfielder", number: 24, age: 19 },
  { id: 482312, name: "Stijn Middendorp", korean_name: "스테인 미덴도르프", team_id: 196, position: "Midfielder", number: 25, age: 21 },
  { id: 502436, name: "Jelani Seedorf", korean_name: "옐라니 세도르프", team_id: 196, position: "Midfielder", number: 28, age: 21 },
  { id: 272455, name: "D. Sanches Fernandes", korean_name: "다니엘 산체스 페르난데스", team_id: 196, position: "Midfielder", number: 30, age: 24 },
  { id: 439497, name: "L. Oetoehganal", korean_name: "레온 우투흐하날", team_id: 196, position: "Midfielder", number: 35, age: 21 },
  { id: 423709, name: "Do-Yong Yoon", korean_name: "윤도영", team_id: 196, position: "Attacker", number: 7, age: 19 },
  { id: 305711, name: "R. Omorowa", korean_name: "리치 오모로와", team_id: 196, position: "Attacker", number: 9, age: 21 },
  { id: 158614, name: "Szymon Włodarczyk", korean_name: "시몬 블로다르치크", team_id: 196, position: "Attacker", number: 9, age: 22 },
  { id: 359464, name: "R. Rosario", korean_name: "리치 로사리오", team_id: 196, position: "Attacker", number: 14, age: 21 },
  { id: 129052, name: "J. Donkor", korean_name: "줄리안 돈코르", team_id: 196, position: "Attacker", number: 21, age: 27 },
  { id: 180128, name: "Stefan Mitrović", korean_name: "스테판 미트로비치", team_id: 196, position: "Attacker", number: 22, age: 23 },
  { id: 372230, name: "N. Groen", korean_name: "네이선 흐룬", team_id: 196, position: "Attacker", number: 28, age: 21 },
  { id: 36938, name: "M. van Duinen", korean_name: "마크 판 다이넌", team_id: 196, position: "Attacker", number: 29, age: 34 },
  { id: 480305, name: "Jerolldino Armantrading", korean_name: "제롤디노 아르만트레이딩", team_id: 196, position: "Attacker", number: 33, age: 19 },
];

// FC Volendam (Team ID: 416) - 43명
export const FC_VOLENDAM_PLAYERS: PlayerMapping[] = [
  { id: 328669, name: "K. van Oevelen", korean_name: "카이 판 우벨런", team_id: 416, position: "Goalkeeper", number: 1, age: 22 },
  { id: 330623, name: "Roy Johannes Maria Steur", korean_name: "로이 요하네스 마리아 스퇴르", team_id: 416, position: "Goalkeeper", number: 16, age: 20 },
  { id: 203770, name: "Dion Vlak", korean_name: "디온 플라크", team_id: 416, position: "Goalkeeper", number: 22, age: 24 },
  { id: 272835, name: "D. Payne", korean_name: "다니 페인", team_id: 416, position: "Defender", number: 2, age: 23 },
  { id: 68330, name: "M. Amevor", korean_name: "마르코 아메보르", team_id: 416, position: "Defender", number: 3, age: 34 },
  { id: 38781, name: "X. Mbuyamba", korean_name: "자비에르 음부얌바", team_id: 416, position: "Defender", number: 4, age: 24 },
  { id: 412882, name: "Precious Joel Uche-Chukwu Ugwu", korean_name: "프레셔스 조엘 우체추쿠 우구", team_id: 416, position: "Defender", number: 5, age: 19 },
  { id: 37923, name: "Aaron Meijers", korean_name: "아론 메이어르스", team_id: 416, position: "Defender", number: 14, age: 38 },
  { id: 36584, name: "B. Benamar", korean_name: "빌랄 베나마르", team_id: 416, position: "Defender", number: 15, age: 28 },
  { id: 434028, name: "Nick Verschuren", korean_name: "닉 페르스휘런", team_id: 416, position: "Defender", number: 20, age: 20 },
  { id: 359843, name: "G. Curiel", korean_name: "헤리 쿠리엘", team_id: 416, position: "Defender", number: 23, age: 23 },
  { id: 485955, name: "Luca Blondeau", korean_name: "루카 블론도", team_id: 416, position: "Defender", number: 25, age: 19 },
  { id: 309867, name: "S. Esajas", korean_name: "샤쿠르 에사야스", team_id: 416, position: "Defender", number: 28, age: 23 },
  { id: 162090, name: "Y. Leliendal", korean_name: "요르디 렐리엔달", team_id: 416, position: "Defender", number: 32, age: 23 },
  { id: 37746, name: "A. Plat", korean_name: "아흐메드 플라트", team_id: 416, position: "Midfielder", number: 6, age: 27 },
  { id: 296135, name: "Gibson Osahumen Yah", korean_name: "깁슨 오사후멘 야", team_id: 416, position: "Midfielder", number: 8, age: 22 },
  { id: 38819, name: "J. Jacobs", korean_name: "요시프 제이콥스", team_id: 416, position: "Midfielder", number: 8, age: 28 },
  { id: 37272, name: "B. Kuwas", korean_name: "빌랄 쿠와스", team_id: 416, position: "Midfielder", number: 10, age: 33 },
  { id: 489932, name: "Anass Bouziane", korean_name: "아나스 부지안", team_id: 416, position: "Midfielder", number: 15, age: 19 },
  { id: 404774, name: "F. Klomp", korean_name: "프랑크 클롬프", team_id: 416, position: "Midfielder", number: 17, age: 24 },
  { id: 427259, name: "N. Bukala", korean_name: "네이선 부칼라", team_id: 416, position: "Midfielder", number: 18, age: 20 },
  { id: 330272, name: "M. Mau-Asam", korean_name: "맥스 마우아삼", team_id: 416, position: "Midfielder", number: 27, age: 21 },
  { id: 365660, name: "Kiano Dyer", korean_name: "키아노 다이어", team_id: 416, position: "Midfielder", number: 33, age: 19 },
  { id: 346672, name: "I. Nazih", korean_name: "이마드 나지", team_id: 416, position: "Midfielder", number: 34, age: 19 },
  { id: 314007, name: "M. de Haan", korean_name: "믹 더 한", team_id: 416, position: "Midfielder", number: 36, age: 22 },
  { id: 283588, name: "J. Antonioli", korean_name: "줄리안 안토니올리", team_id: 416, position: "Midfielder", number: 37, age: 21 },
  { id: 528294, name: "R. van Cruijsen", korean_name: "로빈 판 크라위선", team_id: 416, position: "Midfielder", number: 40, age: null },
  { id: 525881, name: "Robin van Cruijsen", korean_name: "로빈 판 크라위선", team_id: 416, position: "Midfielder", number: 40, age: null },
  { id: 442963, name: "B. van Driel", korean_name: "빌리 판 드릴", team_id: 416, position: "Midfielder", number: 48, age: 20 },
  { id: 180466, name: "Anthony Kevin N. Descotte", korean_name: "앤서니 케빈 N. 데스코트", team_id: 416, position: "Midfielder", number: 99, age: 22 },
  { id: 62262, name: "Ozan Can Kökçü", korean_name: "오잔 잔 쾨크취", team_id: 416, position: "Attacker", number: 7, age: 27 },
  { id: 24949, name: "H. Veerman", korean_name: "헹크 페이르만", team_id: 416, position: "Attacker", number: 9, age: 34 },
  { id: 275910, name: "K. Blommestijn", korean_name: "케빈 블로메스테인", team_id: 416, position: "Attacker", number: 9, age: 26 },
  { id: 296030, name: "A. Oehlers", korean_name: "아민 울러르스", team_id: 416, position: "Attacker", number: 11, age: 21 },
  { id: 503554, name: "Mauro Zijlstra", korean_name: "마우로 제일스트라", team_id: 416, position: "Attacker", number: 19, age: 21 },
  { id: 38710, name: "R. Mühren", korean_name: "로빈 뮈렌", team_id: 416, position: "Attacker", number: 21, age: 36 },
  { id: 503553, name: "Key-Shawn Wong-A-Soij", korean_name: "키션 웡아소이", team_id: 416, position: "Attacker", number: 24, age: 19 },
  { id: 369739, name: "Q. Hoeve", korean_name: "퀸시 후버", team_id: 416, position: "Attacker", number: 27, age: 22 },
  { id: 2155, name: "E. Manu", korean_name: "엘비스 마누", team_id: 416, position: "Attacker", number: 28, age: 32 },
  { id: 525882, name: "Jesper Tielemans", korean_name: "예스퍼 틸러만스", team_id: 416, position: "Attacker", number: 39, age: null },
  { id: 467676, name: "C. Demircioglu", korean_name: "첸크 데미르치오글루", team_id: 416, position: "Attacker", number: 77, age: 23 },
  { id: 526845, name: "J. Tielemans", korean_name: "예스퍼 틸러만스", team_id: 416, position: undefined, number: 39, age: null },
  { id: 526838, name: "R. van Cruijsen", korean_name: "로빈 판 크라위선", team_id: 416, position: undefined, number: 40, age: null },
];

// Feyenoord (Team ID: 209) - 47명
export const FEYENOORD_PLAYERS: PlayerMapping[] = [
  { id: 37137, name: "J. Bijlow", korean_name: "유스틴 베일로", team_id: 209, position: "Goalkeeper", number: 1, age: 27 },
  { id: 374500, name: "M. Berger", korean_name: "미카 베르헤르", team_id: 209, position: "Goalkeeper", number: 1, age: 21 },
  { id: 36776, name: "T. Wellenreuther", korean_name: "티몬 벨렌로이터", team_id: 209, position: "Goalkeeper", number: 22, age: 30 },
  { id: 198483, name: "L. Bossin", korean_name: "루카 보생", team_id: 209, position: "Goalkeeper", number: 39, age: 29 },
  { id: 441274, name: "I. Ka", korean_name: "이사크 카", team_id: 209, position: "Goalkeeper", number: 64, age: 19 },
  { id: 37147, name: "B. Nieuwkoop", korean_name: "바르트 니우코프", team_id: 209, position: "Defender", number: 2, age: 29 },
  { id: 37143, name: "L. Geertruida", korean_name: "루츠 헤이르트라위다", team_id: 209, position: "Defender", number: 2, age: 25 },
  { id: 39362, name: "M. Pedersen", korean_name: "마르쿠스 페데르센", team_id: 209, position: "Defender", number: 3, age: 25 },
  { id: 328141, name: "T. Beelen", korean_name: "토마스 벨런", team_id: 209, position: "Defender", number: 3, age: 24 },
  { id: 32858, name: "Tsuyoshi Watanabe", korean_name: "와타나베 츠요시", team_id: 209, position: "Defender", number: 4, age: 28 },
  { id: 37742, name: "G. Smal", korean_name: "히스 스말", team_id: 209, position: "Defender", number: 5, age: 28 },
  { id: 337587, name: "Jordan Jacob Bos", korean_name: "조던 야코브 보스", team_id: 209, position: "Defender", number: 15, age: 23 },
  { id: 2431, name: "M. López", korean_name: "마테오 로페스", team_id: 209, position: "Defender", number: 15, age: 26 },
  { id: 280687, name: "Hugo Bueno", korean_name: "우고 부에노", team_id: 209, position: "Defender", number: 16, age: 23 },
  { id: 7529, name: "G. Trauner", korean_name: "그레고어 트라우너", team_id: 209, position: "Defender", number: 18, age: 33 },
  { id: 297583, name: "J. Mitchell", korean_name: "저스틴 미첼", team_id: 209, position: "Defender", number: 20, age: 21 },
  { id: 1949, name: "Anel Ahmedhodžić", korean_name: "아넬 아흐메도지치", team_id: 209, position: "Defender", number: 21, age: 26 },
  { id: 359390, name: "G. Read", korean_name: "조지 리드", team_id: 209, position: "Defender", number: 26, age: 19 },
  { id: 945, name: "J. Lotomba", korean_name: "조던 로톰바", team_id: 209, position: "Defender", number: 30, age: 27 },
  { id: 414188, name: "Malcolm John Matarr Jeng", korean_name: "말콤 존 마타르 젱", team_id: 209, position: "Defender", number: 31, age: 20 },
  { id: 30399, name: "D. Hancko", korean_name: "다비드 한츠코", team_id: 209, position: "Defender", number: 33, age: 28 },
  { id: 441221, name: "J. Plug", korean_name: "요르디 플뤼흐", team_id: 209, position: "Defender", number: 43, age: 20 },
  { id: 441275, name: "D. Giersthove", korean_name: "다안 히르스토버", team_id: 209, position: "Defender", number: 48, age: 20 },
  { id: 2901, name: "Hwang In-Beom", korean_name: "황인범", team_id: 209, position: "Midfielder", number: 6, age: 29 },
  { id: 40911, name: "J. Moder", korean_name: "야쿠프 모데르", team_id: 209, position: "Midfielder", number: 7, age: 26 },
  { id: 38747, name: "Q. Timber", korean_name: "킴 팀버", team_id: 209, position: "Midfielder", number: 8, age: 24 },
  { id: 66208, name: "O. Lingr", korean_name: "온드레이 링르", team_id: 209, position: "Midfielder", number: 9, age: 27 },
  { id: 36910, name: "C. Stengs", korean_name: "칼빈 스텡스", team_id: 209, position: "Midfielder", number: 10, age: 27 },
  { id: 161176, name: "P. Wålemark", korean_name: "폰투스 볼레마르크", team_id: 209, position: "Midfielder", number: 10, age: 24 },
  { id: 361888, name: "Shiloh Kiesar 't Zand", korean_name: "쉴로 키에사르 트 잔트", team_id: 209, position: "Midfielder", number: 10, age: 22 },
  { id: 37784, name: "Sem Steijn", korean_name: "셈 스테인", team_id: 209, position: "Midfielder", number: 14, age: 24 },
  { id: 326067, name: "A. Hadj-Moussa", korean_name: "아니스 하즈 무사", team_id: 209, position: "Midfielder", number: 23, age: 23 },
  { id: 284071, name: "O. Targhalline", korean_name: "오타이 타르갈린", team_id: 209, position: "Midfielder", number: 28, age: 23 },
  { id: 314266, name: "Luciano Valente", korean_name: "루시아누 발렌치", team_id: 209, position: "Midfielder", number: 40, age: 22 },
  { id: 491239, name: "T. van den Elshout", korean_name: "테오 판 덴 엘스하우트", team_id: 209, position: "Midfielder", number: 44, age: 18 },
  { id: 371228, name: "T. Kraaijeveld", korean_name: "티스 크라이에벨트", team_id: 209, position: "Midfielder", number: 47, age: 18 },
  { id: 94562, name: "S. Giménez", korean_name: "산티아고 히메네스", team_id: 209, position: "Attacker", number: 7, age: 24 },
  { id: 72155, name: "A. Ueda", korean_name: "우에다 아야세", team_id: 209, position: "Attacker", number: 9, age: 27 },
  { id: 2001, name: "Cyle Christopher Larin", korean_name: "카일 크리스토퍼 라린", team_id: 209, position: "Attacker", number: 10, age: 30 },
  { id: 128385, name: "Gonçalo Óscar Albuquerque Borges", korean_name: "곤살루 오스카르 보르제스", team_id: 209, position: "Attacker", number: 11, age: 24 },
  { id: 9363, name: "Igor Paixão", korean_name: "이고르 파이샹", team_id: 209, position: "Attacker", number: 14, age: 25 },
  { id: 342163, name: "L. Sauer", korean_name: "라세 자우어", team_id: 209, position: "Attacker", number: 16, age: 20 },
  { id: 162703, name: "Casper Tengstedt", korean_name: "카스퍼 텡스테트", team_id: 209, position: "Attacker", number: 17, age: 25 },
  { id: 458540, name: "Gaoussou Kyassou Diarra", korean_name: "가우수 키아수 디아라", team_id: 209, position: "Attacker", number: 27, age: 23 },
  { id: 407365, name: "S. Carrillo", korean_name: "산티아고 카리요", team_id: 209, position: "Attacker", number: 31, age: 19 },
  { id: 412873, name: "A. Sliti", korean_name: "아미네 슬리티", team_id: 209, position: "Attacker", number: 32, age: 19 },
  { id: 361487, name: "J. Slory", korean_name: "제이든 슬로리", team_id: 209, position: "Attacker", number: 36, age: 20 },
];

// Fortuna Sittard (Team ID: 205) - 34명
export const FORTUNA_SITTARD_PLAYERS: PlayerMapping[] = [
  { id: 38759, name: "L. Koopmans", korean_name: "로렌스 코프만스", team_id: 205, position: "Goalkeeper", number: 1, age: 32 },
  { id: 444020, name: "Boaz Broekmans", korean_name: "보아즈 브룩만스", team_id: 205, position: "Goalkeeper", number: 16, age: 18 },
  { id: 429024, name: "N. Martens", korean_name: "나이스 마르텐스", team_id: 205, position: "Goalkeeper", number: 25, age: 21 },
  { id: 37359, name: "M. Branderhorst", korean_name: "마이클 브란데르호르스트", team_id: 205, position: "Goalkeeper", number: 31, age: 32 },
  { id: 467814, name: "Ramazan Bayram", korean_name: "라마잔 바이람", team_id: 205, position: "Goalkeeper", number: 71, age: 21 },
  { id: 129125, name: "S. Adewoye", korean_name: "새뮤얼 아데워예", team_id: 205, position: "Defender", number: 4, age: 25 },
  { id: 273361, name: "S. van Ottele", korean_name: "사이먼 판 오텔레", team_id: 205, position: "Defender", number: 6, age: 23 },
  { id: 203786, name: "J. Dahlhaus", korean_name: "야스퍼 달하우스", team_id: 205, position: "Defender", number: 8, age: 24 },
  { id: 19065, name: "Ivo Pinto", korean_name: "이보 핀투", team_id: 205, position: "Defender", number: 12, age: 35 },
  { id: 536, name: "D. Sinkgraven", korean_name: "다비 싱크라펜", team_id: 205, position: "Defender", number: 22, age: 30 },
  { id: 326029, name: "P. Brittijn", korean_name: "페리 브리테인", team_id: 205, position: "Defender", number: 23, age: 21 },
  { id: 20627, name: "Houboulang Mendes", korean_name: "우불랑 멘데스", team_id: 205, position: "Defender", number: 26, age: 27 },
  { id: 284359, name: "Justin Quincy Hubner", korean_name: "저스틴 퀸시 휘브너", team_id: 205, position: "Defender", number: 28, age: 22 },
  { id: 467813, name: "Dean Bisschops", korean_name: "딘 비스쇼프스", team_id: 205, position: "Defender", number: 37, age: 20 },
  { id: 40201, name: "Iván Márquez", korean_name: "이반 마르케스", team_id: 205, position: "Defender", number: 44, age: 31 },
  { id: 2115, name: "A. Halilović", korean_name: "아네스 할릴로비치", team_id: 205, position: "Midfielder", number: 10, age: 29 },
  { id: 268572, name: "É. Michut", korean_name: "에두아르 미슈", team_id: 205, position: "Midfielder", number: 20, age: 22 },
  { id: 335912, name: "M. Kerkez", korean_name: "마테오 케르케즈", team_id: 205, position: "Midfielder", number: 21, age: 25 },
  { id: 2109, name: "S. Bastien", korean_name: "사무엘 바스티앙", team_id: 205, position: "Midfielder", number: 22, age: 29 },
  { id: 327811, name: "H. Korkmazyürek", korean_name: "하산 코르크마즈위렉", team_id: 205, position: "Midfielder", number: 36, age: 22 },
  { id: 470472, name: "Tristan Schenkhuizen", korean_name: "트리스탄 스헹크하위전", team_id: 205, position: "Midfielder", number: 38, age: 21 },
  { id: 525846, name: "Moussa Gbemou", korean_name: "무사 그베무", team_id: 205, position: "Midfielder", number: 46, age: 18 },
  { id: 554358, name: "Amin Laoukili", korean_name: "아민 라우킬리", team_id: 205, position: "Midfielder", number: 47, age: null },
  { id: 380913, name: "Luka Tunjic", korean_name: "루카 툰지치", team_id: 205, position: "Midfielder", number: 77, age: 20 },
  { id: 335069, name: "R. Fosso", korean_name: "라이언 포소", team_id: 205, position: "Midfielder", number: 80, age: 23 },
  { id: 37273, name: "K. Peterson", korean_name: "크리스티안 피터슨", team_id: 205, position: "Attacker", number: 7, age: 31 },
  { id: 38132, name: "K. Sierhuis", korean_name: "카이 시어르하위스", team_id: 205, position: "Attacker", number: 9, age: 27 },
  { id: 275828, name: "M. Aïko", korean_name: "마크 아이코", team_id: 205, position: "Attacker", number: 11, age: 24 },
  { id: 38725, name: "J. Lonwijk", korean_name: "제이 론베이크", team_id: 205, position: "Attacker", number: 17, age: 26 },
  { id: 2383, name: "D. Limnios", korean_name: "디미트리오스 림니오스", team_id: 205, position: "Attacker", number: 18, age: 27 },
  { id: 38129, name: "P. Gladon", korean_name: "피에르 글라돈", team_id: 205, position: "Attacker", number: 19, age: 32 },
  { id: 447409, name: "O. Johnson", korean_name: "오비 존슨", team_id: 205, position: "Attacker", number: 45, age: 20 },
  { id: 236, name: "M. Ihattaren", korean_name: "모하메드 이하타렌", team_id: 205, position: "Attacker", number: 52, age: 23 },
  { id: 41592, name: "Úmaro Embaló", korean_name: "우마루 엠발로", team_id: 205, position: "Attacker", number: 85, age: 24 },
];

// GO Ahead Eagles (Team ID: 410) - 30명
export const GO_AHEAD_EAGLES_PLAYERS: PlayerMapping[] = [
  { id: 25311, name: "L. Plogmann", korean_name: "리비우스 플로그만", team_id: 410, position: "Goalkeeper", number: 1, age: 25 },
  { id: 8470, name: "J. De Busser", korean_name: "제이 더 부서", team_id: 410, position: "Goalkeeper", number: 22, age: 26 },
  { id: 291418, name: "S. Jansen", korean_name: "센 얀선", team_id: 410, position: "Goalkeeper", number: 30, age: 21 },
  { id: 352225, name: "N. Verdoni", korean_name: "니콜로 베르도니", team_id: 410, position: "Goalkeeper", number: 33, age: 22 },
  { id: 37451, name: "M. Deijl", korean_name: "마틴 데일", team_id: 410, position: "Defender", number: 2, age: 28 },
  { id: 25260, name: "G. Nauber", korean_name: "헤리트 나우버르", team_id: 410, position: "Defender", number: 3, age: 33 },
  { id: 36887, name: "J. Kramer", korean_name: "예스퍼 크라머", team_id: 410, position: "Defender", number: 4, age: 29 },
  { id: 203755, name: "D. James", korean_name: "다니엘 제임스", team_id: 410, position: "Defender", number: 5, age: 25 },
  { id: 312903, name: "Giovanni van Zwam", korean_name: "조반니 판 즈밤", team_id: 410, position: "Defender", number: 25, age: 21 },
  { id: 162200, name: "J. Dirksen", korean_name: "준 디르크선", team_id: 410, position: "Defender", number: 26, age: 22 },
  { id: 378962, name: "P. Saathof", korean_name: "파트릭 사토프", team_id: 410, position: "Defender", number: 28, age: 22 },
  { id: 378966, name: "A. Adelgaard", korean_name: "알렉산더 아델고르", team_id: 410, position: "Defender", number: 29, age: 22 },
  { id: 277922, name: "C. Twigt", korean_name: "카스퍼 트비흐트", team_id: 410, position: "Midfielder", number: 6, age: 22 },
  { id: 262677, name: "J. Breum", korean_name: "야코프 브레움", team_id: 410, position: "Midfielder", number: 7, age: 22 },
  { id: 37781, name: "E. Linthorst", korean_name: "에베르트 린토르스트", team_id: 410, position: "Midfielder", number: 8, age: 25 },
  { id: 128765, name: "S. Tengstedt", korean_name: "사무엘 텡스테트", team_id: 410, position: "Midfielder", number: 10, age: 25 },
  { id: 378963, name: "R. Weijenberg", korean_name: "라미 베이엔베르흐", team_id: 410, position: "Midfielder", number: 15, age: 21 },
  { id: 162061, name: "X. Blomme", korean_name: "자비에르 블로메", team_id: 410, position: "Midfielder", number: 20, age: 23 },
  { id: 36865, name: "M. Meulensteen", korean_name: "믹 뮐렌스틴", team_id: 410, position: "Midfielder", number: 21, age: 26 },
  { id: 36896, name: "Kenzo Goudmijn", korean_name: "켄조 하우드메인", team_id: 410, position: "Midfielder", number: 24, age: 24 },
  { id: 524315, name: "Y. Rahmouni", korean_name: "야신 라무니", team_id: 410, position: "Midfielder", number: 34, age: 19 },
  { id: 362568, name: "M. Smit", korean_name: "맥스 스미트", team_id: 410, position: "Attacker", number: 9, age: 22 },
  { id: 216756, name: "O. Sivertsen", korean_name: "오스카르 시베르트선", team_id: 410, position: "Attacker", number: 11, age: 21 },
  { id: 48057, name: "O. Pettersson", korean_name: "올리버 페테르손", team_id: 410, position: "Attacker", number: 14, age: 25 },
  { id: 137837, name: "V. Edvardsen", korean_name: "빅토르 에드바르센", team_id: 410, position: "Attacker", number: 16, age: 29 },
  { id: 162762, name: "M. Suray", korean_name: "마르셀 수레이", team_id: 410, position: "Attacker", number: 17, age: 24 },
  { id: 37124, name: "R. Margaret", korean_name: "로보아 마가렛", team_id: 410, position: "Attacker", number: 18, age: 25 },
  { id: 162143, name: "T. Baeten", korean_name: "티스 바텐", team_id: 410, position: "Attacker", number: 23, age: 23 },
  { id: 37028, name: "F. Stokkers", korean_name: "핀 스토커르스", team_id: 410, position: "Attacker", number: 27, age: 29 },
  { id: 511370, name: "O. Boakye", korean_name: "오스카르 보아키예", team_id: 410, position: "Attacker", number: 31, age: 18 },
];

// Groningen (Team ID: 202) - 36명
export const GRONINGEN_PLAYERS: PlayerMapping[] = [
  { id: 36854, name: "E. Vaessen", korean_name: "에티엔 파선", team_id: 202, position: "Goalkeeper", number: 1, age: 30 },
  { id: 162245, name: "L. Štubljar", korean_name: "루카 슈투블랴르", team_id: 202, position: "Goalkeeper", number: 13, age: 21 },
  { id: 37217, name: "H. Jurjus", korean_name: "히데 율르위스", team_id: 202, position: "Goalkeeper", number: 21, age: 31 },
  { id: 359370, name: "D. Baron", korean_name: "딘 바론", team_id: 202, position: "Goalkeeper", number: 24, age: 23 },
  { id: 420931, name: "S. Petiet", korean_name: "스벤 페티에", team_id: 202, position: "Goalkeeper", number: 41, age: 20 },
  { id: 439830, name: "Wouter Prins", korean_name: "바우터르 프린스", team_id: 202, position: "Defender", number: 2, age: 21 },
  { id: 314264, name: "T. Blokzijl", korean_name: "토메 블록제일", team_id: 202, position: "Defender", number: 3, age: 20 },
  { id: 412872, name: "Dies Janse", korean_name: "디스 얀서", team_id: 202, position: "Defender", number: 4, age: 19 },
  { id: 90957, name: "M. Rente", korean_name: "마르코 렌터", team_id: 202, position: "Defender", number: 5, age: 28 },
  { id: 446871, name: "Tyrique Mercera", korean_name: "타이리크 메르세라", team_id: 202, position: "Defender", number: 16, age: 22 },
  { id: 454545, name: "Sven Bouland", korean_name: "스벤 바울란트", team_id: 202, position: "Defender", number: 22, age: 19 },
  { id: 497022, name: "E. van der Laan", korean_name: "에너스 판 데르 란", team_id: 202, position: "Defender", number: 26, age: 17 },
  { id: 93060, name: "M. Peersman", korean_name: "마르코 페이르스만", team_id: 202, position: "Defender", number: 43, age: 34 },
  { id: 526553, name: "Petrit Preniqi", korean_name: "페트리트 프레니치", team_id: 202, position: "Defender", number: 48, age: 36 },
  { id: 291505, name: "S. Resink", korean_name: "스타인 레싱크", team_id: 202, position: "Midfielder", number: 6, age: 22 },
  { id: 384585, name: "Travis Enrique Hernes", korean_name: "트래비스 엔리케 헤르네스", team_id: 202, position: "Midfielder", number: 7, age: 20 },
  { id: 314267, name: "T. de Jonge", korean_name: "티스 더 용어", team_id: 202, position: "Midfielder", number: 8, age: 22 },
  { id: 394608, name: "J. Schreuders", korean_name: "조이 스흐뢰더르스", team_id: 202, position: "Midfielder", number: 14, age: 21 },
  { id: 473416, name: "D. van der Werff", korean_name: "드리스 판 데르 베르프", team_id: 202, position: "Midfielder", number: 17, age: 21 },
  { id: 36903, name: "M. Seuntjens", korean_name: "로엘 세윈턴스", team_id: 202, position: "Midfielder", number: 20, age: 33 },
  { id: 526554, name: "Besnik Mashuku", korean_name: "베스닉 마슈쿠", team_id: 202, position: "Midfielder", number: 44, age: null },
  { id: 526555, name: "Yénio Holder", korean_name: "예니오 홀더르", team_id: 202, position: "Midfielder", number: 55, age: null },
  { id: 28733, name: "B. Willumsson", korean_name: "브릴리안트 빌룸손", team_id: 202, position: "Attacker", number: 9, age: 25 },
  { id: 282136, name: "Noam Fritz Emeran", korean_name: "노암 프리츠 에메란", team_id: 202, position: "Attacker", number: 11, age: 23 },
  { id: 40298, name: "O. Zawada", korean_name: "올리버 자바다", team_id: 202, position: "Attacker", number: 19, age: 29 },
  { id: 392044, name: "T. van Bergen", korean_name: "토마스 판 베르헌", team_id: 202, position: "Attacker", number: 26, age: 21 },
  { id: 178168, name: "Rui Mendes", korean_name: "루이 멘데스", team_id: 202, position: "Attacker", number: 27, age: 26 },
  { id: 452390, name: "Nils Eggens", korean_name: "닐스 에겐스", team_id: 202, position: "Attacker", number: 57, age: 20 },
  { id: 321039, name: "Ryan Higgins", korean_name: "라이언 히긴스", team_id: 202, position: "Attacker", number: 69, age: 30 },
  { id: 526842, name: "J. Dillema", korean_name: "야니크 딜레마", team_id: 202, position: undefined, number: 44, age: null },
  { id: 528296, name: "R. Kelder", korean_name: "로만 켈더르", team_id: 202, position: undefined, number: 48, age: null },
  { id: 526843, name: "R. Kelder", korean_name: "로만 켈더르", team_id: 202, position: undefined, number: 48, age: null },
  { id: 526844, name: "Y. Holder", korean_name: "예니오 홀더르", team_id: 202, position: undefined, number: 55, age: null },
  { id: 528297, name: "Y. Holder", korean_name: "예니오 홀더르", team_id: 202, position: undefined, number: 55, age: null },
  { id: 526841, name: "M. Hoekstra", korean_name: "마테이스 훅스트라", team_id: 202, position: undefined, number: 69, age: null },
  { id: 528295, name: "M. Hoekstra", korean_name: "마테이스 훅스트라", team_id: 202, position: undefined, number: 69, age: null },
];

// Heerenveen (Team ID: 210) - 28명
export const HEERENVEEN_PLAYERS: PlayerMapping[] = [
  { id: 361500, name: "B. Klaverboer", korean_name: "빔 클라버보어", team_id: 210, position: "Goalkeeper", number: 22, age: 20 },
  { id: 37729, name: "N. Bakker", korean_name: "노르딘 바커르", team_id: 210, position: "Goalkeeper", number: 31, age: 28 },
  { id: 31632, name: "A. Noppert", korean_name: "안드리스 노페르트", team_id: 210, position: "Goalkeeper", number: 44, age: 31 },
  { id: 327347, name: "M. Willemsen", korean_name: "맥스 빌럼선", team_id: 210, position: "Defender", number: 3, age: 22 },
  { id: 37453, name: "S. Kersten", korean_name: "샘 케르스턴", team_id: 210, position: "Defender", number: 4, age: 27 },
  { id: 40224, name: "P. Bochniewicz", korean_name: "파벨 보흐니에비치", team_id: 210, position: "Defender", number: 5, age: 29 },
  { id: 37183, name: "J. van Overeem", korean_name: "야니크 판 오버럼", team_id: 210, position: "Defender", number: 6, age: 31 },
  { id: 431651, name: "Mats Egbring", korean_name: "마츠 에흐브링", team_id: 210, position: "Defender", number: 15, age: 19 },
  { id: 314285, name: "N. Hopland", korean_name: "니콜라스 홉란트", team_id: 210, position: "Defender", number: 17, age: 21 },
  { id: 135841, name: "V. Zagaritis", korean_name: "바실리오스 자가리티스", team_id: 210, position: "Defender", number: 19, age: 24 },
  { id: 200078, name: "H. Petrov", korean_name: "흐리스토 페트로프", team_id: 210, position: "Defender", number: 28, age: 23 },
  { id: 503982, name: "R. Bouw", korean_name: "라파엘 바우", team_id: 210, position: "Defender", number: 34, age: 19 },
  { id: 425585, name: "O. Braude", korean_name: "오르 브라우데", team_id: 210, position: "Defender", number: 45, age: 21 },
  { id: 37460, name: "L. Brouwers", korean_name: "루카스 브라우어르스", team_id: 210, position: "Midfielder", number: 8, age: 27 },
  { id: 128311, name: "Ringo Meerveld", korean_name: "링고 메이르벨트", team_id: 210, position: "Midfielder", number: 10, age: 23 },
  { id: 325845, name: "L. Smans", korean_name: "루카스 스만스", team_id: 210, position: "Midfielder", number: 14, age: 22 },
  { id: 310037, name: "M. Linday", korean_name: "마일로 린데이", team_id: 210, position: "Midfielder", number: 16, age: 22 },
  { id: 281662, name: "J. Trenskow", korean_name: "야콥 트렌스코", team_id: 210, position: "Midfielder", number: 20, age: 25 },
  { id: 431887, name: "E. van Ee", korean_name: "에스페르 판 에", team_id: 210, position: "Midfielder", number: 21, age: 22 },
  { id: 512737, name: "Kai Jansen", korean_name: "카이 얀선", team_id: 210, position: "Midfielder", number: 32, age: 18 },
  { id: 480854, name: "Isaiah Ahmed", korean_name: "아이자야 아메드", team_id: 210, position: "Midfielder", number: 35, age: 20 },
  { id: 396217, name: "N. Courtens", korean_name: "노아 코르턴스", team_id: 210, position: "Midfielder", number: 36, age: 19 },
  { id: 174797, name: "M. Rivera", korean_name: "마르쿠스 리베라", team_id: 210, position: "Attacker", number: 7, age: 23 },
  { id: 37163, name: "D. Vente", korean_name: "다니엘 펜터", team_id: 210, position: "Attacker", number: 9, age: 26 },
  { id: 202087, name: "A. van Axel Dongen", korean_name: "아민 판 악셀 동언", team_id: 210, position: "Attacker", number: 26, age: 21 },
  { id: 323824, name: "V. Sejk", korean_name: "빅토르 세익", team_id: 210, position: "Attacker", number: 27, age: 23 },
  { id: 382371, name: "J. Rijssel", korean_name: "야콥 레이설", team_id: 210, position: "Attacker", number: 33, age: 18 },
  { id: 453717, name: "E. Gürbüz", korean_name: "에게 귀르뷔즈", team_id: 210, position: "Attacker", number: 50, age: 18 },
];

// Heracles (Team ID: 206) - 30명
export const HERACLES_PLAYERS: PlayerMapping[] = [
  { id: 92975, name: "F. de Keijzer", korean_name: "파비안 더 케이저르", team_id: 206, position: "Goalkeeper", number: 1, age: 25 },
  { id: 358449, name: "T. Jansink", korean_name: "틸 얀싱크", team_id: 206, position: "Goalkeeper", number: 16, age: 22 },
  { id: 8742, name: "R. Mantel", korean_name: "로이 만텔", team_id: 206, position: "Goalkeeper", number: 30, age: 25 },
  { id: 524230, name: "L. Zeevalkink", korean_name: "라스 제발링크", team_id: 206, position: "Goalkeeper", number: null, age: 20 },
  { id: 322868, name: "M. Benita", korean_name: "마르쿠스 베니타", team_id: 206, position: "Defender", number: 2, age: 22 },
  { id: 177714, name: "J. Wieckhoff", korean_name: "얀 비크호프", team_id: 206, position: "Defender", number: 3, age: 25 },
  { id: 37670, name: "D. Mirani", korean_name: "다리오 미라니", team_id: 206, position: "Defender", number: 4, age: 29 },
  { id: 203153, name: "S. Čestić", korean_name: "사사 체스티치", team_id: 206, position: "Defender", number: 6, age: 24 },
  { id: 93006, name: "D. van der Kust", korean_name: "드리스 판 데르 쿠스트", team_id: 206, position: "Defender", number: 15, age: 24 },
  { id: 280837, name: "L. Milani", korean_name: "루카 밀라니", team_id: 206, position: "Defender", number: 22, age: 24 },
  { id: 38118, name: "M. te Wierik", korean_name: "마이크 터 비릭", team_id: 206, position: "Defender", number: 23, age: 33 },
  { id: 1393, name: "I. Mesík", korean_name: "이반 메식", team_id: 206, position: "Defender", number: 24, age: 24 },
  { id: 470471, name: "Jop Tijink", korean_name: "욥 테이잉크", team_id: 206, position: "Defender", number: 27, age: 20 },
  { id: 37371, name: "J. Bruijn", korean_name: "얀 브라인", team_id: 206, position: "Midfielder", number: 5, age: 29 },
  { id: 161901, name: "B. Limbombe", korean_name: "비란 림봄베", team_id: 206, position: "Midfielder", number: 7, age: 24 },
  { id: 37081, name: "M. Engels", korean_name: "마르코 엥헬스", team_id: 206, position: "Midfielder", number: 8, age: 32 },
  { id: 38122, name: "T. Bruns", korean_name: "토마스 브룬스", team_id: 206, position: "Midfielder", number: 10, age: 33 },
  { id: 21152, name: "J. Reine-Adélaïde", korean_name: "제프 레네아들라이드", team_id: 206, position: "Midfielder", number: 11, age: 27 },
  { id: 19360, name: "J. Žambůrek", korean_name: "얀 잠부렉", team_id: 206, position: "Midfielder", number: 13, age: 24 },
  { id: 365918, name: "T. van Gilst", korean_name: "테오 판 힐스트", team_id: 206, position: "Midfielder", number: 17, age: 22 },
  { id: 318531, name: "Y. Borges Sanches", korean_name: "얀 보르헤스 산체스", team_id: 206, position: "Midfielder", number: 21, age: 21 },
  { id: 38126, name: "D. van Kaam", korean_name: "다니엘 판 캄", team_id: 206, position: "Midfielder", number: 26, age: 25 },
  { id: 407378, name: "G. Sambo", korean_name: "고다이 삼보", team_id: 206, position: "Midfielder", number: 28, age: 19 },
  { id: 358450, name: "S. Scheperman", korean_name: "셈 스헤퍼르만", team_id: 206, position: "Midfielder", number: 32, age: 23 },
  { id: 38123, name: "A. Hrustić", korean_name: "아이야즈 흐루스티치", team_id: 206, position: "Midfielder", number: 70, age: 29 },
  { id: 38464, name: "Walid Ould-Chikh", korean_name: "왈리드 울드쉬크", team_id: 206, position: "Midfielder", number: 73, age: 26 },
  { id: 36985, name: "J. Hornkamp", korean_name: "얀니스 호른캄프", team_id: 206, position: "Attacker", number: 9, age: 27 },
  { id: 144691, name: "L. Kulenović", korean_name: "로브레 쿨레노비치", team_id: 206, position: "Attacker", number: 19, age: 26 },
  { id: 413074, name: "D. van Oorschot", korean_name: "다비드 판 오르스호트", team_id: 206, position: "Attacker", number: 20, age: 20 },
  { id: 301457, name: "A. Satriano", korean_name: "아구스틴 사트리아노", team_id: 206, position: "Attacker", number: 31, age: 22 },
];

// NAC Breda (Team ID: 203) - 33명
export const NAC_BREDA_PLAYERS: PlayerMapping[] = [
  { id: 37419, name: "R. Kortsmit", korean_name: "로이 코르츠미트", team_id: 203, position: "Goalkeeper", number: 1, age: 33 },
  { id: 525, name: "K. Lamprou", korean_name: "콘스탄티노스 람프루", team_id: 203, position: "Goalkeeper", number: 31, age: 34 },
  { id: 40220, name: "D. Bielica", korean_name: "다니엘 비엘리차", team_id: 203, position: "Goalkeeper", number: 99, age: 26 },
  { id: 129067, name: "B. Lucassen", korean_name: "보이 루카선", team_id: 203, position: "Defender", number: 2, age: 27 },
  { id: 38737, name: "B. Kemper", korean_name: "발렌틴 켐퍼르", team_id: 203, position: "Defender", number: 4, age: 26 },
  { id: 19043, name: "T. Kongolo", korean_name: "테렌스 콩골로", team_id: 203, position: "Defender", number: 5, age: 31 },
  { id: 1717, name: "L. Greiml", korean_name: "레오 그라이믈", team_id: 203, position: "Defender", number: 12, age: 24 },
  { id: 55882, name: "E. Mahmutović", korean_name: "엘리아스 마무토비치", team_id: 203, position: "Defender", number: 15, age: 28 },
  { id: 479629, name: "D. van Reeuwijk", korean_name: "다안 판 레우베이크", team_id: 203, position: "Defender", number: 18, age: 18 },
  { id: 322863, name: "Jayden Candelaria", korean_name: "제이든 칸델라리아", team_id: 203, position: "Defender", number: 21, age: 21 },
  { id: 36886, name: "R. Hillen", korean_name: "릭 힐런", team_id: 203, position: "Defender", number: 22, age: 22 },
  { id: 453918, name: "Cherrion Valerius", korean_name: "체리온 발레리우스", team_id: 203, position: "Defender", number: 25, age: 20 },
  { id: 433623, name: "L. Mol", korean_name: "렉스 몰", team_id: 203, position: "Defender", number: 28, age: 21 },
  { id: 526685, name: "Julien Nota", korean_name: "줄리앙 노타", team_id: 203, position: "Defender", number: 29, age: 17 },
  { id: 272724, name: "C. Staring", korean_name: "카스퍼 스타링", team_id: 203, position: "Midfielder", number: 6, age: 24 },
  { id: 36931, name: "C. Leemans", korean_name: "클린트 리먼스", team_id: 203, position: "Midfielder", number: 8, age: 30 },
  { id: 290548, name: "M. Nassoh", korean_name: "마르셀 나소", team_id: 203, position: "Midfielder", number: 10, age: 22 },
  { id: 327874, name: "R. Paula", korean_name: "로베르투 파울라", team_id: 203, position: "Midfielder", number: 11, age: 21 },
  { id: 8789, name: "K. Sowah", korean_name: "칼리파 소와", team_id: 203, position: "Midfielder", number: 14, age: 25 },
  { id: 296642, name: "M. Balard", korean_name: "마르틴 발라르", team_id: 203, position: "Midfielder", number: 16, age: 25 },
  { id: 39094, name: "F. Oldrup Jensen", korean_name: "프레데릭 올드룹 옌센", team_id: 203, position: "Midfielder", number: 20, age: 32 },
  { id: 314078, name: "J. Talvitie", korean_name: "요오나스 탈비티에", team_id: 203, position: "Midfielder", number: 32, age: 20 },
  { id: 24876, name: "L. Holtby", korean_name: "루이스 홀트비", team_id: 203, position: "Midfielder", number: 90, age: 35 },
  { id: 129788, name: "C. Brym", korean_name: "클라이드 브림", team_id: 203, position: "Attacker", number: 7, age: 27 },
  { id: 38713, name: "S. van Hooijdonk", korean_name: "시드니 판 호이돈크", team_id: 203, position: "Attacker", number: 17, age: 25 },
  { id: 373800, name: "D. Versluis", korean_name: "다비드 페르슬라위스", team_id: 203, position: "Attacker", number: 23, age: 22 },
  { id: 528300, name: "P. Reulen", korean_name: "페페인 뢸런", team_id: 203, position: "Attacker", number: 26, age: null },
  { id: 320418, name: "Pepijn Reulen", korean_name: "페페인 뢸런", team_id: 203, position: "Attacker", number: 26, age: null },
  { id: 384808, name: "M. Soumano", korean_name: "마마두 수마노", team_id: 203, position: "Attacker", number: 34, age: 20 },
  { id: 340082, name: "B. Ghalidi", korean_name: "바드르 할리디", team_id: 203, position: "Attacker", number: 55, age: 20 },
  { id: 526839, name: "P. Reulen", korean_name: "페페인 뢸런", team_id: 203, position: undefined, number: 26, age: null },
  { id: 526846, name: "C. Chiza", korean_name: "치아고 시자", team_id: 203, position: undefined, number: 29, age: null },
  { id: 527665, name: "J. Erat", korean_name: "얀 에라트", team_id: 203, position: undefined, number: null, age: null },
];

// NEC Nijmegen (Team ID: 413) - 40명
export const NEC_NIJMEGEN_PLAYERS: PlayerMapping[] = [
  { id: 129054, name: "G. Crettaz", korean_name: "지브랄타르 크레타즈", team_id: 413, position: "Goalkeeper", number: 1, age: 25 },
  { id: 124, name: "J. Cillessen", korean_name: "야스퍼 실레선", team_id: 413, position: "Goalkeeper", number: 22, age: 36 },
  { id: 203769, name: "R. Janse", korean_name: "로빈 얀서", team_id: 413, position: "Goalkeeper", number: 31, age: 23 },
  { id: 492120, name: "Freek Entius", korean_name: "프레이크 엔티위스", team_id: 413, position: "Goalkeeper", number: 36, age: 19 },
  { id: 480302, name: "Martijn Overmars", korean_name: "마르테인 오버마르스", team_id: 413, position: "Goalkeeper", number: 38, age: 19 },
  { id: 274275, name: "B. Pereira", korean_name: "바울루 페레이라", team_id: 413, position: "Defender", number: 2, age: 22 },
  { id: 625, name: "P. Sandler", korean_name: "필리프 산들러", team_id: 413, position: "Defender", number: 3, age: 28 },
  { id: 278159, name: "Ahmetcan Kaplan", korean_name: "아흐메트칸 카플란", team_id: 413, position: "Defender", number: 4, age: 22 },
  { id: 36888, name: "T. Ouwejan", korean_name: "토마스 아우베얀", team_id: 413, position: "Defender", number: 5, age: 29 },
  { id: 56003, name: "Elazar Dasa", korean_name: "엘라자르 다사", team_id: 413, position: "Defender", number: 14, age: 33 },
  { id: 1813, name: "J. Willems", korean_name: "예트로 빌렘스", team_id: 413, position: "Defender", number: 15, age: 31 },
  { id: 30797, name: "B. Nuytinck", korean_name: "브람 나위팅크", team_id: 413, position: "Defender", number: 17, age: 35 },
  { id: 354506, name: "K. Sano", korean_name: "코디 사노", team_id: 413, position: "Defender", number: 23, age: 22 },
  { id: 37151, name: "C. Verdonk", korean_name: "칼빈 베르돈크", team_id: 413, position: "Defender", number: 24, age: 28 },
  { id: 353808, name: "Deveron Fonville", korean_name: "데베론 폰빌", team_id: 413, position: "Defender", number: 24, age: 22 },
  { id: 527911, name: "Yassin Moslih", korean_name: "야신 모슬리", team_id: 413, position: "Defender", number: 37, age: null },
  { id: 14343, name: "Darko Nejašmić", korean_name: "다르코 네야슈미치", team_id: 413, position: "Midfielder", number: 6, age: 26 },
  { id: 25622, name: "V. Misidjan", korean_name: "바파 미시잔", team_id: 413, position: "Midfielder", number: 7, age: 32 },
  { id: 340545, name: "A. Darelas", korean_name: "알렉산드로스 다렐라스", team_id: 413, position: "Midfielder", number: 8, age: 22 },
  { id: 330315, name: "Noé Lebreton", korean_name: "노에 르브르통", team_id: 413, position: "Midfielder", number: 20, age: 21 },
  { id: 1582, name: "Róber", korean_name: "로베르", team_id: 413, position: "Midfielder", number: 21, age: 24 },
  { id: 378864, name: "S. Ouaissa", korean_name: "사미 우아이사", team_id: 413, position: "Midfielder", number: 25, age: 21 },
  { id: 36937, name: "V. van Crooij", korean_name: "바우트 판 크로이", team_id: 413, position: "Midfielder", number: 32, age: 29 },
  { id: 507621, name: "Yousri Sbai", korean_name: "유스리 스바이", team_id: 413, position: "Midfielder", number: 33, age: 21 },
  { id: 526551, name: "Sam de Laat", korean_name: "샘 더 라트", team_id: 413, position: "Midfielder", number: 35, age: null },
  { id: 152850, name: "D. Proper", korean_name: "디르크 프로퍼르", team_id: 413, position: "Midfielder", number: 71, age: 23 },
  { id: 422572, name: "K. Shiogai", korean_name: "시오가이 코다이", team_id: 413, position: "Attacker", number: 9, age: 20 },
  { id: 161884, name: "S. Hansen", korean_name: "쇠런 한센", team_id: 413, position: "Attacker", number: 10, age: 23 },
  { id: 50120, name: "T. Chery", korean_name: "라세 셰리", team_id: 413, position: "Attacker", number: 10, age: 37 },
  { id: 360032, name: "B. Önal", korean_name: "바하티르 외날", team_id: 413, position: "Attacker", number: 11, age: 21 },
  { id: 57224, name: "L. Olden Larsen", korean_name: "라르스 올덴 라르센", team_id: 413, position: "Attacker", number: 14, age: 27 },
  { id: 33289, name: "Koki Ogawa", korean_name: "오가와 고키", team_id: 413, position: "Attacker", number: 18, age: 28 },
  { id: 453719, name: "L. Nieuwenhuijs", korean_name: "루카 니우언하위스", team_id: 413, position: "Attacker", number: 26, age: 18 },
  { id: 37134, name: "B. Linssen", korean_name: "브리얀 린선", team_id: 413, position: "Attacker", number: 30, age: 35 },
  { id: 526840, name: "S. de Laat", korean_name: "샘 더 라트", team_id: 413, position: undefined, number: 35, age: null },
  { id: 528299, name: "S. de Laat", korean_name: "샘 더 라트", team_id: 413, position: undefined, number: 35, age: null },
  { id: 528298, name: "Y. Moslih", korean_name: "야신 모슬리", team_id: 413, position: undefined, number: 37, age: null },
  { id: 551117, name: "M. van de Wiel", korean_name: "마이크 판 더 빌", team_id: 413, position: undefined, number: 39, age: null },
  { id: 530273, name: "M. van de Wiel", korean_name: "마이크 판 더 빌", team_id: 413, position: undefined, number: 40, age: null },
  { id: 551114, name: "M. Overmars", korean_name: "마르테인 오버마르스", team_id: 413, position: undefined, number: null, age: null },
];

// PEC Zwolle (Team ID: 193) - 32명
export const PEC_ZWOLLE_PLAYERS: PlayerMapping[] = [
  { id: 36881, name: "J. Schendelaar", korean_name: "야스퍼 스헨델라르", team_id: 193, position: "Goalkeeper", number: 1, age: 25 },
  { id: 338499, name: "T. de Graaff", korean_name: "티스 더 흐라프", team_id: 193, position: "Goalkeeper", number: 16, age: 21 },
  { id: 505297, name: "Nick Dobben", korean_name: "닉 도번", team_id: 193, position: "Goalkeeper", number: 40, age: 17 },
  { id: 319928, name: "D. Verduin", korean_name: "다이크 페르다인", team_id: 193, position: "Goalkeeper", number: 41, age: 22 },
  { id: 343154, name: "Lennard Becker", korean_name: "렌나르트 베커르", team_id: 193, position: "Goalkeeper", number: 48, age: 20 },
  { id: 36970, name: "S. Floranus", korean_name: "샘 플로라뉘스", team_id: 193, position: "Defender", number: 2, age: 27 },
  { id: 271581, name: "O. Aertssen", korean_name: "올리비에 아르트선", team_id: 193, position: "Defender", number: 3, age: 21 },
  { id: 279868, name: "A. MacNulty", korean_name: "아누아르 맥널티", team_id: 193, position: "Defender", number: 4, age: 22 },
  { id: 336582, name: "Tristan Gooijer", korean_name: "트리스탄 호이어르", team_id: 193, position: "Defender", number: 6, age: 21 },
  { id: 15690, name: "S. Graves", korean_name: "샘 그레이브스", team_id: 193, position: "Defender", number: 28, age: 26 },
  { id: 351240, name: "D. van der Haar", korean_name: "다미안 판 데르 하르", team_id: 193, position: "Defender", number: 33, age: 21 },
  { id: 453956, name: "Dylan Ruward", korean_name: "딜런 뤼바르트", team_id: 193, position: "Defender", number: 42, age: 20 },
  { id: 272695, name: "Zico Buurmeester", korean_name: "지코 뷔르메스터르", team_id: 193, position: "Midfielder", number: 8, age: 23 },
  { id: 8764, name: "D. Mbayo", korean_name: "다비드 음바요", team_id: 193, position: "Midfielder", number: 11, age: 24 },
  { id: 37588, name: "O. Velanas", korean_name: "오디세아스 벨라나스", team_id: 193, position: "Midfielder", number: 18, age: 27 },
  { id: 353732, name: "Jan Faberski", korean_name: "얀 파베르스키", team_id: 193, position: "Midfielder", number: 19, age: 19 },
  { id: 474376, name: "G. Reiziger", korean_name: "기오반니 레이지허르", team_id: 193, position: "Midfielder", number: 20, age: 20 },
  { id: 37647, name: "K. de Rooij", korean_name: "케빈 더 로이", team_id: 193, position: "Midfielder", number: 22, age: 25 },
  { id: 38822, name: "T. Oosting", korean_name: "톰 오스팅", team_id: 193, position: "Midfielder", number: 25, age: 25 },
  { id: 525900, name: "Jadiel Pereira da Gama", korean_name: "자디엘 페레이라 다 가마", team_id: 193, position: "Midfielder", number: 26, age: 16 },
  { id: 242, name: "R. Thomas", korean_name: "라이언 토마스", team_id: 193, position: "Midfielder", number: 30, age: 31 },
  { id: 425821, name: "N. Fichtinger", korean_name: "니콜라스 피히팅어", team_id: 193, position: "Midfielder", number: 34, age: 21 },
  { id: 50745, name: "Jamiro Monteiro", korean_name: "자미로 몬테이루", team_id: 193, position: "Midfielder", number: 35, age: 32 },
  { id: 494137, name: "G. Rahajaän", korean_name: "기오반니 라하얀", team_id: 193, position: "Midfielder", number: 38, age: 17 },
  { id: 163054, name: "Shola Maxwell Shoretire", korean_name: "쇼라 맥스웰 쇼레티레", team_id: 193, position: "Attacker", number: 7, age: 21 },
  { id: 38780, name: "K. Kostons", korean_name: "클라스 코스톤스", team_id: 193, position: "Attacker", number: 10, age: 26 },
  { id: 287381, name: "S. Lagsir", korean_name: "사미 라그시르", team_id: 193, position: "Attacker", number: 21, age: 22 },
  { id: 37130, name: "T. Buitink", korean_name: "토마스 바위팅크", team_id: 193, position: "Attacker", number: 29, age: 25 },
  { id: 387342, name: "David Voute", korean_name: "다비드 바우터", team_id: 193, position: "Attacker", number: 39, age: 20 },
  { id: 26358, name: "B. Manu", korean_name: "블레싱 마누", team_id: 193, position: "Attacker", number: 77, age: 28 },
  { id: 529345, name: "L. Bakker", korean_name: "레나르트 바커르", team_id: 193, position: undefined, number: 48, age: null },
  { id: 551118, name: "B. Rahajaan", korean_name: "브라이언 라하얀", team_id: 193, position: undefined, number: null, age: null },
];

// PSV Eindhoven (Team ID: 197) - 49명
export const PSV_EINDHOVEN_PLAYERS: PlayerMapping[] = [
  { id: 37818, name: "Nick Quinten Olij", korean_name: "니크 콴텐 올레이", team_id: 197, position: "Goalkeeper", number: 1, age: 30 },
  { id: 371523, name: "T. Smolenaars", korean_name: "트립 스몰레나르스", team_id: 197, position: "Goalkeeper", number: 16, age: 20 },
  { id: 328193, name: "N. Schiks", korean_name: "니키 스키크스", team_id: 197, position: "Goalkeeper", number: 24, age: 21 },
  { id: 138804, name: "Matěj Kovář", korean_name: "마테이 코바르지", team_id: 197, position: "Goalkeeper", number: 32, age: 25 },
  { id: 162451, name: "Anass Salah-Eddine", korean_name: "아나스 살라에딘", team_id: 197, position: "Defender", number: 2, age: 23 },
  { id: 770, name: "R. Karsdorp", korean_name: "릭 카르스도르프", team_id: 197, position: "Defender", number: 2, age: 30 },
  { id: 312841, name: "E. van de Blaak", korean_name: "에릭 판 더 블라크", team_id: 197, position: "Defender", number: 3, age: 20 },
  { id: 453707, name: "M. Bresser", korean_name: "마티스 브레서", team_id: 197, position: "Defender", number: 3, age: 18 },
  { id: 37145, name: "T. Malacia", korean_name: "타이렐 말라시아", team_id: 197, position: "Defender", number: 3, age: 26 },
  { id: 361385, name: "Yarek Gasiorowski Hernandis", korean_name: "야레크 가시오로프스키", team_id: 197, position: "Defender", number: 3, age: 20 },
  { id: 228, name: "A. Obispo", korean_name: "아르만도 오비스포", team_id: 197, position: "Defender", number: 4, age: 26 },
  { id: 231, name: "J. Teze", korean_name: "요던 테제", team_id: 197, position: "Defender", number: 4, age: 26 },
  { id: 342054, name: "R. Flamingo", korean_name: "라이언 플라밍호", team_id: 197, position: "Defender", number: 6, age: 23 },
  { id: 38735, name: "S. Dest", korean_name: "세르히뇨 데스트", team_id: 197, position: "Defender", number: 8, age: 25 },
  { id: 22160, name: "O. Boscagli", korean_name: "올리비에 보스칼리", team_id: 197, position: "Defender", number: 18, age: 28 },
  { id: 215827, name: "F. Oppegård", korean_name: "프레드릭 오페고르", team_id: 197, position: "Defender", number: 22, age: 23 },
  { id: 37890, name: "J. Schouten", korean_name: "헤레미 쇼우턴", team_id: 197, position: "Defender", number: 22, age: 28 },
  { id: 191233, name: "Kiliann Eric Sildillia", korean_name: "킬리안 에릭 실딜리아", team_id: 197, position: "Defender", number: 25, age: 23 },
  { id: 412869, name: "Eus Waayers", korean_name: "에이스 바이어르스", team_id: 197, position: "Defender", number: 33, age: 19 },
  { id: 412871, name: "W. Kuhn", korean_name: "바우터 쿤", team_id: 197, position: "Defender", number: 36, age: 19 },
  { id: 102851, name: "R. Ledezma", korean_name: "리카르도 레데스마", team_id: 197, position: "Defender", number: 37, age: 25 },
  { id: 307426, name: "A. Nagalo", korean_name: "아드리언 나갈로", team_id: 197, position: "Defender", number: 39, age: 23 },
  { id: 162037, name: "M. Tillman", korean_name: "말리크 틸만", team_id: 197, position: "Midfielder", number: 7, age: 23 },
  { id: 327895, name: "Paul Wanner", korean_name: "파울 바너", team_id: 197, position: "Midfielder", number: 10, age: 20 },
  { id: 272543, name: "C. Driouech", korean_name: "쿠아이브 드리우에크", team_id: 197, position: "Midfielder", number: 11, age: 23 },
  { id: 233, name: "Mauro Júnior", korean_name: "마우루 주니오르", team_id: 197, position: "Midfielder", number: 17, age: 26 },
  { id: 37749, name: "J. Veerman", korean_name: "요이 페이르만", team_id: 197, position: "Midfielder", number: 23, age: 27 },
  { id: 313078, name: "I. Babadi", korean_name: "이사크 바바디", team_id: 197, position: "Midfielder", number: 26, age: 20 },
  { id: 43036, name: "Dennis Man", korean_name: "데니스 만", team_id: 197, position: "Midfielder", number: 27, age: 27 },
  { id: 402272, name: "T. Land", korean_name: "타이고 란트", team_id: 197, position: "Midfielder", number: 28, age: 19 },
  { id: 474550, name: "Noah Fernandez", korean_name: "노아 페르난데스", team_id: 197, position: "Midfielder", number: 31, age: 19 },
  { id: 161897, name: "I. Saibari", korean_name: "이스마일 사이바리", team_id: 197, position: "Midfielder", number: 34, age: 24 },
  { id: 434623, name: "J. van den Berg", korean_name: "요르디 판 덴 베르흐", team_id: 197, position: "Midfielder", number: 35, age: 18 },
  { id: 439829, name: "Jordy Bawuah", korean_name: "요르디 바부아", team_id: 197, position: "Midfielder", number: 37, age: 19 },
  { id: 207, name: "I. Perišić", korean_name: "이반 페리시치", team_id: 197, position: "Attacker", number: 5, age: 36 },
  { id: 365018, name: "Ruben van Bommel", korean_name: "루벤 판 보멜", team_id: 197, position: "Attacker", number: 7, age: 21 },
  { id: 290549, name: "J. Bakayoko", korean_name: "요한 바카요코", team_id: 197, position: "Attacker", number: 9, age: 22 },
  { id: 409840, name: "J. Uneken", korean_name: "욥 운에컨", team_id: 197, position: "Attacker", number: 9, age: 21 },
  { id: 361481, name: "J. van Duiven", korean_name: "야손 판 다위번", team_id: 197, position: "Attacker", number: 9, age: 20 },
  { id: 246, name: "L. de Jong", korean_name: "뤼크 더 용", team_id: 197, position: "Attacker", number: 9, age: 35 },
  { id: 73868, name: "R. Pepi", korean_name: "리카르도 페피", team_id: 197, position: "Attacker", number: 9, age: 22 },
  { id: 544, name: "N. Lang", korean_name: "노아 랑", team_id: 197, position: "Attacker", number: 10, age: 26 },
  { id: 248, name: "H. Lozano", korean_name: "이르빙 로사노", team_id: 197, position: "Attacker", number: 11, age: 30 },
  { id: 25646, name: "Alassane Alexandre Pléa", korean_name: "알라산 알렉상드르 플레아", team_id: 197, position: "Attacker", number: 14, age: 32 },
  { id: 329409, name: "E. Bajraktarevic", korean_name: "에스미르 바이라크타레비치", team_id: 197, position: "Attacker", number: 19, age: 20 },
  { id: 36905, name: "G. Til", korean_name: "기소 틸", team_id: 197, position: "Attacker", number: 20, age: 28 },
  { id: 36907, name: "Myron Boadu", korean_name: "마이런 보아두", team_id: 197, position: "Attacker", number: 21, age: 24 },
  { id: 18833, name: "Lucas Pérez", korean_name: "루카스 페레스", team_id: 197, position: "Attacker", number: 27, age: 37 },
  { id: 419629, name: "Robin van Duiven", korean_name: "로빈 판 다위번", team_id: 197, position: "Attacker", number: 40, age: 19 },
];

// Sparta Rotterdam (Team ID: 426) - 25명
export const SPARTA_ROTTERDAM_PLAYERS: PlayerMapping[] = [
  { id: 36828, name: "J. Drommel", korean_name: "요엘 드로멜", team_id: 426, position: "Goalkeeper", number: 1, age: 29 },
  { id: 36964, name: "F. Bednarek", korean_name: "피에트 베드나렉", team_id: 426, position: "Goalkeeper", number: 20, age: 33 },
  { id: 280671, name: "P. Kuiper", korean_name: "페페 카위퍼르", team_id: 426, position: "Goalkeeper", number: 30, age: 21 },
  { id: 194645, name: "S. Sambo", korean_name: "사이드 삼보", team_id: 426, position: "Defender", number: 2, age: 24 },
  { id: 405379, name: "M. Young", korean_name: "마이크 영", team_id: 426, position: "Defender", number: 3, age: 20 },
  { id: 19497, name: "B. Martins Indi", korean_name: "브루노 마르팅스 인디", team_id: 426, position: "Defender", number: 4, age: 33 },
  { id: 148128, name: "Teo Quintero", korean_name: "테오 킨테로", team_id: 426, position: "Defender", number: 5, age: 26 },
  { id: 36862, name: "S. Bakari", korean_name: "사이드 바카리", team_id: 426, position: "Defender", number: 12, age: 31 },
  { id: 145548, name: "T. Velthuis", korean_name: "텔흐위스", team_id: 426, position: "Defender", number: 13, age: 23 },
  { id: 18845, name: "P. van Aanholt", korean_name: "패트릭 판 안홀트", team_id: 426, position: "Defender", number: 14, age: 35 },
  { id: 359984, name: "M. Kleijn", korean_name: "마르코 클레인", team_id: 426, position: "Defender", number: 15, age: 20 },
  { id: 451592, name: "G. Vianello", korean_name: "조르조 비아넬로", team_id: 426, position: "Defender", number: 22, age: 18 },
  { id: 377266, name: "M. de Ligt", korean_name: "마르코 더 리흐트", team_id: 426, position: "Defender", number: 22, age: 21 },
  { id: 272454, name: "J. Baas", korean_name: "요수아 바스", team_id: 426, position: "Midfielder", number: 6, age: 23 },
  { id: 39091, name: "J. Kitolano", korean_name: "조슈아 키톨라노", team_id: 426, position: "Midfielder", number: 8, age: 24 },
  { id: 36925, name: "P. Clement", korean_name: "펠레 클레먼트", team_id: 426, position: "Midfielder", number: 10, age: 29 },
  { id: 444790, name: "A. Oufkir", korean_name: "아민 우프키르", team_id: 426, position: "Midfielder", number: 11, age: 19 },
  { id: 435739, name: "A. Santos", korean_name: "아얀 산투스", team_id: 426, position: "Midfielder", number: 16, age: 20 },
  { id: 37156, name: "J. Toornstra", korean_name: "요르스 토른스트라", team_id: 426, position: "Midfielder", number: 18, age: 36 },
  { id: 92977, name: "L. Duijvestijn", korean_name: "룩 다위베스테인", team_id: 426, position: "Midfielder", number: 21, age: 26 },
  { id: 1815, name: "J. de Guzmán", korean_name: "조나단 더 구스만", team_id: 426, position: "Midfielder", number: 22, age: 38 },
  { id: 39100, name: "T. Lauritsen", korean_name: "토비아스 라우리트선", team_id: 426, position: "Attacker", number: 9, age: 28 },
  { id: 237131, name: "S. Mito", korean_name: "슈토 미토", team_id: 426, position: "Attacker", number: 11, age: 23 },
  { id: 28786, name: "N. Þórisson", korean_name: "니콜라이 토리손", team_id: 426, position: "Attacker", number: 19, age: 26 },
  { id: 270660, name: "Joel Ideho", korean_name: "조엘 이데호", team_id: 426, position: "Attacker", number: 21, age: 22 },
];

// Telstar (Team ID: 427) - 41명
export const TELSTAR_PLAYERS: PlayerMapping[] = [
  { id: 37817, name: "R. Koeman", korean_name: "로날드 쿠만", team_id: 427, position: "Goalkeeper", number: 1, age: 30 },
  { id: 214129, name: "T. Bodak", korean_name: "토마시 보다크", team_id: 427, position: "Goalkeeper", number: 13, age: 23 },
  { id: 38731, name: "Daan Reiziger", korean_name: "단 레이지허르", team_id: 427, position: "Goalkeeper", number: 20, age: 24 },
  { id: 399874, name: "L. van Ingen", korean_name: "레온 판 잉언", team_id: 427, position: "Goalkeeper", number: 28, age: 21 },
  { id: 37252, name: "J. Hardeveld", korean_name: "야콥 하르데펠트", team_id: 427, position: "Defender", number: 2, age: 30 },
  { id: 61144, name: "M. Apau", korean_name: "모리츠 아파우", team_id: 427, position: "Defender", number: 3, age: 35 },
  { id: 272539, name: "G. Offerhaus", korean_name: "기스 오퍼르하위스", team_id: 427, position: "Defender", number: 4, age: 24 },
  { id: 390028, name: "Neville Ogidi Nwankwo", korean_name: "네빌 오기디 은완크워", team_id: 427, position: "Defender", number: 5, age: 23 },
  { id: 272692, name: "S. Dirks", korean_name: "샘 디르크스", team_id: 427, position: "Defender", number: 5, age: 24 },
  { id: 37928, name: "D. Bakker", korean_name: "다비드 바커르", team_id: 427, position: "Defender", number: 6, age: 30 },
  { id: 70442, name: "Nigel Ogidi Nwankwo", korean_name: "나이젤 오기디 은완크워", team_id: 427, position: "Defender", number: 14, age: 27 },
  { id: 433064, name: "A. Lechkar", korean_name: "아민 레흐카르", team_id: 427, position: "Defender", number: 15, age: 24 },
  { id: 203773, name: "J. den Haan", korean_name: "요리트 덴 한", team_id: 427, position: "Defender", number: 16, age: 24 },
  { id: 281160, name: "D. Koswal", korean_name: "다비드 코스발", team_id: 427, position: "Defender", number: 21, age: 22 },
  { id: 480311, name: "Abdelraffie Benzzine", korean_name: "압델라피 벤지네", team_id: 427, position: "Defender", number: 24, age: 19 },
  { id: 480310, name: "Jaylan von Schooneveld", korean_name: "제일런 폰 스호네펠트", team_id: 427, position: "Defender", number: 26, age: 20 },
  { id: 37935, name: "Dion Omar Rudchell Malone", korean_name: "디온 오마르 말론", team_id: 427, position: "Defender", number: 29, age: 36 },
  { id: 510804, name: "Jessy Lobbes", korean_name: "제시 로베스", team_id: 427, position: "Midfielder", number: 5, age: null },
  { id: 399875, name: "J. Turfkruier", korean_name: "야스퍼 투르프크라위어", team_id: 427, position: "Midfielder", number: 8, age: 23 },
  { id: 149225, name: "T. Owusu", korean_name: "토마스 오우수", team_id: 427, position: "Midfielder", number: 8, age: 26 },
  { id: 406846, name: "T. Noslin", korean_name: "타흐 노슬린", team_id: 427, position: "Midfielder", number: 11, age: 23 },
  { id: 37373, name: "T. Overtoom", korean_name: "틸 오버토름", team_id: 427, position: "Midfielder", number: 12, age: 35 },
  { id: 38799, name: "Dylan Mertens", korean_name: "딜런 메르턴스", team_id: 427, position: "Midfielder", number: 16, age: 30 },
  { id: 349560, name: "N. Rossen", korean_name: "닉 로선", team_id: 427, position: "Midfielder", number: 17, age: 21 },
  { id: 274518, name: "R. van Ekeris", korean_name: "로빈 판 에케리스", team_id: 427, position: "Midfielder", number: 18, age: 23 },
  { id: 522966, name: "Rayyan Koubini", korean_name: "라이얀 쿠비니", team_id: 427, position: "Midfielder", number: 23, age: null },
  { id: 517339, name: "Aleck Viotey", korean_name: "알렉 비오테이", team_id: 427, position: "Midfielder", number: 28, age: null },
  { id: 38825, name: "M. Kaandorp", korean_name: "마티스 칸도르프", team_id: 427, position: "Midfielder", number: 34, age: 27 },
  { id: 345155, name: "Jochem Ritmeester van de Kamp", korean_name: "요헴 리트메이스터 판 더 캄프", team_id: 427, position: "Midfielder", number: 39, age: 22 },
  { id: 379487, name: "S. Hetli", korean_name: "세바스티안 헤틀리", team_id: 427, position: "Attacker", number: 7, age: 24 },
  { id: 283439, name: "Milan Zonneveld", korean_name: "밀란 조네펠트", team_id: 427, position: "Attacker", number: 9, age: 22 },
  { id: 37442, name: "Y. El Kachati", korean_name: "야신 엘 카차티", team_id: 427, position: "Attacker", number: 9, age: 26 },
  { id: 36850, name: "M. Hamdaoui", korean_name: "무니르 함다위", team_id: 427, position: "Attacker", number: 10, age: 32 },
  { id: 37616, name: "Z. Eddahchouri", korean_name: "자카리아 에다쿠리", team_id: 427, position: "Attacker", number: 10, age: 25 },
  { id: 402798, name: "F. Quaedvlieg", korean_name: "프란스 쾨드플리흐", team_id: 427, position: "Attacker", number: 15, age: 22 },
  { id: 446648, name: "Sebastiaan Hagedoorn", korean_name: "세바스티안 하헤도른", team_id: 427, position: "Attacker", number: 19, age: 21 },
  { id: 194815, name: "Patrick Brouwer", korean_name: "패트릭 브라우어르", team_id: 427, position: "Attacker", number: 27, age: 24 },
  { id: 93460, name: "R. Kharchouch", korean_name: "레다 카르슈슈", team_id: 427, position: "Attacker", number: 27, age: 30 },
  { id: 407644, name: "R. Oudsten", korean_name: "로반 아우드스턴", team_id: 427, position: "Attacker", number: 28, age: 15 },
  { id: 93072, name: "Kay Tejan", korean_name: "카이 테얀", team_id: 427, position: "Attacker", number: 30, age: 28 },
  { id: 297883, name: "C. Seedorf", korean_name: "클라렌스 세도르프", team_id: 427, position: "Attacker", number: 47, age: 25 },
];

// Twente (Team ID: 415) - 41명
export const TWENTE_PLAYERS: PlayerMapping[] = [
  { id: 37765, name: "L. Unnerstall", korean_name: "라르스 운너스탈", team_id: 415, position: "Goalkeeper", number: 1, age: 35 },
  { id: 523, name: "I. El Maach", korean_name: "이사크 엘 마크", team_id: 415, position: "Goalkeeper", number: 16, age: 25 },
  { id: 363486, name: "S. Karssies", korean_name: "스탄 카르시스", team_id: 415, position: "Goalkeeper", number: 21, age: 22 },
  { id: 50974, name: "P. Tytoń", korean_name: "프셰미슬라프 티톤", team_id: 415, position: "Goalkeeper", number: 22, age: 38 },
  { id: 272723, name: "M. Hilgers", korean_name: "마츠 힐헤르스", team_id: 415, position: "Defender", number: 2, age: 24 },
  { id: 137721, name: "G. Lagerbielke", korean_name: "구스타프 라게르빌케", team_id: 415, position: "Defender", number: 3, age: 25 },
  { id: 37254, name: "Robin Pröpper", korean_name: "로빈 프뢰퍼르", team_id: 415, position: "Defender", number: 3, age: 32 },
  { id: 43076, name: "B. Kuipers", korean_name: "바르트 카위퍼르스", team_id: 415, position: "Defender", number: 5, age: 31 },
  { id: 393191, name: "Gerald Alders", korean_name: "제럴드 알데르스", team_id: 415, position: "Defender", number: 6, age: 20 },
  { id: 453794, name: "Guilherme Martinho Peixoto", korean_name: "길례르미 마르티뉴 페이소투", team_id: 415, position: "Defender", number: 12, age: 19 },
  { id: 8935, name: "A. Van Hoorenbeeck", korean_name: "아흐메드 판 호렌벡", team_id: 415, position: "Defender", number: 17, age: 27 },
  { id: 48190, name: "A. Sampsted", korean_name: "알프레드 삼프스테드", team_id: 415, position: "Defender", number: 23, age: 27 },
  { id: 292553, name: "Stav Lemkin", korean_name: "스타브 렘킨", team_id: 415, position: "Defender", number: 23, age: 22 },
  { id: 37370, name: "B. van Rooij", korean_name: "바르트 판 로이", team_id: 415, position: "Defender", number: 28, age: 24 },
  { id: 291994, name: "M. Bruns", korean_name: "맥스 브룬스", team_id: 415, position: "Defender", number: 38, age: 23 },
  { id: 408853, name: "M. Rots", korean_name: "마르셀 로츠", team_id: 415, position: "Defender", number: 39, age: 19 },
  { id: 494106, name: "R. Nijstad", korean_name: "리에프 네이스타트", team_id: 415, position: "Defender", number: 43, age: 17 },
  { id: 137209, name: "M. Kjølø", korean_name: "마티아스 휠레", team_id: 415, position: "Midfielder", number: 4, age: 24 },
  { id: 129047, name: "Ramiz Larbi Zerrouki", korean_name: "라미즈 라르비 제루키", team_id: 415, position: "Midfielder", number: 6, age: 27 },
  { id: 161883, name: "Y. Regeer", korean_name: "요프 레헤이르", team_id: 415, position: "Midfielder", number: 6, age: 22 },
  { id: 36989, name: "M. van Bergen", korean_name: "미힐 판 베르헌", team_id: 415, position: "Midfielder", number: 7, age: 26 },
  { id: 272726, name: "D. Rots", korean_name: "다인 로츠", team_id: 415, position: "Midfielder", number: 11, age: 24 },
  { id: 191879, name: "Kristian Nökkvi Hlynsson", korean_name: "크리스티안 뇌크비 흘린손", team_id: 415, position: "Midfielder", number: 14, age: 21 },
  { id: 428077, name: "H. Kuster", korean_name: "하르트 쿠스터르", team_id: 415, position: "Midfielder", number: 20, age: 20 },
  { id: 36934, name: "Thomas van den Belt", korean_name: "토마스 판 덴 벨트", team_id: 415, position: "Midfielder", number: 20, age: 24 },
  { id: 241, name: "M. Sadílek", korean_name: "미할 사딜렉", team_id: 415, position: "Midfielder", number: 23, age: 26 },
  { id: 453713, name: "B. Nagel", korean_name: "벤 나헬", team_id: 415, position: "Midfielder", number: 26, age: null },
  { id: 352730, name: "Sondre Holmlund Ørjasæter", korean_name: "손드레 홀룬드 외리아세테르", team_id: 415, position: "Midfielder", number: 27, age: 22 },
  { id: 38706, name: "A. Verschueren", korean_name: "아리노 페르스휘런", team_id: 415, position: "Midfielder", number: 32, age: 28 },
  { id: 408854, name: "G. Besselink", korean_name: "히스 베설링크", team_id: 415, position: "Midfielder", number: 41, age: 21 },
  { id: 336562, name: "Daouda Weidmann", korean_name: "다우다 바이트만", team_id: 415, position: "Midfielder", number: 42, age: 22 },
  { id: 30413, name: "Marko Pjaca", korean_name: "마르코 피야차", team_id: 415, position: "Attacker", number: 7, age: 30 },
  { id: 162157, name: "T. Booth", korean_name: "타일러 부스", team_id: 415, position: "Attacker", number: 8, age: 24 },
  { id: 48390, name: "R. van Wolfswinkel", korean_name: "리키 판 볼프스빙컬", team_id: 415, position: "Attacker", number: 9, age: 36 },
  { id: 36987, name: "S. Lammers", korean_name: "샘 라메르스", team_id: 415, position: "Attacker", number: 10, age: 28 },
  { id: 328670, name: "Y. Taha", korean_name: "야신 타하", team_id: 415, position: "Attacker", number: 10, age: 23 },
  { id: 455252, name: "Lucas Vennegoor of Hesselink", korean_name: "루카스 페네호르 오프 헤설링크", team_id: 415, position: "Attacker", number: 25, age: 19 },
  { id: 496426, name: "Owen Panneflek", korean_name: "오웬 파네플렉", team_id: 415, position: "Attacker", number: 30, age: 19 },
  { id: 264419, name: "S. Ltaief", korean_name: "사심 르타이프", team_id: 415, position: "Attacker", number: 30, age: 25 },
  { id: 161894, name: "N. Ünüvar", korean_name: "누리 위뉘바르", team_id: 415, position: "Attacker", number: 37, age: 22 },
  { id: 551116, name: "B. Nagel", korean_name: "벤 나헬", team_id: 415, position: undefined, number: null, age: null },
];

// Utrecht (Team ID: 207) - 32명
export const UTRECHT_PLAYERS: PlayerMapping[] = [
  { id: 584, name: "V. Barkas", korean_name: "바실리오스 바르카스", team_id: 207, position: "Goalkeeper", number: 1, age: 31 },
  { id: 37247, name: "M. Brouwer", korean_name: "마텐 브라우어르", team_id: 207, position: "Goalkeeper", number: 25, age: 32 },
  { id: 299817, name: "K. Gadellaa", korean_name: "키스 하델라", team_id: 207, position: "Goalkeeper", number: 33, age: 22 },
  { id: 408675, name: "M. Eppink", korean_name: "마크 에핑크", team_id: 207, position: "Goalkeeper", number: 51, age: 19 },
  { id: 37874, name: "S. Horemans", korean_name: "시에베 호레만스", team_id: 207, position: "Defender", number: 2, age: 27 },
  { id: 19322, name: "M. van der Hoorn", korean_name: "미케 판 데르 호른", team_id: 207, position: "Defender", number: 3, age: 33 },
  { id: 28646, name: "K. Finnsson", korean_name: "콜베인 핀손", team_id: 207, position: "Defender", number: 5, age: 26 },
  { id: 127803, name: "S. El Karouani", korean_name: "수피안 엘 카루아니", team_id: 207, position: "Defender", number: 16, age: 25 },
  { id: 47814, name: "N. Vesterlund", korean_name: "니콜라이 베스테를룬드", team_id: 207, position: "Defender", number: 23, age: 26 },
  { id: 232, name: "N. Viergever", korean_name: "닉 피어헤버르", team_id: 207, position: "Defender", number: 24, age: 36 },
  { id: 161898, name: "M. Didden", korean_name: "마르크 디던", team_id: 207, position: "Defender", number: 40, age: 24 },
  { id: 37735, name: "M. Eerdhuijzen", korean_name: "마이크 에르드하위전", team_id: 207, position: "Defender", number: 44, age: 25 },
  { id: 37760, name: "D. Murkin", korean_name: "데이비드 머킨", team_id: 207, position: "Defender", number: 55, age: 26 },
  { id: 156998, name: "D. van den Berg", korean_name: "다비드 판 덴 베르흐", team_id: 207, position: "Midfielder", number: 6, age: 25 },
  { id: 350641, name: "I. Jenner", korean_name: "이사크 예너", team_id: 207, position: "Midfielder", number: 6, age: 21 },
  { id: 38752, name: "V. Jensen", korean_name: "빅토르 옌센", team_id: 207, position: "Midfielder", number: 7, age: 25 },
  { id: 203162, name: "C. Bozdoğan", korean_name: "칸 보즈도안", team_id: 207, position: "Midfielder", number: 8, age: 24 },
  { id: 266814, name: "Y. Cathline", korean_name: "요안 카틀린", team_id: 207, position: "Midfielder", number: 10, age: 23 },
  { id: 284295, name: "Zidane Iqbal", korean_name: "지단 이크발", team_id: 207, position: "Midfielder", number: 14, age: 22 },
  { id: 367472, name: "A. Blake", korean_name: "애덤 블레이크", team_id: 207, position: "Midfielder", number: 15, age: 20 },
  { id: 425819, name: "G. Zechiël", korean_name: "히드온 제히엘", team_id: 207, position: "Midfielder", number: 21, age: 21 },
  { id: 192434, name: "Miguel Rodríguez", korean_name: "미겔 로드리게스", team_id: 207, position: "Midfielder", number: 22, age: 22 },
  { id: 321746, name: "A. Engwanda", korean_name: "아딤 엥완다", team_id: 207, position: "Midfielder", number: 27, age: 22 },
  { id: 359315, name: "R. El Arguioui", korean_name: "리다 엘 아르기우이", team_id: 207, position: "Midfielder", number: 43, age: 20 },
  { id: 494134, name: "J. van Ommeren", korean_name: "준 판 오메런", team_id: 207, position: "Midfielder", number: 46, age: 17 },
  { id: 93007, name: "D. Min", korean_name: "민다비드", team_id: 207, position: "Attacker", number: 9, age: 26 },
  { id: 280317, name: "N. Ohio", korean_name: "노아 오하이오", team_id: 207, position: "Attacker", number: 11, age: 22 },
  { id: 401916, name: "J. van de Haar", korean_name: "야덴 판 더 하르", team_id: 207, position: "Attacker", number: 15, age: 20 },
  { id: 391283, name: "E. Demircan", korean_name: "에게 데미르찬", team_id: 207, position: "Attacker", number: 17, age: 20 },
  { id: 539, name: "D. de Wit", korean_name: "다비드 더 비트", team_id: 207, position: "Attacker", number: 20, age: 27 },
  { id: 364809, name: "M. Jonathans", korean_name: "마틸트 요나탄스", team_id: 207, position: "Attacker", number: 26, age: 21 },
  { id: 1826, name: "Sébastien Romain Teddy Haller", korean_name: "세바스티앙 알러", team_id: 207, position: "Attacker", number: 91, age: 31 },
];

// 에레디비지에 전체 선수 (668명, 18개 팀)
export const EREDIVISIE_PLAYERS: PlayerMapping[] = [
  ...AJAX_PLAYERS,
  ...AZ_ALKMAAR_PLAYERS,
  ...EXCELSIOR_PLAYERS,
  ...FC_VOLENDAM_PLAYERS,
  ...FEYENOORD_PLAYERS,
  ...FORTUNA_SITTARD_PLAYERS,
  ...GO_AHEAD_EAGLES_PLAYERS,
  ...GRONINGEN_PLAYERS,
  ...HEERENVEEN_PLAYERS,
  ...HERACLES_PLAYERS,
  ...NAC_BREDA_PLAYERS,
  ...NEC_NIJMEGEN_PLAYERS,
  ...PEC_ZWOLLE_PLAYERS,
  ...PSV_EINDHOVEN_PLAYERS,
  ...SPARTA_ROTTERDAM_PLAYERS,
  ...TELSTAR_PLAYERS,
  ...TWENTE_PLAYERS,
  ...UTRECHT_PLAYERS,
];
