import { PlayerMapping } from './index';

// J1 League Players

// Albirex Niigata
export const ALBIREX_NIIGATA_PLAYERS: PlayerMapping[] = [
  { id: 33620, name: "K. Fujita", korean_name: "K. 후지타", team_id: 311, position: "Goalkeeper", number: 1, age: 24 },
  { id: 33847, name: "J. Geria", korean_name: "J. 게리아", team_id: 311, position: "Defender", number: 2, age: 32 },
  { id: 33630, name: "S. Okamoto", korean_name: "S. 오카모토", team_id: 311, position: "Defender", number: 4, age: 25 },
  { id: 32949, name: "M. Fitzgerald", korean_name: "M. 피츠제럴드", team_id: 311, position: "Defender", number: 5, age: 37 },
  { id: 109255, name: "K. Taniguchi", korean_name: "K. 다니구치", team_id: 311, position: "Attacker", number: 7, age: 30 },
  { id: 33651, name: "K. Yamura", korean_name: "K. 야무라", team_id: 311, position: "Attacker", number: 9, age: 28 },
  { id: 180923, name: "Danilo Gomes", korean_name: "다닐로 고메스", team_id: 311, position: "Midfielder", number: 11, age: 26 },
  { id: 356560, name: "R. Ochiai", korean_name: "R. 오치아이", team_id: 311, position: "Midfielder", number: 13, age: 26 },
  { id: 33626, name: "F. Hayakawa", korean_name: "F. 하야카와", team_id: 311, position: "Defender", number: 15, age: 31 },
  { id: 33634, name: "H. Akiyama", korean_name: "H. 아키야마", team_id: 311, position: "Midfielder", number: 16, age: 25 },
  { id: 33151, name: "Y. Wakatsuki", korean_name: "Y. 와카츠키", team_id: 311, position: "Attacker", number: 18, age: 23 },
  { id: 32916, name: "Y. Hoshi", korean_name: "Y. 호시", team_id: 311, position: "Midfielder", number: 19, age: 33 },
  { id: 64331, name: "Miguel Silveira", korean_name: "미겔 실베이라", team_id: 311, position: "Midfielder", number: 20, age: 22 },
  { id: 307956, name: "R. Tashiro", korean_name: "R. 타시로", team_id: 311, position: "Goalkeeper", number: 21, age: 27 },
  { id: 206924, name: "T. Arai", korean_name: "T. 아라이", team_id: 311, position: "Midfielder", number: 22, age: 28 },
  { id: 33987, name: "D. Yoshimitsu", korean_name: "D. 요시미츠", team_id: 311, position: "Goalkeeper", number: 23, age: 32 },
  { id: 109334, name: "S. Fujiwara", korean_name: "S. 후지와라", team_id: 311, position: "Defender", number: 25, age: 30 },
  { id: 455188, name: "J. Okumura", korean_name: "J. 오쿠무라", team_id: 311, position: "Midfielder", number: 30, age: 24 },
  { id: 33637, name: "Y. Horigome", korean_name: "Y. 호리고메", team_id: 311, position: "Defender", number: 31, age: 31 },
  { id: 33641, name: "Y. Takagi", korean_name: "Y. 타카기", team_id: 311, position: "Midfielder", number: 33, age: 33 },
  { id: 32880, name: "K. Chiba", korean_name: "K. 치바", team_id: 311, position: "Defender", number: 35, age: 40 },
  { id: 354518, name: "K. Mori", korean_name: "K. 모리", team_id: 311, position: "Defender", number: 38, age: 26 },
  { id: 201060, name: "M. Hasegawa", korean_name: "M. 하세가와", team_id: 311, position: "Attacker", number: 41, age: 27 },
  { id: 265828, name: "K. Hashimoto", korean_name: "K. 하시모토", team_id: 311, position: "Defender", number: 42, age: 26 },
  { id: 370122, name: "Keisuke Kasai", korean_name: "케이스케케 카사이", team_id: 311, position: "Midfielder", number: 46, age: 23 },
  { id: 458245, name: "Y. Otake", korean_name: "Y. 오타케", team_id: 311, position: "Midfielder", number: 48, age: 20 },
  { id: 382545, name: "H. Uemura", korean_name: "H. 우에무라", team_id: 311, position: "Defender", number: 50, age: 24 },
  { id: 278499, name: "Moraes", korean_name: "모라이스", team_id: 311, position: "Attacker", number: 55, age: 25 },
  { id: 47627, name: "A. Boudah", korean_name: "A. 보우다", team_id: 311, position: "Attacker", number: 65, age: 26 },
  { id: 33412, name: "Y. Ono", korean_name: "Y. 오노", team_id: 311, position: "Attacker", number: 99, age: 33 },
  { id: 410012, name: "S. Uchiyama", korean_name: "S. 우치야마", team_id: 311, position: "Goalkeeper", number: null, age: 19 },
  { id: 524837, name: "Y. Yasuda", korean_name: "Y. 야스다", team_id: 311, position: "Defender", number: null, age: 18 },
];

// Avispa Fukuoka
export const AVISPA_FUKUOKA_PLAYERS: PlayerMapping[] = [
  { id: 33985, name: "T. Nagaishi", korean_name: "T. 나가이시", team_id: 316, position: "Goalkeeper", number: 1, age: 29 },
  { id: 33511, name: "M. Yuzawa", korean_name: "M. 유자와", team_id: 316, position: "Midfielder", number: 2, age: 32 },
  { id: 32952, name: "T. Nara", korean_name: "T. 나라", team_id: 316, position: "Defender", number: 3, age: 32 },
  { id: 33594, name: "T. Kamijima", korean_name: "T. 카미지마", team_id: 316, position: "Defender", number: 5, age: 28 },
  { id: 415189, name: "M. Shigemi", korean_name: "M. 시게미", team_id: 316, position: "Midfielder", number: 6, age: 24 },
  { id: 32861, name: "K. Konno", korean_name: "K. 콘노", team_id: 316, position: "Midfielder", number: 8, age: 28 },
  { id: 89712, name: "S. Zahedi", korean_name: "S. 자헤디", team_id: 316, position: "Attacker", number: 9, age: 30 },
  { id: 33948, name: "H. Jogo", korean_name: "H. 조고", team_id: 316, position: "Attacker", number: 10, age: 39 },
  { id: 119661, name: "T. Miki", korean_name: "T. 미키", team_id: 316, position: "Midfielder", number: 11, age: 27 },
  { id: 48494, name: "N. Ben Khalifa", korean_name: "나심 벤 칼리파", team_id: 316, position: "Attacker", number: 13, age: 33 },
  { id: 33079, name: "S. Nago", korean_name: "S. 나고", team_id: 316, position: "Attacker", number: 14, age: 29 },
  { id: 33132, name: "H. Akino", korean_name: "H. 아키노", team_id: 316, position: "Midfielder", number: 15, age: 31 },
  { id: 33068, name: "I. Oda", korean_name: "I. 오다", team_id: 316, position: "Defender", number: 16, age: 27 },
  { id: 33252, name: "Wellington Tanque", korean_name: "웰링턴 탄케", team_id: 316, position: "Attacker", number: 17, age: 37 },
  { id: 32998, name: "Y. Iwasaki", korean_name: "Y. 이와사키", team_id: 316, position: "Attacker", number: 18, age: 27 },
  { id: 508073, name: "Kim Moon-Hyeon", korean_name: "김문현", team_id: 316, position: "Defender", number: 19, age: 23 },
  { id: 307929, name: "T. Ando", korean_name: "T. 안도", team_id: 316, position: "Defender", number: 20, age: 26 },
  { id: 265656, name: "K. Fujimoto", korean_name: "K. 후지모토", team_id: 316, position: "Attacker", number: 22, age: 27 },
  { id: 33356, name: "Y. Obata", korean_name: "Y. 오바타", team_id: 316, position: "Goalkeeper", number: 24, age: 24 },
  { id: 33942, name: "Y. Kitajima", korean_name: "Y. 키타지마", team_id: 316, position: "Midfielder", number: 25, age: 25 },
  { id: 433907, name: "S. Usui", korean_name: "S. 우스이", team_id: 316, position: "Attacker", number: 27, age: 24 },
  { id: 91864, name: "Y. Maejima", korean_name: "Y. 마에지마", team_id: 316, position: "Defender", number: 29, age: 28 },
  { id: 33418, name: "M. Murakami", korean_name: "M. 무라카미", team_id: 316, position: "Goalkeeper", number: 31, age: 33 },
  { id: 550743, name: "A. Sani Brown", korean_name: "A. Sani 브라운", team_id: 316, position: null, number: 32, age: null },
  { id: 508074, name: "S. Brown", korean_name: "S. 브라운", team_id: 316, position: "Attacker", number: 32, age: 19 },
  { id: 34060, name: "M. Tashiro", korean_name: "M. 타시로", team_id: 316, position: "Defender", number: 37, age: 32 },
  { id: 91692, name: "J. Ikeda", korean_name: "J. 이케다", team_id: 316, position: "Defender", number: 40, age: 29 },
  { id: 455835, name: "Y. Hashimoto", korean_name: "Y. 하시모토", team_id: 316, position: "Midfielder", number: 47, age: 23 },
  { id: 519156, name: "S. Sato", korean_name: "S. 사토", team_id: 316, position: "Attacker", number: 50, age: 22 },
  { id: 410010, name: "K. Suganuma", korean_name: "K. 스가누마", team_id: 316, position: "Goalkeeper", number: 51, age: 24 },
  { id: 522581, name: "H. Maeda", korean_name: "H. 마에다", team_id: 316, position: "Attacker", number: 53, age: 17 },
  { id: 33425, name: "T. Shichi", korean_name: "T. 시치", team_id: 316, position: "Defender", number: 77, age: 32 },
  { id: 33402, name: "D. Matsuoka", korean_name: "D. 마츠오카", team_id: 316, position: "Midfielder", number: 88, age: 24 },
  { id: 550754, name: "H. Maeda", korean_name: "H. 마에다", team_id: 316, position: null, number: null, age: null },
  { id: 550753, name: "K. Suganuma", korean_name: "K. 스가누마", team_id: 316, position: null, number: null, age: null },
  { id: 550751, name: "M. Kim", korean_name: "M. 김", team_id: 316, position: null, number: null, age: null },
  { id: 500914, name: "S. Takemoto", korean_name: "S. 타케모토", team_id: 316, position: "Midfielder", number: null, age: 16 },
];

// Cerezo Osaka
export const CEREZO_OSAKA_PLAYERS: PlayerMapping[] = [
  { id: 33870, name: "K. Fukui", korean_name: "K. 후쿠이", team_id: 291, position: "Goalkeeper", number: 1, age: 30 },
  { id: 109351, name: "N. Matsumoto", korean_name: "N. 마츠모토", team_id: 291, position: "Midfielder", number: 2, age: 24 },
  { id: 32853, name: "T. Nakamura", korean_name: "T. 나카무라", team_id: 291, position: "Defender", number: 2, age: 24 },
  { id: 32980, name: "R. Shindo", korean_name: "R. 신도", team_id: 291, position: "Defender", number: 3, age: 29 },
  { id: 33428, name: "Y. Hirano", korean_name: "Y. 히라노", team_id: 291, position: "Midfielder", number: 4, age: 29 },
  { id: 33940, name: "H. Kida", korean_name: "H. 키다", team_id: 291, position: "Midfielder", number: 5, age: 25 },
  { id: 32953, name: "K. Noborizato", korean_name: "K. 노보리자토", team_id: 291, position: "Defender", number: 6, age: 35 },
  { id: 33684, name: "S. Uejo", korean_name: "S. 우에조", team_id: 291, position: "Midfielder", number: 7, age: 28 },
  { id: 403457, name: "R. Osako", korean_name: "R. 오사코", team_id: 291, position: "Midfielder", number: 8, age: 21 },
  { id: 1991, name: "S. Kagawa", korean_name: "S. 카가와", team_id: 291, position: "Midfielder", number: 8, age: 36 },
  { id: 61159, name: "Rafael Ratão", korean_name: "하파엘 하타옹", team_id: 291, position: "Attacker", number: 9, age: 30 },
  { id: 182008, name: "S. Tanaka", korean_name: "S. 타나카", team_id: 291, position: "Midfielder", number: 10, age: 28 },
  { id: 288011, name: "Thiago Andrade", korean_name: "치아구 안드라데", team_id: 291, position: "Midfielder", number: 11, age: 25 },
  { id: 33185, name: "M. Nakajima", korean_name: "M. 나카지마", team_id: 291, position: "Attacker", number: 13, age: 26 },
  { id: 33159, name: "K. Funaki", korean_name: "K. 후나키", team_id: 291, position: "Defender", number: 14, age: 27 },
  { id: 109274, name: "H. Okuda", korean_name: "H. 오쿠다", team_id: 291, position: "Defender", number: 16, age: 24 },
  { id: 403458, name: "R. Sakata", korean_name: "R. 사카타", team_id: 291, position: "Midfielder", number: 17, age: 21 },
  { id: 33155, name: "Kim Jin-Hyeon", korean_name: "김진현", team_id: 291, position: "Goalkeeper", number: 21, age: 38 },
  { id: 369478, name: "Niko Takahashi Cendagorta", korean_name: "니코 타카하시 센다고르타", team_id: 291, position: "Defender", number: 22, age: 20 },
  { id: 65, name: "Dion-Johan Cools", korean_name: "디온 쿨스", team_id: 291, position: "Defender", number: 27, age: 29 },
  { id: 440567, name: "K. Furuyama", korean_name: "K. 후루야마", team_id: 291, position: "Attacker", number: 29, age: 23 },
  { id: 109348, name: "R. Nishio", korean_name: "R. 니시오", team_id: 291, position: "Defender", number: 33, age: 24 },
  { id: 33052, name: "K. Yoshino", korean_name: "K. 요시노", team_id: 291, position: "Midfielder", number: 35, age: 31 },
  { id: 520841, name: "Chimezie Kai Ezemuokwe", korean_name: "치메지 카이 에제무오퀘", team_id: 291, position: "Defender", number: 43, age: 16 },
  { id: 2591, name: "S. Hatanaka", korean_name: "S. 하타나카", team_id: 291, position: "Defender", number: 44, age: 30 },
  { id: 411128, name: "K. Makiguchi", korean_name: "K. 마키구치", team_id: 291, position: "Goalkeeper", number: 47, age: 21 },
  { id: 291138, name: "M. Shibayama", korean_name: "M. 시바야마", team_id: 291, position: "Midfielder", number: 48, age: 23 },
  { id: 9962, name: "Vitor Bueno", korean_name: "부에노 비토르", team_id: 291, position: "Attacker", number: 55, age: 31 },
  { id: 153274, name: "A. Ohata", korean_name: "A. 오하타", team_id: 291, position: "Defender", number: 66, age: 24 },
  { id: 32996, name: "Lucas Fernandes", korean_name: "루카스 페르난데스", team_id: 291, position: "Midfielder", number: 77, age: 31 },
  { id: 133317, name: "Go Kambayashi", korean_name: "고고 캄바야시", team_id: 291, position: "Goalkeeper", number: null, age: 23 },
  { id: 466967, name: "K. Isibor", korean_name: "K. 이시보르", team_id: 291, position: "Goalkeeper", number: null, age: 18 },
  { id: 522402, name: "R. Onoda", korean_name: "R. 오노다", team_id: 291, position: "Attacker", number: null, age: 18 },
];

// Fagiano Okayama
export const FAGIANO_OKAYAMA_PLAYERS: PlayerMapping[] = [
  { id: 237242, name: "M. Sasaki", korean_name: "M. 사사키", team_id: 310, position: "Goalkeeper", number: 1, age: 23 },
  { id: 33337, name: "Y. Tatsuta", korean_name: "Y. 타츠타", team_id: 310, position: "Defender", number: 2, age: 27 },
  { id: 506847, name: "K. Fujii", korean_name: "K. 후지이", team_id: 310, position: "Midfielder", number: 3, age: 22 },
  { id: 550720, name: "K. Fujii", korean_name: "K. 후지이", team_id: 310, position: null, number: 3, age: null },
  { id: 550707, name: "K. Abe", korean_name: "K. 아베", team_id: 310, position: null, number: 4, age: null },
  { id: 33723, name: "K. Abe", korean_name: "K. 아베", team_id: 310, position: "Defender", number: 4, age: 26 },
  { id: 33633, name: "Y. Yanagi", korean_name: "Y. 야나기", team_id: 310, position: "Defender", number: 5, age: 31 },
  { id: 109372, name: "Y. Wakasa", korean_name: "Y. 와카사", team_id: 310, position: "Midfielder", number: 6, age: 29 },
  { id: 33348, name: "R. Takeuchi", korean_name: "R. 타케우치", team_id: 310, position: "Midfielder", number: 7, age: 34 },
  { id: 33605, name: "A. Esaka", korean_name: "A. 에사카", team_id: 310, position: "Attacker", number: 8, age: 33 },
  { id: 159829, name: "Gleyson", korean_name: "글레이송 가르시아 지 올리베이라", team_id: 310, position: "Attacker", number: 11, age: 29 },
  { id: 457162, name: "R. Ota", korean_name: "R. 오타", team_id: 310, position: "Attacker", number: 11, age: 23 },
  { id: 33720, name: "J. Kanayama", korean_name: "J. 카나야마", team_id: 310, position: "Goalkeeper", number: 13, age: 37 },
  { id: 318059, name: "R. Tabei", korean_name: "R. 타베이", team_id: 310, position: "Midfielder", number: 14, age: 26 },
  { id: 309809, name: "K. Kudo", korean_name: "K. 쿠도", team_id: 310, position: "Defender", number: 15, age: 22 },
  { id: 506849, name: "Y. Iesaka", korean_name: "Y. 이에사카", team_id: 310, position: "Midfielder", number: 16, age: 23 },
  { id: 33463, name: "R. Sueyoshi", korean_name: "R. 스에요시", team_id: 310, position: "Midfielder", number: 17, age: 29 },
  { id: 33602, name: "D. Tagami", korean_name: "D. 타가미", team_id: 310, position: "Defender", number: 18, age: 32 },
  { id: 352460, name: "H. Iwabuchi", korean_name: "H. 이와부치", team_id: 310, position: "Midfielder", number: 19, age: 28 },
  { id: 550721, name: "H. Iwabuchi", korean_name: "H. 이와부치", team_id: 310, position: null, number: 19, age: null },
  { id: 457159, name: "K. Kawakami", korean_name: "K. 카와카미", team_id: 310, position: "Goalkeeper", number: 21, age: 24 },
  { id: 33588, name: "K. Ichimi", korean_name: "K. 이치미", team_id: 310, position: "Attacker", number: 22, age: 28 },
  { id: 352454, name: "R. Saga", korean_name: "R. 사가", team_id: 310, position: "Midfielder", number: 23, age: 27 },
  { id: 33213, name: "I. Fujita", korean_name: "I. 후지타", team_id: 310, position: "Midfielder", number: 24, age: 34 },
  { id: 550711, name: "T. Kimura", korean_name: "T. 키무라", team_id: 310, position: null, number: 27, age: null },
  { id: 304914, name: "T. Kimura", korean_name: "T. 키무라", team_id: 310, position: "Attacker", number: 27, age: 27 },
  { id: 33276, name: "M. Matsumoto", korean_name: "M. 마츠모토", team_id: 310, position: "Midfielder", number: 28, age: 30 },
  { id: 33440, name: "K. Saito", korean_name: "K. 사이토", team_id: 310, position: "Attacker", number: 29, age: 32 },
  { id: 33908, name: "Y. Kamiya", korean_name: "Y. 카미야", team_id: 310, position: "Midfielder", number: 33, age: 28 },
  { id: 410840, name: "R. Sato", korean_name: "R. 사토", team_id: 310, position: "Midfielder", number: 39, age: 19 },
  { id: 352453, name: "E. Miyamoto", korean_name: "E. 미야모토", team_id: 310, position: "Midfielder", number: 41, age: 27 },
  { id: 550729, name: "Y. Suzuki", korean_name: "Y. 스즈키", team_id: 310, position: null, number: 43, age: null },
  { id: 67875, name: "Y. Suzuki", korean_name: "Y. 스즈키", team_id: 310, position: "Defender", number: 43, age: 27 },
  { id: 24918, name: "S. Brodersen", korean_name: "S. 브로더센", team_id: 310, position: "Goalkeeper", number: 49, age: 28 },
  { id: 199886, name: "H. Kato", korean_name: "H. 카토", team_id: 310, position: "Midfielder", number: 50, age: 24 },
  { id: 550712, name: "H. Kato", korean_name: "H. 카토", team_id: 310, position: null, number: 50, age: null },
  { id: 33453, name: "T. Yanagi", korean_name: "T. 야나기", team_id: 310, position: "Defender", number: 88, age: 28 },
  { id: 318170, name: "Werik Popó", korean_name: "웨리크 포포", team_id: 310, position: "Attacker", number: 98, age: 24 },
  { id: 27076, name: "Lucão", korean_name: "루캉캉", team_id: 310, position: "Attacker", number: 99, age: 30 },
  { id: 473599, name: "K. Suemune", korean_name: "K. 스에무네", team_id: 310, position: "Attacker", number: null, age: 18 },
  { id: 510575, name: "R. Senda", korean_name: "R. 센다", team_id: 310, position: "Defender", number: null, age: 18 },
  { id: 550708, name: "R. Tabei", korean_name: "R. 타베이", team_id: 310, position: null, number: null, age: null },
  { id: 550749, name: "Y. Iesaka", korean_name: "Y. 이에사카", team_id: 310, position: null, number: null, age: null },
];

// FC Tokyo
export const FC_TOKYO_PLAYERS: PlayerMapping[] = [
  { id: 2593, name: "S. Muroya", korean_name: "S. 무로야", team_id: 292, position: "Defender", number: 2, age: 31 },
  { id: 458243, name: "Baek In-Hwan", korean_name: "백인환", team_id: 292, position: "Defender", number: 3, age: 20 },
  { id: 32852, name: "M. Morishige", korean_name: "M. 모리시게", team_id: 292, position: "Defender", number: 3, age: 38 },
  { id: 33162, name: "Y. Kimoto", korean_name: "Y. 키모토", team_id: 292, position: "Defender", number: 4, age: 32 },
  { id: 109271, name: "S. Kimura", korean_name: "S. 키무라", team_id: 292, position: "Defender", number: 5, age: 24 },
  { id: 440, name: "Y. Nagatomo", korean_name: "Y. 나가토모", team_id: 292, position: "Defender", number: 5, age: 39 },
  { id: 109382, name: "K. Bangnagande", korean_name: "K. 방나간데", team_id: 292, position: "Defender", number: 6, age: 24 },
  { id: 416967, name: "S. Anzai", korean_name: "S. 안자이", team_id: 292, position: "Midfielder", number: 7, age: 23 },
  { id: 33310, name: "T. Ko", korean_name: "T. 코", team_id: 292, position: "Midfielder", number: 8, age: 27 },
  { id: 32859, name: "K. Higashi", korean_name: "K. 히가시", team_id: 292, position: "Midfielder", number: 10, age: 35 },
  { id: 268144, name: "T. Ogashiwa", korean_name: "T. 오가시와", team_id: 292, position: "Attacker", number: 11, age: 27 },
  { id: 32848, name: "G. Hatano", korean_name: "G. 하타노", team_id: 292, position: "Goalkeeper", number: 13, age: 27 },
  { id: 34012, name: "K. Yamashita", korean_name: "K. 야마시타", team_id: 292, position: "Attacker", number: 14, age: 29 },
  { id: 369768, name: "K. Sato", korean_name: "K. 사토", team_id: 292, position: "Midfielder", number: 16, age: 24 },
  { id: 33220, name: "K. Tsukagawa", korean_name: "K. 츠카가와", team_id: 292, position: "Midfielder", number: 16, age: 31 },
  { id: 109453, name: "T. Terayama", korean_name: "T. 테라야마", team_id: 292, position: "Midfielder", number: 17, age: 25 },
  { id: 2599, name: "K. Hashimoto", korean_name: "K. 하시모토", team_id: 292, position: "Midfielder", number: 18, age: 32 },
  { id: 288013, name: "Marcelo Ryan", korean_name: "마르셀루 라이언", team_id: 292, position: "Attacker", number: 19, age: 23 },
  { id: 33017, name: "K. Endo", korean_name: "K. 엔도", team_id: 292, position: "Midfielder", number: 22, age: 28 },
  { id: 15795, name: "A. Scholz", korean_name: "A. 숄츠", team_id: 292, position: "Defender", number: 24, age: 33 },
  { id: 527931, name: "T. Kominato", korean_name: "T. 코미나토", team_id: 292, position: null, number: 25, age: null },
  { id: 115608, name: "Kyota Tokiwa", korean_name: "교교타 토키와", team_id: 292, position: "Midfielder", number: 27, age: 23 },
  { id: 141184, name: "L. Nozawa", korean_name: "L. 노자와", team_id: 292, position: "Attacker", number: 28, age: 22 },
  { id: 115609, name: "T. Oka", korean_name: "T. 오카", team_id: 292, position: "Defender", number: 30, age: 24 },
  { id: 369956, name: "M. Kobayashi", korean_name: "M. 코바야시", team_id: 292, position: "Goalkeeper", number: 31, age: 20 },
  { id: 364593, name: "K. Doi", korean_name: "K. 도이", team_id: 292, position: "Defender", number: 32, age: 21 },
  { id: 371233, name: "K. Tawaratsumida", korean_name: "K. 타와라츠미다", team_id: 292, position: "Midfielder", number: 33, age: 21 },
  { id: 342132, name: "H. Nishido", korean_name: "H. 니시도", team_id: 292, position: "Midfielder", number: 36, age: 24 },
  { id: 33608, name: "K. Koizumi", korean_name: "K. 코이즈미", team_id: 292, position: "Midfielder", number: 37, age: 30 },
  { id: 33027, name: "T. Nakagawa", korean_name: "T. 나카가와", team_id: 292, position: "Attacker", number: 39, age: 33 },
  { id: 44492, name: "Marcos Guilherme de Almeida Santos Matos", korean_name: "마르코스 마토스", team_id: 292, position: "Midfielder", number: 40, age: 30 },
  { id: 109381, name: "T. Nozawa", korean_name: "T. 노자와", team_id: 292, position: "Goalkeeper", number: 41, age: 23 },
  { id: 9704, name: "Henrique Trevisan", korean_name: "엔히키 트레비산", team_id: 292, position: "Defender", number: 44, age: 28 },
  { id: 355472, name: "Y. Arai", korean_name: "Y. 아라이", team_id: 292, position: "Midfielder", number: 48, age: 21 },
  { id: 511265, name: "M. Kitahara", korean_name: "M. 키타하라", team_id: 292, position: "Attacker", number: 77, age: 16 },
  { id: 2892, name: "Kim Seung-Gyu", korean_name: "김승규", team_id: 292, position: "Goalkeeper", number: 81, age: 35 },
  { id: 495504, name: "T. Yamaguchi", korean_name: "T. 야마구치", team_id: 292, position: "Attacker", number: 88, age: 19 },
  { id: 54235, name: "Everton Galdino", korean_name: "에베르통 갈디노", team_id: 292, position: "Attacker", number: 98, age: 28 },
  { id: 32992, name: "K. Shirai", korean_name: "K. 시라이", team_id: 292, position: "Defender", number: 99, age: 31 },
  { id: 423787, name: "W. Goto", korean_name: "W. 고토", team_id: 292, position: "Goalkeeper", number: null, age: 19 },
];

// Gamba Osaka
export const GAMBA_OSAKA_PLAYERS: PlayerMapping[] = [
  { id: 2587, name: "M. Higashiguchi", korean_name: "M. 히가시구치", team_id: 293, position: "Goalkeeper", number: 1, age: 39 },
  { id: 33692, name: "S. Fukuoka", korean_name: "S. 후쿠오카", team_id: 293, position: "Defender", number: 2, age: 30 },
  { id: 64280, name: "R. Handa", korean_name: "R. 한다", team_id: 293, position: "Defender", number: 3, age: 23 },
  { id: 33297, name: "K. Kurokawa", korean_name: "K. 쿠로카와", team_id: 293, position: "Defender", number: 4, age: 28 },
  { id: 2592, name: "G. Miura", korean_name: "G. 미우라", team_id: 293, position: "Defender", number: 5, age: 30 },
  { id: 2605, name: "T. Usami", korean_name: "T. 우사미", team_id: 293, position: "Attacker", number: 7, age: 33 },
  { id: 130231, name: "D. Hayashi", korean_name: "D. 하야시", team_id: 293, position: "Attacker", number: 8, age: 28 },
  { id: 33320, name: "R. Meshino", korean_name: "R. 메시노", team_id: 293, position: "Attacker", number: 8, age: 27 },
  { id: 33312, name: "S. Kurata", korean_name: "S. 쿠라타", team_id: 293, position: "Midfielder", number: 10, age: 37 },
  { id: 44497, name: "I. Jebali", korean_name: "I. 제발리", team_id: 293, position: "Attacker", number: 11, age: 34 },
  { id: 73856, name: "S. Abe", korean_name: "S. 아베", team_id: 293, position: "Midfielder", number: 13, age: 28 },
  { id: 33714, name: "T. Kishimoto", korean_name: "T. 키시모토", team_id: 293, position: "Defender", number: 15, age: 28 },
  { id: 33710, name: "T. Suzuki", korean_name: "T. 스즈키", team_id: 293, position: "Midfielder", number: 16, age: 28 },
  { id: 199795, name: "R. Yamashita", korean_name: "R. 야마시타", team_id: 293, position: "Midfielder", number: 17, age: 28 },
  { id: 423786, name: "R. Araki", korean_name: "R. 아라키", team_id: 293, position: "Goalkeeper", number: 18, age: 18 },
  { id: 32886, name: "S. Nakatani", korean_name: "S. 나카타니", team_id: 293, position: "Defender", number: 20, age: 29 },
  { id: 33242, name: "R. Hatsuse", korean_name: "R. 하츠세", team_id: 293, position: "Defender", number: 21, age: 28 },
  { id: 33719, name: "J. Ichimori", korean_name: "J. 이치모리", team_id: 293, position: "Goalkeeper", number: 22, age: 34 },
  { id: 48077, name: "D. Hümmet", korean_name: "데니즈 휘메트", team_id: 293, position: "Attacker", number: 23, age: 29 },
  { id: 33755, name: "Y. Egawa", korean_name: "Y. 에가와", team_id: 293, position: "Defender", number: 24, age: 25 },
  { id: 319012, name: "R. Mito", korean_name: "R. 미토", team_id: 293, position: "Midfielder", number: 27, age: 23 },
  { id: 455404, name: "Zhang Ao lin", korean_name: "아올린 장", team_id: 293, position: "Goalkeeper", number: 31, age: 20 },
  { id: 529815, name: "T. Yamamoto", korean_name: "T. 야마모토", team_id: 293, position: null, number: 36, age: null },
  { id: 423802, name: "Gaku Nawata", korean_name: "Gaku 나와타", team_id: 293, position: "Midfielder", number: 38, age: 19 },
  { id: 367572, name: "H. Minamino", korean_name: "H. 미나미노", team_id: 293, position: "Attacker", number: 42, age: 21 },
  { id: 568667, name: "Y. Nobata", korean_name: "Y. 노바타", team_id: 293, position: null, number: 43, age: null },
  { id: 33496, name: "K. Okunuki", korean_name: "K. 오쿠누키", team_id: 293, position: "Midfielder", number: 44, age: 26 },
  { id: 9351, name: "Juan Alano", korean_name: "후안 알라노", team_id: 293, position: "Midfielder", number: 47, age: 29 },
  { id: 33069, name: "S. Sasaki", korean_name: "S. 사사키", team_id: 293, position: "Defender", number: 67, age: 25 },
  { id: 166701, name: "Welton Felipe", korean_name: "웰통 펠리페", team_id: 293, position: "Midfielder", number: 97, age: 28 },
  { id: 568612, name: "T. Yamamoto", korean_name: "T. 야마모토", team_id: 293, position: null, number: null, age: null },
];

// Kashima
export const KASHIMA_PLAYERS: PlayerMapping[] = [
  { id: 304782, name: "T. Hayakawa", korean_name: "T. 하야카와", team_id: 290, position: "Goalkeeper", number: 1, age: 26 },
  { id: 2590, name: "K. Anzai", korean_name: "K. 안자이", team_id: 290, position: "Defender", number: 2, age: 30 },
  { id: 34418, name: "Kim Tae-Hyeon", korean_name: "김태현", team_id: 290, position: "Defender", number: 3, age: 25 },
  { id: 33070, name: "I. Sekigawa", korean_name: "I. 세키가와", team_id: 290, position: "Defender", number: 5, age: 25 },
  { id: 33077, name: "K. Misao", korean_name: "K. 미사오", team_id: 290, position: "Midfielder", number: 6, age: 29 },
  { id: 32855, name: "R. Ogawa", korean_name: "R. 오가와", team_id: 290, position: "Defender", number: 7, age: 29 },
  { id: 9550, name: "Léo Ceará", korean_name: "레오 세아라", team_id: 290, position: "Attacker", number: 9, age: 30 },
  { id: 2604, name: "G. Shibasaki", korean_name: "G. 시바사키", team_id: 290, position: "Midfielder", number: 10, age: 33 },
  { id: 32875, name: "K. Tagawa", korean_name: "K. 타가와", team_id: 290, position: "Attacker", number: 11, age: 26 },
  { id: 32969, name: "K. Chinen", korean_name: "K. 치넨", team_id: 290, position: "Attacker", number: 13, age: 30 },
  { id: 33399, name: "Y. Higuchi", korean_name: "Y. 히구치", team_id: 290, position: "Midfielder", number: 14, age: 29 },
  { id: 197446, name: "Talles", korean_name: "탈레스", team_id: 290, position: "Attacker", number: 17, age: 27 },
  { id: 403322, name: "S. Morooka", korean_name: "S. 모로오카", team_id: 290, position: "Attacker", number: 19, age: 25 },
  { id: 304786, name: "Y. Funabashi", korean_name: "Y. 후나바시", team_id: 290, position: "Midfielder", number: 20, age: 23 },
  { id: 455185, name: "K. Nono", korean_name: "K. 노노", team_id: 290, position: "Defender", number: 22, age: 23 },
  { id: 403321, name: "K. Tsukui", korean_name: "K. 츠쿠이", team_id: 290, position: "Defender", number: 23, age: 21 },
  { id: 33596, name: "R. Koike", korean_name: "R. 코이케", team_id: 290, position: "Defender", number: 25, age: 30 },
  { id: 197973, name: "Y. Matsumura", korean_name: "Y. 마츠무라", team_id: 290, position: "Midfielder", number: 27, age: 24 },
  { id: 351529, name: "S. Mizoguchi", korean_name: "S. 미조구치", team_id: 290, position: "Defender", number: 28, age: 21 },
  { id: 33687, name: "Y. Kajikawa", korean_name: "Y. 카지카와", team_id: 290, position: "Goalkeeper", number: 29, age: 34 },
  { id: 197971, name: "T. Yamada", korean_name: "T. 야마다", team_id: 290, position: "Goalkeeper", number: 31, age: 23 },
  { id: 423791, name: "H. Matsumoto", korean_name: "H. 마츠모토", team_id: 290, position: "Defender", number: 32, age: 19 },
  { id: 449198, name: "H. Tokuda", korean_name: "H. 토쿠다", team_id: 290, position: "Attacker", number: 34, age: 18 },
  { id: 474154, name: "M. Sato", korean_name: "M. 사토", team_id: 290, position: "Defender", number: 36, age: 18 },
  { id: 403320, name: "Park Eui-Jeong", korean_name: "박의정", team_id: 290, position: "Goalkeeper", number: 38, age: 21 },
  { id: 404029, name: "Y. Shimoda", korean_name: "Y. 시모다", team_id: 290, position: "Midfielder", number: 40, age: 21 },
  { id: 33089, name: "Y. Suzuki", korean_name: "Y. 스즈키", team_id: 290, position: "Attacker", number: 40, age: 29 },
  { id: 500918, name: "M. Yoshida", korean_name: "M. 요시다", team_id: 290, position: "Attacker", number: 45, age: 17 },
  { id: 8670, name: "N. Ueda", korean_name: "N. 우에다", team_id: 290, position: "Defender", number: 55, age: 31 },
  { id: 197972, name: "R. Araki", korean_name: "R. 아라키", team_id: 290, position: "Midfielder", number: 71, age: 23 },
  { id: 61157, name: "A. Čavrić", korean_name: "알렉산다르 차브리치", team_id: 290, position: "Midfielder", number: 77, age: 31 },
  { id: 550763, name: "A. Motosuna", korean_name: "A. 모토스나", team_id: 290, position: null, number: null, age: null },
  { id: 550727, name: "M. Yoshida", korean_name: "M. 요시다", team_id: 290, position: null, number: null, age: null },
];

// Kashiwa Reysol
export const KASHIWA_REYSOL_PLAYERS: PlayerMapping[] = [
  { id: 33591, name: "H. Saruta", korean_name: "H. 사루타", team_id: 281, position: "Goalkeeper", number: 1, age: 26 },
  { id: 33393, name: "H. Mitsumaru", korean_name: "H. 미츠마루", team_id: 281, position: "Defender", number: 2, age: 32 },
  { id: 33694, name: "Diego", korean_name: "디에고", team_id: 281, position: "Midfielder", number: 3, age: 30 },
  { id: 33595, name: "T. Koga", korean_name: "T. 코가", team_id: 281, position: "Defender", number: 4, age: 27 },
  { id: 311885, name: "H. Tanaka", korean_name: "H. 타나카", team_id: 281, position: "Defender", number: 5, age: 22 },
  { id: 33613, name: "Y. Yamada", korean_name: "Y. 야마다", team_id: 281, position: "Midfielder", number: 6, age: 25 },
  { id: 33672, name: "Y. Koizumi", korean_name: "Y. 코이즈미", team_id: 281, position: "Attacker", number: 8, age: 29 },
  { id: 33615, name: "M. Hosoya", korean_name: "M. 호소야", team_id: 281, position: "Attacker", number: 9, age: 24 },
  { id: 33712, name: "Masa", korean_name: "마사", team_id: 281, position: "Attacker", number: 11, age: 26 },
  { id: 33064, name: "T. Inukai", korean_name: "T. 이누카이", team_id: 281, position: "Defender", number: 13, age: 32 },
  { id: 33577, name: "T. Koyamatsu", korean_name: "T. 코야마츠", team_id: 281, position: "Midfielder", number: 14, age: 30 },
  { id: 304912, name: "Y. Komi", korean_name: "Y. 코미", team_id: 281, position: "Attacker", number: 15, age: 23 },
  { id: 33161, name: "E. Katayama", korean_name: "E. 카타야마", team_id: 281, position: "Defender", number: 16, age: 34 },
  { id: 33612, name: "K. Tezuka", korean_name: "K. 테즈카", team_id: 281, position: "Midfielder", number: 17, age: 29 },
  { id: 33555, name: "Y. Kakita", korean_name: "Y. 카키타", team_id: 281, position: "Attacker", number: 18, age: 28 },
  { id: 403460, name: "F. Mohamado", korean_name: "F. 모하마도", team_id: 281, position: "Midfielder", number: 19, age: 21 },
  { id: 33736, name: "H. Nakama", korean_name: "H. 나카마", team_id: 281, position: "Attacker", number: 19, age: 33 },
  { id: 33705, name: "Y. Konishi", korean_name: "Y. 코니시", team_id: 281, position: "Midfielder", number: 21, age: 27 },
  { id: 33299, name: "H. Noda", korean_name: "H. 노다", team_id: 281, position: "Defender", number: 22, age: 28 },
  { id: 318654, name: "T. Kubo", korean_name: "T. 쿠보", team_id: 281, position: "Midfielder", number: 24, age: 26 },
  { id: 32910, name: "R. Kojima", korean_name: "R. 코지마", team_id: 281, position: "Goalkeeper", number: 25, age: 28 },
  { id: 33131, name: "D. Sugioka", korean_name: "D. 스기오카", team_id: 281, position: "Defender", number: 26, age: 27 },
  { id: 455195, name: "K. Kumasaka", korean_name: "K. 쿠마사카", team_id: 281, position: "Midfielder", number: 27, age: 24 },
  { id: 33642, name: "S. Toshima", korean_name: "S. 토시마", team_id: 281, position: "Midfielder", number: 28, age: 30 },
  { id: 33689, name: "Kengo Nagai", korean_name: "켄고 나가이", team_id: 281, position: "Goalkeeper", number: 29, age: 31 },
  { id: 91697, name: "T. Shimamura", korean_name: "T. 시마무라", team_id: 281, position: "Midfielder", number: 29, age: 26 },
  { id: 32899, name: "S. Naruse", korean_name: "S. 나루세", team_id: 281, position: "Midfielder", number: 31, age: 24 },
  { id: 552647, name: "Y. Yamanouchi", korean_name: "Y. 야마노우치", team_id: 281, position: null, number: 32, age: null },
  { id: 33436, name: "E. Shirai", korean_name: "E. 시라이", team_id: 281, position: "Midfielder", number: 33, age: 30 },
  { id: 508071, name: "S. Nakajima", korean_name: "S. 나카지마", team_id: 281, position: "Attacker", number: 37, age: 23 },
  { id: 507610, name: "N. Nakagawa", korean_name: "N. 나카가와", team_id: 281, position: "Midfielder", number: 39, age: 23 },
  { id: 33398, name: "R. Harakawa", korean_name: "R. 하라카와", team_id: 281, position: "Midfielder", number: 40, age: 32 },
  { id: 352444, name: "D. Sakata", korean_name: "D. 사카타", team_id: 281, position: "Goalkeeper", number: 41, age: 31 },
  { id: 206933, name: "W. Harada", korean_name: "W. 하라다", team_id: 281, position: "Midfielder", number: 42, age: 29 },
  { id: 199157, name: "K. Matsumoto", korean_name: "K. 마츠모토", team_id: 281, position: "Goalkeeper", number: 46, age: 28 },
  { id: 403461, name: "K. Kumasawa", korean_name: "K. 쿠마사와", team_id: 281, position: "Midfielder", number: 48, age: 24 },
  { id: 199913, name: "S. Baba", korean_name: "S. 바바", team_id: 281, position: "Defender", number: 88, age: 24 },
  { id: 500908, name: "K. Chonan", korean_name: "K. 초난", team_id: 281, position: "Midfielder", number: null, age: 15 },
  { id: 467241, name: "T. Kuwata", korean_name: "T. 쿠와타", team_id: 281, position: "Defender", number: null, age: 23 },
  { id: 507609, name: "Y. Furusawa", korean_name: "Y. 후루사와", team_id: 281, position: "Attacker", number: null, age: 22 },
  { id: 500911, name: "Y. Kamo", korean_name: "Y. 카모", team_id: 281, position: "Midfielder", number: null, age: 17 },
];

// Kawasaki Frontale
export const KAWASAKI_FRONTALE_PLAYERS: PlayerMapping[] = [
  { id: 32946, name: "Jung Sung-Ryong", korean_name: "정성룡", team_id: 294, position: "Goalkeeper", number: 1, age: 40 },
  { id: 337593, name: "K. Takai", korean_name: "K. 타카이", team_id: 294, position: "Defender", number: 2, age: 21 },
  { id: 32947, name: "Jesiel", korean_name: "제시엘", team_id: 294, position: "Defender", number: 4, age: 31 },
  { id: 351498, name: "A. Sasaki", korean_name: "A. 사사키", team_id: 294, position: "Defender", number: 5, age: 25 },
  { id: 199156, name: "Y. Yamamoto", korean_name: "Y. 야마모토", team_id: 294, position: "Midfielder", number: 6, age: 28 },
  { id: 32950, name: "S. Kurumaya", korean_name: "S. 쿠루마야", team_id: 294, position: "Defender", number: 7, age: 33 },
  { id: 268141, name: "K. Tachibanada", korean_name: "K. 타치바나다", team_id: 294, position: "Midfielder", number: 8, age: 27 },
  { id: 195985, name: "Erison", korean_name: "에리송", team_id: 294, position: "Attacker", number: 9, age: 26 },
  { id: 32962, name: "R. Oshima", korean_name: "R. 오시마", team_id: 294, position: "Midfielder", number: 10, age: 32 },
  { id: 32971, name: "Y. Kobayashi", korean_name: "Y. 코바야시", team_id: 294, position: "Attacker", number: 11, age: 38 },
  { id: 356370, name: "S. Miura", korean_name: "S. 미우라", team_id: 294, position: "Defender", number: 13, age: 25 },
  { id: 32967, name: "Y. Wakizaka", korean_name: "Y. 와키자카", team_id: 294, position: "Midfielder", number: 14, age: 30 },
  { id: 304117, name: "S. Tanabe", korean_name: "S. 타나베", team_id: 294, position: "Defender", number: 15, age: 23 },
  { id: 381079, name: "Y. Ozeki", korean_name: "Y. 오제키", team_id: 294, position: "Midfielder", number: 16, age: 20 },
  { id: 24878, name: "T. Ito", korean_name: "T. 이토", team_id: 294, position: "Midfielder", number: 17, age: 28 },
  { id: 33610, name: "Y. Segawa", korean_name: "Y. 세가와", team_id: 294, position: "Midfielder", number: 18, age: 31 },
  { id: 206964, name: "S. Kawahara", korean_name: "S. 카와하라", team_id: 294, position: "Midfielder", number: 19, age: 27 },
  { id: 32943, name: "S. Ando", korean_name: "S. 안도", team_id: 294, position: "Goalkeeper", number: 21, age: 35 },
  { id: 53600, name: "F. Uremović", korean_name: "필리프 우레모비치", team_id: 294, position: "Defender", number: 22, age: 28 },
  { id: 10425, name: "Marcinho", korean_name: "마르시뉴", team_id: 294, position: "Midfielder", number: 23, age: 30 },
  { id: 206955, name: "T. Miyagi", korean_name: "T. 미야기", team_id: 294, position: "Attacker", number: 24, age: 24 },
  { id: 370130, name: "H. Yamauchi", korean_name: "H. 야마우치", team_id: 294, position: "Midfielder", number: 26, age: 24 },
  { id: 489927, name: "R. Kamihashi", korean_name: "R. 카미하시", team_id: 294, position: "Defender", number: 27, age: 23 },
  { id: 377045, name: "Patrick Verhon", korean_name: "파트릭 베르혼", team_id: 294, position: "Midfielder", number: 28, age: 21 },
  { id: 403464, name: "Toya Myogan", korean_name: "토야 묘간", team_id: 294, position: "Midfielder", number: 29, age: 21 },
  { id: 550737, name: "H. Noda", korean_name: "H. 노다", team_id: 294, position: null, number: 30, age: null },
  { id: 508072, name: "H. Noda", korean_name: "H. 노다", team_id: 294, position: "Defender", number: 30, age: 19 },
  { id: 37040, name: "S. van Wermeskerken", korean_name: "판베르메스케르켄 사이", team_id: 294, position: "Defender", number: 31, age: 31 },
  { id: 32885, name: "Y. Maruyama", korean_name: "Y. 마루야마", team_id: 294, position: "Defender", number: 35, age: 36 },
  { id: 527845, name: "K. Mochiyama", korean_name: "K. 모치야마", team_id: 294, position: null, number: 36, age: null },
  { id: 423794, name: "K. Tsuchiya", korean_name: "K. 츠치야", team_id: 294, position: "Defender", number: 39, age: 19 },
  { id: 550725, name: "K. Tsuchiya", korean_name: "K. 츠치야", team_id: 294, position: null, number: 39, age: null },
  { id: 457196, name: "S. Nakagawa", korean_name: "S. 나카가와", team_id: 294, position: "Goalkeeper", number: 39, age: 24 },
  { id: 32959, name: "A. Ienaga", korean_name: "A. 이에나가", team_id: 294, position: "Midfielder", number: 41, age: 39 },
  { id: 13575, name: "C. Haydar", korean_name: "C. 하이다르", team_id: 294, position: "Defender", number: 44, age: 24 },
  { id: 26729, name: "L. Romanić", korean_name: "라자르 로마니치", team_id: 294, position: "Attacker", number: 91, age: 27 },
  { id: 47017, name: "L. Yamaguchi", korean_name: "L. 야마구치", team_id: 294, position: "Goalkeeper", number: 98, age: 27 },
  { id: 510718, name: "H. Izawa", korean_name: "H. 이자와", team_id: 294, position: "Goalkeeper", number: null, age: 18 },
  { id: 506390, name: "Lee Geun-Hyeong", korean_name: "이근형", team_id: 294, position: "Goalkeeper", number: null, age: 19 },
  { id: 489928, name: "N. Matsuzawa", korean_name: "N. 마츠자와", team_id: 294, position: "Goalkeeper", number: null, age: 18 },
];

// Kyoto Sanga
export const KYOTO_SANGA_PLAYERS: PlayerMapping[] = [
  { id: 2891, name: "Gu Sung-Yun", korean_name: "구성윤", team_id: 302, position: "Goalkeeper", number: 1, age: 31 },
  { id: 453750, name: "R. Iida", korean_name: "R. 이이다", team_id: 302, position: "Defender", number: 2, age: 20 },
  { id: 225085, name: "S. Fukuda", korean_name: "S. 후쿠다", team_id: 302, position: "Defender", number: 2, age: 25 },
  { id: 91684, name: "S. Asada", korean_name: "S. 아사다", team_id: 302, position: "Defender", number: 3, age: 27 },
  { id: 9602, name: "Patrick William", korean_name: "파트릭 윌리엄", team_id: 302, position: "Defender", number: 4, age: 28 },
  { id: 226301, name: "H. Tawiah", korean_name: "H. 타위아", team_id: 302, position: "Defender", number: 5, age: 27 },
  { id: 270984, name: "João Pedro", korean_name: "조앙 페드루", team_id: 302, position: "Midfielder", number: 6, age: 26 },
  { id: 199897, name: "S. Kawasaki", korean_name: "S. 카와사키", team_id: 302, position: "Midfielder", number: 7, age: 24 },
  { id: 32904, name: "T. Yonemoto", korean_name: "T. 요네모토", team_id: 302, position: "Midfielder", number: 8, age: 35 },
  { id: 9896, name: "Rafael Elias", korean_name: "하파엘 엘리아스", team_id: 302, position: "Attacker", number: 9, age: 26 },
  { id: 33575, name: "S. Fukuoka", korean_name: "S. 후쿠오카", team_id: 302, position: "Midfielder", number: 10, age: 25 },
  { id: 80315, name: "Marco Túlio", korean_name: "마르쿠 툴리오", team_id: 302, position: "Attacker", number: 11, age: 27 },
  { id: 32871, name: "T. Hara", korean_name: "T. 하라", team_id: 302, position: "Attacker", number: 14, age: 26 },
  { id: 281946, name: "K. Nagata", korean_name: "K. 나가타", team_id: 302, position: "Defender", number: 15, age: 23 },
  { id: 9535, name: "Léo Gomes", korean_name: "레오 고메스", team_id: 302, position: "Midfielder", number: 16, age: 28 },
  { id: 33738, name: "S. Takeda", korean_name: "S. 타케다", team_id: 302, position: "Midfielder", number: 16, age: 31 },
  { id: 422571, name: "Y. Anzai", korean_name: "Y. 안자이", team_id: 302, position: "Midfielder", number: 17, age: 20 },
  { id: 33137, name: "T. Matsuda", korean_name: "T. 마츠다", team_id: 302, position: "Attacker", number: 18, age: 30 },
  { id: 410841, name: "K. Kita", korean_name: "K. 키타", team_id: 302, position: "Defender", number: 20, age: 20 },
  { id: 33154, name: "K. Kakoi", korean_name: "K. 카코이", team_id: 302, position: "Goalkeeper", number: 21, age: 34 },
  { id: 281380, name: "H. Sugai", korean_name: "H. 스가이", team_id: 302, position: "Defender", number: 22, age: 27 },
  { id: 351537, name: "Y. Miyamoto", korean_name: "Y. 미야모토", team_id: 302, position: "Defender", number: 24, age: 26 },
  { id: 91871, name: "G. Ota", korean_name: "G. 오타", team_id: 302, position: "Goalkeeper", number: 26, age: 35 },
  { id: 199899, name: "F. Yamada", korean_name: "F. 야마다", team_id: 302, position: "Midfielder", number: 27, age: 24 },
  { id: 24968, name: "M. Okugawa", korean_name: "M. 오쿠가와", team_id: 302, position: "Attacker", number: 29, age: 29 },
  { id: 356712, name: "S. Hiraga", korean_name: "S. 히라가", team_id: 302, position: "Attacker", number: 31, age: 20 },
  { id: 33076, name: "T. Hirato", korean_name: "T. 히라토", team_id: 302, position: "Midfielder", number: 39, age: 28 },
  { id: 351532, name: "K. Sato", korean_name: "K. 사토", team_id: 302, position: "Midfielder", number: 44, age: 25 },
  { id: 410014, name: "R. Nakano", korean_name: "R. 나카노", team_id: 302, position: "Midfielder", number: 48, age: 23 },
  { id: 32920, name: "Y. Suzuki", korean_name: "Y. 스즈키", team_id: 302, position: "Defender", number: 50, age: 33 },
  { id: 9461, name: "Barreto", korean_name: "바헤투", team_id: 302, position: "Midfielder", number: 88, age: 30 },
  { id: 33381, name: "S. Nagasawa", korean_name: "S. 나가사와", team_id: 302, position: "Attacker", number: 93, age: 37 },
  { id: 47503, name: "Marc Vito", korean_name: "Marc 비토", team_id: 302, position: "Goalkeeper", number: 96, age: 29 },
  { id: 206917, name: "A. Fantini", korean_name: "A. 판티니", team_id: 302, position: "Goalkeeper", number: null, age: 27 },
  { id: 518452, name: "Yoon Sung-Jun", korean_name: "윤성준", team_id: 302, position: "Midfielder", number: null, age: 18 },
];

// Machida Zelvia
export const MACHIDA_ZELVIA_PLAYERS: PlayerMapping[] = [
  { id: 33294, name: "K. Tani", korean_name: "K. 타니", team_id: 303, position: "Goalkeeper", number: 1, age: 25 },
  { id: 153268, name: "H. Nakamura", korean_name: "H. 나카무라", team_id: 303, position: "Defender", number: 2, age: 28 },
  { id: 33201, name: "Tomoki Imai", korean_name: "토모키 이마이", team_id: 303, position: "Defender", number: 2, age: 35 },
  { id: 2596, name: "G. Shōji", korean_name: "쇼지 겐", team_id: 303, position: "Defender", number: 3, age: 33 },
  { id: 33989, name: "R. Kikuchi", korean_name: "R. 키쿠치", team_id: 303, position: "Defender", number: 4, age: 29 },
  { id: 36969, name: "I. Drešević", korean_name: "I. Drešević", team_id: 303, position: "Defender", number: 5, age: 28 },
  { id: 455193, name: "H. Mochizuki", korean_name: "H. 모치즈키", team_id: 303, position: "Defender", number: 6, age: 24 },
  { id: 32902, name: "Y. Soma", korean_name: "Y. 소마", team_id: 303, position: "Attacker", number: 7, age: 28 },
  { id: 33582, name: "K. Sento", korean_name: "K. 센토", team_id: 303, position: "Midfielder", number: 8, age: 31 },
  { id: 109400, name: "S. Fujio", korean_name: "S. 후지오", team_id: 303, position: "Attacker", number: 9, age: 24 },
  { id: 2908, name: "Na Sang-Ho", korean_name: "나상호", team_id: 303, position: "Attacker", number: 10, age: 29 },
  { id: 33244, name: "A. Masuyama", korean_name: "A. 마스야마", team_id: 303, position: "Midfielder", number: 11, age: 28 },
  { id: 33194, name: "T. Morita", korean_name: "T. 모리타", team_id: 303, position: "Goalkeeper", number: 13, age: 35 },
  { id: 6993, name: "M. Duke", korean_name: "M. 듀크", team_id: 303, position: "Attacker", number: 15, age: 34 },
  { id: 33432, name: "H. Mae", korean_name: "H. 마에", team_id: 303, position: "Midfielder", number: 16, age: 30 },
  { id: 32964, name: "H. Shimoda", korean_name: "H. 시모다", team_id: 303, position: "Midfielder", number: 18, age: 34 },
  { id: 36920, name: "Y. Nakayama", korean_name: "Y. 나카야마", team_id: 303, position: "Defender", number: 19, age: 28 },
  { id: 846, name: "T. Nishimura", korean_name: "T. 니시무라", team_id: 303, position: "Attacker", number: 20, age: 29 },
  { id: 354511, name: "T. Numata", korean_name: "T. 누마타", team_id: 303, position: "Attacker", number: 22, age: 26 },
  { id: 33088, name: "R. Shirasaki", korean_name: "R. 시라사키", team_id: 303, position: "Midfielder", number: 23, age: 32 },
  { id: 403473, name: "K. Hayashi", korean_name: "K. 하야시", team_id: 303, position: "Defender", number: 26, age: 25 },
  { id: 423695, name: "Cha Je-Hoon", korean_name: "차재훈", team_id: 303, position: "Midfielder", number: 28, age: 19 },
  { id: 33892, name: "Y. Nakashima", korean_name: "Y. 나카시마", team_id: 303, position: "Attacker", number: 30, age: 41 },
  { id: 111266, name: "N. Lavi", korean_name: "N. 라비", team_id: 303, position: "Midfielder", number: 31, age: 29 },
  { id: 33532, name: "Y. Arai", korean_name: "Y. 아라이", team_id: 303, position: "Goalkeeper", number: 44, age: 30 },
  { id: 318662, name: "K. Higuchi", korean_name: "K. 히구치", team_id: 303, position: "Midfielder", number: 46, age: 22 },
  { id: 466966, name: "K. Kuwayama", korean_name: "K. 쿠와야마", team_id: 303, position: "Attacker", number: 49, age: 23 },
  { id: 351083, name: "A. Burns", korean_name: "A. 번스", team_id: 303, position: "Goalkeeper", number: 50, age: 22 },
  { id: 109315, name: "D. Okamura", korean_name: "D. 오카무라", team_id: 303, position: "Defender", number: 50, age: 28 },
  { id: 33347, name: "D. Takahashi", korean_name: "D. 타카하시", team_id: 303, position: "Midfielder", number: 66, age: 26 },
  { id: 282285, name: "T. Narasaka", korean_name: "T. 나라사카", team_id: 303, position: "Defender", number: 77, age: 23 },
  { id: 99186, name: "Oh Se-Hun", korean_name: "오세훈", team_id: 303, position: "Attacker", number: 90, age: 26 },
  { id: 484688, name: "C. Mayaka", korean_name: "C. 마야카", team_id: 303, position: "Midfielder", number: null, age: 19 },
  { id: 506388, name: "Kaung Zan Mara", korean_name: "카웅 잔 마라", team_id: 303, position: "Goalkeeper", number: null, age: 23 },
  { id: 422372, name: "T. Takasaki", korean_name: "T. 타카사키", team_id: 303, position: "Midfielder", number: null, age: 19 },
];

// Nagoya Grampus
export const NAGOYA_GRAMPUS_PLAYERS: PlayerMapping[] = [
  { id: 2589, name: "D. Schmidt", korean_name: "D. 슈미트", team_id: 288, position: "Goalkeeper", number: 1, age: 33 },
  { id: 32850, name: "T. Kodama", korean_name: "T. 코다마", team_id: 288, position: "Goalkeeper", number: 1, age: 38 },
  { id: 33038, name: "Y. Nogami", korean_name: "Y. 노가미", team_id: 288, position: "Midfielder", number: 2, age: 34 },
  { id: 304118, name: "Y. Sato", korean_name: "Y. 사토", team_id: 288, position: "Defender", number: 3, age: 27 },
  { id: 33237, name: "D. Miya", korean_name: "D. 미야", team_id: 288, position: "Defender", number: 4, age: 29 },
  { id: 33476, name: "A. Kawazura", korean_name: "A. 카와즈라", team_id: 288, position: "Defender", number: 6, age: 31 },
  { id: 32894, name: "R. Izumi", korean_name: "R. 이즈미", team_id: 288, position: "Attacker", number: 7, age: 32 },
  { id: 33373, name: "K. Shiihashi", korean_name: "K. 시이하시", team_id: 288, position: "Midfielder", number: 8, age: 28 },
  { id: 33427, name: "Y. Asano", korean_name: "Y. 아사노", team_id: 288, position: "Midfielder", number: 9, age: 28 },
  { id: 32907, name: "Mateus", korean_name: "마테우스", team_id: 288, position: "Attacker", number: 10, age: 31 },
  { id: 33976, name: "Y. Yamagishi", korean_name: "Y. 야마기시", team_id: 288, position: "Attacker", number: 11, age: 32 },
  { id: 32882, name: "H. Fujii", korean_name: "H. 후지이", team_id: 288, position: "Defender", number: 13, age: 25 },
  { id: 33048, name: "T. Morishima", korean_name: "T. 모리시마", team_id: 288, position: "Midfielder", number: 14, age: 28 },
  { id: 33043, name: "S. Inagaki", korean_name: "S. 이나가키", team_id: 288, position: "Midfielder", number: 15, age: 34 },
  { id: 32879, name: "Y. Takeda", korean_name: "Y. 타케다", team_id: 288, position: "Goalkeeper", number: 16, age: 38 },
  { id: 32868, name: "T. Uchida", korean_name: "T. 우치다", team_id: 288, position: "Defender", number: 17, age: 27 },
  { id: 32872, name: "K. Nagai", korean_name: "K. 나가이", team_id: 288, position: "Attacker", number: 18, age: 36 },
  { id: 33933, name: "K. Mikuni", korean_name: "K. 미쿠니", team_id: 288, position: "Defender", number: 20, age: 25 },
  { id: 33005, name: "D. Sugimoto", korean_name: "D. 스기모토", team_id: 288, position: "Goalkeeper", number: 21, age: 32 },
  { id: 369709, name: "G. Kato", korean_name: "G. 카토", team_id: 288, position: "Midfielder", number: 26, age: 22 },
  { id: 33827, name: "K. Nakayama", korean_name: "K. 나카야마", team_id: 288, position: "Midfielder", number: 27, age: 29 },
  { id: 423799, name: "S. Sugiura", korean_name: "S. 스기우라", team_id: 288, position: "Midfielder", number: 30, age: 19 },
  { id: 369098, name: "H. Suzuki", korean_name: "H. 스즈키", team_id: 288, position: "Midfielder", number: 32, age: 20 },
  { id: 351531, name: "T. Kikuchi", korean_name: "T. 키쿠치", team_id: 288, position: "Midfielder", number: 33, age: 26 },
  { id: 449199, name: "A. Pisano", korean_name: "A. 피사노", team_id: 288, position: "Goalkeeper", number: 35, age: 19 },
  { id: 33491, name: "M. Ono", korean_name: "M. 오노", team_id: 288, position: "Midfielder", number: 41, age: 29 },
  { id: 465790, name: "S. Mori", korean_name: "S. 모리", team_id: 288, position: "Midfielder", number: 44, age: 18 },
  { id: 33667, name: "S. Tokumoto", korean_name: "S. 토쿠모토", team_id: 288, position: "Defender", number: 55, age: 30 },
  { id: 33104, name: "R. Yamanaka", korean_name: "R. 야마나카", team_id: 288, position: "Midfielder", number: 66, age: 32 },
  { id: 33397, name: "T. Hara", korean_name: "T. 하라", team_id: 288, position: "Defender", number: 70, age: 27 },
  { id: 368277, name: "K. Sakakibara", korean_name: "K. 사카키바라", team_id: 288, position: "Attacker", number: 71, age: 24 },
  { id: 15653, name: "K. Junker", korean_name: "K. 융커", team_id: 288, position: "Attacker", number: 77, age: 31 },
  { id: 350153, name: "Lelê", korean_name: "렐레", team_id: 288, position: "Attacker", number: 99, age: 28 },
  { id: 486384, name: "A. Mawuto", korean_name: "A. 마우토", team_id: 288, position: "Attacker", number: null, age: 22 },
  { id: 550761, name: "H. Suzuki", korean_name: "H. 스즈키", team_id: 288, position: null, number: null, age: null },
  { id: 527030, name: "R. Onishi", korean_name: "R. 오니시", team_id: 288, position: "Attacker", number: null, age: 18 },
];

// Sanfrecce Hiroshima
export const SANFRECCE_HIROSHIMA_PLAYERS: PlayerMapping[] = [
  { id: 33034, name: "K. Osako", korean_name: "K. 오사코", team_id: 282, position: "Goalkeeper", number: 1, age: 26 },
  { id: 225092, name: "T. Yamasaki", korean_name: "T. 야마사키", team_id: 282, position: "Defender", number: 3, age: 24 },
  { id: 33035, name: "H. Araki", korean_name: "H. 아라키", team_id: 282, position: "Defender", number: 4, age: 29 },
  { id: 33045, name: "H. Kawabe", korean_name: "H. 카와베", team_id: 282, position: "Attacker", number: 6, age: 30 },
  { id: 33378, name: "R. Germain", korean_name: "R. 제르맹", team_id: 282, position: "Attacker", number: 9, age: 30 },
  { id: 33026, name: "Marcos Júnior", korean_name: "마르코스 주니오르", team_id: 282, position: "Attacker", number: 10, age: 32 },
  { id: 33624, name: "N. Arai", korean_name: "N. 아라이", team_id: 282, position: "Defender", number: 13, age: 29 },
  { id: 33960, name: "O. Iyoha", korean_name: "O. 이요하", team_id: 282, position: "Attacker", number: 13, age: 27 },
  { id: 33142, name: "S. Tanaka", korean_name: "S. 타나카", team_id: 282, position: "Midfielder", number: 14, age: 23 },
  { id: 355998, name: "S. Nakano", korean_name: "S. 나카노", team_id: 282, position: "Midfielder", number: 15, age: 25 },
  { id: 8517, name: "K. Kinoshita", korean_name: "K. 키노시타", team_id: 282, position: "Attacker", number: 17, age: 31 },
  { id: 33000, name: "D. Suga", korean_name: "D. 스가", team_id: 282, position: "Midfielder", number: 18, age: 27 },
  { id: 2595, name: "S. Sasaki", korean_name: "S. 사사키", team_id: 282, position: "Defender", number: 19, age: 36 },
  { id: 33795, name: "S. Inoue", korean_name: "S. 이노우에", team_id: 282, position: "Midfielder", number: 20, age: 28 },
  { id: 109305, name: "Y. Tanaka", korean_name: "Y. 타나카", team_id: 282, position: "Goalkeeper", number: 21, age: 30 },
  { id: 33042, name: "S. Higashi", korean_name: "S. 히가시", team_id: 282, position: "Midfielder", number: 24, age: 25 },
  { id: 33853, name: "Y. Chajima", korean_name: "Y. 차지마", team_id: 282, position: "Midfielder", number: 25, age: 34 },
  { id: 34189, name: "Jeong Min-Ki", korean_name: "정민기", team_id: 282, position: "Goalkeeper", number: 26, age: 29 },
  { id: 1353, name: "T. Arslan", korean_name: "T. 아르슬란", team_id: 282, position: "Midfielder", number: 30, age: 35 },
  { id: 392714, name: "S. Koshimichi", korean_name: "S. 코시미치", team_id: 282, position: "Midfielder", number: 32, age: 21 },
  { id: 44054, name: "T. Shiotani", korean_name: "T. 시오타니", team_id: 282, position: "Midfielder", number: 33, age: 37 },
  { id: 423798, name: "Y. Nakajima", korean_name: "Y. 나카지마", team_id: 282, position: "Attacker", number: 35, age: 19 },
  { id: 449197, name: "A. Inoue", korean_name: "A. 이노우에", team_id: 282, position: "Attacker", number: 36, age: 19 },
  { id: 34496, name: "Kim Ju-Sung", korean_name: "김주성", team_id: 282, position: "Defender", number: 37, age: 25 },
  { id: 491469, name: "C. Hill", korean_name: "C. 힐", team_id: 282, position: "Goalkeeper", number: 38, age: 23 },
  { id: 508070, name: "S. Nakamura", korean_name: "S. 나카무라", team_id: 282, position: "Attacker", number: 39, age: 23 },
  { id: 340991, name: "M. Ohara", korean_name: "M. 오하라", team_id: 282, position: "Midfielder", number: 40, age: 25 },
  { id: 491467, name: "S. Kobayashi", korean_name: "S. 코바야시", team_id: 282, position: "Attacker", number: 45, age: 17 },
  { id: 350849, name: "T. Semba", korean_name: "T. 센바", team_id: 282, position: "Midfielder", number: 47, age: 26 },
  { id: 199792, name: "M. Kato", korean_name: "M. 카토", team_id: 282, position: "Attacker", number: 51, age: 28 },
  { id: 309778, name: "M. Mitsuta", korean_name: "M. 미츠타", team_id: 282, position: "Attacker", number: 51, age: 26 },
  { id: 33355, name: "G. Kawanami", korean_name: "G. 카와나미", team_id: 282, position: "Goalkeeper", number: 77, age: 34 },
  { id: 1918, name: "V. Germain", korean_name: "V. 제르맹", team_id: 282, position: "Attacker", number: 98, age: 35 },
  { id: 491468, name: "H. Ogawa", korean_name: "H. 오가와", team_id: 282, position: "Goalkeeper", number: null, age: 18 },
  { id: 491466, name: "M. Sota", korean_name: "M. 소타", team_id: 282, position: "Attacker", number: null, age: 18 },
];

// Shimizu S-pulse
export const SHIMIZU_S_PULSE_PLAYERS: PlayerMapping[] = [
  { id: 33061, name: "Y. Oki", korean_name: "Y. 오키", team_id: 283, position: "Goalkeeper", number: 1, age: 26 },
  { id: 33394, name: "Y. Takahashi", korean_name: "Y. 타카하시", team_id: 283, position: "Defender", number: 3, age: 32 },
  { id: 281944, name: "S. Hasukawa", korean_name: "S. 하스카와", team_id: 283, position: "Defender", number: 4, age: 27 },
  { id: 33821, name: "K. Kitazume", korean_name: "K. 키타즈메", team_id: 283, position: "Defender", number: 5, age: 33 },
  { id: 33971, name: "K. Miyamoto", korean_name: "K. 미야모토", team_id: 283, position: "Midfielder", number: 6, age: 29 },
  { id: 9617, name: "Capixaba", korean_name: "카픽사바", team_id: 283, position: "Midfielder", number: 7, age: 28 },
  { id: 32926, name: "K. Kozuka", korean_name: "K. 코즈카", team_id: 283, position: "Attacker", number: 8, age: 31 },
  { id: 109292, name: "H. Nakahara", korean_name: "H. 나카하라", team_id: 283, position: "Midfielder", number: 11, age: 29 },
  { id: 289882, name: "R. Yamahara", korean_name: "R. 야마하라", team_id: 283, position: "Midfielder", number: 14, age: 26 },
  { id: 351019, name: "K. Chiba", korean_name: "K. 치바", team_id: 283, position: "Attacker", number: 15, age: 22 },
  { id: 33328, name: "T. Umeda", korean_name: "T. 우메다", team_id: 283, position: "Goalkeeper", number: 16, age: 25 },
  { id: 550745, name: "T. Umeda", korean_name: "T. 우메다", team_id: 283, position: null, number: 16, age: null },
  { id: 269554, name: "M. Yumiba", korean_name: "M. 유미바", team_id: 283, position: "Midfielder", number: 17, age: 23 },
  { id: 377093, name: "S. Saito", korean_name: "S. 사이토", team_id: 283, position: "Attacker", number: 18, age: 25 },
  { id: 199845, name: "K. Matsuzaki", korean_name: "K. 마츠자키", team_id: 283, position: "Midfielder", number: 19, age: 28 },
  { id: 33318, name: "S. Yajima", korean_name: "S. 야지마", team_id: 283, position: "Midfielder", number: 21, age: 31 },
  { id: 33354, name: "K. Kitagawa", korean_name: "K. 키타가와", team_id: 283, position: "Attacker", number: 23, age: 29 },
  { id: 119269, name: "Mateus Brunetti", korean_name: "마테우스 브루네티", team_id: 283, position: "Defender", number: 25, age: 26 },
  { id: 457181, name: "R. Gunji", korean_name: "R. 군지", team_id: 283, position: "Attacker", number: 27, age: 20 },
  { id: 32888, name: "Y. Yoshida", korean_name: "Y. 요시다", team_id: 283, position: "Midfielder", number: 28, age: 35 },
  { id: 11342, name: "A. Ahmedov", korean_name: "A. 아흐메도프", team_id: 283, position: "Attacker", number: 29, age: 30 },
  { id: 2600, name: "T. Inui", korean_name: "T. 이누이", team_id: 283, position: "Attacker", number: 33, age: 37 },
  { id: 351084, name: "Z. Uno", korean_name: "Z. 우노", team_id: 283, position: "Midfielder", number: 36, age: 22 },
  { id: 550713, name: "Z. Uno", korean_name: "Z. 우노", team_id: 283, position: null, number: 36, age: null },
  { id: 518451, name: "R. Ohata", korean_name: "R. 오하타", team_id: 283, position: "Midfielder", number: 37, age: 22 },
  { id: 32915, name: "K. Haneda", korean_name: "K. 하네다", team_id: 283, position: "Defender", number: 41, age: 28 },
  { id: 515451, name: "Y. Doi", korean_name: "Y. 도이", team_id: 283, position: "Midfielder", number: 42, age: 18 },
  { id: 404340, name: "R. Abe", korean_name: "R. 아베", team_id: 283, position: "Goalkeeper", number: 46, age: 24 },
  { id: 495502, name: "Y. Shimamoto", korean_name: "Y. 시마모토", team_id: 283, position: "Midfielder", number: 47, age: 19 },
  { id: 415188, name: "S. Kotake", korean_name: "S. 코타케", team_id: 283, position: "Midfielder", number: 49, age: 19 },
  { id: 41225, name: "A. Stephens", korean_name: "A. 스티븐스", team_id: 283, position: "Attacker", number: 50, age: 31 },
  { id: 458573, name: "M. Nishihara", korean_name: "M. 니시하라", team_id: 283, position: "Midfielder", number: 55, age: 19 },
  { id: 199891, name: "J. Sumiyoshi", korean_name: "J. 스미요시", team_id: 283, position: "Defender", number: 66, age: 28 },
  { id: 416314, name: "S. Takagi", korean_name: "S. 타카기", team_id: 283, position: "Defender", number: 70, age: 23 },
  { id: 422375, name: "Y. Inokoshi", korean_name: "Y. 이노코시", team_id: 283, position: "Goalkeeper", number: 71, age: 24 },
  { id: 9354, name: "Matheus Bueno", korean_name: "마테우스 부에노", team_id: 283, position: "Midfielder", number: 98, age: 27 },
  { id: 515453, name: "K. Iwanaga", korean_name: "K. 이와나가", team_id: 283, position: "Defender", number: null, age: 18 },
  { id: 515452, name: "T. Iwao", korean_name: "T. 이와오", team_id: 283, position: "Defender", number: null, age: 18 },
  { id: 404341, name: "T. Kemmotsu", korean_name: "T. 켐모츠", team_id: 283, position: "Defender", number: null, age: 25 },
  { id: 508075, name: "T. Sasaki", korean_name: "T. 사사키", team_id: 283, position: "Goalkeeper", number: null, age: 18 },
];

// Shonan Bellmare
export const SHONAN_BELLMARE_PLAYERS: PlayerMapping[] = [
  { id: 199153, name: "T. Hata", korean_name: "T. 하타", team_id: 284, position: "Defender", number: 3, age: 23 },
  { id: 130229, name: "K. Tachi", korean_name: "K. 타치", team_id: 284, position: "Defender", number: 4, age: 28 },
  { id: 10310, name: "Zé Ricardo", korean_name: "제 리카르도", team_id: 284, position: "Midfielder", number: 6, age: 26 },
  { id: 33314, name: "K. Onose", korean_name: "K. 오노세", team_id: 284, position: "Midfielder", number: 7, age: 32 },
  { id: 33127, name: "K. Ohno", korean_name: "K. 오노", team_id: 284, position: "Defender", number: 8, age: 36 },
  { id: 33248, name: "Y. Oda", korean_name: "Y. 오다", team_id: 284, position: "Attacker", number: 9, age: 24 },
  { id: 351015, name: "A. Suzuki", korean_name: "A. 스즈키", team_id: 284, position: "Attacker", number: 10, age: 22 },
  { id: 304790, name: "T. Hiraoka", korean_name: "T. 히라오카", team_id: 284, position: "Midfielder", number: 13, age: 23 },
  { id: 33485, name: "A. Barada", korean_name: "A. 바라다", team_id: 284, position: "Midfielder", number: 14, age: 34 },
  { id: 33313, name: "K. Okuno", korean_name: "K. 오쿠노", team_id: 284, position: "Midfielder", number: 15, age: 25 },
  { id: 268147, name: "R. Nemoto", korean_name: "R. 네모토", team_id: 284, position: "Attacker", number: 16, age: 25 },
  { id: 237058, name: "S. Tamura", korean_name: "S. 타무라", team_id: 284, position: "Midfielder", number: 17, age: 23 },
  { id: 109221, name: "M. Ikeda", korean_name: "M. 이케다", team_id: 284, position: "Midfielder", number: 18, age: 26 },
  { id: 206937, name: "S. Fukuda", korean_name: "S. 후쿠다", team_id: 284, position: "Attacker", number: 19, age: 24 },
  { id: 351014, name: "J. Suzuki", korean_name: "J. 스즈키", team_id: 284, position: "Defender", number: 20, age: 22 },
  { id: 495499, name: "S. Ishibashi", korean_name: "S. 이시바시", team_id: 284, position: "Midfielder", number: 20, age: 19 },
  { id: 92027, name: "T. Nagai", korean_name: "T. 나가이", team_id: 284, position: "Goalkeeper", number: 21, age: 30 },
  { id: 33363, name: "K. Oiwa", korean_name: "K. 오이와", team_id: 284, position: "Defender", number: 22, age: 36 },
  { id: 506389, name: "K. Matsumoto", korean_name: "K. 마츠모토", team_id: 284, position: "Defender", number: 23, age: 18 },
  { id: 33178, name: "H. Okuno", korean_name: "H. 오쿠노", team_id: 284, position: "Midfielder", number: 25, age: 36 },
  { id: 1498, name: "Luiz Phellype", korean_name: "루이스 펠리페", team_id: 284, position: "Attacker", number: 27, age: 32 },
  { id: 33529, name: "S. Ota", korean_name: "S. 오타", team_id: 284, position: "Midfielder", number: 28, age: 29 },
  { id: 468740, name: "K. Watanabe", korean_name: "K. 와타나베", team_id: 284, position: "Attacker", number: 29, age: 23 },
  { id: 550746, name: "K. Sanada", korean_name: "K. 사나다", team_id: 284, position: null, number: 31, age: null },
  { id: 33122, name: "K. Sanada", korean_name: "K. 사나다", team_id: 284, position: "Goalkeeper", number: 31, age: 26 },
  { id: 351536, name: "S. Matsumura", korean_name: "S. 마츠무라", team_id: 284, position: "Midfielder", number: 32, age: 22 },
  { id: 109395, name: "N. Takahashi", korean_name: "N. 타카하시", team_id: 284, position: "Defender", number: 33, age: 24 },
  { id: 32965, name: "Y. Suzuki", korean_name: "Y. 스즈키", team_id: 284, position: "Midfielder", number: 37, age: 32 },
  { id: 137140, name: "K. Itohara", korean_name: "K. 이토하라", team_id: 284, position: "Goalkeeper", number: 41, age: 27 },
  { id: 32986, name: "Kim Min-Tae", korean_name: "김민태", team_id: 284, position: "Defender", number: 47, age: 32 },
  { id: 237202, name: "Shinya Nakano", korean_name: "Shinya 나카노", team_id: 284, position: "Defender", number: 47, age: 22 },
  { id: 199628, name: "T. Fujii", korean_name: "T. 후지이", team_id: 284, position: "Midfielder", number: 50, age: 27 },
  { id: 33046, name: "H. Matsumoto", korean_name: "H. 마츠모토", team_id: 284, position: "Midfielder", number: 66, age: 25 },
  { id: 410011, name: "H. Ishii", korean_name: "H. 이시이", team_id: 284, position: "Attacker", number: 77, age: 20 },
  { id: 33785, name: "N. Kamifukumoto", korean_name: "N. 카미후쿠모토", team_id: 284, position: "Goalkeeper", number: 99, age: 36 },
  { id: 423788, name: "K. Honda", korean_name: "K. 혼다", team_id: 284, position: "Defender", number: null, age: 19 },
];

// Tokyo Verdy
export const TOKYO_VERDY_PLAYERS: PlayerMapping[] = [
  { id: 80392, name: "Matheus Vidotto", korean_name: "마테우스 칼데이라 비도토", team_id: 306, position: "Goalkeeper", number: 1, age: 32 },
  { id: 282282, name: "D. Fukazawa", korean_name: "D. 후카자와", team_id: 306, position: "Midfielder", number: 2, age: 27 },
  { id: 353589, name: "H. Taniguchi", korean_name: "H. 다니구치", team_id: 306, position: "Defender", number: 3, age: 26 },
  { id: 304783, name: "N. Hayashi", korean_name: "N. 하야시", team_id: 306, position: "Defender", number: 4, age: 27 },
  { id: 404352, name: "Y. Tsunashima", korean_name: "Y. 츠나시마", team_id: 306, position: "Midfielder", number: 4, age: 25 },
  { id: 109337, name: "K. Chida", korean_name: "K. 치다", team_id: 306, position: "Defender", number: 5, age: 31 },
  { id: 404357, name: "R. Inoue", korean_name: "R. 이노우에", team_id: 306, position: "Defender", number: 5, age: 25 },
  { id: 32898, name: "K. Miyahara", korean_name: "K. 미야하라", team_id: 306, position: "Defender", number: 6, age: 29 },
  { id: 33799, name: "K. Morita", korean_name: "K. 모리타", team_id: 306, position: "Midfielder", number: 7, age: 25 },
  { id: 33839, name: "K. Saito", korean_name: "K. 사이토", team_id: 306, position: "Midfielder", number: 8, age: 28 },
  { id: 197974, name: "I. Someno", korean_name: "I. 소메노", team_id: 306, position: "Attacker", number: 9, age: 24 },
  { id: 319007, name: "Y. Kimura", korean_name: "Y. 키무라", team_id: 306, position: "Attacker", number: 10, age: 24 },
  { id: 319021, name: "H. Yamami", korean_name: "H. 야마미", team_id: 306, position: "Attacker", number: 11, age: 26 },
  { id: 319006, name: "G. Yamada", korean_name: "G. 야마다", team_id: 306, position: "Attacker", number: 13, age: 25 },
  { id: 33308, name: "Y. Fukuda", korean_name: "Y. 후쿠다", team_id: 306, position: "Attacker", number: 14, age: 26 },
  { id: 153277, name: "K. Suzuki", korean_name: "K. 스즈키", team_id: 306, position: "Defender", number: 15, age: 23 },
  { id: 32860, name: "R. Hirakawa", korean_name: "R. 히라카와", team_id: 306, position: "Midfielder", number: 16, age: 25 },
  { id: 353590, name: "T. Inami", korean_name: "T. 이나미", team_id: 306, position: "Midfielder", number: 17, age: 26 },
  { id: 199915, name: "Y. Matsuhashi", korean_name: "Y. 마츠하시", team_id: 306, position: "Midfielder", number: 19, age: 24 },
  { id: 109241, name: "Soma Meshino", korean_name: "Soma 메시노", team_id: 306, position: "Midfielder", number: 20, age: 24 },
  { id: 33897, name: "H. Mawatari", korean_name: "H. 마와타리", team_id: 306, position: "Goalkeeper", number: 21, age: 31 },
  { id: 109385, name: "Y. Nagasawa", korean_name: "Y. 나가사와", team_id: 306, position: "Goalkeeper", number: 21, age: 29 },
  { id: 33771, name: "H. Onaga", korean_name: "H. 오나가", team_id: 306, position: "Midfielder", number: 22, age: 30 },
  { id: 409625, name: "I. Kumatoriya", korean_name: "I. 쿠마토리야", team_id: 306, position: "Attacker", number: 25, age: 22 },
  { id: 507700, name: "Y. Uchida", korean_name: "Y. 우치다", team_id: 306, position: "Midfielder", number: 26, age: 23 },
  { id: 422684, name: "R. Shirai", korean_name: "R. 시라이", team_id: 306, position: "Attacker", number: 27, age: 20 },
  { id: 422686, name: "J. Yamamoto", korean_name: "J. 야마모토", team_id: 306, position: "Midfielder", number: 28, age: 19 },
  { id: 302954, name: "M. Sako", korean_name: "M. 사코", team_id: 306, position: "Defender", number: 29, age: 23 },
  { id: 423796, name: "G. Kawamura", korean_name: "G. 카와무라", team_id: 306, position: "Attacker", number: 30, age: 19 },
  { id: 33298, name: "R. Matsuda", korean_name: "R. 마츠다", team_id: 306, position: "Defender", number: 36, age: 26 },
  { id: 109397, name: "S. Kawasaki", korean_name: "S. 카와사키", team_id: 306, position: "Attacker", number: 37, age: 24 },
  { id: 125669, name: "S. Toyama", korean_name: "S. 토야마", team_id: 306, position: "Attacker", number: 38, age: 23 },
  { id: 471929, name: "Shion Nakayama", korean_name: "시온 나카야마", team_id: 306, position: "Midfielder", number: 39, age: 18 },
  { id: 425765, name: "Y. Arai", korean_name: "Y. 아라이", team_id: 306, position: "Attacker", number: 40, age: 22 },
  { id: 370128, name: "S. Teranuma", korean_name: "S. 테라누마", team_id: 306, position: "Attacker", number: 45, age: 24 },
  { id: 315631, name: "Ghaith Mansour Hamid Al Mhairat", korean_name: "가이스 만수르 하미드 알 므하이라트", team_id: 306, position: "Attacker", number: 71, age: 22 },
  { id: 527117, name: "H. Hirao", korean_name: "H. 히라오", team_id: 306, position: null, number: 71, age: null },
  { id: 0, name: "H. Hirao", korean_name: "H. 히라오", team_id: 306, position: "Attacker", number: 71, age: 20 },
  { id: 453748, name: "K. Nakamura", korean_name: "K. 나카무라", team_id: 306, position: "Goalkeeper", number: null, age: 20 },
];

// Urawa
export const URAWA_PLAYERS: PlayerMapping[] = [
  { id: 33093, name: "S. Nishikawa", korean_name: "S. 니시카와", team_id: 287, position: "Goalkeeper", number: 1, age: 39 },
  { id: 41961, name: "Danilo Boza", korean_name: "다닐루 보자", team_id: 287, position: "Defender", number: 3, age: 27 },
  { id: 33931, name: "H. Ishihara", korean_name: "H. 이시하라", team_id: 287, position: "Defender", number: 4, age: 26 },
  { id: 57169, name: "M. Høibråten", korean_name: "마리우스 회브로텐", team_id: 287, position: "Defender", number: 5, age: 30 },
  { id: 33047, name: "T. Matsumoto", korean_name: "T. 마츠모토", team_id: 287, position: "Midfielder", number: 6, age: 27 },
  { id: 10474, name: "Matheus Sávio", korean_name: "마테우스 사비오", team_id: 287, position: "Midfielder", number: 8, age: 28 },
  { id: 25379, name: "G. Haraguchi", korean_name: "G. 하라구치", team_id: 287, position: "Midfielder", number: 9, age: 34 },
  { id: 2603, name: "S. Nakajima", korean_name: "S. 나카지마", team_id: 287, position: "Midfielder", number: 10, age: 31 },
  { id: 30931, name: "Samuel Gustafson", korean_name: "사무엘 구스타프손", team_id: 287, position: "Midfielder", number: 11, age: 30 },
  { id: 41218, name: "Thiago Santana", korean_name: "치아구 산타나", team_id: 287, position: "Attacker", number: 12, age: 32 },
  { id: 33643, name: "R. Watanabe", korean_name: "R. 와타나베", team_id: 287, position: "Midfielder", number: 13, age: 29 },
  { id: 8508, name: "T. Sekine", korean_name: "T. 세키네", team_id: 287, position: "Midfielder", number: 14, age: 30 },
  { id: 307938, name: "K. Matsuyama", korean_name: "K. 마츠야마", team_id: 287, position: "Goalkeeper", number: 15, age: 27 },
  { id: 91859, name: "A. Niekawa", korean_name: "A. 니에카와", team_id: 287, position: "Goalkeeper", number: 16, age: 31 },
  { id: 288918, name: "H. Komori", korean_name: "H. 코모리", team_id: 287, position: "Attacker", number: 17, age: 25 },
  { id: 206967, name: "T. Takahashi", korean_name: "T. 타카하시", team_id: 287, position: "Attacker", number: 18, age: 27 },
  { id: 33636, name: "S. Homma", korean_name: "S. 혼마", team_id: 287, position: "Midfielder", number: 19, age: 25 },
  { id: 317334, name: "M. Nagakura", korean_name: "M. 나가쿠라", team_id: 287, position: "Attacker", number: 20, age: 26 },
  { id: 141156, name: "T. Okubo", korean_name: "T. 오쿠보", team_id: 287, position: "Midfielder", number: 21, age: 27 },
  { id: 33112, name: "K. Shibato", korean_name: "K. 시바토", team_id: 287, position: "Midfielder", number: 22, age: 30 },
  { id: 119662, name: "Y. Matsuo", korean_name: "Y. 마츠오", team_id: 287, position: "Midfielder", number: 24, age: 28 },
  { id: 351538, name: "K. Yasui", korean_name: "K. 야스이", team_id: 287, position: "Midfielder", number: 25, age: 25 },
  { id: 33101, name: "T. Ogiwara", korean_name: "T. 오기와라", team_id: 287, position: "Defender", number: 26, age: 26 },
  { id: 474582, name: "T. Teruuchi", korean_name: "T. 테루우치", team_id: 287, position: "Attacker", number: 27, age: 19 },
  { id: 441588, name: "K. Nemoto", korean_name: "K. 네모토", team_id: 287, position: "Defender", number: 28, age: 23 },
  { id: 32897, name: "N. Maeda", korean_name: "N. 마에다", team_id: 287, position: "Attacker", number: 30, age: 31 },
  { id: 304794, name: "Yudai Fujiwara", korean_name: "후지와라 유다이", team_id: 287, position: "Defender", number: 34, age: 23 },
  { id: 109332, name: "R. Inoue", korean_name: "R. 이노우에", team_id: 287, position: "Defender", number: 35, age: 28 },
  { id: 356185, name: "J. Hayakawa", korean_name: "J. 하야카와", team_id: 287, position: "Midfielder", number: 39, age: 20 },
  { id: 318860, name: "R. Nitta", korean_name: "R. 닛타", team_id: 287, position: "Attacker", number: 41, age: 22 },
  { id: 32985, name: "T. Kaneko", korean_name: "T. 카네코", team_id: 287, position: "Midfielder", number: 77, age: 28 },
  { id: 109314, name: "S. Yoshida", korean_name: "S. 요시다", team_id: 287, position: "Goalkeeper", number: 81, age: 29 },
  { id: 33914, name: "Y. Naganuma", korean_name: "Y. 나가누마", team_id: 287, position: "Midfielder", number: 88, age: 28 },
  { id: 988, name: "Isaac Kiese Thelin", korean_name: "이삭 키에스 텔린", team_id: 287, position: "Attacker", number: 99, age: 33 },
  { id: 524336, name: "A. Malcolm", korean_name: "A. 말콤", team_id: 287, position: "Goalkeeper", number: null, age: 17 },
  { id: 33085, name: "Hiroki Abe", korean_name: "히로키 아베", team_id: 287, position: "Attacker", number: null, age: 26 },
  { id: 524229, name: "R. Hidano", korean_name: "R. 히다노", team_id: 287, position: "Midfielder", number: null, age: 22 },
  { id: 369479, name: "R. Sato", korean_name: "R. 사토", team_id: 287, position: "Goalkeeper", number: null, age: 22 },
  { id: 524338, name: "T. Wada", korean_name: "T. 와다", team_id: 287, position: "Midfielder", number: null, age: 16 },
  { id: 524337, name: "Y. Tanaka", korean_name: "Y. 타나카", team_id: 287, position: "Defender", number: null, age: 17 },
];

// Vissel Kobe
export const VISSEL_KOBE_PLAYERS: PlayerMapping[] = [
  { id: 33230, name: "D. Maekawa", korean_name: "D. 마에카와", team_id: 289, position: "Goalkeeper", number: 1, age: 31 },
  { id: 109237, name: "N. Iino", korean_name: "N. 이이노", team_id: 289, position: "Midfielder", number: 2, age: 29 },
  { id: 10165, name: "Matheus Thuler", korean_name: "마테우스 툴레르", team_id: 289, position: "Defender", number: 3, age: 26 },
  { id: 195738, name: "T. Yamakawa", korean_name: "T. 야마카와", team_id: 289, position: "Defender", number: 4, age: 28 },
  { id: 33148, name: "M. Saito", korean_name: "M. 사이토", team_id: 289, position: "Midfielder", number: 5, age: 26 },
  { id: 33013, name: "T. Ohgihara", korean_name: "T. 오기하라", team_id: 289, position: "Midfielder", number: 6, age: 34 },
  { id: 25153, name: "Y. Ideguchi", korean_name: "Y. 이데구치", team_id: 289, position: "Midfielder", number: 7, age: 29 },
  { id: 32972, name: "T. Miyashiro", korean_name: "T. 미야시로", team_id: 289, position: "Midfielder", number: 9, age: 25 },
  { id: 25330, name: "Y. Osako", korean_name: "Y. 오사코", team_id: 289, position: "Attacker", number: 10, age: 35 },
  { id: 18905, name: "Y. Muto", korean_name: "Y. 무토", team_id: 289, position: "Attacker", number: 11, age: 33 },
  { id: 92046, name: "D. Sasaki", korean_name: "D. 사사키", team_id: 289, position: "Attacker", number: 13, age: 26 },
  { id: 33115, name: "K. Yuruki", korean_name: "K. 유루키", team_id: 289, position: "Midfielder", number: 14, age: 30 },
  { id: 33562, name: "Y. Honda", korean_name: "Y. 혼다", team_id: 289, position: "Defender", number: 15, age: 34 },
  { id: 80534, name: "Caetano", korean_name: "카이타노", team_id: 289, position: "Defender", number: 16, age: 26 },
  { id: 33456, name: "H. Ide", korean_name: "H. 이데", team_id: 289, position: "Midfielder", number: 18, age: 31 },
  { id: 33066, name: "Y. Koike", korean_name: "Y. 코이케", team_id: 289, position: "Defender", number: 20, age: 29 },
  { id: 32944, name: "S. Arai", korean_name: "S. 아라이", team_id: 289, position: "Goalkeeper", number: 21, age: 37 },
  { id: 319019, name: "H. Motoyama", korean_name: "H. 모토야마", team_id: 289, position: "Defender", number: 22, age: 26 },
  { id: 33008, name: "R. Hirose", korean_name: "R. 히로세", team_id: 289, position: "Defender", number: 23, age: 30 },
  { id: 24872, name: "G. Sakai", korean_name: "G. 사카이", team_id: 289, position: "Defender", number: 24, age: 34 },
  { id: 304879, name: "Y. Kuwasaki", korean_name: "Y. 쿠와사키", team_id: 289, position: "Midfielder", number: 25, age: 27 },
  { id: 54491, name: "Jean Patrick", korean_name: "Jean 파트릭", team_id: 289, position: "Attacker", number: 26, age: 28 },
  { id: 10074, name: "Erik", korean_name: "에리크", team_id: 289, position: "Attacker", number: 27, age: 31 },
  { id: 33556, name: "R. Komatsu", korean_name: "R. 코마츠", team_id: 289, position: "Attacker", number: 29, age: 27 },
  { id: 33250, name: "K. Yamauchi", korean_name: "K. 야마우치", team_id: 289, position: "Midfielder", number: 30, age: 23 },
  { id: 33096, name: "T. Iwanami", korean_name: "T. 이와나미", team_id: 289, position: "Defender", number: 31, age: 31 },
  { id: 506565, name: "R. Ubong", korean_name: "R. 우봉", team_id: 289, position: "Goalkeeper", number: 32, age: 20 },
  { id: 305749, name: "R. Hashimoto", korean_name: "R. 하시모토", team_id: 289, position: "Attacker", number: 33, age: 20 },
  { id: 377929, name: "N. Tominaga", korean_name: "N. 토미나가", team_id: 289, position: "Attacker", number: 35, age: 21 },
  { id: 363322, name: "M. Hidaka", korean_name: "M. 히다카", team_id: 289, position: "Midfielder", number: 44, age: 22 },
  { id: 146562, name: "P. Obi", korean_name: "P. 오비", team_id: 289, position: "Goalkeeper", number: 50, age: 28 },
  { id: 500913, name: "T. Seguchi", korean_name: "T. 세구치", team_id: 289, position: "Attacker", number: 51, age: 17 },
  { id: 477135, name: "K. Hamasaki", korean_name: "K. 하마사키", team_id: 289, position: "Midfielder", number: 52, age: 18 },
  { id: 525249, name: "Y. Miyahara", korean_name: "Y. 미야하라", team_id: 289, position: "Attacker", number: 55, age: 20 },
  { id: 509245, name: "T. Satomi", korean_name: "T. 사토미", team_id: 289, position: "Midfielder", number: 56, age: 16 },
  { id: 525248, name: "R. Irie", korean_name: "R. 이리에", team_id: 289, position: "Defender", number: 57, age: 21 },
  { id: 33164, name: "R. Matsuda", korean_name: "R. 마츠다", team_id: 289, position: "Defender", number: 66, age: 34 },
  { id: 41349, name: "Shūichi Gonda", korean_name: "곤다 슈이치", team_id: 289, position: "Goalkeeper", number: 71, age: 36 },
  { id: 329660, name: "Klismahn", korean_name: "구스타보 클리스만", team_id: 289, position: "Midfielder", number: 77, age: 26 },
  { id: 509244, name: "S. Hara", korean_name: "S. 하라", team_id: 289, position: "Defender", number: null, age: 18 },
];

// Yokohama FC
export const YOKOHAMA_FC_PLAYERS: PlayerMapping[] = [
  { id: 10478, name: "Phelipe Megiolaro", korean_name: "펠리페 메기올라로알베스", team_id: 307, position: "Goalkeeper", number: 1, age: 26 },
  { id: 33091, name: "R. Ishii", korean_name: "R. 이시이", team_id: 307, position: "Goalkeeper", number: 1, age: 25 },
  { id: 33424, name: "B. Nduka", korean_name: "B. 은두카", team_id: 307, position: "Defender", number: 2, age: 29 },
  { id: 91177, name: "J. Suzuki", korean_name: "J. 스즈키", team_id: 307, position: "Defender", number: 3, age: 29 },
  { id: 550705, name: "Y. Lara", korean_name: "라라 Y.", team_id: 307, position: null, number: 4, age: null },
  { id: 10030, name: "Yuri Lara", korean_name: "유리 라라", team_id: 307, position: "Midfielder", number: 4, age: 31 },
  { id: 32975, name: "A. Fukumori", korean_name: "A. 후쿠모리", team_id: 307, position: "Defender", number: 5, age: 33 },
  { id: 32987, name: "Y. Komai", korean_name: "Y. 코마이", team_id: 307, position: "Midfielder", number: 6, age: 33 },
  { id: 33316, name: "L. Takae", korean_name: "L. 타카에", team_id: 307, position: "Midfielder", number: 7, age: 27 },
  { id: 2607, name: "M. Suzuki", korean_name: "M. 스즈키", team_id: 307, position: "Attacker", number: 7, age: 31 },
  { id: 33192, name: "T. Yamane", korean_name: "T. 야마네", team_id: 307, position: "Midfielder", number: 8, age: 26 },
  { id: 199882, name: "S. Sakuragawa", korean_name: "S. 사쿠라가와", team_id: 307, position: "Attacker", number: 9, age: 24 },
  { id: 77992, name: "João Paulo", korean_name: "조앙 파울로", team_id: 307, position: "Attacker", number: 10, age: 29 },
  { id: 33254, name: "Keijiro Ogawa", korean_name: "오가와 케이지로", team_id: 307, position: "Attacker", number: 13, age: 33 },
  { id: 32990, name: "Y. Nakano", korean_name: "Y. 나카노", team_id: 307, position: "Midfielder", number: 14, age: 32 },
  { id: 33086, name: "S. Ito", korean_name: "S. 이토", team_id: 307, position: "Attacker", number: 15, age: 37 },
  { id: 33421, name: "M. Ito", korean_name: "M. 이토", team_id: 307, position: "Defender", number: 16, age: 33 },
  { id: 109197, name: "M. Arai", korean_name: "M. 아라이", team_id: 307, position: "Midfielder", number: 17, age: 28 },
  { id: 403474, name: "S. Van Eerden", korean_name: "숀 반 에르덴", team_id: 307, position: "Defender", number: 19, age: 21 },
  { id: 33981, name: "T. Murata", korean_name: "T. 무라타", team_id: 307, position: "Midfielder", number: 20, age: 25 },
  { id: 91743, name: "A. Ichikawa", korean_name: "A. 이치카와", team_id: 307, position: "Goalkeeper", number: 21, age: 27 },
  { id: 33097, name: "K. Iwatake", korean_name: "K. 이와타케", team_id: 307, position: "Defender", number: 22, age: 29 },
  { id: 54874, name: "Michel", korean_name: "미셸", team_id: 307, position: "Midfielder", number: 23, age: 28 },
  { id: 33549, name: "R. Kubota", korean_name: "R. 쿠보타", team_id: 307, position: "Attacker", number: 23, age: 24 },
  { id: 40328, name: "J. Słowik", korean_name: "스워비크 J.", team_id: 307, position: "Goalkeeper", number: 24, age: 34 },
  { id: 77884, name: "Léo Bahia", korean_name: "Léo 바이아", team_id: 307, position: "Defender", number: 27, age: 31 },
  { id: 550735, name: "K. Kumakura", korean_name: "K. 쿠마쿠라", team_id: 307, position: null, number: 28, age: null },
  { id: 506845, name: "K. Kumakura", korean_name: "K. 쿠마쿠라", team_id: 307, position: "Defender", number: 28, age: 23 },
  { id: 33906, name: "K. Yamazaki", korean_name: "K. 야마자키", team_id: 307, position: "Defender", number: 30, age: 30 },
  { id: 385691, name: "K. Muroi", korean_name: "K. 무로이", team_id: 307, position: "Attacker", number: 33, age: 25 },
  { id: 404363, name: "H. Ogura", korean_name: "H. 오구라", team_id: 307, position: "Midfielder", number: 34, age: 24 },
  { id: 467678, name: "K. Maeda", korean_name: "K. 마에다", team_id: 307, position: "Attacker", number: 37, age: 18 },
  { id: 289884, name: "K. Mori", korean_name: "K. 모리", team_id: 307, position: "Attacker", number: 39, age: 25 },
  { id: 506615, name: "Takanari Endo", korean_name: "다키나리 엔도", team_id: 307, position: "Midfielder", number: 39, age: 23 },
  { id: 550733, name: "T. Endo", korean_name: "T. 엔도", team_id: 307, position: null, number: 39, age: null },
  { id: 403472, name: "M. Endo", korean_name: "M. 엔도", team_id: 307, position: "Goalkeeper", number: 40, age: 24 },
  { id: 32878, name: "T. Shibuya", korean_name: "T. 시부야", team_id: 307, position: "Goalkeeper", number: 45, age: 30 },
  { id: 109384, name: "Izumi Miyata", korean_name: "이즈미 미야타", team_id: 307, position: "Attacker", number: 46, age: 24 },
  { id: 462735, name: "S. Sato", korean_name: "S. 사토", team_id: 307, position: "Defender", number: 46, age: 22 },
  { id: 264813, name: "K. Shimbo", korean_name: "K. 심보", team_id: 307, position: "Defender", number: 48, age: 23 },
  { id: 506846, name: "N. Komazawa", korean_name: "N. 코마자와", team_id: 307, position: "Attacker", number: 49, age: 23 },
  { id: 370138, name: "K. Nagata", korean_name: "K. 나가타", team_id: 307, position: "Midfielder", number: 50, age: 23 },
  { id: 519157, name: "K. Hosoi", korean_name: "K. 호소이", team_id: 307, position: "Midfielder", number: 70, age: 22 },
  { id: 550740, name: "K. Hosoi", korean_name: "K. 호소이", team_id: 307, position: null, number: 70, age: null },
  { id: 33023, name: "K. Yamada", korean_name: "K. 야마다", team_id: 307, position: "Midfielder", number: 76, age: 26 },
  { id: 33273, name: "Adaílton", korean_name: "아다일톤", team_id: 307, position: "Attacker", number: 90, age: 35 },
  { id: 49122, name: "Lukian", korean_name: "루키안", team_id: 307, position: "Attacker", number: 91, age: 34 },
  { id: 457194, name: "J. Hashimoto", korean_name: "J. 하시모토", team_id: 307, position: "Midfielder", number: null, age: 24 },
  { id: 506844, name: "J. Hata", korean_name: "J. 하타", team_id: 307, position: "Defender", number: null, age: 18 },
  { id: 538017, name: "R. Ishii", korean_name: "R. 이시이", team_id: 307, position: null, number: null, age: null },
  { id: 519158, name: "S. Tsukuda", korean_name: "S. 츠쿠다", team_id: 307, position: "Defender", number: null, age: 18 },
];

// Yokohama F. Marinos -여기부터 다시시
export const YOKOHAMA_F_MARINOS_PLAYERS: PlayerMapping[] = [
  { id: 32912, name: "W. Popp", korean_name: "W. 포프", team_id: 296, position: "Goalkeeper", number: 1, age: 31 },
  { id: 33362, name: "K. Nagato", korean_name: "K. 나가토", team_id: 296, position: "Defender", number: 2, age: 30 },
  { id: 33804, name: "K. Watanabe", korean_name: "K. 와타나베", team_id: 296, position: "Midfielder", number: 6, age: 27 },
  { id: 10042, name: "Élber", korean_name: "Élber", team_id: 296, position: "Midfielder", number: 7, age: 33 },
  { id: 33018, name: "T. Kida", korean_name: "T. 키다", team_id: 296, position: "Midfielder", number: 8, age: 31 },
  { id: 146585, name: "D. Tono", korean_name: "D. 토노", team_id: 296, position: "Attacker", number: 9, age: 26 },
  { id: 41630, name: "Yan Matheus", korean_name: "마테우스 Yan", team_id: 296, position: "Midfielder", number: 11, age: 27 },
  { id: 13209, name: "J. Quiñónes", korean_name: "J. Quiñónes", team_id: 296, position: "Defender", number: 13, age: 28 },
  { id: 199887, name: "A. Uenaka", korean_name: "A. 우에나카", team_id: 296, position: "Midfielder", number: 14, age: 24 },
  { id: 353587, name: "R. Kato", korean_name: "R. 카토", team_id: 296, position: "Defender", number: 16, age: 26 },
  { id: 199627, name: "K. Inoue", korean_name: "K. 이노우에", team_id: 296, position: "Midfielder", number: 17, age: 27 },
  { id: 288914, name: "George Onaiwu", korean_name: "George 오나이우", team_id: 296, position: "Midfielder", number: 18, age: 25 },
  { id: 550742, name: "G. Onaiwu", korean_name: "G. 오나이우", team_id: 296, position: null, number: 18, age: null },
  { id: 33004, name: "Park Il-Gyu", korean_name: "박일규", team_id: 296, position: "Goalkeeper", number: 19, age: 36 },
  { id: 33016, name: "J. Amano", korean_name: "J. 아마노", team_id: 296, position: "Midfielder", number: 20, age: 34 },
  { id: 33003, name: "H. Iikura", korean_name: "H. 이이쿠라", team_id: 296, position: "Goalkeeper", number: 21, age: 39 },
  { id: 206972, name: "E. Matsuda", korean_name: "E. 마츠다", team_id: 296, position: "Midfielder", number: 22, age: 24 },
  { id: 284784, name: "R. Tsunoda", korean_name: "R. 츠노다", team_id: 296, position: "Defender", number: 22, age: 26 },
  { id: 24939, name: "R. Miyaichi", korean_name: "R. 미야이치", team_id: 296, position: "Attacker", number: 23, age: 33 },
  { id: 33140, name: "T. Suzuki", korean_name: "T. 스즈키", team_id: 296, position: "Midfielder", number: 25, age: 25 },
  { id: 550736, name: "D. David", korean_name: "D. 다비드", team_id: 296, position: null, number: 26, age: null },
  { id: 111277, name: "D. David", korean_name: "D. 다비드", team_id: 296, position: "Attacker", number: 26, age: 29 },
  { id: 33012, name: "K. Matsubara", korean_name: "K. 마츠바라", team_id: 296, position: "Defender", number: 27, age: 32 },
  { id: 351542, name: "R. Yamane", korean_name: "R. 야마네", team_id: 296, position: "Midfielder", number: 28, age: 22 },
  { id: 41686, name: "Yuri Araújo", korean_name: "유리 아라우조", team_id: 296, position: "Midfielder", number: 30, age: 29 },
  { id: 369476, name: "R. Kimura", korean_name: "R. 키무라", team_id: 296, position: "Goalkeeper", number: 31, age: 22 },
  { id: 529017, name: "Y. Tanaka", korean_name: "Y. 타나카", team_id: 296, position: null, number: 32, age: null },
  { id: 369713, name: "K. Suwama", korean_name: "K. 스와마", team_id: 296, position: "Defender", number: 33, age: 22 },
  { id: 550718, name: "K. Suwama", korean_name: "K. 스와마", team_id: 296, position: null, number: 33, age: null },
  { id: 403477, name: "T. Kimura", korean_name: "T. 키무라", team_id: 296, position: "Midfielder", number: 34, age: 25 },
  { id: 550741, name: "K. Sekitomi", korean_name: "K. 세키토미", team_id: 296, position: null, number: 35, age: null },
  { id: 529335, name: "S. Kanta", korean_name: "S. 칸타", team_id: 296, position: "Defender", number: 35, age: null },
  { id: 38777, name: "Jordy Croux", korean_name: "요르디디 크루시", team_id: 296, position: "Midfielder", number: 37, age: 31 },
  { id: 33632, name: "T. Watanabe", korean_name: "T. 와타나베", team_id: 296, position: "Defender", number: 39, age: 26 },
  { id: 381676, name: "K. Matsumura", korean_name: "K. 마츠무라", team_id: 296, position: "Midfielder", number: 41, age: 21 },
  { id: 489924, name: "R. Noguchi", korean_name: "R. 노구치", team_id: 296, position: "Defender", number: 43, age: 19 },
  { id: 6849, name: "T. Deng", korean_name: "T. 덩", team_id: 296, position: "Defender", number: 44, age: 28 },
  { id: 350011, name: "K. Aziangbe", korean_name: "K. 아지앙베", team_id: 296, position: "Defender", number: 45, age: 22 },
  { id: 479272, name: "H. Asada", korean_name: "H. 아사다", team_id: 296, position: "Attacker", number: 46, age: 17 },
  { id: 32968, name: "K. Yamamura", korean_name: "K. 야마무라", team_id: 296, position: "Midfielder", number: 47, age: 36 },
  { id: 352457, name: "K. Tanimura", korean_name: "K. 타니무라", team_id: 296, position: "Attacker", number: 48, age: 27 },
  { id: 500912, name: "K. Kato", korean_name: "K. 카토", team_id: 296, position: "Midfielder", number: 49, age: 17 },
  { id: 491465, name: "K. Suzuki", korean_name: "K. 스즈키", team_id: 296, position: "Goalkeeper", number: null, age: 18 },
  { id: 490651, name: "Shoma Yamashita", korean_name: "쇼마마 야마시타", team_id: 296, position: "Goalkeeper", number: null, age: 19 },
];

export const J1_LEAGUE_PLAYERS: PlayerMapping[] = [
  ...ALBIREX_NIIGATA_PLAYERS,
  ...AVISPA_FUKUOKA_PLAYERS,
  ...CEREZO_OSAKA_PLAYERS,
  ...FAGIANO_OKAYAMA_PLAYERS,
  ...FC_TOKYO_PLAYERS,
  ...GAMBA_OSAKA_PLAYERS,
  ...KASHIMA_PLAYERS,
  ...KASHIWA_REYSOL_PLAYERS,
  ...KAWASAKI_FRONTALE_PLAYERS,
  ...KYOTO_SANGA_PLAYERS,
  ...MACHIDA_ZELVIA_PLAYERS,
  ...NAGOYA_GRAMPUS_PLAYERS,
  ...SANFRECCE_HIROSHIMA_PLAYERS,
  ...SHIMIZU_S_PULSE_PLAYERS,
  ...SHONAN_BELLMARE_PLAYERS,
  ...TOKYO_VERDY_PLAYERS,
  ...URAWA_PLAYERS,
  ...VISSEL_KOBE_PLAYERS,
  ...YOKOHAMA_FC_PLAYERS,
  ...YOKOHAMA_F_MARINOS_PLAYERS,
];
