import { PlayerMapping } from './index';

// 덴마크 수페르리가 선수 매핑 데이터 (383명, 12개 팀)

// Aarhus (Team ID: 406) - 31명
export const AARHUS_PLAYERS: PlayerMapping[] = [
  { id: 470281, name: "Frederik Emmery", korean_name: "프레데릭 에메리", team_id: 406, position: "Attacker" },
  { id: 24973, name: "J. Serra", korean_name: "J. 세하", team_id: 406, position: "Attacker" },
  { id: 108490, name: "Kristian Fredrik Malt Arnstad", korean_name: "크리스티안 아른스타드", team_id: 406, position: "Attacker" },
  { id: 15598, name: "P. Mortensen", korean_name: "P. 모르텐센", team_id: 406, position: "Attacker" },
  { id: 458689, name: "R. Gyamfi", korean_name: "R. 자피", team_id: 406, position: "Attacker" },
  { id: 15943, name: "S. Jørgensen", korean_name: "S. 요르겐센", team_id: 406, position: "Attacker" },
  { id: 514279, name: "S. Tchamche", korean_name: "S. 샴체", team_id: 406, position: "Attacker" },
  { id: 15964, name: "T. Bech", korean_name: "T. 베크", team_id: 406, position: "Attacker" },
  { id: 495841, name: "Tómas Óli Kristjánsson", korean_name: "토마스 크리스티안손", team_id: 406, position: "Attacker" },
  { id: 194816, name: "Y. Badji", korean_name: "Y. 바지", team_id: 406, position: "Attacker" },
  { id: 151738, name: "E. Kahl", korean_name: "E. 칼", team_id: 406, position: "Defender" },
  { id: 15584, name: "F. Tingager", korean_name: "F. 팅가게르", team_id: 406, position: "Defender" },
  { id: 2730, name: "H. Dalsgaard", korean_name: "H. 달스가르", team_id: 406, position: "Defender" },
  { id: 315567, name: "J. Andersen", korean_name: "J. 안데르센", team_id: 406, position: "Defender" },
  { id: 309875, name: "J. Jensen-Abbew", korean_name: "J. 옌센-아베우", team_id: 406, position: "Defender" },
  { id: 465901, name: "Luka Callø", korean_name: "루카 칼로", team_id: 406, position: "Defender" },
  { id: 15931, name: "R. Carstensen", korean_name: "R. 카르스텐센", team_id: 406, position: "Defender" },
  { id: 15668, name: "T. Mølgaard", korean_name: "T. 묄고르", team_id: 406, position: "Defender" },
  { id: 15786, name: "J. Hansen", korean_name: "J. 한센", team_id: 406, position: "Goalkeeper" },
  { id: 425313, name: "J. Hutters", korean_name: "J. 휘터스", team_id: 406, position: "Goalkeeper" },
  { id: 105141, name: "L. Wahlstedt", korean_name: "L. 발스테트", team_id: 406, position: "Goalkeeper" },
  { id: 25312, name: "F. Beijmo", korean_name: "F. 베이모", team_id: 406, position: "Midfielder" },
  { id: 46283, name: "G. Links", korean_name: "G. 링크스", team_id: 406, position: "Midfielder" },
  { id: 277745, name: "K. Arnstad", korean_name: "K. 아른스타드", team_id: 406, position: "Midfielder" },
  { id: 48025, name: "Kevin Yakob", korean_name: "케빈 야콥", team_id: 406, position: "Midfielder" },
  { id: 57425, name: "Markus Solbakken", korean_name: "마르쿠스 솔바켄", team_id: 406, position: "Midfielder" },
  { id: 15699, name: "N. Poulsen", korean_name: "N. 폴센", team_id: 406, position: "Midfielder" },
  { id: 515773, name: "Oskar Skou Haugstrup", korean_name: "오스카 스코우 호그스트룹", team_id: 406, position: "Midfielder" },
  { id: 550856, name: "O. Haugstrup", korean_name: "O. 호그스트룹", team_id: 406, position: "Midfielder" },
  { id: 562349, name: "T. Kristjansson", korean_name: "T. 크리스티안손", team_id: 406, position: "Midfielder" },
  { id: 550857, name: "Z. Grantzau", korean_name: "Z. 그란트소", team_id: 406, position: "Midfielder" },
];

// Brondby (Team ID: 407) - 27명
export const BRONDBY_PLAYERS: PlayerMapping[] = [
  { id: 291839, name: "F. Bundgaard", korean_name: "F. 분고르", team_id: 407, position: "Attacker" },
  { id: 524210, name: "J. Agyekum", korean_name: "J. 아제쿰", team_id: 407, position: "Attacker" },
  { id: 494387, name: "J. Ambæk", korean_name: "J. 암베크", team_id: 407, position: "Attacker" },
  { id: 381677, name: "K. Uchino", korean_name: "K. 우치노", team_id: 407, position: "Attacker" },
  { id: 404057, name: "Marcus Younis", korean_name: "마르쿠스 유니스", team_id: 407, position: "Attacker" },
  { id: 25297, name: "Michael Gregoritsch", korean_name: "미하엘 그레고리치", team_id: 407, position: "Attacker" },
  { id: 361352, name: "N. Nartey", korean_name: "N. 나르테이", team_id: 407, position: "Attacker" },
  { id: 441958, name: "Clement Bischoff", korean_name: "클레멘트 비스호프", team_id: 407, position: "Defender" },
  { id: 15928, name: "F. Alves", korean_name: "F. 알베스", team_id: 407, position: "Defender" },
  { id: 266599, name: "J. Che", korean_name: "J. 체", team_id: 407, position: "Defender" },
  { id: 8711, name: "J. Vanlerberghe", korean_name: "J. 반레르베르헤", team_id: 407, position: "Defender" },
  { id: 154799, name: "L. Binks", korean_name: "L. 빙크스", team_id: 407, position: "Defender" },
  { id: 61183, name: "M. Divković", korean_name: "M. 디브코비치", team_id: 407, position: "Defender" },
  { id: 24881, name: "M. Köhlert", korean_name: "M. 쾰레르트", team_id: 407, position: "Defender" },
  { id: 128763, name: "O. Villadsen", korean_name: "O. 빌라센", team_id: 407, position: "Defender" },
  { id: 48189, name: "R. Lauritsen", korean_name: "R. 라우리트센", team_id: 407, position: "Defender" },
  { id: 37171, name: "S. Klaiber", korean_name: "S. 클라이버", team_id: 407, position: "Defender" },
  { id: 267868, name: "G. Beavers", korean_name: "G. 비버스", team_id: 407, position: "Goalkeeper" },
  { id: 7598, name: "P. Pentz", korean_name: "P. 펜츠", team_id: 407, position: "Goalkeeper" },
  { id: 16053, name: "T. Mikkelsen", korean_name: "T. 미켈센", team_id: 407, position: "Goalkeeper" },
  { id: 478101, name: "William Sonne-Schmidt", korean_name: "윌리엄 소네-슈미트", team_id: 407, position: "Goalkeeper" },
  { id: 264094, name: "B. Tahirović", korean_name: "B. 타히로비치", team_id: 407, position: "Midfielder" },
  { id: 932, name: "D. Wass", korean_name: "D. 바스", team_id: 407, position: "Midfielder" },
  { id: 510351, name: "Mathias Jensen", korean_name: "마티아스 옌센", team_id: 407, position: "Midfielder" },
  { id: 16176, name: "N. Vallys", korean_name: "N. 발리스", team_id: 407, position: "Midfielder" },
  { id: 206937, name: "S. Fukuda", korean_name: "S. 후쿠다", team_id: 407, position: "Midfielder" },
  { id: 36868, name: "S. Spierings", korean_name: "S. 스피링스", team_id: 407, position: "Midfielder" },
];

// FC Copenhagen (Team ID: 400) - 31명
export const FC_COPENHAGEN_PLAYERS: PlayerMapping[] = [
  { id: 1274, name: "A. Cornelius", korean_name: "A. 코르넬리우스", team_id: 400, position: "Attacker" },
  { id: 2093, name: "German Onugkha", korean_name: "게르만 오눅하", team_id: 400, position: "Attacker" },
  { id: 18946, name: "M. Elyounoussi", korean_name: "M. 엘유누시", team_id: 400, position: "Attacker" },
  { id: 2080, name: "V. Claesson", korean_name: "V. 클라에손", team_id: 400, position: "Attacker" },
  { id: 426288, name: "Viktor Bjarki Dadason", korean_name: "빅토르 비아르키 다다손", team_id: 400, position: "Attacker" },
  { id: 161919, name: "Y. Moukoko", korean_name: "유수파 무코코", team_id: 400, position: "Attacker" },
  { id: 1173, name: "B. Meling", korean_name: "B. 멜링", team_id: 400, position: "Defender" },
  { id: 159511, name: "Gabriel Pereira", korean_name: "가브리엘 페레이라", team_id: 400, position: "Defender" },
  { id: 351014, name: "J. Suzuki", korean_name: "J. 스즈키", team_id: 400, position: "Defender" },
  { id: 354267, name: "M. Garananga", korean_name: "M. 가라낭가", team_id: 400, position: "Defender" },
  { id: 2431, name: "M. López", korean_name: "M. 로페스", team_id: 400, position: "Defender" },
  { id: 36885, name: "P. Hatzidiakos", korean_name: "P. 하치디아코스", team_id: 400, position: "Defender" },
  { id: 310199, name: "R. Huescas", korean_name: "R. 후에스카스", team_id: 400, position: "Defender" },
  { id: 334039, name: "W. Renecke", korean_name: "W. 레네케", team_id: 400, position: "Defender" },
  { id: 386285, name: "Yoram Zague", korean_name: "요람 자게", team_id: 400, position: "Defender" },
  { id: 524, name: "D. Kotarski", korean_name: "D. 코타르스키", team_id: 400, position: "Goalkeeper" },
  { id: 90494, name: "N. Trott", korean_name: "N. 트롯", team_id: 400, position: "Goalkeeper" },
  { id: 441252, name: "Oscar Gadeberg-Buur", korean_name: "오스카 가데베르크-부르", team_id: 400, position: "Goalkeeper" },
  { id: 2784, name: "R. Rúnarsson", korean_name: "R. 루나르손", team_id: 400, position: "Goalkeeper" },
  { id: 442537, name: "D. Sarapata", korean_name: "D. 사라파타", team_id: 400, position: "Midfielder" },
  { id: 42012, name: "E. Achouri", korean_name: "E. 아쿠리", team_id: 400, position: "Midfielder" },
  { id: 48203, name: "J. Larsson", korean_name: "J. 라르손", team_id: 400, position: "Midfielder" },
  { id: 444418, name: "Jonathan Moalem", korean_name: "조나단 모알렘", team_id: 400, position: "Midfielder" },
  { id: 2736, name: "L. Lerager", korean_name: "L. 레라게르", team_id: 400, position: "Midfielder" },
  { id: 15934, name: "Mads Emil Møller Madsen", korean_name: "마스 에밀 묄레르 마센", team_id: 400, position: "Midfielder" },
  { id: 15935, name: "M. Mattsson", korean_name: "M. 마트손", team_id: 400, position: "Midfielder" },
  { id: 395602, name: "Oliver Højer", korean_name: "올리버 회에르", team_id: 400, position: "Midfielder" },
  { id: 422779, name: "Robert", korean_name: "로베르트", team_id: 400, position: "Midfielder" },
  { id: 15, name: "T. Delaney", korean_name: "T. 델라니", team_id: 400, position: "Midfielder" },
  { id: 388872, name: "Victor Mow Froholdt", korean_name: "빅토르 모우 프로홀트", team_id: 400, position: "Midfielder" },
  { id: 349212, name: "W. Clem", korean_name: "W. 클렘", team_id: 400, position: "Midfielder" },
];

// FC Fredericia (Team ID: 2061) - 30명
export const FC_FREDERICIA_PLAYERS: PlayerMapping[] = [
  { id: 16041, name: "A. Muçolli", korean_name: "A. 무초리", team_id: 2061, position: "Attacker" },
  { id: 294685, name: "E. Dall", korean_name: "E. 달", team_id: 2061, position: "Attacker" },
  { id: 362460, name: "M. Huldahl", korean_name: "M. 휄달", team_id: 2061, position: "Attacker" },
  { id: 15836, name: "P. Egelund", korean_name: "P. 에겔룬드", team_id: 2061, position: "Attacker" },
  { id: 282416, name: "A. Dahl", korean_name: "A. 달", team_id: 2061, position: "Defender" },
  { id: 438715, name: "Adam Nygaard Andersen", korean_name: "아담 뉘고르 안데르센", team_id: 2061, position: "Defender" },
  { id: 334784, name: "D. Kristjánsson", korean_name: "D. 크리스티안손", team_id: 2061, position: "Defender" },
  { id: 15583, name: "D. Thøgersen", korean_name: "D. 퇴게르센", team_id: 2061, position: "Defender" },
  { id: 326444, name: "F. Rieper", korean_name: "F. 리퍼", team_id: 2061, position: "Defender" },
  { id: 428299, name: "J. Jessen", korean_name: "J. 예센", team_id: 2061, position: "Defender" },
  { id: 343880, name: "J. Kudsk", korean_name: "J. 쿠드스크", team_id: 2061, position: "Defender" },
  { id: 19522, name: "Kristian Majdahl Pedersen", korean_name: "크리스티안 마달 페데르센", team_id: 2061, position: "Defender" },
  { id: 432256, name: "M. Ladefoged", korean_name: "M. 라데포게드", team_id: 2061, position: "Defender" },
  { id: 15924, name: "S. Crone", korean_name: "S. 크로네", team_id: 2061, position: "Defender" },
  { id: 174837, name: "Etienne Green", korean_name: "에티엔 그린", team_id: 2061, position: "Goalkeeper" },
  { id: 428300, name: "M. Eriksen", korean_name: "M. 에릭센", team_id: 2061, position: "Goalkeeper" },
  { id: 83043, name: "M. Lamhauge", korean_name: "M. 람하우게", team_id: 2061, position: "Goalkeeper" },
  { id: 284543, name: "O. Ejeheri", korean_name: "O. 에예헤리", team_id: 2061, position: "Goalkeeper" },
  { id: 15879, name: "A. Pyndt", korean_name: "A. 핀트", team_id: 2061, position: "Midfielder" },
  { id: 341899, name: "D. Haarbo", korean_name: "D. 하르보", team_id: 2061, position: "Midfielder" },
  { id: 16071, name: "E. Simonsen", korean_name: "E. 시몬센", team_id: 2061, position: "Midfielder" },
  { id: 128879, name: "F. Winther", korean_name: "F. 빈테르", team_id: 2061, position: "Midfielder" },
  { id: 16070, name: "G. Marcussen", korean_name: "G. 마르쿠센", team_id: 2061, position: "Midfielder" },
  { id: 412887, name: "Jonatan Holm Lindekilde", korean_name: "요나탄 홀름 린데킬데", team_id: 2061, position: "Midfielder" },
  { id: 15753, name: "M. Opondo", korean_name: "M. 오폰도", team_id: 2061, position: "Midfielder" },
  { id: 128887, name: "O. Buch", korean_name: "O. 부흐", team_id: 2061, position: "Midfielder" },
  { id: 443703, name: "Sofus Østergaard Grandjean Johannese", korean_name: "소푸스 외스테르고르", team_id: 2061, position: "Midfielder" },
  { id: 294772, name: "W. Madsen", korean_name: "W. 마센", team_id: 2061, position: "Midfielder" },
  { id: 550842, name: "M. Huldahl", korean_name: "M. 휄달", team_id: 2061, position: "Midfielder" },
  { id: 550846, name: "M. Ladefoged", korean_name: "M. 라데포게드", team_id: 2061, position: "Midfielder" },
];

// FC Midtjylland (Team ID: 397) - 31명
export const FC_MIDTJYLLAND_PLAYERS: PlayerMapping[] = [
  { id: 40594, name: "A. Buksa", korean_name: "A. 북사", team_id: 397, position: "Attacker" },
  { id: 34211, name: "Cho Gue-Sung", korean_name: "조규성", team_id: 397, position: "Attacker" },
  { id: 307117, name: "D. Osorio", korean_name: "D. 오소리오", team_id: 397, position: "Attacker" },
  { id: 48056, name: "E. Chilufya", korean_name: "E. 칠루프야", team_id: 397, position: "Attacker" },
  { id: 351146, name: "F. Etim", korean_name: "F. 에팀", team_id: 397, position: "Attacker" },
  { id: 340625, name: "Franculino Djú", korean_name: "프랑쿨리노 주", team_id: 397, position: "Attacker" },
  { id: 15810, name: "Júnior Brumado", korean_name: "주니오르 브루마두", team_id: 397, position: "Attacker" },
  { id: 435061, name: "Mikel Johan Gogorza Krüger-Johnsen", korean_name: "미켈 요한 고고르자", team_id: 397, position: "Attacker" },
  { id: 287565, name: "A. Gabriel", korean_name: "A. 가브리엘", team_id: 397, position: "Defender" },
  { id: 421937, name: "B. Konteh Krubally", korean_name: "B. 콘테 크루발리", team_id: 397, position: "Defender" },
  { id: 396213, name: "Gustav Bjerge", korean_name: "구스타프 비에르게", team_id: 397, position: "Defender" },
  { id: 237218, name: "Lee Han-Beom", korean_name: "이한범", team_id: 397, position: "Defender" },
  { id: 19345, name: "M. Bech", korean_name: "M. 베크", team_id: 397, position: "Defender" },
  { id: 30827, name: "M. Erlić", korean_name: "M. 에를리치", team_id: 397, position: "Defender" },
  { id: 404026, name: "O. Diao", korean_name: "O. 디아오", team_id: 397, position: "Defender" },
  { id: 10016, name: "Paulinho", korean_name: "파울리뉴", team_id: 397, position: "Defender" },
  { id: 89754, name: "E. Ólafsson", korean_name: "E. 올라프손", team_id: 397, position: "Goalkeeper" },
  { id: 2727, name: "J. Lössl", korean_name: "J. 뢰슬", team_id: 397, position: "Goalkeeper" },
  { id: 394987, name: "L. Selin", korean_name: "L. 셀린", team_id: 397, position: "Goalkeeper" },
  { id: 374525, name: "Mark Nnamdi Ugboh", korean_name: "마크 남디 우고보", team_id: 397, position: "Goalkeeper" },
  { id: 438717, name: "Alamara Viriato Djabi", korean_name: "알라마라 디아비", team_id: 397, position: "Midfielder" },
  { id: 161790, name: "A. Şimşir", korean_name: "A. 심시르", team_id: 397, position: "Midfielder" },
  { id: 42007, name: "Dani Silva", korean_name: "다니 실바", team_id: 397, position: "Midfielder" },
  { id: 338045, name: "D. Castillo", korean_name: "D. 카스티요", team_id: 397, position: "Midfielder" },
  { id: 946, name: "K. Mbabu", korean_name: "K. 음바부", team_id: 397, position: "Midfielder" },
  { id: 161569, name: "O. Sørensen", korean_name: "O. 쇠렌센", team_id: 397, position: "Midfielder" },
  { id: 311432, name: "P. Bravo", korean_name: "P. 브라보", team_id: 397, position: "Midfielder" },
  { id: 2734, name: "Philip Anyanwu Billing", korean_name: "필립 빌링", team_id: 397, position: "Midfielder" },
  { id: 162218, name: "V. Bak Jensen", korean_name: "V. 바크 옌센", team_id: 397, position: "Midfielder" },
  { id: 371909, name: "V. Byskov", korean_name: "V. 뷔스코프", team_id: 397, position: "Midfielder" },
  { id: 544622, name: "A. Djabi", korean_name: "A. 디아비", team_id: 397, position: "Midfielder" },
];

// FC Nordsjaelland (Team ID: 398) - 35명
export const FC_NORDSJAELLAND_PLAYERS: PlayerMapping[] = [
  { id: 180982, name: "Alexander Lucas Lind Rasmussen", korean_name: "알렉산더 루카스 린드 라스무센", team_id: 398, position: "Attacker" },
  { id: 377909, name: "D. Jóhannesson", korean_name: "D. 요하네손", team_id: 398, position: "Attacker" },
  { id: 513168, name: "H. Boe Rasmussen", korean_name: "H. 보 라스무센", team_id: 398, position: "Attacker" },
  { id: 474155, name: "L. Nene", korean_name: "L. 네네", team_id: 398, position: "Attacker" },
  { id: 39271, name: "O. Solbakken", korean_name: "O. 솔바켄", team_id: 398, position: "Attacker" },
  { id: 513570, name: "P. Amoako", korean_name: "P. 아모아코", team_id: 398, position: "Attacker" },
  { id: 418217, name: "S. Alio", korean_name: "S. 알리오", team_id: 398, position: "Attacker" },
  { id: 342654, name: "S. Egeli", korean_name: "S. 에겔리", team_id: 398, position: "Attacker" },
  { id: 15692, name: "E. Marxen", korean_name: "E. 마르센", team_id: 398, position: "Defender" },
  { id: 476206, name: "I. Seidu", korean_name: "I. 세이두", team_id: 398, position: "Defender" },
  { id: 361421, name: "J. Lähteenmäki", korean_name: "J. 래테엔매키", team_id: 398, position: "Defender" },
  { id: 15791, name: "K. Hansen", korean_name: "K. 한센", team_id: 398, position: "Defender" },
  { id: 396193, name: "L. Høgsberg", korean_name: "L. 횩스베르그", team_id: 398, position: "Defender" },
  { id: 498844, name: "M. Walker", korean_name: "M. 워커", team_id: 398, position: "Defender" },
  { id: 425830, name: "Noah Markmann", korean_name: "노아 마크만", team_id: 398, position: "Defender" },
  { id: 1283, name: "P. Ankersen", korean_name: "P. 안케르센", team_id: 398, position: "Defender" },
  { id: 278551, name: "Runar Robinsønn Norheim", korean_name: "루나르 로빈손 노르헤임", team_id: 398, position: "Defender" },
  { id: 498846, name: "S. Acquah", korean_name: "S. 아쿠아", team_id: 398, position: "Defender" },
  { id: 39310, name: "T. Salquist", korean_name: "T. 살퀴스트", team_id: 398, position: "Defender" },
  { id: 16105, name: "A. Hansen", korean_name: "A. 한센", team_id: 398, position: "Goalkeeper" },
  { id: 24836, name: "J. Busk", korean_name: "J. 부스크", team_id: 398, position: "Goalkeeper" },
  { id: 390619, name: "W. Lykke", korean_name: "W. 뤼케", team_id: 398, position: "Goalkeeper" },
  { id: 461732, name: "A. Mohammed", korean_name: "A. 모하메드", team_id: 398, position: "Midfielder" },
  { id: 475575, name: "Caleb Marfo Yirenkyi", korean_name: "칼렙 마르포 이렌키", team_id: 398, position: "Midfielder" },
  { id: 502190, name: "D. Sanoussi", korean_name: "D. 사누시", team_id: 398, position: "Midfielder" },
  { id: 475394, name: "Justin Janssen", korean_name: "저스틴 얀센", team_id: 398, position: "Midfielder" },
  { id: 15825, name: "M. Brink", korean_name: "M. 브링크", team_id: 398, position: "Midfielder" },
  { id: 444419, name: "M. Heyde", korean_name: "M. 하이데", team_id: 398, position: "Midfielder" },
  { id: 294863, name: "Milan Justin Silva Rasmussen", korean_name: "밀란 저스틴 실바 라스무센", team_id: 398, position: "Midfielder" },
  { id: 15967, name: "N. Røjkjær", korean_name: "N. 뢰크예르", team_id: 398, position: "Midfielder" },
  { id: 162589, name: "R. Ascone", korean_name: "R. 아스코네", team_id: 398, position: "Midfielder" },
  { id: 498845, name: "V. Berthelsen", korean_name: "V. 베르텔센", team_id: 398, position: "Midfielder" },
  { id: 322858, name: "Z. Sertdemir", korean_name: "Z. 세르트데미르", team_id: 398, position: "Midfielder" },
  { id: 550854, name: "V. Gustafsen", korean_name: "V. 구스타프센", team_id: 398, position: "Midfielder" },
  { id: 550855, name: "V. Rutkjaer", korean_name: "V. 루트키예르", team_id: 398, position: "Midfielder" },
];

// Odense (Team ID: 405) - 31명
export const ODENSE_PLAYERS: PlayerMapping[] = [
  { id: 339876, name: "E. Hansborg-Sørensen", korean_name: "E. 한스보르-쇠렌센", team_id: 405, position: "Attacker" },
  { id: 24887, name: "J. Arp", korean_name: "J. 아르프", team_id: 405, position: "Attacker" },
  { id: 37787, name: "J. Grot", korean_name: "J. 그롯", team_id: 405, position: "Attacker" },
  { id: 324030, name: "Jona Niemiec", korean_name: "요나 니미에츠", team_id: 405, position: "Attacker" },
  { id: 128766, name: "L. Deedson", korean_name: "L. 디드슨", team_id: 405, position: "Attacker" },
  { id: 444422, name: "Mads Riis Abrahamsen", korean_name: "마스 리스 아브라함센", team_id: 405, position: "Attacker" },
  { id: 438842, name: "Magnus Hvitfeldt Andersen", korean_name: "마그누스 비트펠트 안데르센", team_id: 405, position: "Attacker" },
  { id: 203253, name: "N. Ganaus", korean_name: "N. 가나우스", team_id: 405, position: "Attacker" },
  { id: 25207, name: "B. Paulsen", korean_name: "B. 파울센", team_id: 405, position: "Defender" },
  { id: 412886, name: "J. Berthel Askou", korean_name: "J. 베르텔 아스코우", team_id: 405, position: "Defender" },
  { id: 198465, name: "J. Gomez", korean_name: "J. 고메스", team_id: 405, position: "Defender" },
  { id: 48654, name: "N. Bürgy", korean_name: "N. 뷔르기", team_id: 405, position: "Defender" },
  { id: 438854, name: "Y. Bojang", korean_name: "Y. 보장", team_id: 405, position: "Defender" },
  { id: 515864, name: "M. Eskildsen", korean_name: "M. 에스킬센", team_id: 405, position: "Goalkeeper" },
  { id: 48368, name: "M. Hansen", korean_name: "M. 한센", team_id: 405, position: "Goalkeeper" },
  { id: 311273, name: "T. Sander", korean_name: "T. 산데르", team_id: 405, position: "Goalkeeper" },
  { id: 39325, name: "V. Myhra", korean_name: "V. 뮈라", team_id: 405, position: "Goalkeeper" },
  { id: 16061, name: "A. Sørensen", korean_name: "A. 쇠렌센", team_id: 405, position: "Midfielder" },
  { id: 15853, name: "G. Grubbe", korean_name: "G. 그루베", team_id: 405, position: "Midfielder" },
  { id: 15955, name: "J. Bonde", korean_name: "J. 본데", team_id: 405, position: "Midfielder" },
  { id: 37224, name: "L. Owusu", korean_name: "L. 오우수", team_id: 405, position: "Midfielder" },
  { id: 376927, name: "M. Ejdum", korean_name: "M. 에이둠", team_id: 405, position: "Midfielder" },
  { id: 371928, name: "M. Jensen", korean_name: "M. 옌센", team_id: 405, position: "Midfielder" },
  { id: 396507, name: "M. McCoy", korean_name: "M. 맥코이", team_id: 405, position: "Midfielder" },
  { id: 396191, name: "Nikolaj Juul-Sandberg", korean_name: "니콜라이 율-산베르크", team_id: 405, position: "Midfielder" },
  { id: 1293, name: "R. Falk", korean_name: "R. 팔크", team_id: 405, position: "Midfielder" },
  { id: 19081, name: "T. Trybull", korean_name: "T. 트리불", team_id: 405, position: "Midfielder" },
  { id: 529402, name: "Vitus Friis", korean_name: "비투스 프리스", team_id: 405, position: "Midfielder" },
  { id: 297614, name: "Wandepanga Ismahila Ouédraogo", korean_name: "완데팡가 이스마힐라", team_id: 405, position: "Midfielder" },
  { id: 444452, name: "W. Martin", korean_name: "W. 마틴", team_id: 405, position: "Midfielder" },
  { id: 550844, name: "V. Friis", korean_name: "V. 프리스", team_id: 405, position: "Midfielder" },
];

// Randers FC (Team ID: 401) - 37명
export const RANDERS_FC_PLAYERS: PlayerMapping[] = [
  { id: 484099, name: "Abdul Sulemana", korean_name: "압둘 술레마나", team_id: 401, position: "Attacker" },
  { id: 363474, name: "Amin Raafat Ali Al Hamawi", korean_name: "아민 라파트 알리", team_id: 401, position: "Attacker" },
  { id: 190934, name: "E. Mahmoud", korean_name: "E. 마흐무드", team_id: 401, position: "Attacker" },
  { id: 180602, name: "F. Danho", korean_name: "F. 단호", team_id: 401, position: "Attacker" },
  { id: 392801, name: "M. Toure", korean_name: "M. 투레", team_id: 401, position: "Attacker" },
  { id: 198352, name: "M. Touré", korean_name: "M. 투레", team_id: 401, position: "Attacker" },
  { id: 1020, name: "S. Odey", korean_name: "S. 오데이", team_id: 401, position: "Attacker" },
  { id: 36971, name: "D. Høegh", korean_name: "D. 회에", team_id: 401, position: "Defender" },
  { id: 162766, name: "L. Lissens", korean_name: "L. 리센스", team_id: 401, position: "Defender" },
  { id: 128761, name: "N. Dyhr", korean_name: "N. 뒤르", team_id: 401, position: "Defender" },
  { id: 312620, name: "O. Jones", korean_name: "O. 존스", team_id: 401, position: "Defender" },
  { id: 15794, name: "O. Olsen", korean_name: "O. 올센", team_id: 401, position: "Defender" },
  { id: 36999, name: "W. Dammers", korean_name: "W. 담머스", team_id: 401, position: "Defender" },
  { id: 16080, name: "J. Storch", korean_name: "J. 스토르크", team_id: 401, position: "Goalkeeper" },
  { id: 382844, name: "M. Demirci", korean_name: "M. 데미르치", team_id: 401, position: "Goalkeeper" },
  { id: 524766, name: "O. Henriksen", korean_name: "O. 헨릭센", team_id: 401, position: "Goalkeeper" },
  { id: 6870, name: "P. Izzo", korean_name: "P. 이조", team_id: 401, position: "Goalkeeper" },
  { id: 15693, name: "A. Rømer", korean_name: "A. 뢰메르", team_id: 401, position: "Midfielder" },
  { id: 8866, name: "E. Agyiri", korean_name: "E. 아지리", team_id: 401, position: "Midfielder" },
  { id: 15697, name: "F. Lauenborg", korean_name: "F. 라우엔보르", team_id: 401, position: "Midfielder" },
  { id: 526679, name: "Hector Høyrup", korean_name: "헥토르 회이룹", team_id: 401, position: "Midfielder" },
  { id: 48352, name: "J. Björkengren", korean_name: "J. 비외르켄그렌", team_id: 401, position: "Midfielder" },
  { id: 396192, name: "L. Pedersen", korean_name: "L. 페데르센", team_id: 401, position: "Midfielder" },
  { id: 94796, name: "Mads Lennart Nielsen", korean_name: "마스 레나르트 닐센", team_id: 401, position: "Midfielder" },
  { id: 396216, name: "Max Albæk Andersen", korean_name: "막스 알베크 안데르센", team_id: 401, position: "Midfielder" },
  { id: 15859, name: "M. Greve", korean_name: "M. 그레베", team_id: 401, position: "Midfielder" },
  { id: 417304, name: "M. Themsen", korean_name: "M. 템센", team_id: 401, position: "Midfielder" },
  { id: 32621, name: "N. Campbell", korean_name: "N. 캠벨", team_id: 401, position: "Midfielder" },
  { id: 139617, name: "N. Shamoun", korean_name: "N. 샤문", team_id: 401, position: "Midfielder" },
  { id: 520936, name: "O. Seck", korean_name: "O. 세크", team_id: 401, position: "Midfielder" },
  { id: 411286, name: "S. Hansen", korean_name: "S. 한센", team_id: 401, position: "Midfielder" },
  { id: 57422, name: "S. Nordli", korean_name: "S. 노르들리", team_id: 401, position: "Midfielder" },
  { id: 529474, name: "C. Behrens", korean_name: "C. 베렌스", team_id: 401, position: "Midfielder" },
  { id: 529475, name: "F. Sommer", korean_name: "F. 소메르", team_id: 401, position: "Midfielder" },
  { id: 438728, name: "M. Nielsen", korean_name: "M. 닐센", team_id: 401, position: "Midfielder" },
  { id: 550852, name: "M. Nielsen", korean_name: "M. 닐센", team_id: 401, position: "Midfielder" },
  { id: 550841, name: "O. Olsen", korean_name: "O. 올센", team_id: 401, position: "Midfielder" },
];

// Silkeborg (Team ID: 2073) - 31명
export const SILKEBORG_PLAYERS: PlayerMapping[] = [
  { id: 390618, name: "A. Bøndergaard", korean_name: "A. 뵌데르고르", team_id: 2073, position: "Attacker" },
  { id: 356642, name: "Alexander Illum Simmelhack", korean_name: "알렉산더 일룸 시멜하크", team_id: 2073, position: "Attacker" },
  { id: 396190, name: "S. Mikkelsen", korean_name: "S. 미켈센", team_id: 2073, position: "Attacker" },
  { id: 303386, name: "T. Adamsen", korean_name: "T. 아담센", team_id: 2073, position: "Attacker" },
  { id: 290461, name: "A. Busch", korean_name: "A. 부슈", team_id: 2073, position: "Defender" },
  { id: 440577, name: "A. Madsen", korean_name: "A. 마센", team_id: 2073, position: "Defender" },
  { id: 25632, name: "A. Poulsen", korean_name: "A. 폴센", team_id: 2073, position: "Defender" },
  { id: 475177, name: "Benjamin Clemmensen", korean_name: "벤야민 클레멘센", team_id: 2073, position: "Defender" },
  { id: 15873, name: "J. Gammelby", korean_name: "J. 가멜뷔", team_id: 2073, position: "Defender" },
  { id: 202016, name: "L. Montano", korean_name: "L. 몬타노", team_id: 2073, position: "Defender" },
  { id: 204126, name: "Pedro Ganchas", korean_name: "페드로 간샤스", team_id: 2073, position: "Defender" },
  { id: 128219, name: "P. Rödin", korean_name: "P. 뢰딘", team_id: 2073, position: "Defender" },
  { id: 263178, name: "R. Østrøm", korean_name: "R. 외스트룀", team_id: 2073, position: "Defender" },
  { id: 444472, name: "S. Stücker", korean_name: "S. 슈튀커", team_id: 2073, position: "Defender" },
  { id: 339946, name: "A. Andrésen", korean_name: "A. 안드레센", team_id: 2073, position: "Goalkeeper" },
  { id: 474579, name: "B. Holm", korean_name: "B. 홀름", team_id: 2073, position: "Goalkeeper" },
  { id: 15896, name: "N. Larsen", korean_name: "N. 라르센", team_id: 2073, position: "Goalkeeper" },
  { id: 94322, name: "C. McCowatt", korean_name: "C. 맥코와트", team_id: 2073, position: "Midfielder" },
  { id: 48123, name: "J. Andersen", korean_name: "J. 안데르센", team_id: 2073, position: "Midfielder" },
  { id: 396186, name: "J. Nielsen", korean_name: "J. 닐센", team_id: 2073, position: "Midfielder" },
  { id: 277984, name: "M. Freundlich", korean_name: "M. 프로인들리히", team_id: 2073, position: "Midfielder" },
  { id: 15829, name: "M. Larsen", korean_name: "M. 라르센", team_id: 2073, position: "Midfielder" },
  { id: 515927, name: "M. Øxenberg", korean_name: "M. 외센베르크", team_id: 2073, position: "Midfielder" },
  { id: 415261, name: "O. Boesen", korean_name: "O. 보센", team_id: 2073, position: "Midfielder" },
  { id: 15936, name: "P. Mattsson", korean_name: "P. 마트손", team_id: 2073, position: "Midfielder" },
  { id: 36984, name: "R. Al Hajj", korean_name: "R. 알 하즈", team_id: 2073, position: "Midfielder" },
  { id: 128875, name: "S. Berger", korean_name: "S. 베르게르", team_id: 2073, position: "Midfielder" },
  { id: 416992, name: "Villads Westh", korean_name: "빌라스 베스트", team_id: 2073, position: "Midfielder" },
  { id: 16165, name: "Y. Bakiz", korean_name: "Y. 바키즈", team_id: 2073, position: "Midfielder" },
  { id: 534588, name: "B. Clemmensen", korean_name: "B. 클레멘센", team_id: 2073, position: "Midfielder" },
  { id: 544920, name: "M. Oxenberg", korean_name: "M. 옥센베르크", team_id: 2073, position: "Midfielder" },
];

// Sonderjyske (Team ID: 396) - 35명
export const SONDERJYSKE_PLAYERS: PlayerMapping[] = [
  { id: 323541, name: "A. Lyng", korean_name: "A. 링", team_id: 396, position: "Attacker" },
  { id: 89768, name: "K. Ingason", korean_name: "K. 잉가손", team_id: 396, position: "Attacker" },
  { id: 203014, name: "M. Hoppe", korean_name: "M. 호페", team_id: 396, position: "Attacker" },
  { id: 15696, name: "T. Klysner", korean_name: "T. 클리스네르", team_id: 396, position: "Attacker" },
  { id: 522291, name: "Alberto Vogtmann", korean_name: "알베르토 포그트만", team_id: 396, position: "Defender" },
  { id: 16044, name: "A. Oggesen", korean_name: "A. 오게센", team_id: 396, position: "Defender" },
  { id: 144624, name: "Chidiebube Gideon Duru", korean_name: "치디에부베 기데온 두루", team_id: 396, position: "Defender" },
  { id: 57141, name: "D. Grétarsson", korean_name: "D. 그레타르손", team_id: 396, position: "Defender" },
  { id: 94332, name: "D. Wilkins", korean_name: "D. 윌킨스", team_id: 396, position: "Defender" },
  { id: 487883, name: "E. Duru", korean_name: "E. 두루", team_id: 396, position: "Defender" },
  { id: 339940, name: "G. Wagner", korean_name: "G. 바그너", team_id: 396, position: "Defender" },
  { id: 73125, name: "Matti Olsen", korean_name: "마티 올센", team_id: 396, position: "Defender" },
  { id: 81132, name: "M. Jensen", korean_name: "M. 옌센", team_id: 396, position: "Defender" },
  { id: 38719, name: "M. Soulas", korean_name: "M. 술라스", team_id: 396, position: "Defender" },
  { id: 432134, name: "P. Kristensen", korean_name: "P. 크리스텐센", team_id: 396, position: "Defender" },
  { id: 294853, name: "S. Wæver", korean_name: "S. 베베르", team_id: 396, position: "Defender" },
  { id: 333016, name: "B. Pená", korean_name: "B. 페나", team_id: 396, position: "Goalkeeper" },
  { id: 15709, name: "M. Bundgaard", korean_name: "M. 분고르", team_id: 396, position: "Goalkeeper" },
  { id: 15736, name: "N. Flø", korean_name: "N. 플로", team_id: 396, position: "Goalkeeper" },
  { id: 530063, name: "Anders Hoeg", korean_name: "안데르스 회그", team_id: 396, position: "Midfielder" },
  { id: 381337, name: "A. Pedersen", korean_name: "A. 페데르센", team_id: 396, position: "Midfielder" },
  { id: 486885, name: "A. Rrahmani", korean_name: "A. 라흐마니", team_id: 396, position: "Midfielder" },
  { id: 156747, name: "I. Nikolov", korean_name: "I. 니콜로프", team_id: 396, position: "Midfielder" },
  { id: 336611, name: "L. Björklund", korean_name: "L. 비외르클룬드", team_id: 396, position: "Midfielder" },
  { id: 16143, name: "L. Qamili", korean_name: "L. 카밀리", team_id: 396, position: "Midfielder" },
  { id: 273287, name: "M. Agger", korean_name: "M. 아게르", team_id: 396, position: "Midfielder" },
  { id: 474605, name: "M. Haidara", korean_name: "M. 하이다라", team_id: 396, position: "Midfielder" },
  { id: 444421, name: "O. Hyseni", korean_name: "O. 히세니", team_id: 396, position: "Midfielder" },
  { id: 61489, name: "Rúnar Þór Sigurgeirsson", korean_name: "루나르 토르 시구르게이르손", team_id: 396, position: "Midfielder" },
  { id: 15621, name: "R. Vinderslev", korean_name: "R. 빈데르슬레프", team_id: 396, position: "Midfielder" },
  { id: 119103, name: "S. Emini", korean_name: "S. 에미니", team_id: 396, position: "Midfielder" },
  { id: 262846, name: "T. Sommer", korean_name: "T. 소메르", team_id: 396, position: "Midfielder" },
  { id: 529469, name: "A. Hoeg", korean_name: "A. 회그", team_id: 396, position: "Midfielder" },
  { id: 550853, name: "A. Hoeg", korean_name: "A. 회그", team_id: 396, position: "Midfielder" },
  { id: 550843, name: "D. L. Gretarsson", korean_name: "D. L. 그레타르손", team_id: 396, position: "Midfielder" },
];

// Vejle (Team ID: 395) - 34명
export const VEJLE_PLAYERS: PlayerMapping[] = [
  { id: 524738, name: "Abdoulaye Camara", korean_name: "압둘라예 카마라", team_id: 395, position: "Attacker" },
  { id: 15865, name: "A. Jacobsen", korean_name: "A. 야콥센", team_id: 395, position: "Attacker" },
  { id: 393073, name: "Amin Chiakha", korean_name: "아민 치아카", team_id: 395, position: "Attacker" },
  { id: 43088, name: "A. Pitu", korean_name: "A. 피투", team_id: 395, position: "Attacker" },
  { id: 341228, name: "C. Gammelgaard", korean_name: "C. 가멜고르", team_id: 395, position: "Attacker" },
  { id: 15913, name: "J. Amon", korean_name: "J. 아몬", team_id: 395, position: "Attacker" },
  { id: 38824, name: "J. Duin", korean_name: "J. 두인", team_id: 395, position: "Attacker" },
  { id: 202017, name: "W. Faghir", korean_name: "W. 파기르", team_id: 395, position: "Attacker" },
  { id: 448085, name: "A. Sønderskov", korean_name: "A. 쇤데르스코프", team_id: 395, position: "Defender" },
  { id: 16045, name: "C. Sørensen", korean_name: "C. 쇠렌센", team_id: 395, position: "Defender" },
  { id: 37777, name: "D. van Bruggen", korean_name: "D. 반 브뤼헌", team_id: 395, position: "Defender" },
  { id: 342459, name: "Giorgi Tabatadze", korean_name: "기오르기 타바타제", team_id: 395, position: "Defender" },
  { id: 420956, name: "L. Flø", korean_name: "L. 플로", team_id: 395, position: "Defender" },
  { id: 14385, name: "L. Hujber", korean_name: "L. 후이베르", team_id: 395, position: "Defender" },
  { id: 1953, name: "L. Nielsen", korean_name: "L. 닐센", team_id: 395, position: "Defender" },
  { id: 16125, name: "M. Elvius", korean_name: "M. 엘비우스", team_id: 395, position: "Defender" },
  { id: 37452, name: "S. Velkov", korean_name: "S. 벨코프", team_id: 395, position: "Defender" },
  { id: 15662, name: "T. Gundelund", korean_name: "T. 군델룬드", team_id: 395, position: "Defender" },
  { id: 319469, name: "Valdemar Lund Jensen", korean_name: "발데마르 룬드 옌센", team_id: 395, position: "Defender" },
  { id: 456153, name: "G. Knudsen", korean_name: "G. 크누센", team_id: 395, position: "Goalkeeper" },
  { id: 109939, name: "I. Vekič", korean_name: "I. 베키치", team_id: 395, position: "Goalkeeper" },
  { id: 322265, name: "T. Jakobsen", korean_name: "T. 야콥센", team_id: 395, position: "Goalkeeper" },
  { id: 47437, name: "A. Hjulsager", korean_name: "A. 율사게르", team_id: 395, position: "Midfielder" },
  { id: 524396, name: "B. Edjeodji", korean_name: "B. 에제오지", team_id: 395, position: "Midfielder" },
  { id: 515928, name: "C. Astrup", korean_name: "C. 아스트룹", team_id: 395, position: "Midfielder" },
  { id: 15669, name: "L. Hetemi", korean_name: "L. 헤테미", team_id: 395, position: "Midfielder" },
  { id: 281660, name: "Mads Enggård", korean_name: "마스 엥고르", team_id: 395, position: "Midfielder" },
  { id: 2174, name: "M. Duelund", korean_name: "M. 뒤엘룬드", team_id: 395, position: "Midfielder" },
  { id: 199944, name: "M. Murata", korean_name: "M. 무라타", team_id: 395, position: "Midfielder" },
  { id: 202015, name: "M. Vestergård", korean_name: "M. 베스테르고르", team_id: 395, position: "Midfielder" },
  { id: 448086, name: "S. Ravn", korean_name: "S. 라븐", team_id: 395, position: "Midfielder" },
  { id: 375941, name: "T. Lauritsen", korean_name: "T. 라우리트센", team_id: 395, position: "Midfielder" },
  { id: 448084, name: "T. Lykkebak", korean_name: "T. 뤼케박", team_id: 395, position: "Midfielder" },
  { id: 327028, name: "Tobias Bach", korean_name: "토비아스 바흐", team_id: 395, position: "Midfielder" },
];

// Viborg (Team ID: 2070) - 28명
export const VIBORG_PLAYERS: PlayerMapping[] = [
  { id: 295971, name: "A. Ementa", korean_name: "A. 에멘타", team_id: 2070, position: "Attacker" },
  { id: 191229, name: "Bilal Brahimi", korean_name: "빌랄 브라히미", team_id: 2070, position: "Attacker" },
  { id: 359976, name: "C. Nouck", korean_name: "C. 누크", team_id: 2070, position: "Attacker" },
  { id: 287216, name: "Dorian Hanza", korean_name: "도리안 한자", team_id: 2070, position: "Attacker" },
  { id: 378852, name: "Serginho", korean_name: "세르징요", team_id: 2070, position: "Attacker" },
  { id: 93010, name: "T. Freriks", korean_name: "T. 프레릭스", team_id: 2070, position: "Attacker" },
  { id: 368024, name: "Y. Njoh", korean_name: "Y. 느조", team_id: 2070, position: "Attacker" },
  { id: 15823, name: "D. Anyembe", korean_name: "D. 아녜베", team_id: 2070, position: "Defender" },
  { id: 397931, name: "Hjalte Bidstrup", korean_name: "얄테 비드스트룹", team_id: 2070, position: "Defender" },
  { id: 25322, name: "J.  Mbom", korean_name: "J. 음봄", team_id: 2070, position: "Defender" },
  { id: 427804, name: "L. Kirkegaard", korean_name: "L. 키르케고르", team_id: 2070, position: "Defender" },
  { id: 489294, name: "M. Løndal", korean_name: "M. 론달", team_id: 2070, position: "Defender" },
  { id: 71990, name: "O. Bundgaard", korean_name: "O. 분고르", team_id: 2070, position: "Defender" },
  { id: 278556, name: "S. Kuzmić", korean_name: "S. 쿠즈미치", team_id: 2070, position: "Defender" },
  { id: 14592, name: "S. Radić", korean_name: "S. 라디치", team_id: 2070, position: "Defender" },
  { id: 109684, name: "Ž. Zaletel", korean_name: "Z. 잘레텔", team_id: 2070, position: "Defender" },
  { id: 16128, name: "F. Đukić", korean_name: "F. 주키치", team_id: 2070, position: "Goalkeeper" },
  { id: 15950, name: "L. Lund", korean_name: "L. 룬드", team_id: 2070, position: "Goalkeeper" },
  { id: 15922, name: "O. Hedvall", korean_name: "O. 헤드발", team_id: 2070, position: "Goalkeeper" },
  { id: 337806, name: "A. Beck", korean_name: "A. 베크", team_id: 2070, position: "Midfielder" },
  { id: 444021, name: "Frederik Damkjer", korean_name: "프레데릭 담키에르", team_id: 2070, position: "Midfielder" },
  { id: 15963, name: "J. Grønning", korean_name: "J. 그뢰닝", team_id: 2070, position: "Midfielder" },
  { id: 385663, name: "J. Vester", korean_name: "J. 베스테르", team_id: 2070, position: "Midfielder" },
  { id: 36898, name: "M. Hoedemakers", korean_name: "M. 후데마커르스", team_id: 2070, position: "Midfielder" },
  { id: 201972, name: "M. Søndergaard", korean_name: "M. 쇤데르고르", team_id: 2070, position: "Midfielder" },
  { id: 377648, name: "S. Jalal", korean_name: "S. 잘랄", team_id: 2070, position: "Midfielder" },
  { id: 386277, name: "T. Jørgensen", korean_name: "T. 요르겐센", team_id: 2070, position: "Midfielder" },
  { id: 550845, name: "F. Damkjer", korean_name: "F. 담키에르", team_id: 2070, position: "Midfielder" },
];

// 전체 수페르리가 선수 (383명, 12개 팀)
export const SUPERLIGA_PLAYERS: PlayerMapping[] = [
  ...AARHUS_PLAYERS,
  ...BRONDBY_PLAYERS,
  ...FC_COPENHAGEN_PLAYERS,
  ...FC_FREDERICIA_PLAYERS,
  ...FC_MIDTJYLLAND_PLAYERS,
  ...FC_NORDSJAELLAND_PLAYERS,
  ...ODENSE_PLAYERS,
  ...RANDERS_FC_PLAYERS,
  ...SILKEBORG_PLAYERS,
  ...SONDERJYSKE_PLAYERS,
  ...VEJLE_PLAYERS,
  ...VIBORG_PLAYERS,
];
